### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by twenttwo** [google/google-api-php-client#1004]
I want to make a live stream in unity.
So, I download app put  (youtube livestream php ,client php , youtubetest php ) in webftp.
There is something wrong 
Parse error: syntax error, unexpected T_DOUBLE_ARROW in /raid/vhost/ddtmap.com/www/liveStream/Client.php on line 95

 the line95 is     'application_name' => '',
How can I fix  it?

**Comment by mike42** [comment]
Please check your PHP version. The [README](https://github.com/google/google-api-php-client/blob/c157f563f17b6c50668c882c4f9b2fd889569f69/README.md#requirements) states that you need PHP 5.4.0 or higher, which was released in 2012.

You can get the same error if you paste the content of `./src/Google/Client.php` into an online syntax checker for PHP 5.3.

**Comment by bshaffer** [comment]
Thanks for this, @mike42 

@twenttwo Yes, try using the `v1-master` branch instead:

```sh
git clone -b v1-master git@github.com:google/google-api-php-client.git
```
