### ISSUE TITLE
Possible Bug: Setting "Content-Type" of Cloud Storage Object

### ISSUE THREAD

**Issue by memduhcagridemir** [google/google-api-php-client#1008]
I am using this client to upload files to google cloud storage. I think, I encountered a bug.

The method "setContentType()" does not update the metadata associated with the file. It changes the content-type of local object but it does not commit changes to cloud storage. 

``` php
$gsso = new Google_Service_Storage_StorageObject();
$gsso->setContentDisposition('inline');
$gsso->setContentType('application/pdf');
$storage->objects->insert( 'bucket-name', $gsso, $body );
```

This block creates a file with correct content-disposition but "application/octet-stream" as content-type. According to documentation, "application/octet-stream" is chosen automatically if another content-type does not submitted by the user. 

After some research, I found this question in stackoverflow. http://stackoverflow.com/questions/20060445/cant-set-content-type-to-google-storage-with-the-google-php-client

Accepted answer is correct. Using 'mimeType' instead of 'contentType' works. But this is confusing for the users and setContentType() method does not seem to affect the content-type of uploaded file. Therefore, I think this may be a bug of api client.

**Comment by bshaffer** [comment]
This may be a bug in the way the API is documented. This client library is generated from the API discovery doc, and the [Storage API Explorer](https://developers.google.com/apis-explorer/#s/storage/v1/storage.objects.insert) shows the same behavior of having "contentType", but not "mimeType".
