### ISSUE TITLE
Composer not auto-updating google-api-php-client-services to v0.6

### ISSUE THREAD

**Issue by ppast** [google/google-api-php-client#1009]
Hi,

I have a composer project with a requirement for google/apiclient package, v2.0.2 tag. Its composer.json file refers to google/apiclient-services as "^0.5".

**Why does composer not update google/apiclient-services to recent 0.6 release** ??? Using the ^ operator should match any subsequent version (0.6, 0.7, etc.).

If i want the 0.6 release, I have to require the google/apiclient package as dev-master (as one commit after 2.0.2 tag has updated composer.json to require google/apiclient-services with "^0.6" version).

I tried to figure out what is preventing composer from updating the services package, but I failed.

I tried to manually require google/apiclient-services:^0.6 in my project ; it downloads fine. But when I require google/apiclient, it complains about the requirement for "google/apiclient-services:^0.5" (composer.json for v2.0.2 tag) can only be satisfiable by v0.5 tag for google/apiclient-services.

```
Problem 1
    - Installation request for google/apiclient ^2.0.2 -> satisfiable by google/apiclient[v2.0.2].
    - google/apiclient v2.0.2 requires google/apiclient-services ^0.5 -> satisfiable by google/apiclient-services[v0.5] but these conflict with your requirements or minimum-stability.
```

Tag v0.6 is ignored, despite the "^" operator. 

I deleted packages, flush the composer cache, etc., with no success.

Maybe the "v" letter in tags prevents composer from working fine ? I didn't see any issue like this with other packages (however, those "other packages" don't have a "v" letter in their version names).

Maybe it's a Packagist issue/misunderstanding, as when I manually require google/apiclient-services:^0.5 in a project, it does not install last release (should be 0.6 here, thanks to ^ operator), but sticks to 0.5 (and does not update).

Can anyone more "fluent" with Composer/Packagist explain me how all this should be understood, as I quite confused... Why using "^0.5" syntax, if auto-updating does not work... ?

Thanks

**Comment by mike42** [comment]
I can replicate what you're seeing, and I believe that this behaviour is expected for sub-1.0 versions of dependencies (please see [composer docs](https://getcomposer.org/doc/articles/versions.md#caret)):

> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0.`

Once [this change](https://github.com/google/google-api-php-client/commit/b9410f923f312b2a80c5cb9d10c80ed09b8e5da2#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) appears in a release, you would get the new version.

Otherwise, as you note, your options are to either use the currently released dependencies:

```
$ composer require google/apiclient
Using version ^2.0 for google/apiclient
...
  - Installing google/apiclient-services (v0.5)
...
  - Installing google/apiclient (v2.0.2)
```

Or to switch to a `dev` version and cross your fingers, basically:

```
$ composer require google/apiclient:dev-master
...
  - Installing google/apiclient-services (v0.6)
...
  - Installing google/apiclient (dev-master b9410f9)
    Cloning b9410f923f312b2a80c5cb9d10c80ed09b8e5da2
```

**Comment by ppast** [comment]
Woooh ! It was clearly written in the docs I read, I still I didn't catch it ! Didn't realize at the moment I was refering to pre 1.0 versions. 

Thanks a lot for your answer !

"Issue" closed.
