### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Khetaram16** [google/google-api-php-client#1011]
All is working good but when i click on allow to Manage your YouTube account i getting error as per attachment.

Please help me..

![error](https://cloud.githubusercontent.com/assets/16400745/17270395/384525ae-567f-11e6-8968-80509fe805e6.png)

**Comment by bshaffer** [comment]
There are various solutions mentioned in https://github.com/google/google-api-php-client/issues/788 that may help. To summarize, the options are this:

1. Download the [cacert.pem](https://curl.haxx.se/ca/cacert.pem) file
2. Do one of the following
    *  set `curl.cainfo = "PATH_TO/cacert.pem"` in `php.ini`
    * pass the file in the `verify` option to your Guzzle client, i.e.:

        ```php
        $client->setHttpClient(new \GuzzleHttp\Client(array(
            'verify' => 'C:\Windows\curl-ca-bundle.crt',
        )));
        ```

**Comment by doubleOrt** [comment]
@bshaffer  Tried all these options and, nope, not working.
