### ISSUE TITLE
executable file flags set for text files

### ISSUE THREAD

**Issue by peterdd** [google/google-api-php-client#1014]
When I list the unzipped folder on my ssh bash shell, it shows that several files have the executable permission set which is unneeded and clutters the file list (asterisks at row end).

![googleapi](https://cloud.githubusercontent.com/assets/1839154/17294356/a3b673d8-57f6-11e6-8255-aa84722fa2cf.png)

edit: examples/ dir is ok, I set the red marker on wrong line.

**Comment by bshaffer** [comment]
Thank you for finding this! This is now fixed in the latest release (`google-api-php-client-2.0.2`), and we'll be sure to fix this going forward as well.

**Comment by peterdd** [comment]
I used https://github.com/google/google-api-php-client/releases/download/v2.0.2/google-api-php-client-2.0.2_PHP54.zip

and the screenshot was taken from this unzipped...

**Comment by bshaffer** [comment]
I have since updated the zip file. Will you check and verify the permissions are now correct?

**Comment by peterdd** [comment]
Looks good. Thanks. :-)
