### ISSUE TITLE
Real Time Reporting Library is not working with PHP < 5.5

### ISSUE THREAD

**Issue by amirduran** [google/google-api-php-client#1017]
I get the following error when I run Real Time Reporting Library on server with 5.4.45: 

> PHP Fatal error:  Call to undefined function GuzzleHttp\Handler\curl_reset() in 

curl_reset() is defined in PHP > 5.5
Readmefile (documentation) has to be updated

**Comment by bshaffer** [comment]
You need to use Guzzle 5 for PHP 5.4:

```bash
composer require guzzlehttp/guzzle:~5.2
```

Or download the PHP54-specific release on the [Releases](https://github.com/google/google-api-php-client/releases) page.
