### ISSUE TITLE
BC break in Google_Service_Drive_DriveFile

### ISSUE THREAD

**Issue by Nyholm** [google/google-api-php-client#1023]
In version 1.1.7 there was a function `Google_Service_Drive_DriveFile::setTitle`. 
In version 1.1.8 the function was removed. 

The function (and possible others) was removed in this commit: https://github.com/google/google-api-php-client/commit/85309a3520bb5f53368d43e35fd24f43c9556323

**Comment by bshaffer** [comment]
v1.1.7 is on Drive v2: https://github.com/google/google-api-php-client/blob/1.1.7/src/Google/Service/Drive.php#L86
v1.1.8 is on Drive v3: https://github.com/google/google-api-php-client/blob/v1.1.8/src/Google/Service/Drive.php#L76

The versioning of this library does not reflect major version changes in the API, unfortunately (see https://github.com/google/google-api-php-client-services/issues/23), so this is WAD. Sorry for the inconvenience.

**Comment by mvanbaak** [comment]
http://semver.org/

Would be very nice if you guys at google could read that, start caring about your users, and NOT break things because you release a new patch version!
