### ISSUE TITLE
Unknown stream type php://stderr

### ISSUE THREAD

**Issue by eRadical** [google/google-api-php-client#1024]
Defaulting to Monolog is not ok on AppEngine

I get 
[message:protected] => The stream or file "php://stderr" could not be opened: failed to open stream: Unknown stream type php://stderr.

https://cloud.google.com/appengine/docs/php/logs/#PHP_writing_application_logs » says a simple call to syslog() would suffice!

@bshaffer - do you have any path on mitigating this? I might do it myself if I can have a hint/direction...

**Comment by bshaffer** [comment]
Try this:

```php
$client = new Google_Client;
$logger = new Monolog\Logger('google-api-php-client');
$logger->pushHandler(new Monolog\Handler\SyslogHandler('app'));
$client->setLogger($logger);
```

The way to mitigate this would be to call `$this->isAppEngine()` in `Google_Client::createDefaultLogger`. If you want to submit a PR with tests for this, I'd be happy to merge it!

**Comment by bshaffer** [comment]
I submitted #1025 to address this in the library. If you want to pull down my branch and let me know if it works for you, that would be greatly appreciated

```
composer require google/apiclient:dev-fix-default-logger-for-appengine
```

**Comment by eRadical** [comment]
I'll test tomorrow to see if all is ok w/ Monolog\Handler\SyslogHandler and let you know!

**Comment by eRadical** [comment]
All checks are ok!
