### ISSUE TITLE
Changes in google/auth break Guzzle6AuthHandler

### ISSUE THREAD

**Issue by gdhnz** [google/google-api-php-client#1026]
Caching has been removed from the constructor in AuthTokenMiddleware of google/auth.

> Catchable fatal error: Argument 2 passed to Google\Auth\Middleware\AuthTokenMiddleware::__construct() must be callable, array given, called in /app/htdocs/public/google/sheets/vendor/google/apiclient/src/Google/AuthHandler/Guzzle6AuthHandler.php on line 39 and defined in /app/htdocs/public/google/sheets/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php on line 60

From some limited testing, I got it working again in src/Google/AuthHandler/Guzzle6AuthHandler.php by changing...
```
    $middleware = new AuthTokenMiddleware(
        $credentials,
        $this->cacheConfig,
        $this->cache,
        $authHttpHandler,
        $tokenCallback
    );
```

...to...
```
    $middleware = new AuthTokenMiddleware(
        $credentials,
        $authHttpHandler,
        $tokenCallback
    );
```

**Comment by stomaskovic** [comment]
Encountered the same problem and can confirm.

**Comment by bshaffer** [comment]
can you confirm this is now fixed in `master`?

**Comment by gdhnz** [comment]
I've just re-tried my code after updating to dev-master and it's now performing as expected.

Thanks.
