### ISSUE TITLE
Google_Service_Exception::getMessage returns string but ::getErrors returns null

### ISSUE THREAD

**Issue by CNSKnight** [google/google-api-php-client#1027]
This one's not about the message, but the delivery.

``` php
try {
    $service->users_messages->insert(DELEGATE_EMAIL_ADDRESS, $msg);
} catch (Google_Service_Exception $e) {
    if ($msg = $e->getMessage()) {
        acapApp::catchProcessMessage('API Service says: ['.$e->getCode().'] '.$msg, ACAP_WARNING);
    }

    if ($errs = $e->getErrors()) {
        foreach ($errs as $errAry) {
            acapApp::catchProcessMessage('API Service says: ['.$errAry['reason'].'] '.$errAry['message'], ACAP_WARNING);
        }
    }

    return false;
}
```

yields...
- [x] API Service says: [401] { "error": "unauthorized_client", "error_description": "Unauthorized client or scope in request." }
- [ ] But ::getErrors returns only _null_

Is this somehow expected behavior?

**Comment by bshaffer** [comment]
The `getErrors` function is for errors that return from the APIs in this format:
```json
{
    "error": {
        "errors": [
            { "code": 400, "message": "error message" }
        ]
    }
}
```

Yeah this isn't great in the scenario you described, but that's an auth error, and has a different error format than the API errors. So unfortunately this particular issue is probably WAD.

**Comment by CNSKnight** [comment]
um..."WAD"?

**Comment by bshaffer** [comment]
Working as Designed

**Comment by CNSKnight** [comment]
who gnu

**Comment by bshaffer** [comment]
We could check for the auth error format also.
