### ISSUE TITLE
Fetch Merchant Status 

### ISSUE THREAD

**Issue by wernerspiegelpup** [google/google-api-php-client#1034]
Hi there, 

we're managing large sellers with thousands of sub-merchant center accounts. 
Researching for a while now I could not find anything api related to get a merchants status, for example "suspended".

Is there a way i can do that in an automated fashion through the api? 
Webcrawling every sub merchant seems a bit 2004.

Any help is much appreciated.

**Comment by michaelbausor** [comment]
This doesn't seem like the right repo for this question. If you are still having problems please reopen and clarify the problem.
