### ISSUE TITLE
PHP Fatal error: Call to private method Google_Http_MediaFileUpload::getResumeUri() from context

### ISSUE THREAD

**Issue by thamaraiselvam** [google/google-api-php-client#1036]
I am doing chunk upload and it is working fine but in some scenario, following error occurs.
`PHP Fatal error: Call to private method Google_Http_MediaFileUpload::getResumeUri() from context` 

This is following code that I am using to resume chunk.

`$uploadID = $media->getResumeUri();`

Why `fetchResumeUri()` is private? if this is fallback function call and of course we are gonna call `getResumeUri` outside of class.

  `public function getResumeUri()
  {
    return ( $this->resumeUri !== null ? $this->resumeUri : $this->fetchResumeUri() );
  }`

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
