### ISSUE TITLE
Always  get 404 on insert vault in moments 

### ISSUE THREAD

**Issue by divsbhalala** [google/google-api-php-client#1037]
Bellow is my sample code that i am using while inserting moment in google plus

```
try{
    var_dump($res->access_token);
    $accessToken=$this->_gp_client->refreshToken($res->access_token);
    $accessToken=$this->_gp_client->getAccessToken();
    var_dump($accessToken);
    $token=json_decode($accessToken);
    $this->_gp_client->setAccessToken($accessToken);
        $response = $this->_gp_plus->people->get('me');
        print_r($response);
        $this->_gp_plusItemScope->setId($response->id);
        $this->_gp_plusItemScope->setType("http://schema.org/AddAction");
        $this->_gp_plusItemScope->setName("The Google+ Platform");
        $this->_gp_plusItemScope->setDescription("A page that describes just how awesome Google+ is!");
        $this->_gp_plusItemScope->setImage("https://developers.google.com/+/plugins/snippet/examples/thing.png");
        #$this->_gp_plusItemScope->setImage($post_data['post_attachment']);
        $this->_gp_moment->setTarget($this->_gp_plusItemScope);
        $this->_gp_moment->setType("http://schemas.google.com/AddActivity");
        $momentResult = $this->_gp_plus->moments->insert('me', 'vault', $this->_gp_moment);
        print_r($momentResult);
                } catch (Google_Auth_Exception $e) {
                     print_r($e->getMessage());
             }
```

and i am alway gettting 404 errors 
Fatal error:  Uncaught Google_Service_Exception: Error calling POST https://www.googleapis.com/plus/v1/people/me/moments/vault: (404) Not Found in /var/www/html/codeigniter_metronic-master/application/third_party/Google/Http/REST.php:79
Stack trace:
#0 /var/www/html/codeigniter_metronic-master/application/third_party/Google/Http/REST.php(44): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request))
#1 /var/www/html/codeigniter_metronic-master/application/third_party/Google/Client.php(503): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/www/html/codeigniter_metronic-master/application/third_party/Google/Service/Resource.php(195): Google_Client->execute(Object(Google_Http_Request))
#3 /var/www/html/codeigniter_metronic-master/application/third_party/Google/Service/Plus.php(498): Google_Service_Resource->call('insert', Array, 'Google_Service_...')
#4 /var/www/html/codeigniter_metronic-master/application/controllers/gplus.php(234): Google_Service_Plus_Moments_Resource->insert('me in /var/www/html/codeigniter_metronic-master/application/third_party/Google/Http/REST.php on line 79

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.

**Comment by mattwhisenhunt** [comment]
It looks like the Google+ API doesn't support that anymore.
