### ISSUE TITLE
setDateTime on Google_Service_Calendar_EventDateTime should take a \DateTime as parameter

### ISSUE THREAD

**Issue by geoffroyw** [google/google-api-php-client#1040]
Hi,

I was trying to use the ```setDateTime``` method on ```Google_Service_Calendar_EventDateTime```. Instinctively, I thought I could just pass an instance of ```\DateTime```  but it turned out that the method expects a string which represents the formatted DateTime.

I believe the formatting should be transparent for the user. We should be able to pass an instance of ```\DateTime``` to the ```setDateTime``` method (and as a consequence the corresponding getter should return a ```\DateTime```object.

**Comment by bshaffer** [comment]
I agree this would be great! Unfortunately, these libraries are auto-generated, and at this time we do not plan to support DateTime objects, as we do not have a way to automatically distinguish a "date time" parameter from a "string" parameter in the API.
