### ISSUE TITLE
google-api-php-client/src/Google/Service/YouTube.php no found on your git

### ISSUE THREAD

**Issue by amidevous** [google/google-api-php-client#1042]
google-api-php-client/src/Google/Service/YouTube.php no found on your git

https://developers.google.com/youtube/v3/live/code_samples/php

**Comment by bshaffer** [comment]
You're right, these should be linking to [v1-master](https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Service/YouTube.php)

**Comment by dimre01** [comment]
To clarify: is it possible to create an instance of `Google_Service_YouTubeAnalytics` with the most recent version of the API?

**Comment by enes66** [comment]
https://github.com/google/google-api-php-client-services newest repo is here.

**Comment by michaelbausor** [comment]
Resolved
