### ISSUE TITLE
Syntax Error in functions.php

### ISSUE THREAD

**Issue by kimmer99** [google/google-api-php-client#1043]
Got this working fine on my local machine but when I upload the library and my code to the server, I'm getting this error, "Parse error: syntax error, unexpected '[' in /googleapi/google/vendor/guzzlehttp/psr7/src/functions.php on line 77" when I execute the require for the autoload (/googleapi/google/vendor/autoload.php).  The only immediate difference I can tell is that I'm using php5.6.1 on my local machine and the server is using 5.3.3.

Any ideas?  Thanks!

**Comment by recipe** [comment]
You have to upgrade php version on the server.

**Comment by eRadical** [comment]
The shorthand version
`$a = ['short', 'version'];`
was introduced in PHP 5.5!

You need to upgrade to at least that version... but... that version is now unsupported so you should really go all the way to PHP 5.6. At the time I write this you have 4 month of active development pr PHP5.6.

**Comment by kimmer99** [comment]
Yeah, that's what I was afraid of - thanks.

**Comment by eRadical** [comment]
Can you please close this issue?

**Comment by kimmer99** [comment]
Yep - sorry

**Comment by bshaffer** [comment]
FYI Short Array Syntax was [added in PHP 5.4](http://php.net/manual/en/migration54.new-features.php).
