### ISSUE TITLE
Google Service Sheets does not have append method

### ISSUE THREAD

**Issue by joelworsham** [google/google-api-php-client#1049]
Sorry if this is not the place to post this, but I've been searching for hours about this.

Why is it that the class `Google_Service_Sheets` does not have an `append` method? I've tried using `update` and adding `:append` to the range to attempt to fool it into doing an append, but no luck. I'm just trying to do this https://developers.google.com/sheets/samples/writing#append_values.

**Comment by ilinkMathew** [comment]
The latest release of google-api-php-client (v2.0.3) has the append functions included in it. Do check it out
