### ISSUE TITLE
PHP Version Requirement on Installation Page

### ISSUE THREAD

**Issue by jmooring** [google/google-api-php-client#1050]
https://developers.google.com/api-client-library/php/start/installation states that PHP version 5.2.1 or greater is required. It looks like PHP version 5.4 or greater is required -- array notation [] was introduced in 5.4.

**Comment by owneroverall** [comment]
Thanks

Den 19:25 mån 12 sep 2016jmooring <notifications@github.com> skrev:

**Comment by emestud** [comment]
The page has been updated. Thanks very much for pointing that out.
