### ISSUE TITLE
Fatal error: Class 'Google\Auth\Cache\MemoryCacheItemPool' not found in

### ISSUE THREAD

**Issue by developerside** [google/google-api-php-client#1052]
Hi I'm having an issue on the Fatal error: Class 'Google\Auth\Cache\MemoryCacheItemPool' not found in C:\xampp\htdocs\googleapi\src\Google\Client.php on line 1010

i'm using the latest version my code is like this

<?php
	require('../vendor/autoload.php');
	
include_once "templates/base.php";

echo pageHeader("File Upload - Uploading a simple file");

$client = new Google_Client();

/*
$client->setClientId('[app client id].apps.googleusercontent.com');
$client->setClientSecret('[app client secret]');
$client->refreshToken('[your refresh token]');
*/

$client->setClientId('xxx');
$client->setClientSecret('xxx');

echo $client->getLibraryVersion()."version";

$service = new Google_Service_Books($client);

$optParams = array('filter' => 'free-ebooks');
$results = $service->volumes->listVolumes('Henry David Thoreau', $optParams);

print_r($results);

I'm not sure why is causes like this i've check that line and it seems its just a 

 protected function createDefaultCache()
  {
    // use filesystem cache by default if tedivm/stash exists
    if (class_exists('Stash\Pool')) {
      $cache = new Stash\Pool(new Stash\Driver\FileSystem);
    } else {
      $cache = new MemoryCacheItemPool; // <-------------- on this line
    }

    return $cache;
  }

**Comment by bshaffer** [comment]
I updated your code snippet and removed your credentials, but *you must change them immediately* since you posted them publicly.

**Comment by bshaffer** [comment]
Run `composer update` and make sure you have the latest version. It's possible you updated just the code for this library and not the corresponding updates to the vendored libraries.
