### ISSUE TITLE
Update firebase/php-jwt min version

### ISSUE THREAD

**Issue by ashbeats** [google/google-api-php-client#1054]
# 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - google/apiclient v2.0.3 requires google/auth 0.10 -> satisfiable by google/auth[v0.10].
    - Conclusion: don't install google/auth v0.10
    - google/apiclient v2.0.1 requires google/auth 0.9 -> satisfiable by google/auth[v0.9].
    - google/apiclient v2.0.2 requires google/auth 0.9 -> satisfiable by google/auth[v0.9].
    - Conclusion: don't install google/auth v0.9
    - Conclusion: don't install google/auth v0.8|remove firebase/php-jwt v4.0.0
    - Conclusion: don't install google/auth v0.8|don't install firebase/php-jwt v4.0.0
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Installation request for google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - google/auth v0.8 requires firebase/php-jwt ~2.0|~3.0 -> satisfiable by firebase/php-jwt[2.0.0, v2.1.0, v2.2.0, v3.0.0].
    - Can only install one of: firebase/php-jwt[2.0.0, v4.0.0].
    - Can only install one of: firebase/php-jwt[v2.1.0, v4.0.0].
    - Can only install one of: firebase/php-jwt[v2.2.0, v4.0.0].
    - Can only install one of: firebase/php-jwt[v3.0.0, v4.0.0].
    - Installation request for firebase/php-jwt (locked at v4.0.0) -> satisfiable by firebase/php-jwt[v4.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by boredom2** [comment]
Similar problem here. We cant update the Microsoft Azure Package, which needs JWT 4.0 now. Is it possible to support JWT 4.0 in this Project also?

**Comment by tomschlick** [comment]
Another issue with this. Laravel Spark requires `~4.0`

**Comment by angular-tools** [comment]
Have same issue when installing this with `aws/aws-sdk-php` because it requires guzzlehttp/psr7[1.3.1]

`
- google/auth v0.8 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzlehttp/psr7[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - Installation request for guzzlehttp/psr7 (locked at 1.3.1) -> satisfiable by guzzlehttp/psr7[1.3.1].
`

How can I sort this?

**Comment by ashbeats** [comment]
@angular-tools this is not related to the firebase pkg. Just happens that both reference guzzle. 

You can try to update "google-api-php-client" to use guzzle v1.3.1. If it passes all tests, submit a push req or configure composer to use your fork.

**Comment by boredom2** [comment]
Is it possible, that someone releases a Version with JWT@4.0?

**Comment by bshaffer** [comment]
This is fixed and has been tagged in `v2.1.0`. Running `composer update` should update you to the latest version as long as your version is `google/apiclient: ^2.0`

**Comment by jamesgraham** [comment]
Can this be upgraded to v5 now?
