### ISSUE TITLE
Weird behaviour around scopes or tedivm/stash - 401 authError

### ISSUE THREAD

**Issue by erfanimani** [google/google-api-php-client#1056]
I'm seeing some pretty weird behaviour from, what I think is the library, and not the API, but I could be wrong.

I've got the following scopes:

    private $scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "email",
        "profile",
        "https://www.googleapis.com/auth/script.send_mail",
        "https://www.googleapis.com/auth/drive"
    ];

And I receive the auth code, refresh token and access token just fine.

However, when I do the following (with the same scopes):

    $oauthService = new Google_Service_Oauth2($client);
    $response = $oauthService->userinfo->get();

.. I get the following error:

    {
        "error": {
            "errors": [
                {
                    "domain": "global",
                    "reason": "authError",
                    "message": "Invalid Credentials",
                    "locationType": "header",
                    "location": "Authorization"
                }
            ],
            "code": 401,
            "message": "Invalid Credentials"
        }
    }

I know my access token (and access id) are correct, because I've tested them with the following endpoint: https://www.googleapis.com/oauth2/v2/tokeninfo. I also know that getting user info is part of the originally requested scopes (email and profile).

So I've tried removing the scopes altogether, because the user has already given consent, so I don't think it's necessary that I specify the scopes again (correct me if I'm wrong).. but that gives me the following error:

    Invalid or Empty Node passed to getItem constructor.

    #0 /project/vendor/google/auth/src/CacheTrait.php(37): Stash\Pool->getItem(Array)
    #1 /project/vendor/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php(164): Google\Auth\Middleware\ScopedAccessTokenMiddleware->getCachedValue('')
    #2 /project/vendor/google/auth/src/Middleware/ScopedAccessTokenMiddleware.php(133): Google\Auth\Middleware\ScopedAccessTokenMiddleware->fetchToken()
    #3 /project/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): Google\Auth\Middleware\ScopedAccessTokenMiddleware->Google\Auth\Middleware\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
    #4 /project/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
    #5 /project/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
    #6 /project/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
    #7 /project/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
    #8 /project/vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
    #9 /project/vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
    #10 /project/vendor/guzzlehttp/guzzle/src/Client.php(104): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
    #11 /project/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(34): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
    #12 /project/vendor/google/apiclient/src/Google/Http/REST.php(74): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
    #13 /project/vendor/google/apiclient/src/Google/Task/Runner.php(181): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
    #14 /project/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()
    #15 /project/vendor/google/apiclient/src/Google/Client.php(781): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...', Array)
    #16 /project/vendor/google/apiclient/src/Google/Service/Resource.php(232): Google_Client->execute(Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
    #17 /project/vendor/google/apiclient-services/src/Google/Service/Oauth2/Resource/Userinfo.php(38): Google_Service_Resource->call('get', Array, 'Google_Service_...')
    #18 /project/docroot/app/code/local/Project/Project/Model/Api/Userinfo.php(18): Google_Service_Oauth2_Resource_Userinfo->get()

(~~And actually, related to this, `tedivm/stash` is a dev-dependency, but it seems to be required even if you're simply using the library - it's not optional ((will throw an error if you try to use the library without having this package installed)), so this might need to change?~~)

Ok.. so we can't leave the scope empty, but we also can't pass in the correct values. Let's try something new:

    $client->setScopes('asdfasdfasdf');
    $oauthService = new Google_Service_Oauth2($client);
    $response = $oauthService->userinfo->get();
    // WORKS!

Seems pretty odd from my POV - I can only get it to work if I pass through non-existent scopes. I've also tried passing through https://www.googleapis.com/auth/userinfo.email and https://www.googleapis.com/auth/userinfo.profile, but I don't think we should be using those any more.

Let me know if this is more suited for a Stackoverflow question. In any case, the `Invalid or Empty Node passed to getItem constructor.` does seem to be a library issue - I'd imagine at the very least you'd want it to throw an exception saying you don't have your scopes set or something.

**Comment by erfanimani** [comment]
Also, calling `$client->setIncludeGrantedScopes(true);` without setting scopes explicitly will throw `Invalid or Empty Node passed to getItem constructor.`

**Comment by erfanimani** [comment]
I've got my app to work, but the workaround isn't very nice. I'm only setting the scopes on the client when creating the authentication URL (`createAuthUrl`). In any other scenario I'm setting a bogus scope to prevent the lib from erroring out.

**Comment by erfanimani** [comment]
Edit: actually, my bad - `class_exists` throws a warning in various PHP frameworks and that's why I got the assumption that `tedivm/stash` was a hard dependency while in reality it's not. Again, not the lib's fault - but the framework as it doesn't conform to PSR-4 standards

> Autoloader implementations MUST NOT throw exceptions, MUST NOT raise errors of any level, and SHOULD NOT return a value.

**Comment by bshaffer** [comment]
Sounds like you have it figured out. Yes, `tedvim/stash` is an **optional** dependency. I have never seen the behavior where `class_exists` throws a warning, that is quite unfortunate.
