### ISSUE TITLE
PLUS_LOGIN scope unconsistent behaviour

### ISSUE THREAD

**Issue by gunnrryy** [google/google-api-php-client#1057]
Hi,
as mentioned in documentation, Google_Service_Plus::PLUS_LOGIN scope fetches 3 things viz. 
1) connections in circles,
2) age range
3) languages
internally it also fetches USERINFO_PROFILE scope which is basic info of User.

when trying this in Google REST API Explorer, adding only plus_login I am able to fetch G+ connections, but however in my application I am not able to fetch G+ connection. tried same thing on Google OauthPlayGround with Plus_login scope, and over there also it didnt fetch G+ connections.

however I had this feature working fine till 13/10/2016. is there any change in google-api-php-client or scope or service ??

**Comment by mattwhisenhunt** [comment]
The APIs are changing all the time to reflect those changes the autogenerated client-services are regenerated.

Did this behavior start after a composer update?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
