### ISSUE TITLE
Cloud sql second generation example

### ISSUE THREAD

**Issue by SergeyCherepanov** [google/google-api-php-client#1059]
I trying to create second generation sql instance. But I not found "machine type" property in Google_Service_SQLAdmin_Settings. Can you add example how to create second generation instance?

Thank you!

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
