### ISSUE TITLE
Cannot query the drafts list using listUsersDrafts() method

### ISSUE THREAD

**Issue by Nimeshka** [google/google-api-php-client#1061]
The Gmail API supports an optional parameter 'q' to filter the list of drafts. 

https://developers.google.com/gmail/api/v1/reference/users/drafts/list

But the client library doesn't support this optional 'q' parameter. When I pass this parameter, it gives the error, An error occurred: (list) unknown parameter: 'q'. It doesn't let me query the drafts for a given keyword and filter the results.

**Comment by bshaffer** [comment]
@Nimeshka which version of this library are you using? The most recent tag of the [client-services repo](https://github.com/google/google-api-php-client-services/blob/v0.7/src/Google/Service/Gmail/Resource/UsersDrafts.php#L87) has support for the `q` parameter.

**Comment by bshaffer** [comment]
Please upgrade to `v2` to resolve this issue:

```
compose require google/apiclient:^2
```
