### ISSUE TITLE
Delete multiple files at once 

### ISSUE THREAD

**Issue by dt-rush** [google/google-api-php-client#1065]
Original feature request from the Public Issue Tracker for App Engine:

"""
I am using the PHP API to upload files to my google Storage.
Sometime, we need to delete a list of image that are in a specific "directory". If we want to delete 50 files, the request take about 10s to execute, wich is not usable in production mode.
What could be good is to pass a list of file to delete :

For exemple instead of :

$storage->objects->delete($bucket, $file);

We could use : 

$storage->objects->delete($bucket,$files);

With files as an array of files.

I know that we can delete multiple file at once, when using the gsutil command, so why not implementing this on the PHP api ?

Thank you in advance.

All the best,
Emmanuel
"""

**Comment by bshaffer** [comment]
You can accomplish this using batch requests:

```php
    $client = $this->getClient();
    $batch = new Google_Http_Batch($client);
    $plus = new Google_Service_Storage($client);
    $client->setUseBatch(true);
    foreach ($files as $i => $file) {
        $batch->add($storage->objects->delete($bucket, $file), $i);
    }
    $result = $batch->execute();
```
