### ISSUE TITLE
Prediction Api- issue while trying to login

### ISSUE THREAD

**Issue by abalakrishnan** [google/google-api-php-client#1067]
I am using this library for perfomaing login and send query for getting prediction results. I am using xampp with php7, when login i get the allow access page and when i click allow the following error on y page. Could you please help

Fatal error: Uncaught TypeError: Argument 1 passed to Google\Auth\OAuth2::fetchAuthToken() must be callable, object given, called in C:\xampp\htdocs\prediction\google-api-php-client\src\Google\Client.php on line 175 and defined in C:\xampp\htdocs\prediction\google-api-php-client\vendor\google\auth\src\OAuth2.php:425 Stack trace: #0 C:\xampp\htdocs\prediction\google-api-php-client\src\Google\Client.php(175): Google\Auth\OAuth2->fetchAuthToken(Object(GuzzleHttp\Client)) #1 C:\xampp\htdocs\prediction\google-api-php-client\src\Google\Client.php(155): Google_Client->fetchAccessTokenWithAuthCode('4/WnvpnSO5HEhNF...') #2 C:\xampp\htdocs\prediction\predict_new.php(23): Google_Client->authenticate('4/WnvpnSO5HEhNF...') #3 {main} thrown in C:\xampp\htdocs\prediction\google-api-php-client\vendor\google\auth\src\OAuth2.php on line 425

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
