### ISSUE TITLE
Getting invalid token response with 2.0.3

### ISSUE THREAD

**Issue by georgekaf** [google/google-api-php-client#1071]
# I updated to 2.0.3 with composer and the same code fails to connect and

retrieve results. I searched the README and the wiki for documentation 
changes but I did not find something new and relevant with authentication.

**This is the code:**

```
$url = 'https://www.googleapis.com/analytics/v3/data/ga?ids=ga:xxxxxxxxx&start-date=yesterday&end-date=yesterday&metrics=ga:users,ga:sessions,ga:bounceRate,ga:pageviews,ga:transactions,ga:tra
nsactionRevenue&samplingLevel=HIGHER_PRECISION&sort=-ga:transactionRevenue';

$client = new Google_Client();

putenv("GOOGLE_APPLICATION_CREDENTIALS=$filePathToJsonFile");
$client->useApplicationDefaultCredentials();

$client->addScope(Google_Service_Analytics::ANALYTICS);
$client->addScope(Google_Service_Analytics::ANALYTICS_MANAGE_USERS_READONLY);
$client->addScope(Google_Service_Analytics::ANALYTICS_READONLY);
$client->addScope(Google_Service_Analytics::ANALYTICS_PROVISION);

$httpClient = $client->authorize();
$response   = $httpClient->get($url);
$result     = $response->getBody();
```

I use direct queries and a service account to connect. The code stays the same between any apiclient  updates or downgrades.

**With google/apiclient v2.0.2** (google/apiclient-services (v0.5), google/auth (v0.9))

```
GuzzleHttp\Message\Response Object
(
[reasonPhrase:GuzzleHttp\Message\Response:private] => OK
[statusCode:GuzzleHttp\Message\Response:private] => 200
....
```

**With google/apiclient v2.0.3** (google/apiclient-services (v0.7), google/auth (v0.10))

```
GuzzleHttp\Message\Response Object
(
[reasonPhrase:GuzzleHttp\Message\Response:private] => Unauthorized
[statusCode:GuzzleHttp\Message\Response:private] => 401
....

[www-authenticate] => Array
(
[0] => Bearer realm="https://accounts.google.com/", error=invalid_token
)
```

Downgrading to 2.0.2 solves the issue and I can retrieve query results 
properly.

**Comment by bshaffer** [comment]
Can you verify the token going across HTTP is the expected access token? Can you see what class is coming back with `$client->getCache()`?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
