### ISSUE TITLE
VerifyIdToken Method

### ISSUE THREAD

**Issue by Arkadiusz234** [google/google-api-php-client#1074]
I found miss in verifyIdToken method. By comment it should return **Google_Auth_LoginTicket** object if the verification was successful but it return an array with google user data.

**Comment by alexghi** [comment]
`Google_Auth_LoginTicket` was removed.  Calls to `Google_Client::verifyIdToken` now returns
    the payload of the ID Token as an array if the verification is successful. - take from google's UPGRADING.md

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
