### ISSUE TITLE
GmailService $service->users_labels->listUsersLabels($userId); returns "GuzzleHttp\Psr7\Request" object.

### ISSUE THREAD

**Issue by manish-tal** [google/google-api-php-client#1080]
While listing user labels using this code:

```
  /**
   * @var $labelsResponse \Google_Service_Gmail_ListLabelsResponse
   */
  $labels = array();

  $labelsResponse = $this->gmailService->users_labels->listUsersLabels($forUser);
  if ($labelsResponse->getLabels()) {
      $labels = array_merge($labels, $labelsResponse->getLabels());
  }
  return $labels;
```

instead of getting object of _'Google_Service_Gmail_ListLabelsResponse'_ from _listUsersLabels_  method call I got _'GuzzleHttp\Psr7\Request'_

thereafter code fails with exception

`Fatal error: Call to undefined method GuzzleHttp\Psr7\Request::getLabels()` although this has happened only once, I tried multiple times after that but it never happened again.

**Comment by mattwhisenhunt** [comment]
I haven't been able to reproduce this. Please let me know if you find a reliable way to.
