### ISSUE TITLE
Fatal Error if tedivm/stash exists

### ISSUE THREAD

**Issue by lucacaimi** [google/google-api-php-client#1083]
If tedivm/stash exists Fatal Error: Argument 1 passed to Google_AuthHandler_Guzzle5AuthHandler::__construct() must be an instance of Psr\Cache\CacheItemPoolInterface, instance of Stash\Pool given

```
// Google_Client
protected function createDefaultCache()
  {
    // use filesystem cache by default if tedivm/stash exists
    if (class_exists('Stash\Pool')) {
      $cache = new Stash\Pool(new Stash\Driver\FileSystem);
    } else {
      $cache = new MemoryCacheItemPool;
    }

    return $cache;
  }
```

```
// Google_AuthHandler_Guzzle5AuthHandler and Google_AuthHandler_Guzzle6AuthHandler
public function __construct(CacheItemPoolInterface $cache = null, array $cacheConfig = [])
```

**Comment by bshaffer** [comment]
Which version of `tedvim/stash` do you have installed?

**Comment by lucacaimi** [comment]
I was using an old version of `tedvim/stash`, PSR-6 support starts from version `v0.14.1`
https://github.com/tedious/Stash/releases/tag/v0.14.1

**Comment by mattwhisenhunt** [comment]
So it sounds like you got it working?
