### ISSUE TITLE
set "'If-None-Match" in header

### ISSUE THREAD

**Issue by sonalmahajan01** [google/google-api-php-client#1088]
I am using the latest version of YouTube API i.e https://www.googleapis.com/youtube/v3 with PHP client library. In earlier version, to know if an eTag has changed or updated for a resource, we would use the following code:

```
$client->getIo()->setOptions(array(
CURLOPT_HTTPHEADER => array('If-None-Match:<eTag>"')));
try {
   $response = $youtube->playlists->listPlaylists('snippet', array('id' => '6KzzScZSUrs'));
}catch (Google_Service_Exception $e) {
if (304 == $e->getCode()) {
    $response = new EmptyResponse;
} else {
    $response = null;
}
```

In the new version getIo() has been removed. What is the alternative to using this method?

**Comment by mattwhisenhunt** [comment]
That is a great question. Here is the quickest way I have found to set headers:

```php
$client->setDefer(true);
$request = $youtube->playlists->listPlaylists('snippet', array('id' => '6KzzScZSUrs'));
$request = $request->withHeader("If-None-Match", "\"$etag\");
$results = $client->execute($request);
```

**Comment by niklaswa** [comment]
I can't get it to work in the current version. I'd like to use etags too, but the method `withHeader` does not exist on my end unfortunately.
