### ISSUE TITLE
Can't use Google Translate, undefined method Google_Service_Translate_Resource_Translations::list

### ISSUE THREAD

**Issue by xorexore** [google/google-api-php-client#1089]
I have API 2.0 downlaoded via composer on 2016/06/21 and manually uploaded to my site.

I get this message:

`Error: Call to undefined method Google_Service_Translate_Resource_Translations::list()`

This is what I'm doing:

`require_once "/external/google-api-php-client/vendor_new/autoload.php";`
`$client = new Google_Client();`
`$client->setApplicationName(GAPI_APPLICATION_NAME);`
`$client->setAuthConfig(GAPI_CLIENT_SECRET);`
`$translate = new Google_Service_Translate($client);`
`$results = $translate->translations->list( $text, $target_language, '1' );`

I'm using API for several other things like analytics, shorturls, webmastertools... I'ts the first time I try with Translate.

Another doubt that I have is: What is the "CID" parameter? I don't find it anywhere. On the Service source code says:
"\* @opt_param string cid The customization id for translate"
What is a customization id?

When I do a var_dump(translate->translations); , I get this on the "methods" position:

`["methods":"Google_Service_Resource":private]=>`
`array(1) {`
`["list"]=>`
`array(3) {`
`["path"]=>`
`string(2) "v2"`
`["httpMethod"]=>`
`string(3) "GET"`
`["parameters"]=>`
`array(5) {`
`["q"]=>`
`array(4) {`
`["location"]=>`
`string(5) "query"`
`["type"]=>`
`string(6) "string"`
`["repeated"]=>`
`bool(true)`
`["required"]=>`
`bool(true)`
`}`
`["target"]=>`
`array(3) {`
`["location"]=>`
`string(5) "query"`
`["type"]=>`
`string(6) "string"`
`["required"]=>`
`bool(true)`
`}`
`["cid"]=>`
`array(3) {`
`["location"]=>`
`string(5) "query"`
`["type"]=>`
`string(6) "string"`
`["repeated"]=>`
`bool(true)`
`}`
`["format"]=>`
`array(2) {`
`["location"]=>`
`string(5) "query"`
`["type"]=>`
`string(6) "string"`
`}`
`["source"]=>`
`array(2) {`
`["location"]=>`
`string(5) "query"`
`["type"]=>`
`string(6) "string"`
`}`
`}`
`}`
`}`
`

Thanks.

**Comment by xorexore** [comment]
I've updated to latest version on composer and still doesn't work.

**Comment by bshaffer** [comment]
The function is `Google_Service_Translate_Resource_Translations::listTranslations`, not `list`. See [here](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Translate/Resource/Translations.php#L42)
