### ISSUE TITLE
There is no "vendor" folder in the downloaded files. Not works.

### ISSUE THREAD

**Issue by domrachev-insegment** [google/google-api-php-client#1093]
**Heads up!**

We appreciate any bug reports or other contributions, but please note that this issue
tracker is only for this client library. We do not maintain the APIs that this client
library talks to. If you have an issue or questions with how to use a particular API,
you may be better off posting on Stackoverflow under the `google-api` tag.

Thank you!

**Comment by bshaffer** [comment]
@domrachev-insegment have you tried downloading from the [releases](https://github.com/google/google-api-php-client/releases/tag/v2.0.3) section? Make sure you download the zip file `google-api-php-client-2.0.3.zip`

**Comment by domrachev-insegment** [comment]
I just press Download button on main page.
Thanx
