### ISSUE TITLE
Redirecting to OAuth servers 

### ISSUE THREAD

**Issue by Scott972** [google/google-api-php-client#1094]
Most documentation I've come across looks something like this:

 `$client->setClientId($this->_oAuth_client_id);`
`$client->setClientSecret($this->_oAuth_client_sectret);`
`$client->addScope('https://www.googleapis.com/auth/youtube.force-ssl');`
` $redirect_uri = 'https://url.com/callback';`
 `$client->setRedirectUri($redirect_uri);`
`$youtube = new Google_Service_YouTube($client);`

and then jumps directly to something like this:
`if(isset($_GET['code']))...`

Where does the redirect to google's auth servers come into to play here? I am able to get it if I build and send the request manually:

`

     $url = "https://accounts.google.com/o/oauth2/auth";
        $params = array(
            "response_type" => "code",
            "client_id" => $this->_oAuth_client_id,
            "redirect_uri" => 'https://url.com/callback',
            "scope" => "https://www.googleapis.com/auth/youtube.force-ssl"
        );

        $request_to = $url . '?' . http_build_query($params);

        header("Location: " . $request_to);`

Does `Google_Service_YouTube` suppose to initiate the redirect to the auth server?  I've tried every method in the `Google_Client` class that looks like it would redirect to auth, but nothing. No errors. No log messages etc..

**Comment by bshaffer** [comment]
The correct way to do this is by calling `Google_Client::createAuthUrl` and can be seen in [`simple-file-upload.php`](https://github.com/google/google-api-php-client/blob/master/examples/simple-file-upload.php):

```php
$authUrl = $client->createAuthUrl();
```
and then in the HTML:
```html+php
<?php if (isset($authUrl)): ?>
  <div class="request">
    <a class='login' href='<?= $authUrl ?>'>Connect Me!</a>
  </div>
```
