### ISSUE TITLE
Delete events from google calendar

### ISSUE THREAD

**Issue by PeterJason** [google/google-api-php-client#1100]
Hi

I can't delete events (with api) from google calendar, i can insert, list, etc..but i can't delete.

Can u see what's wrong?

Thank you.

**Comment by DevDGD** [comment]
did you find an answer?

**Comment by net-tools** [comment]
1 year later, I hope so !

**Comment by mariuszmalek** [comment]
Try this:

```
$service = new Google_Service_Calendar( $client );
$service->events->delete( 'primary', $event_id );
```
