### ISSUE TITLE
Analytics API: Update view (profile) error

### ISSUE THREAD

**Issue by simon-tannai** [google/google-api-php-client#1104]
Hi ! 

I'm working with Google Analytics Management and Views (in limited beta). 
I can create or delete a View without any issue, but the Update method return an error:

> PHP Fatal error:  Uncaught Google_Service_Exception: {"error":{"errors":[{"domain":"global","reason":"required","message":"Field currency is required."}],"code":400,"message":"Field currency is required."}} in /02 - Dev/google-analytics-tool/vendor/google/apiclient/src/Google/Http/REST.php:118

The code ([from example](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/profiles/update#examples)):

```
<?php
try {
  $this->_analytics->management_profiles->update($this->_accountId, $webPropertyId, $viewId, $profile);
  return true;
}
catch (apiServiceException $e) {
  echo "There was an Analytics API service error {$e->getCode()}: {$e->getMessage()}".PHP_EOL;
  return false;
}
catch (apiException $e) {
  echo "There was a general API error {$e->getCode()}: {$e->getMessage()}".PHP_EOL;
  return false;
}
?>
```

A solution exists ?

**Comment by mattwhisenhunt** [comment]
You may want to use [API Explorer](https://developers.google.com/apis-explorer/#p/analytics/v3/analytics.management.profileUserLinks.update) to poke around and find all the required fields. It sounds like you need to include currency in an update query.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We suggested some course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
