### ISSUE TITLE
I Cant Find Google Client Library Documentation 

### ISSUE THREAD

**Issue by mostafateto** [google/google-api-php-client#1108]
i have only one problem when i search about google client library for  (php) i cant find any documentation so i cant know library methods .

please any one know where i can find documentation for php tell me .

**Comment by net-tools** [comment]
Maybe on the [Google API Explorer](https://developers.google.com/apis-explorer/#p/) ? Methods are the same whichever language you code with.

Some links (PHP  samples available) : 

- [Drive API
](https://developers.google.com/drive/v2/reference/)
- [Calendar API](https://developers.google.com/google-apps/calendar/v3/reference/)
- [Gmail](https://developers.google.com/gmail/api/)

**Comment by bshaffer** [comment]
Thanks @net-tools !
