### ISSUE TITLE
Example Profile Filter Links with PHP client library

### ISSUE THREAD

**Issue by nowis-st** [google/google-api-php-client#1109]
Hi !

I saw that there isn't example with PHP client library on Profile Filter Links.
I had to search into sources to find methods ans her parameters.

So, I would like to help someone who's need to use Filter Links with PHP like me.
Here my code example for insert:
```php
$filterRef = new Google_Service_Analytics_FilterRef();

$filterRef->setId('123456789');

$profileFilterLink = new Google_Service_Analytics_ProfileFilterLink();
$profileFilterLink->setFilterRef($filterRef);

$analytics->management_profileFilterLinks
    // Account ID, Property ID, View ID, Google_Service_Analytics_ProfileFilterLink
    ->insert('123456', 'UA-123456789-1', '123456789', $profileFilterLink);
```

And example for list:

```php
$analytics->management_profileFilterLinks
    // Account ID, Property ID, View ID
    ->listManagementProfileFilterLinks('123456', 'UA-123456789-1', '123456789');
```

`management_profileFilterLinks` is an instance of `Google_Service_Analytics_Resource_ManagementProfileFilterLinks` class, defined in `vendor/google/apiclient-services/src/Google/Service/Analytics/Resource/ManagementProfileFilterLinks.php`.
You will find all methods into this file.

**Comment by bshaffer** [comment]
Thank you for providing this very helpful info!
