### ISSUE TITLE
Getting redirect_uri_mismatch error at the time of getting refresh token

### ISSUE THREAD

**Issue by jane027** [google/google-api-php-client#1115]
Hi,

I am using google client library to upload my products on google shopping. I have created project to get client id and secret. Also created merchant center account.

Now when I am trying to upload products with google credential and it is giving me a url to get refresh token. And when I am following the url given by this library to get refresh token then it is giving my "redirect_uri_mismatch" or 400 error.

I am not able to figure out what the issue is? I have tried lot of things to fix the same but still in problem.

Can anyone please tell me how can i get the refresh token?

**Comment by bshaffer** [comment]
You have to register your client's redirect uris in the cloud console. This is in **API Manager** > **Credentials**. Select (or create) a set of Web Credentials and you should see a section marked `Authorized redirect URIs`. Put the domain and path in there, and this should fix the issue.

**Comment by jane027** [comment]
Thanks for giving your solution. I have add my redirect uri in the field mentioned by you. But after adding redirect uri, still got the same issue "Redirect URI Mismatch"

My Redirect URI is: http://www.teststore.com/module/googleshopping/getrefreshtoken

What's wrong here?

**Comment by bshaffer** [comment]
What is the URL you are redirecting to? My best guess is there is a typo in your registered URL, you registered a different protocol (i.e. https vs http), or something along these lines.

**Comment by hellboy81** [comment]
@jane027 How can u solved this problem?

**Comment by redochka** [comment]
i have the same problem, how to solve please?

**Comment by bshaffer** [comment]
Make sure the redirect URL matches EXACTLY with what you've registered. It's possible you're using `http` in one and `https` in the other.

**Comment by redochka** [comment]
I am extremely sure that I have put the exact same URL. I also checked that there is trailing white spaces, etc. 

I have already setup perfectly fine this in the past, but today with this URL it's stuck... :(
