### ISSUE TITLE
Fatal error: Class 'Google\Auth\OAuth2' not found in /include/Google/Client.php on line 926

### ISSUE THREAD

**Issue by qvivi88** [google/google-api-php-client#1117]
**Missing Auth folder (I downloaded the whole sample from git)**

As per title, there's a line of code retrieving OAuth2, but there's no such "Auth" folder in git.
Is there any other complete documentation I can refer to? Thanks.

Thank you!

**Comment by bshaffer** [comment]
Please follow the instructions in the readme and install this library and
dependencies using composer.

**Comment by bshaffer** [comment]
Either of the options under `Installation` should do the trick: https://github.com/google/google-api-php-client#installation
