### ISSUE TITLE
Chunked downloading of large files via Drive service not possible?

### ISSUE THREAD

**Issue by mattsims** [google/google-api-php-client#1124]
Hi,

I am attempting to chunk-download a file using the Drive service with the following code:

    $response = $google_drive_service->files->get( $file_id, array( 'alt' => 'media' ) );

    $chunk_size_bytes = 1 * 1024 * 1024; // Download in 1 MB chunks

    $download_size = $response->hasHeader( 'Content-Length' ) ? $response->getHeader( 'Content-Length' )[0] : 0;

    $downloaded_bytes = 0;

    while ( ! $response->getBody()->eof() ) {
        fwrite( $file_handle, $response->getBody()->read( $chunk_size_bytes ) );

        $downloaded_bytes += $chunk_size_bytes;
        $downloaded_percent = $downloaded_bytes / $download_size * 100;
    }

I was expecting the `$response` object to be a file pointer that I could then stream the body (file contents) to a local file in chunks (allowing progress monitoring etc.).

However, it appears that the `get()` method loads the entire body into memory at that point, so the download is effectively completed before the `while()` loop is reached.

Is there a way to tell the response not to download the entire body at that point?  Issue #142 appears to relate to a similar problem and mentions using the `Range: bytes` header to specify a portion of the file, which could be a solution, but I can't work out how to specify this header so if anyone can enlighten me it would be much appreciated!

I have also investigated getting the file's `webContentLink` and then using curl to download that, but any files over 25 MB are firewalled with a 'Google cannot provide a virus-scan' page that then needs manual confirmation to proceed with the actual file download, hence problematic to script.

Chunked uploading works great, it just doesn't seem possible to do the same for downloads – not sure if this is a Google API limitation or something within the  client library?

Many thanks in advance for any pointers anyone may be able to give me to get around this!

**Comment by bshaffer** [comment]
Hello Matt!
You have two options here:

## Call not chunked

You can use the Guzzle client to call the API directly, and stream the response to a file without pulling the entire response into memory:

```php
$http = $client->authorize();
$url = sprintf('/drive/v3/files/%s', $fileId),
$response = $http->request('GET', $url, [
    'query' => ['alt' => 'media'],
]);
```
The downside is there is no chunked size specified, so you're still synchronously waiting for the download the entire time.

## Call in chunks

The Drive API requires the `Range` header to be set in order to download chunks from the API, so passing this option in allows you to download in chunks:

```php
$http = $client->authorize();
$chunkSizeBytes = 1 * 1024 * 1024; // Download in 1 MB chunks
$chunkStart = 0;
do {
    $chunkEnd = $chunkStart + $chunkSizeBytes;
    $response = $http->request(
        'GET',
        sprintf('/drive/v3/files/%s', $fileId),
        [
            'query' => ['alt' => 'media'],
            'headers' => [
                'Range' => sprintf('bytes=%s-%s', $chunkStart, $chunkEnd)
            ]
        ]
    );
    $chunkStart = $chunkEnd + 1;
    fwrite($fileHandle, $response->getBody()->getContents());
} while ($response->getHeaderLine('Content-Length') > 0);
```

I'm going to add an example for this.

**Comment by bshaffer** [comment]
Here is a full sample: #1127

**Comment by mattsims** [comment]
Thank you so much for taking the time to do this @bshaffer, much appreciated!

**Comment by hlaporthein** [comment]
Hello @bshaffer , I did exactly as you mentioned above but, the **while loop** is going infinity. So, I created a log file and logs file shows too many **255** from $response->getHeaderLine( 'Content-Length' ). Could you tell me why I am getting infinity loop.


```

//Download in 1 MB chunks
	$chunkSizeBytes = 1 * 1024 * 1024;
	$chunkStart     = 0;

// get the authorized Guzzle HTTP Client from Google_Client
	$http = $client->authorize();

// get the file ID and file size
	$files    = $service->files->listFiles( [
		'q'      => "name='photo4.jpg'",
		'fields' => 'files(id,size)',
	] );
	$fileId   = $files[0]->id;
	$fileSize = intval( $files[0]->size );

// make a call for each chunk and write it to a file
	$fileHandle = fopen( CO_THEME_DOC_ROOT . '/photo4.jpg', 'a+' );
	$logs = fopen(CO_THEME_DOC_ROOT .'logs.txt', 'a');
	do {
		$chunkEnd   = $chunkStart + $chunkSizeBytes;
		$response   = $http->request(
			'GET',
			sprintf( '/drive/v3/files/%s', $fileId ),
			[
				'query'   => [ 'alt' => 'media' ],
				'headers' => [
					'Range' => sprintf( 'bytes=%s-%s', $chunkStart, $chunkEnd ),
				],
			]
		);
		$chunkStart = $chunkEnd + 1;
		fwrite( $fileHandle, $response->getBody()->getContents() );
		fwrite($logs, $response->getHeaderLine( 'Content-Length' ) ."\n");
	} while ( $response->getHeaderLine( 'Content-Length' ) > 0 );

// close the file handle
	fclose( $logs );
	fclose( $fileHandle );

```

**Comment by Samutz** [comment]
I came across this same issue today. After getting the required data in chunks, it kept going with Content-Length always returning 225 instead of 0. This is because the server returns an error when requesting an invalid range.

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "requestedRangeNotSatisfiable",
    "message": "Request range not satisfiable"
   }
  ],
  "code": 416,
  "message": "Request range not satisfiable"
 }
}
```
So I changed the while condition to check the status code instead of Content-Length.
```
while ($response->getStatusCode()==206);
```

**Comment by hassanazimi** [comment]
@bshaffer I have used your code for downloading in MB chunks but this code downloads in KB instead of MB any ideas?
here is my code:

```php
$fp = fopen($tmpPath = Storage::disk('tmp')->path($fileName), 'w+');

			// Download in 3 MB chunks:
			$chunkSizeBytes = 1024 * 1024;
			$chunkStart = 0;

			// Iterate over each chunk and write it to our file
			do {
				$chunkEnd = $chunkStart + $chunkSizeBytes;
				logger()->info("Downloading chunk {$chunkStart} - {$chunkEnd} of {$file->size} bytes");

				$response = $http->request(
					'GET',
					sprintf('/drive/v3/files/%s', $file->file_id),
					[
						'query'   => ['alt' => 'media'],
						'headers' => [
							'Range' => sprintf('bytes=%s-%s', $chunkStart, $chunkEnd)
                                                           // 'Content-Length' => $chunkSizeBytes, // I added this and improved to 50KB but downloading never ends even after the file size exceeded!
						],
					]
				);
				$chunkStart = $chunkEnd + 1;
				fwrite($fp, $response->getBody()->getContents());
			} while ($response->getHeaderLine('Content-Length') > 0);

			fclose($fp);
```

**Comment by hassanazimi** [comment]
@Samutz you saved my ass. thank you
