### ISSUE TITLE
still having issues with invalid credentials

### ISSUE THREAD

**Issue by daemon-byte** [google/google-api-php-client#1125]
I have looked through the issues and seen this problem occurs before but I am running the latest 2.1.0 with a services account and it still seems to have the problem. It worked great at first but then it stopped running and gave me invalid credentials. I commented out the cache code and that gave me a JWT signature error. When I put in a new credential file it worked fine again for a while. Then it stopped with the same errors. My code is the following: 

```
$client = new Google_Client();
  #$cache = new Stash\Pool(new Stash\Driver\FileSystem);
  #$client->setCache($cache);
  $client->setApplicationName("Hello Analytics Reporting");
  $client->addScope(Google_Service_Analytics::ANALYTICS_READONLY);

  putenv("GOOGLE_APPLICATION_CREDENTIALS={$key}");
  $client->useApplicationDefaultCredentials();
  $analytics = new Google_Service_Analytics($client);
    
$optParams = array(
        'dimensions' => 'ga:pagePath',
        'filters' => "ga:pagePath=={$path}",
        );
    $results = $analytics->data_ga->get(
       'ga:' . $profileId,
       '2005-01-01',
       'today',
       'ga:uniquePageviews',
       $optParams);
```

**Comment by bshaffer** [comment]
@daemon-byte Try installing `2.1.1` and see if the problem persists.

**Comment by daemon-byte** [comment]
for reasons I still can't figure out my original credential file creates a JWT signature failure but the 2nd one I generated now never dies so that's good enough for me :) Thanks for solving it so quickly.
