### ISSUE TITLE
cuRL error 1

### ISSUE THREAD

**Issue by andershagebakken** [google/google-api-php-client#1126]
Hi. I am trying to upload a file, but I keep getting the following error: cURL error 1: Protocol "https" not supported or disabled in libcurl. I have installed curl with ssl. How can I fix this? Thanks.

**Comment by bshaffer** [comment]
This is not a problem with this library, but with your curl configuration. There may be additional steps you have to take even if you compile curl using `--with-ssl`. See the [curl documentation](https://curl.haxx.se/docs/install.html) for more information.
