### ISSUE TITLE
large-file-upload error

### ISSUE THREAD

**Issue by dinihou** [google/google-api-php-client#1136]
hi every one
i am new in google api , i wont to upload a big file with  large-file-upload.php
about 3.5 go but i have this error after operation begin

![img_18012017_213042](https://cloud.githubusercontent.com/assets/25209492/22083885/2de5fff8-ddce-11e6-9dc6-3d808029bad9.png)

any one can help ?

**Comment by bshaffer** [comment]
Hello @dinihou !
Can you tell me what version of cURL / PHP you are running? Post the result of `phpinfo();` here.

**Comment by dinihou** [comment]
hi @bshaffer 
sorry for the late , this my php info
(i can't attach so i upload )
http://ge.tt/6bcXXRi2

thank u for helping me bro

**Comment by mattwhisenhunt** [comment]
Maybe just attach a gist instead.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
