### ISSUE TITLE
Not returning nextSyncToken

### ISSUE THREAD

**Issue by waleedmazhar** [google/google-api-php-client#1141]
I am getting weird problem in google php calendar api. It is not returning nextsynctoken.

  ```
    This is var_export of $service->events->listEvents($calendarId, $optParams);
    
    Google_Service_Calendar_Events::__set_state(array(
       'collection_key' => 'items',
       'accessRole' => 'owner',
       'defaultRemindersType' => 'Google_Service_Calendar_EventReminder',
       'defaultRemindersDataType' => 'array',
       'description' => NULL,
       'etag' => '"p32o8lfd2qbkt20g"',
       'itemsType' => 'Google_Service_Calendar_Event',
       'itemsDataType' => 'array',
       'kind' => 'calendar#events',
       'nextPageToken' => NULL,
       'nextSyncToken' => NULL,
       'summary' => 'Meetings',
       'timeZone' => '',
       'updated' => '2017-01-30T10:18:50.782Z',
       'internal_gapi_mappings' => 
      array (
      ),
       'modelData' => 
      array (
        'defaultReminders' => 
        array (
        ),
        'items' => 
        array (
        ),
      ),
       'processed' => 
      array (
      ),
    ))
```

While in api explorer, it is sending nextsynctoken.

Thanks in advance.

**Comment by lfroidmo** [comment]
I have the exact same behavior with people API...

**Comment by lfroidmo** [comment]
Find the solution for the people API : see #1168. But not the same solution for the calendar API.

**Comment by mattwhisenhunt** [comment]
@waleedmazhar have you experienced this problem since 2.1.3 and the inclusion of requestSyncToken in optParams?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
