### ISSUE TITLE
Removal of Google_Signer_P12: Signing Urls with JWT

### ISSUE THREAD

**Issue by johan-lejdung** [google/google-api-php-client#1147]
Among other classes Google_Signer_P12 was removed in favor of firebase/jwt.

Although there is not example of how to migrate and how use this new function for signing urls.
Are there any claims that are mandatory?

**Comment by mattwhisenhunt** [comment]
I don't understand your question 'Are there any claims that are mandatory?' if v1 is still working for you I would stick with that for as long as possible.

Is Google_Signer_P12 the only breaking change keeping you from moving to v2?

**Comment by johan-lejdung** [comment]
I ended up moving over to 'google/cloud-storage' instead. But yes the fact that I were no longer able to create any signed URLs using the newer version was what were keeping me from moving version. I were talking about [JWT claims](https://tools.ietf.org/html/rfc7519). I really dont like the idea of sticking to an old and outdated version, just because.

**Comment by bshaffer** [comment]
We have some examples of how to migrate the previous functionality of the P12 credentials to the new JSON credentials. See [`UPGRADING.md`](https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#google_auth_assertioncredentials-has-been-removed)

**Comment by johan-lejdung** [comment]
Not really. I used it to sign a URL. All that is mentioned about the removed class `Google_Signer_P12 ` is:

```
firebase/jwt is now used for all JWT signing and verifying. As a result, the following classes have been changed or removed:
- Removed Google_Signer_P12
- Removed Google_Verifier_Pem
- Removed Google_Auth_LoginTicket (see below)
```
