### ISSUE TITLE
name spaces conflict when using with other libraries like google oauth signin/signup

### ISSUE THREAD

**Issue by saikiranmarripati** [google/google-api-php-client#1149]
I am using google oauth signin/signup and spreadsheet reader in my codeigniter project.

there is a namespace issue with using

`$client = new Google_Client();`

can u please fix this or suggest me how to overcome this problem.

**Comment by bshaffer** [comment]
Please elaborate on your issue. What is causing a namespace conflict? It's possible you have this library accidentally included twice and are therefore getting a `Class already defined` error.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
