### ISSUE TITLE
Support of php 5.4 in release 2.1.2

### ISSUE THREAD

**Issue by deepansh90** [google/google-api-php-client#1150]
The DCM/DFA Reporting and Trafficking API Service (DFAreporting.php) in google-api-php-client 2.1.1 is currently set to work with version v2.6 which will be sunset on may 31 (https://developers.google.com/doubleclick-advertisers/reporting/deprecation). 

When will there be a new release of php client that support php 5.4 and works with the newest version (v2.7) in time?

**Comment by bshaffer** [comment]
I believe you are on the `v1-master` branch. Check out the latest version ([`2.1.1`](https://github.com/google/google-api-php-client/releases/tag/v2.1.2)), which has [`2.7`](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Dfareporting.php#L19), or follow the instructions to [Use the latest API Services in V1](https://github.com/google/google-api-php-client-services#usage-in-v1).

**Comment by bshaffer** [comment]
Another possiblity is there's something else in your dependency tree that is forcing a lower version of the `google/apiclient-services` library. As you can see, `v2.1.2` supports [`google/apiclient-services:v0.9`](https://github.com/google/google-api-php-client/blob/v2.1.2/composer.json#L11), which in turn [supports DFA 2.7](https://github.com/google/google-api-php-client-services/blob/v0.9/src/Google/Service/Dfareporting.php). 

You could try explicitly requiring the dependency like this:

```
composer require google/apiclient-services:v0.9
```

And see what error is thrown. This will help you determine why you're not getting the correct version.

**Comment by bshaffer** [comment]
Version 2.1.2 does support php 5.4, so closing this issue.
