### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by GraceBasilioRomero** [google/google-api-php-client#1152]
Hi, there! Hope you are doing fine.

I've been trying to install google-api-php-client but I keep getting this:

> Problem 1
>     - The requested package google/cloud (installed at v0.13.0, required as 0.13.2) is satisfiable by google/cloud[v0.13.0] but these conflict with your requirements or minimum-stability.
>   Problem 2
>     - The requested package google/auth (installed at v0.10, required as ^0.11) is satisfiable by google/auth[v0.10] but these conflict with your requirements or minimum-stability.

Not sure what I'm doing wrong... pasting my composer.json below:

```
{
    "require": {
      "php": "~5.5.0|~5.6.0|~7.0.0",
      "google/cloud": "0.13.2",
      "silex/silex": "^1.3",
      "symfony/yaml": "^3.0",
      "twig/twig": "^1.22",
	  "google/auth":"^0.11",
        "google/apiclient-services": "^0.9"
    },
    "require-dev": {
      "behat/mink": "^1.7",
      "behat/mink-goutte-driver": "^1.2",
      "phpunit/phpunit": "~4",
      "symfony/browser-kit": "^3.0",
      "symfony/http-kernel": "^3.0",
      "google/cloud-tools": "^0.6"
    },
    "autoload": {
        "psr-0": {
            "Google_Service_": "src"
        }
    }
}
```

Can you please help?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
