### ISSUE TITLE
Problems with Drive Upload PHP

### ISSUE THREAD

**Issue by JURALOVE** [google/google-api-php-client#1156]
Hello frieds

I'm new in this community, but I have been watched projects very interesting, however I'm writting because I have one problem with Drive Upload PHP library. This code run, but it hasn't runned since 2 o 3 days. I have tried change credentials with new credentials and I changed to auth2, but I have the same problem:

PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message '{
 "error": "unauthorized_client",
 "error_description": "Client is unauthorized to retrieve access tokens using this method."

So, I imagine it's a token problem, but do you know any solution???

My code:

`<?php

	require_once ('google/vendor/autoload.php');
	
	putenv('GOOGLE_APPLICATION_CREDENTIALS=23.json');

	$client = new Google_Client();
	$client->useApplicationDefaultCredentials();
	$client->setApplicationName("MyApp");
	$client->setScopes(['https://www.googleapis.com/auth/drive']);
	$client->setSubject('*****@gmail.com');

	$service = new Google_Service_Drive($client);
	
	//Create a new folder
	$files= array();
	$dir = dir('tmp');
	while ($file = $dir->read()) {
		if ($file != '.' && $file != '..') {
			$files[] = $file;
		}
	}
	$dir->close();
       
	$file = new Google_Service_Drive_DriveFile();
	foreach ($files as $file_name) {
		$file_path = 'tmp/'.$file_name;
		$file->setName($file_name);
		$file->setDescription('Drive BK');
		$file->setMimeType('application/tar.gz');
		$createdFile = $service->files->create($file, array(
		'data' => file_get_contents($file_path),
		'mimeType' => 'application/zip',
		'uploadType' => 'media'
		));
	}
	
	$dir = dir('tmp');
	chdir('tmp');
	
	while ($file = $dir->read()) {
		if ($file != '.' && $file != '..') {
			$t=unlink($file);
		}
	}
	$dir->close();
?>`

Thank you for watching, and suggestions 

Regards

**EDIT: I have kwown SSL has changed, can it be the problem?**

**Comment by MarcGuay** [comment]
I am also having this problem.

**Comment by net-tools** [comment]
I'm using Drive API and I'm not having this issue. 

Do you still have it ? Have you tried to setup your `Google_Client` with direct method calls instead of using the json file ? :

```php
$client->setClientId('xxxx');
$client->setClientSecret('xxx');
```

By the way, I'm not sure the `setSubject` is relevant, unless you are using a service account.

**Comment by MarcGuay** [comment]
I believe that the OP is using a service account.  My problem was resolved by "Delegating domain-wide authority to the service account" as described here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

**Comment by JURALOVE** [comment]
Hello net-tools and MarcGuay

Thank you for all. I'll study your suggestions on the next week and I'll talk about my progresss. One thing more, I'm trying to use a service account.

**Comment by JURALOVE** [comment]
@MarcGuay  one question. When you have enabled "Delegating domain-wide ...", Have you had to make some thing to run???

**Comment by MarcGuay** [comment]
@JURALOVE I'm not sure that I understand your question but I don't believe I had to change any code after following the instructions for delegating domain-wide authority.

**Comment by JURALOVE** [comment]
Thank you friends. I have found a solution for my problem, but finally I haven't used service account

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
