### ISSUE TITLE
Uncaught exception upon refreshing the page

### ISSUE THREAD

**Issue by hiddekat** [google/google-api-php-client#1157]
Fatal error: Uncaught InvalidArgumentException: Invalid token format in (...)

Whenever I refresh the page I will get this error. The token is not in wrong format, it's been used (and therefor it probably doesn't work), but I want to prevent that my users see these messages. It should just fetch a new code. Is there a way?

My code:

	require_once 'system/plugins/Google/vendor/autoload.php';
	$client = new Google_Client();

	$client->setAuthConfig('*/google_secret.json');
	$client->addScope('openid email');
	$redirect_uri = '*/google';
	$client->setRedirectUri($redirect_uri);
	
	if (isset($_GET['code'])) {
		try {
			$token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
			$client->setAccessToken($token);
		}
		catch (\Google_Service_Exception $e) {
			print_r($e);
		}
	}

	if (!isset($token)) {          
		// Generate an URL to request access from Google's OAuth 2.0 server:
		$authUrl = $client->createAuthUrl();
			  
		// Redirect the user to Google's OAuth server
		header('Location: ' . filter_var($authUrl, FILTER_SANITIZE_URL));
		exit();
			  
	} 
	$access_token = $token;

	$oauth2Service = new Google_Service_Oauth2($client);
	$guserinfo = $oauth2Service->userinfo;
	$userinfo = $guserinfo->get();

**Comment by mohe2015** [comment]
I think it means the code is valid just once. You should save the $token var für example in the user's session var after you generated it from the code using fetchAccessTokenWithAuthCode. Then you just have to call setAccessToken with the previous saved token.

**Comment by net-tools** [comment]
Yes, the `code` uri parameter is valid only once. 

Thanks to `fetchAccessTokenWithAuthCode` you exchange this code to an access token.

Depending on your setup (offline access or not), the token may be used for 1 hour or indefinitely used (in that case, the token includes a refresh token).

Save the token in session, as mohe2015 suggested, database or any relevant storage, and reuse-it at any time through `setAccessToken`.

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.
