### ISSUE TITLE
Error Class 'Google_Service_SearchConsole' not found / Access to API - SearchConsole not service object (Server to Server Applications)

### ISSUE THREAD

**Issue by semiromid** [google/google-api-php-client#1159]
Error - Class 'Google_Service_SearchConsole' not found

I not can find service object for **SearchConsole**:

_Using OAuth 2.0 for Server to Server Applications_
[](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)

Need get access to API  - **SearchConsole**

I have PHP code:

```
$json_file = __DIR__.'/OAuth2-0-ec277a9ccbc0.json';
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/'.$json_file);
$client = new Google_Client();
$client->useApplicationDefaultCredentials();

$sqladmin = new Google_ServiceSearchConsole($client); // need service object for **SearchConsole**
```

**Comment by himmerman** [comment]
that is not the right service object for search console.
`$search_console = new Google_Service_Webmasters($client);`
