### ISSUE TITLE
I just want to ask, is this using the V3 or the V2 Api? 

### ISSUE THREAD

**Issue by MiguelQueiroz** [google/google-api-php-client#1160]

**Comment by bshaffer** [comment]
Hey @MiguelQueiroz ! This library uses multiple APIs, so you'll have to be more specific. Which API are you asking about?

**Comment by MiguelQueiroz** [comment]
Drive API. But i looks like its V3

**Comment by bshaffer** [comment]
@MiguelQueiroz Correct!
