### ISSUE TITLE
support for Android enterprise?

### ISSUE THREAD

**Issue by ndubbaka** [google/google-api-php-client#1165]
Can anyone suggest me some sample code on using Android enterprise functionality here https://github.com/google/google-api-php-client-services/tree/master/src/Google/Service/AndroidEnterprise ?

I am looking to build an EMM console in PHP using Play EMM API https://developers.google.com/android/work/setup

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
