### ISSUE TITLE
Use of auth_uri and token_uri from auth configuration object

### ISSUE THREAD

**Issue by stevenscg** [google/google-api-php-client#1167]
Question: Are the `auth_uri` and `token_uri` values from the auth configuration object downloaded from the developer console used by the library?

Example:
```json
{
    "web": {
        "client_id": "XXXXX.apps.googleusercontent.com",
        "project_id": "dummy-id",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "YYYYYY",
        "redirect_uris": [
        ],
        "javascript_origins": [
        ]
    }
}
```

I looked through the code and searched here and did not find any obvious usage of these.

We have a use case where we need to be able to direct some requests to a different host (think something like Runscope or an internal proxy) by providing the new URIs via the configuration object.

**Comment by stevenscg** [comment]
@bshaffer Do you happen to know if the `auth_uri` and `token_uri` values from the auth configuration object downloaded from the developer console used by the library?

**Comment by mattwhisenhunt** [comment]
It looks like they are hardcoded: https://github.com/google/google-api-php-client/blob/a68d080658241cd059cd3434c55193630197f47f/src/Google/Client.php#L947

**Comment by RENSAAS** [comment]
https://github.com/googleapis/google-api-php-client/issues/1167

**Comment by RENSAAS** [comment]
[[
  {
    "id": "pudgy-penguins",
    "contract_address": "0xBd3531dA5CF5857e7CfAA92426877b022e612cf8",
    "asset_platform_id": "ethereum",
    "name": "Pudgy Penguins",
    "symbol": "PPG",
    "image": {
      "small": "https://coin-images.coingecko.com/nft_contracts/images/38/small/pudgy.jpg?1730778323",
      "small_2x": "https://coin-images.coingecko.com/nft_contracts/images/38/small_2x/pudgy.jpg?1730778323"
    },
    "description": "Pudgy Penguins is a collection of 8,888 unique NFTs featuring cute cartoon penguins, which are generated from a collection of 150 different hand-drawn traits...",
    "native_currency": "ethereum",
    "native_currency_symbol": "ETH",
    "floor_price": {
      "native_currency": 12.17,
      "usd": 44360
    },
    "market_cap": {
      "native_currency": 108211,
      "usd": 394267328
    },
    "volume_24h": {
      "native_currency": 402.37,
      "usd": 1466028
    },
    "floor_price_in_usd_24h_percentage_change": 8.27604,
    "floor_price_24h_percentage_change": {
      "usd": 8.27603609555289,
      "native_currency": 1.6277092654424
    },
    "": {
      "usd": 8.27603609555281,
      "native_currency": 1.6277092654424
    },
    "one_day_average_sale_price_24h_percentage_change": {
      "usd": 32.6876748821441,
      "native_currency": 24.5404332508984
    },
    "number_of_unique_addresses": 4756,
    "number_of_unique_addresses_24h_percentage_change": 0.10524,
    "volume_in_usd_24h_percentage_change": 32.68767,
    "total_supply": 8888,
    "one_day_sales": 33,
    "one_day_sales_24h_percentage_change": [22.2222222222222](https://github.com/googleapis/google-api-php-client/issues/1167),
    "one_day_average_sale_price": 12.1929990290909,
    "": 1.8967181143714
  }
]](url)
