### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by anuragprasad95** [google/google-api-php-client#1169]
![driveer](https://cloud.githubusercontent.com/assets/3609255/23812652/6cc43fcc-0601-11e7-8416-d1b85bac954a.jpg)

While i was installing the api,i got this error.

Your requirements could not be resolved to an installable set of packages.

Problem 1 - The requested package google/apiclient No version set (parsed as 1.0.0) is satisfiable by googlee/apiclient [No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum stability.

Problem 2 - Installation request for google/apiclient 2.0 ->satisfiable by google/apiclient[v2.0.0].
      -google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8] but these conflict with your requirements or minimum-stability.

**Comment by bshaffer** [comment]
try surrounding `google/apiclient:^2.0` in quotes:
```
composer require "google/apiclient:^2.0"
```

**Comment by vkisku** [comment]
delete the composer.json and other composer related files from the directory and you will be fine. you can also omit ^2.0(version), that will install the latest version if that is what you want.

**Comment by bshaffer** [comment]
@anuragprasad95 try adding `"google/apiclient": "^2.0"` directly to your `composer.json` file under `"required"`, and then running `composer update`:

```
{
    "required": {
        // other dependencies of yours
        "google/apiclient": "^2.0"
    }
    // other stuff in your composer.json file
}
```
