### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by yourchoice** [google/google-api-php-client#1170]
I mention that before that I already had installed (Composer version 1.4.1 2017-03-10 09:29:45):
> composer require minishlink/web-push
> composer require phpmailer/phpmailer

>composer require google/apiclient:^2.0 

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Installation request for google/apiclient 2.0 -> satisfiable by google/apiclient[v2.0.0].
    - Conclusion: remove guzzlehttp/psr7 1.4.1
    - Conclusion: don't install guzzlehttp/psr7 1.4.1
    - google/auth v0.8 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzlehttp/psr7[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - Can only install one of: guzzlehttp/psr7[1.2.0, 1.4.1].
    - Can only install one of: guzzlehttp/psr7[1.2.1, 1.4.1].
    - Can only install one of: guzzlehttp/psr7[1.2.2, 1.4.1].
    - Can only install one of: guzzlehttp/psr7[1.2.3, 1.4.1].
    - Installation request for guzzlehttp/psr7 (locked at 1.4.1) -> satisfiable by guzzlehttp/psr7[1.4.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by bshaffer** [comment]
Try adding the `google/apiclient` requirement directly to `composer.json` and then running `composer update`:

```json
{
    "require": {
        "minishlink/web-push": "^1.4",
        "phpmailer/phpmailer": "^5.2",
	"google/apiclient":"^2.0"
    }
}
```

I followed these instructions and was able to install the library no problem. It installed `2.1.2`.
