### ISSUE TITLE
Bug in code (leeway is set to 1 rather than being increased by 1)

### ISSUE THREAD

**Issue by hamzawain7** [google/google-api-php-client#1172]
In google-api-php-client/src/Google/AccessToken/Verify.php line 213 you are not adding 1 to JWT leeway like you mentioned in the comments but rather setting it to 1. Kindly fix it.

if (property_exists($jwtClass, 'leeway')) {
// adds 1 second to JWT leeway
$jwtClass::$leeway = 1;
}

**Comment by danielhiga** [comment]
I also have problems with this. I often have more than a second offset.
I set leeway before instantiate Google_AccessToken_Verify. But this code overrides my value for 1 second.

**Comment by adrienlamotte** [comment]
Same here. 
For the moment I just changed Verify.php to : 
`$jwtClass::$leeway += 1;`

**Comment by highstrike** [comment]
When is this going to get fixed?

**Comment by sciamano89** [comment]
Please fix. Should take 1 second to add a + in front of an =
😁

**Comment by scottybo** [comment]
Any word on this?

**Comment by StenKoning** [comment]
nope

2018-06-13 15:16 GMT+02:00 Scott Bowler <notifications@github.com>:

**Comment by bshaffer** [comment]
I have submitted a PR #1455 to fix this effectively. There has been the ability to [pass in your own JWT service](https://github.com/google/google-api-php-client/blob/master/tests/Google/AccessToken/VerifyTest.php#L95) so that this leeway is not called:

```php
// Create the Google client object
$client = new Google_Client();
// Create the JWT service and set Leeway (if you want)
$jwt = new Firebase\Jwt\Jwt;
$jwt::$leeway = 1.5;
// pass the JWT service into the Verify class and verify the ID token
$verify = new Google_AccessToken_Verify($client->getHttpClient(), null, $jwt);
$payload = $verify->verifyIdToken($token['id_token'], $data->aud);
```

Global `Firebase\Jwt\Jwt::$leeway` is never changed.
