### ISSUE TITLE
I try to get GA stats for some pages in a loop, but after around 20 iterations I get cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by yourchoice** [google/google-api-php-client#1173]
I try to get google analytics stats for some pages in a loop, but after around 20 iterations I get "cURL error 60: SSL certificate problem". I tried with 10 iterations in loop and working. My loop is limited to 60 iterations, but seems that around iteration 20, crashes with this error: 

> PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
> Stack trace:
> #0 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
> 
> Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
> Stack trace:
> #0 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 ...\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

Google Client:

```
$client = new Google_Client();
$client->setAuthConfig($this->clientSecretsPath);
$client->addScope(Google_Service_Analytics::ANALYTICS_READONLY);
$client->setAccessType('offline');
$client->setApprovalPrompt('force');
$client->setRedirectUri($cfg_gapi['redirect']);
$httpClient = new \GuzzleHttp\Client(array( 'curl' => array( CURLOPT_SSL_VERIFYPEER => false ), ));//CURLOPT_CAINFO => $this->cacertPath,
$client->setHttpClient($httpClient);
```

For $httpClient I tried and CURLOPT_CAINFO , but same result.

I try to get stats for details pages in a recipe web site: sessions, visits, uniquevisits for 2years ago, 1 year ago, 30 days ago, 7days ago, 1 day ago. I have around 50000 recipes. Seems that hard to get these stats.

Any help can be useful.
Thank You.

**Comment by yourchoice** [comment]
..PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message '{
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "errors": [
      {
        "message": "The service is currently unavailable.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "UNAVAILABLE"
  }
}

**Comment by bshaffer** [comment]
If you're getting backend errors, you should try to retry the service. If you're getting a certificate error, try the following:

* Save the following to `cacert.pem`: https://curl.haxx.se/ca/cacert.pem

* put it here:

    > C:\xampp\php\extras\ssl\cacert.pem

* in your php.ini put this line in this section:
    ```
    ;;;;;;;;;;;;;;;;;;;;
    ; php.ini Options  ;
    ;;;;;;;;;;;;;;;;;;;;

    curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"
    ```
* restart your webserver/apache
