### ISSUE TITLE
Google Analytic 》 Reporting API V4, when I run php error

### ISSUE THREAD

**Issue by df257** [google/google-api-php-client#1175]
I read this document: https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-php

when I run php error:
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\wamp\www\test_google\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
( ! ) GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\wamp\www\test_google\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by df257** [comment]
![qq](https://cloud.githubusercontent.com/assets/7835444/23986122/8c416086-0a5d-11e7-859a-26ceca58710f.jpg)

**Comment by bshaffer** [comment]
If the SSL certificates are not properly installed in your system, you may get this error:

    cURL error 60: SSL certificate problem: unable to get local issuer certificate.
    You can solve this issue as follows:

1. Download a file with the updated list of certificates from https://curl.haxx.se/ca/cacert.pem

1. Move the downloaded cacert.pem file to some safe location in your system

1. Update your php.ini file and configure the path to that file:
    ```
    ; Linux and macOS systems
    curl.cainfo = "/path/to/cacert.pem"

    ; Windows systems
    curl.cainfo = "C:\path\to\cacert.pem"
    ```

Alternatively, add the `cacert.pem` file to your application and then set the Guzzle Client to use it:

```php

$client = new Google_Client();
$client->setHttpClient(new GuzzleHttp\Client([
    'verify' => '/path/to/cacert.pem',
]);
```

**Comment by df257** [comment]
@bshaffer It not work, problems still exist

**Comment by df257** [comment]
My environment is wampserver2.5, win32

**Comment by df257** [comment]
php.ini is in apache/bin

**Comment by df257** [comment]
![qq 20170317112033](https://cloud.githubusercontent.com/assets/7835444/24027612/c229252a-0b03-11e7-935b-1f37ab0078ed.gif)
Strange, suddenly there is a change! Nothing different to change.
![qq](https://cloud.githubusercontent.com/assets/7835444/24027644/0c154a4c-0b04-11e7-902c-d4f9c022b777.jpg)

**Comment by df257** [comment]
Problem solved

**Comment by clever-ro-oliveira** [comment]
My issue has been resolved by adding a backslash (\) before GuzzleHttp:
$client->setHttpClient(new \GuzzleHttp\Client(['verify' => false]));
