### ISSUE TITLE
Installation instructions don't make sense without composer

### ISSUE THREAD

**Issue by xgretsch** [google/google-api-php-client#1176]
The "download directly" instructions don't make sense: without composer, there isn't a "vendor" directory, and it's not clear how to create an autoload.php file - the one in the package says that it's for legacy compatibility only and should not be used.

By the way, I realise that composer is the preferred way of installation. However, the instructions given result in a download of 5107 files in 318 directories - crazily overweight when all I'm trying to do is use the authentication.

**Comment by jdpedrie** [comment]
If you don't want to use composer, you can download one of the releases from the [releases](https://github.com/google/google-api-php-client/releases) page. (Choose one of the .zip files such as google-api-php-client-2.1.1.zip.)

Those will still have all the required dependencies though. The only difference is that the `composer install` piece is done for you.

**Comment by xgretsch** [comment]
So is there genuinely no solution which does the authentication in less than 5000 files?

**Comment by rasiciliano** [comment]
Yes i dont understand how to install in my we without composer

**Comment by bshaffer** [comment]
The way to install without composer is to go to the [releases](https://github.com/google/google-api-php-client/releases) page and click `google-api-php-client-2.1.1.zip`. You then unzip the resulting package, place it wherever you'd like in your code, and include the file `vendor/autoload.php` anywhere:

```php
<?php

require_once '/path/to/google-api-php-client-2.1.1/vendor/autoload.php';

// All the classes are now autoloaded!
$client = new Google_Client();
```

**Comment by rasiciliano** [comment]
thanks @bshaffer i do that!! .  but them i get this "Parse error: syntax error, unexpected '[' in /home/tripleho/public_html/presite/calendar/vendor/guzzlehttp/psr7/src/functions.php on line 78"

its a bug on the API ?

**Comment by bshaffer** [comment]
@rasiciliano This is because you're most likely running a version of PHP lower than PHP 5.4, which is not supported.
