### ISSUE TITLE
Missing clear indication how to use oauth 2.0 with picasa

### ISSUE THREAD

**Issue by JorricksTU** [google/google-api-php-client#1179]
Hello,

I was wondering how I could use this library to later connect to picasa.
The requested function is to connect from the server to the picasa album function (in an authenticated manner). Could someone shed some light on the solution please?

**Comment by JorricksTU** [comment]
How can I be so stupid.. I completely missed the readMe.. Sorry for the annoying issue, please remove it if possible :)

**Comment by bshaffer** [comment]
Hey no problem! I assume you found your answer in the [Making HTTP Requests Directly](https://github.com/google/google-api-php-client#making-http-requests-directly) section?
