### ISSUE TITLE
Support Guzzle 6.x

### ISSUE THREAD

**Issue by dluces** [google/google-api-php-client#1182]
Guzzle 6.2.1 was released almost a year ago and it addresses some important [issues](https://github.com/guzzle/guzzle/releases/tag/6.2.1). However, this library only supports 5.2x and 6.0.x. I believe there's no breaking changes in the 6.x versions, so maybe a change to `^6.0` in the `composer.json` file should be enough.

**Comment by bshaffer** [comment]
In this context, the tilde (`~`) and caret (`^`) mean the same thing. They only diverge with versions `< 1.0` (see [docs](https://getcomposer.org/doc/articles/versions.md#tilde))

If you install and inspect the `composer.lock` file, you'll see the following:

```
"name": "guzzlehttp/guzzle",
 "version": "6.2.3",
```

So the current version supports Guzzle 6.2.

**Comment by dluces** [comment]
@bshaffer You're absolutely right. This should have been a dependency issue in my project.
