### ISSUE TITLE
cURL error 6: Could not resolve host: www.googleapis.com

### ISSUE THREAD

**Issue by irasmaster** [google/google-api-php-client#1184]
I get such exception trying to authenticate in Google-API:

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: www.googleapis.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 ../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 ../vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 ../vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 ../vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 ../vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(72): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 ../vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 ../vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 ../vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 ../vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 ../vendor/guzzlehttp/guzzle/src/Client.php(275): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 ../vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 ../vendor/guzzlehttp/guzzle/src/Client.php(104): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#13 ../vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(34): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#14 ../vendor/google/auth/src/OAuth2.php(492): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
#15 ../vendor/google/apiclient/src/Google/Client.php(190): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle6HttpHandler))

**Comment by irasmaster** [comment]
Resolved :)

**Comment by omarllorens** [comment]
@irasmaster Can you explain how did you fixed this error, please?

**Comment by go-yaro** [comment]
@irasmaster i have a same error with you. can you talk more about the solution? thx

**Comment by irasmaster** [comment]
@omarllorens @go-yaro In my case, it was a server problem. Puppet updated libc, after what apt should restart dependant services, including php-fpm, but it didn't. So solution was the script to restart PHP after every package update.

**Comment by omarllorens** [comment]
Thank you @irasmaster !

**Comment by go-yaro** [comment]
@ianbarber it works for me. thank you.

**Comment by Paratron** [comment]
I had the same error today developing locally in a vagrant box.
Turns out the vagrant box had network issues after my machine went once to hibernate and back up. I restarted the vagrant instance end everything works fine again!

**Comment by masjoey** [comment]
just restart your server from whm

**Comment by ashley7** [comment]
Just restart your server

**Comment by Simprosys-InfoMedia** [comment]
Hello, We are also getting Same Daily at the same time. So can you someone please help me how to resolver this permanently?

**Comment by ashley7** [comment]
When I was on localhost, Some requests would return that error and sometimes they would pass and return results, but since I went live, I have never seen them, even the speeds increased

**Comment by Meenu-Jain** [comment]
I also restarted my server and it worked

**Comment by vicdecode** [comment]
Sometimes this happens when the nameservers for google are not set in your /etc/resolv.conf file. You can fix it by doing this: https://stackoverflow.com/questions/24967855/curl-6-could-not-resolve-host-google-com-name-or-service-not-known

**Comment by rdundon** [comment]
At the risk of being redundant, restarting also works when encountering this error in a docker instance.

**Comment by bfsim** [comment]
Had the same issue today. It was a VPN issue. Once ExpressVPN was disconnected: worked again!
