### ISSUE TITLE
 PHP Warning: A non-numeric value encountered in src/Google/Logger/Abstract.php on line 371

### ISSUE THREAD

**Issue by chriscct7** [google/google-api-php-client#1185]
On the 1.x branch, the following error was reported on a PHP 7.1 NGINX  install:
```
[error] 8772#0: *178045 FastCGI sent in stderr: “PHP message: PHP Warning: A non-numeric value encountered in src/Google/Logger/Abstract.php on line 371” while reading response header from upstream
```

Here's the affected code (lines 367 - 375):
```
    if (version_compare(PHP_VERSION, '5.4.0', '>=')) {
      $options = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
      if ($this->allowNewLines) {
        $options |= JSON_PRETTY_PRINT; // <-- line 371 in question
      }
      return @json_encode($value, $options);
    }
```

Given the logical OR's on 3 constants that are defined by PHP to be ints I'm not sure how this error is possible, but maybe if a distro is overriding the default PHP constants it might be prudent to cast the constants to integers (in case the distro is defining them as booleans)

**Comment by bshaffer** [comment]
I would suggest upgrading to `^2.0` of this library, as we no longer support `v1`.

**Comment by chriscct7** [comment]
@bshaffer Version 2.x requires PHP 5.4 or newer though right?

**Comment by bshaffer** [comment]
Indeed it does :(

If you're running a lower version of PHP, and you find a fix, I'd be happy to merge it.
