### ISSUE TITLE
Can google update Client.php line 479 to isset the $this->token['expires_in'])

### ISSUE THREAD

**Issue by elvis-hammerulo** [google/google-api-php-client#1186]
from :

$expired = ($created
      + ( $this->token['expires_in']  - 30)) < time();

to :
$expired = ($created
      + (isset($this->token['expires_in']) ? $this->token['expires_in'] : 0 - 30)) < time();

Here my code: 

                // create the Google client
                $client = new Google_Client();
                $client->setAccessToken(Session::get('google_provider_token'));
                // get user email address
                $google_oauth =new Google_Service_Oauth2($client);
                $google_account_email = $google_oauth->userinfo->get();
                $http = $client->authorize();
                // the userID to post for, which has already been authorized by your oauth client
                $userId = $google_account_email->getID();
                // create the URL for this user ID
                $url = sprintf('https://www.googleapis.com/plusPages/v2/people/%s/activities', $userId);
                // create your HTTP request object
                $headers = [
                    'content-type' => 'application/json',
                ];

                $body = [
                  "object" => [
                        "content" =>  $request->message,
                        "attachments" => [
                            ["url" => route('contentpage', $slug)],
                        ],
                  ],
                  "access" => [
                    "items" => [
                        ["type" => "public"]
                    ],
                  ]
                ];

                $postGooglePlus = new \GuzzleHttp\Psr7\Request('POST', $url, $headers, json_encode($body));
                // make the HTTP request
                $response = $http->send($postGooglePlus);

**Heads up!**

We appreciate any bug reports or other contributions, but please note that this issue
tracker is only for this client library. We do not maintain the APIs that this client
library talks to. If you have an issue or questions with how to use a particular API,
you may be better off posting on Stackoverflow under the `google-api` tag.

Thank you!

**Comment by dextermb** [comment]
I am having the same issue with an undefined index of `expires_in` at `Client.php:480` (`isAccessTokenExpired()`).

Here is a quick fix:
```
return ($created + (isset($this->token['expires_in']) ? $this->token['expires_in'] : 3600 - 30)) < time();
```

**Comment by elvis-hammerulo** [comment]
Thanks dextermb,

I already resolved the issue by adding  refreshToken() method in order to get the 'expires_in' variable since I'm using laravel socialite on login authentication to get token.       
      
$token = $client->refreshToken(Session::get('google_provider_token'));
$client->setAccessToken($token);

So, no need to update the core file everytime the composer updates ran :)

**Comment by dextermb** [comment]
@elvis-hammerulo surely your _fix_ doesn't actually resolve the issue, you're just skipping checking if the access token has expired or not. You're making extra requests where they might not be needed? 💀

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free explain why you believe fixing it is essential for users of this client library.
