### ISSUE TITLE
Resumable File Upload error

### ISSUE THREAD

**Issue by usmanfm** [google/google-api-php-client#1188]
I am unable to perform resumable upload using this api please Help Me

MY Code

`                            $storageObject->setName("FIle Name.mp3");
				
                              $storageObject->setBucket($data["bucket_name"]); 

				$mimetype = mime_content_type($data["temp_name"]);

				$chunkSizeBytes = 1 * 1024 * 1024;

				$storageClient->setDefer(true);

				$status = false;

				$filetoupload = array('name' => "FIle Name.mp3", 'uploadType' => 'resumable');

	

				$request = $storageService->objects->insert( $data["bucket_name"], $storageObject, $filetoupload );

				$media = new Google_Http_MediaFileUpload($storageClient, $request, $mimetype, null, true, $chunkSizeBytes);

				$media->setFileSize(filesize($data["file_temp_name"]));
				$handle = fopen($data["file_temp_name"], "rb");

				while (!$status && !feof($handle)) 
				{
				   $chunk = fread($handle, $chunkSizeBytes);
				   $status = $media->nextChunk($chunk);
				}

				$result = false;
				if($status != false) {
				$result = $status;
				}

				fclose($handle);
				// Reset to the client to execute requests immediately in the future.
				$storageClient->setDefer(false);`

my error 
 **{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "wrongUrlForUpload",
    "message": "Upload requests must include an uploadType URL parameter and a URL path beginning with /upload/",
    "extendedHelp": "https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload"
   }
  ],
  "code": 400,
  "message": "Upload requests must include an uploadType URL parameter and a URL path beginning with /upload/"
 }
}**

**Comment by mattwhisenhunt** [comment]
Check out https://github.com/GoogleCloudPlatform/google-cloud-php to access this Google Cloud API.
