### ISSUE TITLE
Tag a new release that includes upgrade to apiclient-services v0.11

### ISSUE THREAD

**Issue by kalifg** [google/google-api-php-client#1190]
In #1171 the `apiclient-services` dependency was upgraded to v0.11.  This includes some fixes to file naming that were causing conflicts on Macs and other systems with case-insensitive file systems.

Because of this I have had to upgrade my PHP project to point to a specific commit of this project instead of being able to follow `~2.0`.  Are there any plans to create a new release soon?

Thank you for all of your work!

**Comment by bshaffer** [comment]
Done! Thanks for the bump.

https://github.com/google/google-api-php-client/releases/tag/v2.1.3

**Comment by kalifg** [comment]
Thank you!
