### ISSUE TITLE
pageSize parameter has no effect

### ISSUE THREAD

**Issue by dewahab** [google/google-api-php-client#1192]
Google API V3
PHP Framework: Yii2
PHP Version: 5.6.3
Drive URL: https://www.googleapis.com/drive/v3/files?pageSize=3&orderBy=folder%2Cname

I have 64 (files+folders) in my drive. It always returns 64 files, no matter what number is specified for pageSize parameter. Below is the function I used:

```
function files($service, $folder='', $params=['pageSize' => 1, 'orderBy' => 'folder,name'])
{
	$result = [];
	$pageToken = NULL;

	do
	{
		try
		{
			$parameters = [];
				
			if ($pageToken)
				$parameters['pageToken'] = $pageToken;

			$parameters = array_merge($parameters, $params);

			$files = $service->files->listFiles( $parameters );

			$result = array_merge($result, $files->getFiles());
			$pageToken = $files->getNextPageToken();
		}
			
		catch (Exception $e)
		{
			print "An error occurred: " . $e->getMessage();
			$pageToken = NULL;
		}

	} while ($pageToken);
		
	return $result;
}
```

**Comment by mattwhisenhunt** [comment]
It may be a minimum limit. Have you tested this on [API Explorer](https://developers.google.com/apis-explorer/#p/)?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
