### ISSUE TITLE
LIBVER not updated in src/Google/Client.php - Release ver 2.1.3

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [google/google-api-php-client#1193]
Hi,

I downloaded 2.1.3 release and checked src/Google/Client.php. i found  const LIBVER = "2.1.2";
Plz let me know why LIBVER not updated. Am I using correction ver 2.1.3 release?

**Comment by DHANDAPANISATTANATHAN** [comment]
Hi,

Any updates why LIBVER = 2.1.2 still in VER 2.1.3?

**Comment by mattwhisenhunt** [comment]
Looks like this have been fixed.
