### ISSUE TITLE
fetchAccessTokenWithAssertion "json key is missing the type field"

### ISSUE THREAD

**Issue by danielmajor** [google/google-api-php-client#1200]
We're trying to use fetchAccessTokenWithAssertion with an OAuth2 json file, but are currently receiving: "json key is missing the type field".  It looks like the 'type' is not being sent in through $jsonKey, but everything else is - any ideas on why this may be happening?

Also - is this the best route to use for creating an access token *without* the user having to login?  I'm hoping to use OAuth2 since that seems to be required by Google Ads API (from what I can tell).

Thanks in advance for any input here!

**Comment by bshaffer** [comment]
Hey! Yes, this is the method to use for service accounts. Nice work!
Have you inspected the json file to see if the "type" field exists? I think the issue here is you downloaded **Client Credentials** from the Developer console instead of downloading **Service Account Credentials**, which include a type field (like this):

```json
{
  "type": "service_account",
  "project_id": "XXX",
  "private_key_id": "XXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\nXXX\n-----END PRIVATE KEY-----\n",

  "client_email": "XXX@XXX.iam.gserviceaccount.com",
  "client_id": null,
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "revoke_uri": "https://accounts.google.com/o/oauth2/revoke",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/XXX%40XXX.iam.gserviceaccount.com"
}
```
