### ISSUE TITLE
the downloaded zip folder doesnot have all the folders and the files

### ISSUE THREAD

**Issue by Sharma-Ravin** [google/google-api-php-client#1201]

**Comment by sitecarp** [comment]
I'm experiencing the same problem. I downloaded the full release v2.1.3 and got this error:
Fatal error: Uncaught exception 'Exception' with message 'This library must be installed via composer or by downloading the full package.

**Comment by bshaffer** [comment]
Follow the instructions under [Download the Release](https://github.com/google/google-api-php-client#download-the-release) and you will have a package with all the dependencies.

You probably downloaded the zip file titled `Source Code`. Instead, download the zip file called `google-api-php-client-2.1.3.zip`.

**Comment by sitecarp** [comment]
Yep! Sorry about that.
