### ISSUE TITLE
Call to undefined method Google_Client::fetchAccessTokenWithAuthCode()

### ISSUE THREAD

**Issue by ulrichdohou** [google/google-api-php-client#1204]
Hello im having this problem. Im working with google Gmail Api. I did every thing on my own server it is working fine. I uploaded to another one but i get this error Fatal error: Uncaught Error: Call to undefined method Google_Client::fetchAccessTokenWithAuthCode().

**Comment by bshaffer** [comment]
You are probably using `v1.x` instead of `v2.x`. Please verify you've required the correct version of this library. That method is only available in the `v2.x` version.

**Comment by ulrichdohou** [comment]
I got it. There was another version (the old one) in the project. tks

**Comment by mbirabhadra** [comment]
what a shame. these so called open sourcers should learn from Microsoft regarding backwards compatibility. Cavemen and their CLIs. What a mess!

**Comment by NItesh181993** [comment]
If i am using authenticate() then it is giving me this error
Fatal error: Uncaught exception 'Google_Auth_Exception' with message 'Error fetching OAuth2 access token, message: 'invalid_grant: Bad Request'' in C:\xampp\htdocs\tutorials\php-login-using-google\vendor\google\apiclient\src\Google\Auth\OAuth2.php:126 Stack trace: #0 C:\xampp\htdocs\tutorials\php-login-using-google\vendor\google\apiclient\src\Google\Client.php(128): Google_Auth_OAuth2->authenticate('4/ygGkjKL66r05y...', false) #1 C:\xampp\htdocs\tutorials\php-login-using-google\index.php(14): Google_Client->authenticate('4/ygGkjKL66r05y...') #2 {main} thrown in C:\xampp\htdocs\tutorials\php-login-using-google\vendor\google\apiclient\src\Google\Auth\OAuth2.php on line 126
