### ISSUE TITLE
Client requires PHP 5.5 not PHP 5.4+ as listed in readme

### ISSUE THREAD

**Issue by electric-al** [google/google-api-php-client#1205]
Using PubSubClient on php 5.4.45 gives:

```
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in ...vendor/google/cloud/src/Core/RequestWrapper.php on line 217
```

According to PHP docs, ::class is php 5.5+

http://php.net/manual/en/language.oop5.constants.php
>The special ::class constant are available as of PHP 5.5.0, and allows for fully qualified class name resolution at compile, this is useful for namespaced classes:

**Comment by bshaffer** [comment]
It looks like you're using the [`google/cloud`](https://github.com/GoogleCloudPlatform/google-cloud-php) package. This repository is for `google/apiclient`. `google/cloud` [supports PHP 5.5+ only](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/composer.json#L41).

If you absolutely must use PHP 5.4, try downloading the PHP-5.4 specific release from the releases page [here](https://github.com/google/google-api-php-client#download-the-release). Then you can call the pubsub APIs using the pubsub classes included in this package. However, it is **highly recommended** to use `google/cloud` and upgrade to PHP 5.5+ instead.
