### ISSUE TITLE
Using without Composer seems to be deprecated?

### ISSUE THREAD

**Issue by garycarlyle** [google/google-api-php-client#1206]
Hi,

I have tried to use the full download by uploading to a server but it still has the Composer related error messaged.

Does the related instruction need to be removed?

The last one I could find that works without composer is version 1 but that won't connect to the API. So is pointless.

**Comment by bshaffer** [comment]
Downloading without composer IS supported! See [this section](https://github.com/google/google-api-php-client#download-the-release) of the README. Just download the release (w/ bundled vendors) from the releases page.

**Comment by garycarlyle** [comment]
I think I tried that but I installed Composer on my shared server with SSH and it all works great now. =)
