### ISSUE TITLE
max-results

### ISSUE THREAD

**Issue by ahsan-riaz** [google/google-api-php-client#1208]
Hello Everyone,

Can you please help me, how to set "max-results" parameter with Google_Service_AnalyticsReporting
what is appropriate function to pass this parameter?

Thank you

**Comment by bshaffer** [comment]
You're going to have to be more specific. Analytics Reporting is an entire API. What are you trying to accomplish?

**Comment by ahsan-riaz** [comment]
@bshaffer thanks for reply, actually I am using Google_Service_AnalyticsReporting API Client and want to apply limit on maximum results. how can i achieve this?
As for Page order I am using following function: setOrderBys()
