### ISSUE TITLE
Google Plus Post Using API

### ISSUE THREAD

**Issue by Aadriya** [google/google-api-php-client#1210]
How to Post Data into Google Plus with Assess token or anything Using Codeignator

**Comment by bshaffer** [comment]
Hey there @Aadriya ! Check out the [examples](https://github.com/google/google-api-php-client/tree/master/examples) by following the instructions in the README. But it would look something like this:

```php
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_credentials.json');
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(["https://www.googleapis.com/auth/plus.me"]);
$plus = new Google_Service_Plus($this->getClient());
// get a person
$person = $plus->people->get("118051310819094153327");
```
Substitute the last line with whatever API call you need.

As far as posting for a specific person, you will need to grant the service account Domain Wide Delegation, or use a specific access token for that user by implementing a 3-legged auth flow (see [this example](https://github.com/google/google-api-php-client/blob/master/examples/simple-file-upload.php))

I do not have any specific insight into Code Igniter integration. Good luck!
