### ISSUE TITLE
Youtube.php is missing

### ISSUE THREAD

**Issue by supmuk** [google/google-api-php-client#1211]
![error](https://cloud.githubusercontent.com/assets/22065927/25616412/78a7b7ea-2f4d-11e7-9f0c-0cc17721c8ce.png)

I trying to locate youtube.php file i am unable to find this file.
I copy all file using composer and download from git but i am unable to find the youtube.php

**Comment by bshaffer** [comment]
This code sample is outdated, and is using the `v1-master` branch. 

I'm not sure where you received this sample code, but if you follow the [current youtube sample](https://developers.google.com/youtube/v3/code_samples/php), you'll have better luck.
