### ISSUE TITLE
Fatal error: Class 'Google_Client' not found 

### ISSUE THREAD

**Issue by simonericci** [google/google-api-php-client#1214]
Api installed manually, not via Composer, downloaded from here (first zip): https://github.com/google/google-api-php-client/releases

I got this error, trying to instantiate the main class: 
**Fatal error: Class 'Google_Client' not found** 
- Php "require_once" looks ok (no error).
- Json's credentials looks ok (no error).
- Class instance not ok.

`require_once('./vendor/autoload.php');
	putenv('GOOGLE_APPLICATION_CREDENTIALS=./mycredentials.json');
	$client = new Google_Client();
	$client->useApplicationDefaultCredentials();
	$client->setScopes('https://www.googleapis.com/auth/fusiontables');
	$service = new Google_Service_Fusiontables($client);`

This is the source code I can see in /vendor/autoload.php
`<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit9c18b0e2f8ac75b5fbc347bb34dca41d::getLoader();`

Any hint?

**Comment by bshaffer** [comment]
Hey @simonericci 
Can you do an `ls -la` in your root directory? It's possible you're in the wrong directory, and so pulling in a different `vendor/autoload.php` than the one required in this library. Also, perform an 'ls -la src/Google` to verify the `Client.php` file exists where it should be.

**Comment by simonericci** [comment]
Whoops, /src folder missing... thanks @bshaffer

**Comment by induraniv** [comment]
Class 'vendor\Google\src\Google\Google_Client' not found
Api installed manually, not via Composer.

**Comment by Wakodebe** [comment]
I have the same problem, but havent find a solution yet

**Comment by Wakodebe** [comment]
Any help

**Comment by garciacarmonaam** [comment]
Did somebody find out a solution finally?

**Comment by ravcing** [comment]
<?php

require 'C:\xampp\phpMyAdmin\vendor\autoload.php';
use Google\Cloud\Translate\TranslateClient;

**Comment by luispinonferrer-capgemini** [comment]
Any solution ?

**Comment by mattwhisenhunt** [comment]
@induraniv @Wakodebe @garciacarmonaam @luispinonferrer-capgemini 
[Google_Client](https://github.com/googleapis/google-api-php-client/blob/4e0fd83510e579043e10e565528b323b7c2b3c81/src/Google/Client.php) is located in src/Google/Client.php of the package archive.

The error 'Fatal error: Class 'Google_Client' not found' indicates that Client.php was not included/required explicitly or automatically. That is typically due to [a line like](https://github.com/googleapis/google-api-php-client/blob/4e0fd83510e579043e10e565528b323b7c2b3c81/examples/simple-file-upload.php#L18)
```php
include_once __DIR__ . '/../vendor/autoload.php';
```
not resolving to the correct location (in the package archive: vendor/autoload.php). The path of autoload is relative any file with this line so make sure to account for that if you paste this line into other files.

**Comment by tusharzore1** [comment]
check the file composer.json

and add "vendor/google/apiclient/src/Google" in classmap array if not exist.

and run `composer dump autoload`

```
"autoload": {
        "classmap": [
            "vendor/google/apiclient/src/Google"
        ]
}
```

**Comment by bshaffer** [comment]
You should definitely not need to add an autoload directive to your `composer.json`. If you install via composer, including `vendor/autoload.php` will suffice. If you downloaded the library zip, you'll need to require the `vendor/autoload.php` file which exists _inside_ that package.

**Comment by tusharzore1** [comment]
Yeah, Definitely.
But somehow laravel framework not able to find class  **Google_Client** into autoload.php. It needs 
class mapping via classmap array.

**Comment by bshaffer** [comment]
@tusharzore1 I do not know why in your specific case the class **Google_Client** isn't found, but I can tell you with certainty the class mapping should not need to be added to the classmap array.

**Comment by pokerpierre** [comment]
I had the same issue and when checking the `autoload_namespaces.php` file I noticed that the Google entry pointed to `'/src'`.  I added that folder and the issue was resolved.

**Comment by kamleshwebtech** [comment]
require_once('/vendor/google-api-php-client-2.4.0/src/Google/autoload.php');
require_once('/vendor/google-api-php-client-2.4.0/vendor/autoload.php');

$client = new Google_Client();

I have checked the file path by file_exists function and included both the autoload files but system is still returning error:
Class 'Google_Client' not found

Please help to fix this issue.

**Comment by kamleshwebtech** [comment]
Is there anyone who can help me to fix this issue?

**Comment by sumantimalsina9** [comment]
I had the same issue in laravel and solved it by importing the Google_Client :

`use Google_Client;`

**Comment by pult** [comment]
install google/apiclient:
>$ composer require google/apiclient

**Comment by tusharzore1** [comment]
I have tried a customised solution for this situation, commented above.

**Comment by msozsari** [comment]
if you have "vendor/google/apiclient/src/Google" directory and still you get this error try **use** command.

`use Google_Client;`

**Comment by yosus** [comment]
The "vendor/autoload.php" file is mainly for backward compatability.

If you are manually installing google-api, you will need to use the v1 branch of the autoload-file (https://github.com/googleapis/google-api-php-client/tree/v1-master) where it will call the require files for all (see below).

Also note that you will need to download other dependencies manually (,e.g. Monolog).  It is easier to use composer to download everything, and just copy out the folders manually (semi-manual method)

`
function google_api_php_client_autoload($className)
{
  $classPath = explode('_', $className);
  if ($classPath[0] != 'Google') {
    return;
  }
  // Drop 'Google', and maximum class file path depth in this project is 3.
  $classPath = array_slice($classPath, 1, 2);
  $filePath = dirname(__FILE__) . '/' . implode('/', $classPath) . '.php';
  if (file_exists($filePath)) {
    require_once($filePath);
  }
}
spl_autoload_register('google_api_php_client_autoload');`

**Comment by DarshitAnjaria** [comment]
> I had the same issue in laravel and solved it by importing the Google_Client :
> 
> `use Google_Client;`

thank you very much this also solve the problem of mine...

**Comment by carolt00** [comment]
> > Tuve el mismo problema en laravel y lo resolví importando Google_Client:
> > `use Google_Client;`
> 
> muchas gracias, esto también resuelve el problema mío ...

Hola, me puedes decir por favor en que parte lo pusiste?

**Comment by maalgorepublic** [comment]
Faced the same issue on Codeigniter, I was including autoload.php of require "\vendor\google\auth\autoload.php" this was causing the problem. 
You don't need to map any class in composer, including autoload of vendor instead of google solved my problem.
require ('vendor\autoload.php')

**Comment by jyot53** [comment]
> if you have "vendor/google/apiclient/src/Google" directory and still you get this error try **use** command.
> 
> `use Google_Client;`

This "vendor/google/apiclient/src/Google" directory is not present after i installed composer

**Comment by dinhkhanh** [comment]
> I had the same issue in laravel and solved it by importing the Google_Client :
> 
> `use Google_Client;`

Save me!

For more clearly, importing `use Google_Client;` and then, instead of using `new \Google_Client();`, use `new Google_Client();` (without backslash).

This also applies to any other Google classes, eg. `Google_Services_Adsense`.

**Comment by Shonu72** [comment]
> > I had the same issue in laravel and solved it by importing the Google_Client :
> > `use Google_Client;`
> 
> Save me!
> 
> For more clearly, importing `use Google_Client;` and then, instead of using `new \Google_Client();`, use `new Google_Client();` (without backslash).
> 
> This also applies to any other Google classes, eg. `Google_Services_Adsense`.

I tried everything as you mentioned but still getting error!!

**Comment by dinhkhanh** [comment]
> > > I had the same issue in laravel and solved it by importing the Google_Client :
> > > `use Google_Client;`
> > 
> > 
> > Save me!
> > For more clearly, importing `use Google_Client;` and then, instead of using `new \Google_Client();`, use `new Google_Client();` (without backslash).
> > This also applies to any other Google classes, eg. `Google_Services_Adsense`.
> 
> I tried everything as you mentioned but still getting error!!

Try this:

```
use Google\Client;

....

$client = new Client();
```

**Comment by bshaffer** [comment]
The base directory is now in `vendor/google/apiclient/src` and  `vendor/google/apiclient-services/src`

If you use composer and include `vendor/autoload.php`, this change will not effect you. However, if you used some other mechanism such as `include_dir`, then this change may have broken your installation.

**Comment by qq854674282** [comment]
> if you have "vendor/google/apiclient/src/Google" directory and still you get this error try **use** command.
> 
> `use Google_Client;`

thx bro~ i'm ok~

**Comment by rajithwijepura** [comment]
> > > > I had the same issue in laravel and solved it by importing the Google_Client :
> > > > `use Google_Client;`
> > > 
> > > 
> > > Save me!
> > > For more clearly, importing `use Google_Client;` and then, instead of using `new \Google_Client();`, use `new Google_Client();` (without backslash).
> > > This also applies to any other Google classes, eg. `Google_Services_Adsense`.
> > 
> > 
> > I tried everything as you mentioned but still getting error!!
> 
> Try this:
> 
> ```
> use Google\Client;
> 
> ....
> 
> $client = new Client();
> ```

Life saver. Thanks. This worked with CakePHP 4

**Comment by darshannv** [comment]
Please update the composer.json

     "google/apiclient": "^2.12.1"
    
Inside the composer.json file under the **extra** update this

     "extra": {
         "google/apiclient-services": [
            "Drive",
            "YouTube"
        ]
    }

under the **script** section at the bottom add this line

    "scripts": {
         "pre-autoload-dump": "Google\\Task\\Composer::cleanup"
     }

After adding it, run the command 

    composer update
    composer dump-autoload 

It will work.
