### ISSUE TITLE
Fatal error while using through developer key

### ISSUE THREAD

**Issue by swapnilbarhate** [google/google-api-php-client#1215]
Uncaught exception 'Google_Service_Exception' with message '{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } } '
when using google calendar api with developer key.

**Comment by bshaffer** [comment]
Hey @swapnilbarhate 
I believe the API you're attempting to call requires an Access Token via a 3-legged oauth flow. Check out the example here: https://github.com/google/google-api-php-client/blob/master/examples/simple-file-upload.php
