### ISSUE TITLE
File download from google drive is not working.

### ISSUE THREAD

**Issue by HuzaifaHaleem** [google/google-api-php-client#1220]
I am trying to export uploaded docx file from google drive to my system. I am following help source provided by google as mentioned below:
$fileId = '1ZdR3L3qP4Bkq8noWLJHSr_iBau0DNT4Kli4SxNc2YEo';
$response = $driveService->files->export($fileId, 'application/pdf', array(
  'alt' => 'media' ));
$content = $response->getBody()->getContents();
**export()** method does not exist in current version of google drive api php. The current version is 2.1.3

**Comment by net-tools** [comment]
Hi,

You have misunderstood the API reference. `export` method is only to convert a Google Doc and download it. Google docs are documents created on the web interface through Docs, Sheets, or Slides.

Other kind of documents (in particular, uploaded files such as your docx word file) should be downloaded through an authorized GET request along with the `alt=media` query parameter.

From [API reference about v3 downloads](https://developers.google.com/drive/v3/web/manage-downloads) : 

```php
$fileId = '0BwwA4oUTeiV1UVNwOHItT0xfa2M';
$response = $driveService->files->get($fileId, array(
  'alt' => 'media' ));
$content = $response->getBody()->getContents();
```

**Comment by Zetat** [comment]
Hi,
Tried here and it didn't work. 

> `$fileId = '0BwwA4oUTeiV1UVNwOHItT0xfa2M';
$response = $driveService->files->get($fileId, array(
  'alt' => 'media' ));
$content = $response->getBody()->getContents();`

Is there any way?

**Comment by bshaffer** [comment]
@Zetat what error did you receive? It's possible you did not authenticate properly. See the example of downloading a file here: https://github.com/googleapis/google-api-php-client/blob/master/examples/large-file-download.php

**Comment by iKlsR** [comment]
This helped me. Simple and to the point https://stackoverflow.com/questions/40028169/google-drive-api-v3-downloading-files-in-php
