### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Google_Service_Exception'

### ISSUE THREAD

**Issue by mithun810** [google/google-api-php-client#1222]
` PHP Fatal error:  Uncaught exception 'Google_Service_Exception'with message '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Required parameter: [resource.schema.field[0].name]",
    "locationType": "parameter",
    "location": "[resource.schema.field[0].name]"
   }
  ],
  "code": 400,
  "message": "Required parameter: [resource.schema.field[0].name]"
 }
}
`

**Comment by bshaffer** [comment]
It looks like you're missing a required parameter in your request. Make sure the `name` property of your resource schema field is set!

**Comment by ArchanaShet** [comment]
I am trying to implement an app using Google API and am facing the following error:

Fatal error: Uncaught exception 'Google_Service_Exception' with message '{"error":{"errors":[{"domain":"global","reason":"required","message":"Login Required","locationType":"header","location":"Authorization"}],"code":401,"message":"Login Required"}}' in E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Http\REST.php:118 Stack trace: #0 E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Task\Runner.php(181): call_user_func_array(Array, Array) #3 E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Http\REST.php(58): Google_Task_Runner->run() #4 E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Client.php(779): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(Guzzl in E:\xampp\htdocs\App\vendor\google\apiclient\src\Google\Http\REST.php on line 118

**Comment by Mohamm6d** [comment]
I have same error no any one could resolve this ?

**Comment by chandumisti** [comment]
i did not get the solution to the above problem

**Comment by chandumisti** [comment]
Uncaught exception 'Google_Service_Exception' with message '{"error":{"errors":[{"domain":"usageLimits","reason":"accessNotConfigured","message":"Project 254734002464 is not found and cannot be used for API calls. If it is recently created, enable Google Analytics API by visiting https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=254734002464 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","extendedHelp":"https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=254734002464"}],"code":403,"message":"Project 254734002464 is not found and cannot be used for API calls. If it is recently created, enable Google Analytics API by visiting https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=254734002464 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."}}' in /var/www/html/m in /var/www/html/myapi/vendor/google/apiclient/src/Google/Http/REST.php on line 118

**Comment by bshaffer** [comment]
@chandumisti
You need to enable the Google Analytics API. You can do so by visiting the following url:

https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=254734002464

**Comment by chandumisti** [comment]
enable.. but it is showing 0 user in my analytics account

**Comment by arnold12** [comment]
I m trying to implement google add group member API and i m getting this error.

Fatal error: Uncaught exception 'Google_Service_Exception' with message '{ "error": { "errors": [ { "domain": "global", "reason": "invalid", "message": "Invalid Input: memberKey" } ], "code": 400, "message": "Invalid Input: memberKey" } } ' in /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Http/REST.php:118 Stack trace: #0 /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Task/Runner.php(176): call_user_func_array(Array, Array) #3 /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Http/REST.php(58): Google_Task_Runner->run() #4 /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Client in /var/www/lists/admin/gsuite/google-api-php-client-2.2.2/src/Google/Http/REST.php on line 118

**Comment by surajwasnik** [comment]
Just go into service account JSON file which you download while creating a service account in google console and add client_id into that file, this is work for me also don't forget to provide access of file that shares a file with service account email id eg. thomasapp@appname-201813.iam.gserviceaccount.com

Hope this will work.
