### ISSUE TITLE
Access drive files of my domain users using service account

### ISSUE THREAD

**Issue by AneebImamdin** [google/google-api-php-client#1223]
I want to upload/download the files of my users (user@mydomain.com). 

This is my code in php :
```
<?php
                putenv('GOOGLE_APPLICATION_CREDENTIALS=service-account.json');
		$client = new Google_Client();
		$client->useApplicationDefaultCredentials();
		$client->setScopes('https://www.googleapis.com/auth/drive.file');
		$client->setSubject('user@mydomain.com');

                $service = new Google_Service_Drive($client);

                $optParams = array(
			  'pageSize' => 10,
			  'fields' => 'nextPageToken, files(id, name)'
			);

	        $results = $service->files->listFiles($optParams);
``` 
I have service-account.json file in my present working directory.

But i am having this error :
```
PHP Fatal error:  Uncaught Google_Service_Exception: {
 "error": "unauthorized_client",
 "error_description": "Client is unauthorized to retrieve access tokens using this method."
}
 in \vendor\google\apiclient\src\Google\Http\REST.php:118
```

If i comment out this line  i get the list of files in my google drive :
$client->setSubject('user@mydomain.com');

But i need to get the files of another user in my domain that's why i am using this line.

**Comment by campbekj** [comment]
Check to make sure you set domain-wide delegation on your service account and make sure you authorized your service account inside G Suite. See [https://developers.google.com/identity/protocols/OAuth2ServiceAccount?hl=en_US#delegatingauthority](url)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. Some clarifying questions were asked a week or more ago and never answered. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
