### ISSUE TITLE
Customsearch - Double quotes

### ISSUE THREAD

**Issue by prodevcon** [google/google-api-php-client#1224]
Hi,

We have a problem using the Customsearch API, with query which has double quotes ex.( "it-hersteller" +schweiz )

Here is the piece code:
```php
$customSearchService = new \Google_Service_Customsearch( $client );

$optParams = array(
	'cx' => $this->customSearchId,
	'start' => $start
	);

$results = $customSearchService->cse->listCse(urlencode($query), $optParams)->getItems();
```
We get the following exception:
```json
{
	"error": {
		"errors": [
			{
			"domain": "global",
			"reason": "invalid",
			"message": "Invalid Value"
			}
		],
		"code": 400,
		"message": "Invalid Value"
	}
}
```
It breaks only when double quotes are used in the query string (which is send to the method listCse urlencoded '%22it-hersteller%22+%2Bschweiz' ).

Can you help please?

Best regards

**Comment by mattwhisenhunt** [comment]
It sounds like you got a valid Invalid Value message. You may want to dig into the API reference and find out why it doesn't like those characters.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
