### ISSUE TITLE
Steps After Connecting to Google App Script

### ISSUE THREAD

**Issue by hamzazafeer** [google/google-api-php-client#1229]
I just connected to Google App Script. 

After Successful connection CMD shows me a message

Folders Under Your Root Folder :
            Complete  <some random letters and digits>

Now i want to know to next what i have to do ?
[https://developers.google.com/apps-script/guides/rest/quickstart/php]()

According to above link i follow the steps for connection. Now how can i read my google sheet in browser. or i can add, update or delete the row by writing script?

**Comment by mattwhisenhunt** [comment]
Are you receiving an error? Please include steps to reproduce.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
