### ISSUE TITLE
$client->createAuthUrl() - append `delegation=1`

### ISSUE THREAD

**Issue by dasiekjs** [google/google-api-php-client#1231]
I try to generate login URL with this api client. I want to create application with Laravel with login by `Branding Account`. 

`
$client = new Google_Client();
    $client->setDeveloperKey("DEV_KEY");
    $client->setClientId('CLIENTID');
    $client->setScopes(array(
        'https://www.googleapis.com/auth/plus.me',
        'https://www.googleapis.com/auth/plus.login'
    ));

    $client->setRedirectUri(route('google-callback')); // TODO

    $auth_url = $client->createAuthUrl().'&delegation=1'; //OOOOOO here
    return \Illuminate\Support\Facades\Redirect::to($auth_url);
`

But when i add delegation = 1, redirect to auth_url remove this parametr :/

What now? Can i Add it manualy? Or maybe it error in my Google App configuration (google + api is enabled)

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. If that is not the case let us know and we will re-open.
