### ISSUE TITLE
Symfony integration?

### ISSUE THREAD

**Issue by retrodans** [google/google-api-php-client#1232]
Is there a way to use this client library in symfony?  I do not necessarily abhore composer, but am unable to see a way to get it working other than just downloading the files and manually integrating

**Comment by mattwhisenhunt** [comment]
Our [releases](https://github.com/google/google-api-php-client/releases) come with all the dependencies and an autoload script.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We didn't see any follow up in over a week so we are closing it. Please feel free to re-open this issue with more information.
