### ISSUE TITLE
 Uncaught exception 'GuzzleHttp\Exception\ClientException'

### ISSUE THREAD

**Issue by cruz93** [google/google-api-php-client#1234]
I am making the call to the API through an example, when executing the example I mark the following error.

Fatal error</b>:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad Request` response:
{
 &quot;error&quot;: &quot;invalid_grant&quot;,
 &quot;error_description&quot;: &quot;Bad Request&quot;
}

' in C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:111
Stack trace:
C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
 C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHtt in C:\xampp\htdocs\APIAdwordsAudience\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 111

Is there any solution

My code is: [https://github.com/cruz93/APIAdWords/blob/master/index.php](url)

**Comment by nikky-kajavadara** [comment]
i am getting that same error.

**Comment by mattwhisenhunt** [comment]
@cruz93 It looks like you are using a different library: https://github.com/googleads/googleads-php-lib did you find help?

@nikky-kajavadara Have you found a solution yet? If not be sure to include some more context around what part of google-api-php-client you are using.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
