### ISSUE TITLE
going crazy with service token auth

### ISSUE THREAD

**Issue by Grummfy** [google/google-api-php-client#1235]
Hello,
With oauth2 access, the libs works well and the given example in the documentation about calendar for example (https://developers.google.com/google-apps/calendar/quickstart/php).

But when you want a service account access it's a bit pain in the ass because no example are given in the documentation. So I follow https://developers.google.com/identity/protocols/OAuth2ServiceAccount?hl=fr#delegatingauthority
But after that I'm totally lost.

How I create my key:
1. on the google api console, I create a project
2. then add a service account on the iam & admin console > service account
3. I have activate the delegation for the g suite
4. I have created key for this service account
5. I add the id of this service account, inside the admin console with the scope url for calendar

So here is the code I get for now
```php
<?php

include __DIR__ . '/vendor/autoload.php';

$client = new \Google_Client();
putenv('GOOGLE_APPLICATION_CREDENTIALS=' . __DIR__ . '/project-service-account-json-key.json'); // I don't find a way to set it by parameter, so I use the env vars
$calendarId = 'XXXX'; // here is the calendar identifier
$client->useApplicationDefaultCredentials();
$client->setSubject('XXX@YYY'); // here is the 'email' in relation with project service account
$client->setApplicationName("test-demo");
$scopes = [Google_Service_Calendar::CALENDAR];
$client->setScopes($scopes);
$client->setAccessType('offline');

if( $client->isAccessTokenExpired())
{
    $client->fetchAccessTokenWithAssertion();
}

$service = new Google_Service_Calendar($client);
var_dump($service->calendarList->get($calendarId));
$list = $service->calendarList->listCalendarList();
var_dump($list->getItems());
```

and the I got 
```
PHP Fatal error:  Uncaught Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not Found"
   }
  ],
  "code": 404,
  "message": "Not Found"
 }
```

So what am I missing?

**Comment by beatscode** [comment]
I get the same responses using Google My business api. Errors are incredibly unhelpful. Also no sane way to reproduce the request in the OAuth playground.

**Comment by mattwhisenhunt** [comment]
@beatscode My Business does not use service accounts as far as I know.

@Grummfy Have you seen https://github.com/google/google-api-php-client/issues/801#issuecomment-171417538? It is pretty thorough walk-through of getting going with service accounts.
