### ISSUE TITLE
google api php client and googleadwords php api?

### ISSUE THREAD

**Issue by johnraypaulin14** [google/google-api-php-client#1238]
Is this particular api can be used along with googleadwords php api?

**Comment by mattwhisenhunt** [comment]
Should do. Are you running into any problems?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
