### ISSUE TITLE
Connecting to datastore emulator shouldn't require credentials

### ISSUE THREAD

**Issue by calsmith** [google/google-api-php-client#1239]
I can connect to the local datastore emulator via the google-api library with the following code:

```
// Start emulator: gcloud beta emulators datastore start --data-dir=_datastore
$this->services = new ServiceBuilder([
    'projectId' => Cloud::getProjectId(),
    'keyFilePath' => 'creds.json' // Why is this required?
]);
putenv('DATASTORE_EMULATOR_HOST=http://localhost:8081');
$datastore = $this->services->datastore();
```

My question is why a key file is required to connect to the local datastore emulator? I have tried replacing the values in the key file with fake values, but it fails unless the keys are from a real production datastore instance. 

It appears that the API library still hits Google's servers even though DATASTORE_EMULATOR_HOST is set.

This is frustrating because it means local development requires an internet connection and my live datastore instance is being hit for local development even though the emulator is handling the actual data.

Can we fix this?

**Comment by mattwhisenhunt** [comment]
For Datastore please use https://github.com/GoogleCloudPlatform/google-cloud-php
