### ISSUE TITLE
Can't get refresh_token

### ISSUE THREAD

**Issue by enzonotario** [google/google-api-php-client#1244]
Hi! Firstly, I don't speak english. So, please, be gently.

I'm trying to keep an offline access from my API with the following workflow:

* I have an ionic app that makes the initial sign in. It has the offline access type so I get a serverAuthCode that I send to my API.
* My API (that also have the offline access type) takes it serverAuthCode and with it, fetch an access_token, but I don't get any refresh_token, so then, when the access_token expires, I can't refresh it.

This is the code in my API:
```
$gClient = new \Google_Client();
$gClient->setAccessType('offline');
$gClient->setApplicationName('xxx');
$gClient->setClientId('xxx');
$gClient->setClientSecret('xxx');
$gClient->setRedirectUri('xxx');
$gClient->setDeveloperKey('xxx');
$gClient->addScope([
    'https://www.googleapis.com/auth/plus.profile.emails.read',
    'https://www.googleapis.com/auth/contacts.readonly',
]);

$accessToken = $gClient->fetchAccessTokenWithAuthCode($serverAuthCode);

$gClient->setAccessToken($accessToken);

$refreshToken = $gClient->getRefreshToken(); // It gives me null

$gOauth2 = new \Google_Service_Oauth2($gClient);

$payload = $gOauth2->userinfo_v2_me->get();
```

Can anyone help me, please?

Thanks!

**Comment by heukirne** [comment]
Besides
```$client->setAccessType('offline');```
Need to include force prompt to Google return the refresh token:
```$client->setApprovalPrompt('force');```
Works for me.

**Comment by enzonotario** [comment]
I also try with ```$gClient->setApprovalPrompt('force');``` but doesn't work too. 

Can you tell me how is your client? that code is in your api?

**Comment by heukirne** [comment]
You can see all my code: https://github.com/heukirne/geolocated-restricted-events/blob/master/generate_credentials.php
It's basically the Google Calendar Api PHP Example
https://developers.google.com/google-apps/calendar/quickstart/php

**Comment by enzonotario** [comment]
I see your code and tryied it. It works perfectly! But I'm using PHP as an API. 

So, from the client (ionic 3), I get an serverAuthCode, that I send to my PHP API and exchange for an access_token. In that way, using the same code (but without generating an authUrl), I don't get any refresh_token.

Do you know any way to approach this case?

**Comment by heukirne** [comment]
Probably the serverAuthCode from Ionic 3 doesn't allow offline access that release the refresh token. Maybe you need to set the access_type to offline in Ionic somewhere.

**Comment by enzonotario** [comment]
Yes, I already setted the access type to offline:
```
window['plugins'].googleplus.login(
  {
    'scopes': 'xxx',
    'webClientId': 'xxx',
    'offline': true,
  }, (gPlusResponse) => {
    // ...
  }, (errors) => {
    // ...
  }
);
}
```

It gives me a serverAuthCode that I exchange for a authCode, that works perfectly until it expires. That's why I want to get an refresh_token. But I can't. I don't understand why. All seems to be good.

**Comment by heukirne** [comment]
Sorry, I can tell you.
You probably should take a look at Java Google Auth Api and look for how you can force the refresh_token.
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/src/android/GooglePlus.java

**Comment by heukirne** [comment]
So, I suggest you to close this issue and open another in cordova-plugin-googleplus.

**Comment by enzonotario** [comment]
Thanks so much! I thought that it was a problem of my API (and this library).

Thanks again!
