### ISSUE TITLE
PageToken submitted as integer causes error

### ISSUE THREAD

**Issue by ProFire** [google/google-api-php-client#1248]
Hi, I noticed that PageToken must be submitted as a String instead of Integer in order for it to work. When it is submitted as an Integer, it causes an error.

`public function setPageToken($token = 1700) {
	$this->reportRequest = new Google_Service_AnalyticsReporting_ReportRequest();
	$this->reportRequest->setPageToken($token);
}`
This code snippet causes this error message when submitting a batchGet:
`{ "error": { "code": 400, "message": "Invalid value at 'report_requests[0].page_token' (TYPE_STRING), 1700", "errors": [ { "message": "Invalid value at 'report_requests[0].page_token' (TYPE_STRING), 1700", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } }`

Instead, if I cast it as a string, it works.
`public function setPageToken($token = 1700) {
	$this->reportRequest = new Google_Service_AnalyticsReporting_ReportRequest();
	$this->reportRequest->setPageToken((string)$token);
}`

I'm not sure if this is an intended behaviour. This problem doesn't occur with setPageSize.

**Comment by mattwhisenhunt** [comment]
Looks like the API defines it as string:
https://analyticsreporting.googleapis.com/$discovery/rest?version=v4
https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#reportrequest
