### ISSUE TITLE
Failed opening required 'Google/Service/AdExchangeSeller.php'

### ISSUE THREAD

**Issue by nhantam** [google/google-api-php-client#1267]
Hello

I have download google=api-php-client and do not see file AdExchangeSeller.php in folder Service

I am using service convert currency https://developers.google.com/ad-exchange/seller-rest/getting-started

Could you help how do I download file "AdExchangeSeller.php" ?

Thanks & Regards
Bang Andre

**Comment by bshaffer** [comment]
Yes, follow the [README instructions](https://github.com/google/google-api-php-client#installation)
