### ISSUE TITLE
fatal error for very long gbq queries- 40k characters

### ISSUE THREAD

**Issue by ras44** [google/google-api-php-client#1268]
I'm using the Google API PHP client to query Google Big Query (GBQ) and am passing in very large automatically generated queries.  The queries have about 40k characters in them.

For smaller queries, I can make an API request and receive a response without any problems.  I receive a fatal error message from PHP:

Allowed memory size of 134217728 bytes exhausted (tried to allocate 74 bytes) in .../vendor/google/apiclient/src/Google/Http/REST.php 
on line 126

I've checked this line and it appears related to pulling the entire request body into memory, shortly after that, there is a function called decodeBody which mentions not decoding the body because "it's probably a really long string".  This appears to be related to my issue.

If I load the 40k-long query into the GBQ gui interface, I can run the query without problems.

**Comment by bshaffer** [comment]
Try upgrading to [v2.2.0](https://github.com/google/google-api-php-client/releases/tag/v2.2.0) of this library, which will use Guzzle HTTP instead of the class above. This will resolve your issue:

```
composer require "google/apiclient:^2"
```
