### ISSUE TITLE
How to set multiple scoop in $this->client->setScopes("email profile"); 

### ISSUE THREAD

**Issue by ankitsingh101** [google/google-api-php-client#1269]
### like me and login 
##above redirect to userinfo.email and userinfo.profile
# i want to use plus.login and plus.me

**Comment by bshaffer** [comment]
```php
    $client->setScopes([
        "https://www.googleapis.com/auth/plus.me",
        "https://www.googleapis.com/auth/plus.login",
    ]);
```

**Comment by msrumon** [comment]
Why is this topic closed? I can't set `profile` scope [here](https://github.com/googleapis/google-api-php-client/blob/6e72a864aad23cc020a097d6b0b650874e972c6b/examples/idtoken.php#L41).
