### ISSUE TITLE
redirect_uri_mismatch error at the time of getting refresh token

### ISSUE THREAD

**Issue by redochka** [google/google-api-php-client#1270]
I am getting this error only with this website: 

https://www.villagem.com

With all other sites, there is no problem.

Here is the redirect URL i build myself and enter in the browser: https://accounts.google.com/o/oauth2/auth?client_id=551509502584-96ij5ikuavlechqtlsak0p859s3tnbao.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fwww.villagem.com%2Findex.php%3Froute%3Dmodule%2Fautoprint_oauth_redirect&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudprint&access_type=offline

in the console i have authorized all possible variations:

https://www.villagem.com/index.php?route=module/autoprint_oauth_redirect 
http://www.villagem.com/index.php?route=module/autoprint_oauth_redirect 
https://villagem.com/index.php?route=module/autoprint_oauth_redirect 
http://villagem.com/index.php?route=module/autoprint_oauth_redirect 

Why i am getting redirect_uri_mismatch

**Comment by bshaffer** [comment]
It could have to do with the `/` in the URL. Try adding the following as an authorized URL:

```
https://www.villagem.com/index.php?route=module%2Fautoprint_oauth_redirect
```

If that doesn't work, try using your front controller so you have a normal URL, i.e. `https://www.villagem.com/oauth_redirect`.

**Comment by redochka** [comment]
Thanks for the suggestion, this is not the problem because if i replace vilagem.com with any other domain it works.

**Comment by redochka** [comment]
Any help please?

**Comment by redochka** [comment]
> If that doesn't work, try using your front controller so you have a normal URL, i.e. https://www.villagem.com/oauth_redirect

You are right !!!

But why it is the problem happening only with villagem.com domain ?

**Comment by redochka** [comment]
The bug was a missing s in (http instead of https) when trying to get the token. I am sorry to have bother you with this. I close the ticket.
