### ISSUE TITLE
Vendor folder is missing

### ISSUE THREAD

**Issue by zmilkman** [google/google-api-php-client#1271]
There is no vendor folder in the project. Is this an error?

Trying to include the include the autoloader without Composer... but the path does not exist, and 
`'/path-to-site/google-api-php/src/Google/autoload.php` referenced the vendor folder...

**Comment by zmilkman** [comment]
NVM - needed to download from `https://github.com/google/google-api-php-client/releases` instead of downloading the folder.

**Comment by devanghire** [comment]
download from that link https://github.com/google/google-api-php-client/releases/google-api-php-client-2.2.2.zip
