### ISSUE TITLE
DataTransfer Insert: error 400 missing resource.applicationDataTransfer

### ISSUE THREAD

**Issue by fingal56** [google/google-api-php-client#1273]
I'm creating simple PHP script for transfering ownerships of files between users in the same domain. I want to use Admin SDK Transfers and Insert method. 

Let's say I have prepared object for creating requests to Transfers resource

`$transfers = new \Google_Service_DataTransfer($googleConnection);`

googleConnection handles service account authorization so i can make requests this way:
`$data = $this->transfers->transfers->listTransfers();`

Based on documentation and Client library **insert** method should work simmilar way. 
Instead I am getting error code 400 with message Missing required field: [resource.applicationDataTransfer].
I must be missing something or there is a bug.  

    `$transferParams = new \Google_Service_DataTransfer_ApplicationTransferParam();
    $transferParams->setKey("PRIVACY_LEVEL"); //what kind of docs I want to transfer
    $transferParams->setValue(['SHARED', 'PRIVATE']);

    $appDataTransfer = new \Google_Service_DataTransfer_ApplicationDataTransfer();
    $appDataTransfer->setApplicationTransferParams($transferParams);

    $appDataTransfer->applicationId = "iDString";    //set application ID

    $newTransfer = New \Google_Service_DataTransfer_DataTransfer();

    $newTransfer->setOldOwnerUserId('accountID'); //origin account IDs are placeholders
    $newTransfer->setNewOwnerUserId('account2ID'); //destination account
    $newTransfer->setApplicationDataTransfers($appDataTransfer);

    $result = $this->transfers->transfers->insert($newTransfer); //execute insert`

Any ideas or hints what could be wrong with such code ? Or is there other way how am I supposed to build insert transfer request through client ?

**Comment by bshaffer** [comment]
Which version of the `google/apiclient-services` library are you using? Make sure you are on the current version (`v0.15`):

```sh
$ composer show | grep google
google/apiclient-services         v0.15   Client library for Google APIs
google/auth                       v1.0    Google Auth Library for PHP
```

**Comment by fingal56** [comment]
I am using current (`v0.16`) version of google/apiclient-services after composer update. 
Main library google/apiclient is (`v2.2.0`). I have also tried to downgrade main library to (`v.2.1.0`) which puts  google/apiclient-services to version (`v0.11.0`)

I got same error output 
```
Google_Service_Exception
{
"error": {
"errors": [
{
"domain": "global",
"reason": "required",
"message": "Missing required field: [resource.applicationDataTransfer]"
}
],
"code": 400,
"message": "Missing required field: [resource.applicationDataTransfer]"
}
}
```
I can manage  users, groups or group members easily. Listing of all performed transfers also works fine. But insert throws that error and it doesn't make much sense to me.

**Comment by fingal56** [comment]
Could anybody at least try to replicate mentioned error ? So I would know if it's a bug or error on my side. Thanks...

**Comment by fingal56** [comment]
Eventually I've got answer from [stackoverflow](https://stackoverflow.com/questions/45268548/google-api-data-transfer-insert-missing-resource-applicationdatatransfer). The issue was with this line

`$newTransfer->setApplicationDataTransfers($appDataTransfer);`

setApplicationDataTransfers method expects an **array** of Google_Service_DataTransfer_DataTransfer 
so correct parameter is **as array** . Now it works as it's supposed to

`$newTransfer->setApplicationDataTransfers([$appDataTransfer]);`
