### ISSUE TITLE
Uncaught exception 'Google\Cloud\Core\Exception\ServiceException' with message 'Option 20056 is not supported by this curl implementation

### ISSUE THREAD

**Issue by suppal16** [google/google-api-php-client#1275]
I am trying to upload file to Big query from Google storage
If I run it through PHP ; I get following errorand warning
ERROR:
Uncaught exception 'Google\Cloud\Core\Exception\ServiceException' with message 'Option 20056 is not supported by this curl implementation
WARNING:
php_sapi_name() has been disabled for security reasons.

If I try to upload file from Big Query WEB UI from google storage then I get following error
ERROR:
Errors:
Not found: URI gs://xxx-bucket/comp1.csv (error code: notFound)

But If I upload File from my computer ,it works with Big Query WEB UI but upto certain FILE SIZE

I will appreciate your help

**Comment by mattwhisenhunt** [comment]
It sounds like you might want to recompile PHP.

In a slightly unrelated note have you seen the new [Google Cloud](https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-install-php) libraries.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
