### ISSUE TITLE
Google Plus Domains post Media.Upload error 400 answer 

### ISSUE THREAD

**Issue by CHDuBar** [google/google-api-php-client#1276]
I want to upload a multimedia file with Google Plus Domains for later post in an Activity. I have been researching in forum, oficial documentation and reviewed Google APIs Client Library for PHP as result I have the next code

   ```
 $mediaUpload = new \Google_Service_PlusDomains_Media(
    	    array(
    	    		'uploadType' => 'media',
    	    		'collection' => 'cloud',
    	    		'media_body' => $completePath, // /u0/.../image.jpg
    	    		'userId' => $this->id_profile, //Google Plus Profile ID
    	    		'displayName' => $imageTemp[1], //image.jpg
    	    		'mediaUrl' => $URL // http://example.com/files/image.jpg 
    	    	)
       );
  $mediaUploadAnswer = $plusdomains->media->insert('me', 'cloud', $mediaUpload);
```

The message error is 

   

>  'domain' => string 'global' 
>     'reason' => string 'invalid' 
>     'message' => string 'Invalid Value' 
> 
>     Error calling POST https://www.googleapis.com/plusDomains/v1/people/me/media/cloud: (400) Invalid Value
> 

I checked all parameters and them are right.

Currently I can post Activity with only text, so I get the Client correctly.

What can be?

**Comment by irealme** [comment]
Hello CHDuBar, I was having same problem, but you are passing wrong arguments to `$mediaUploadAnswer = $plusdomains->media->insert('me', 'cloud', $mediaUpload);`

**Comment by irealme** [comment]
There should be

 ```
$service->media->insert('me','cloud',$file,array(
                'data' => $file_data,
                'mimeType' => $file_mime,
                'uploadType' => 'media',
            ));
```
where,

```
$file_data = file_get_contents( $file_path);
$file_title = basename( $file_path);
$file_mime = $this->mime_content_type($file_title);
$file = new Google_Service_PlusDomains_Media();
$file->setDisplayName($file_title);
$file->setSummary("This is {$file_mime} file");
```

**Comment by irealme** [comment]
Let me know if its helpful for you or not 👍

**Comment by obscurecloud** [comment]
This got me going. 
If you are trying to do a media.insert with the Google Plus API PHP SDK, this is the answer. 
Small change I had to make though:
`$file_mime = $this->mime_content_type($file_title);`
to 
`$file_mime = mime_content_type($file_path);`
If you are working with remote files, check out the comment:
http://php.net/manual/en/function.finfo-file.php#119467

**Comment by mattwhisenhunt** [comment]
Looks like your question was answered by helpful community members. Thanks community! Please feel free re-open if I misread the thread.

**Comment by brainslcdevshop** [comment]
@irealme thanks, you are help me. 
and 
if need only image upload can type as like under
$file_mime  = 'image/*';
