### ISSUE TITLE
Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in [no active file]:0

### ISSUE THREAD

**Issue by zen99** [google/google-api-php-client#1277]
I am performing an ajax call to the script that calls this google client API library and pulling the data needed to be returned back as a response. However the script called when reached the code line "return $analytics->reports->batchGet( $body );" 

It threw an error which I picked up through console.log() where the error says:
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in [no active file]:0
Stack trace:
#0 {main}
  thrown in <b>[no active file]</b> on line <b>0</b><br />

I tried looking into the function batchGet but couldn't find anything & looking up online for posts with similar issues however not specifically related to this library use. Any help would be really appreciated.

**Comment by mattwhisenhunt** [comment]
We publish a NodeJS API client as well, check out https://github.com/google/google-api-nodejs-client/. Other than that I would need to ask for you for more context to be able to answer your question.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
