### ISSUE TITLE
Uncaught exception in Verify::verifyIdToken

### ISSUE THREAD

**Issue by vocoded** [google/google-api-php-client#1279]
Upon upgrade to v2.2, we started seeing these errors on authentication:

```
PHP Fatal error:  Uncaught exception 'Firebase\JWT\SignatureInvalidException' with message 'Signature verification failed'
```

Tracing indicates this is due to a behavioral change in JWT, specifically that code which was previously raising a `DomainException` is now returning a false value:

```
// v4.0:
    $success = openssl_verify($msg, $signature, $key, $algorithm);
    if (!$success) {
        throw new DomainException("OpenSSL unable to verify data: " . openssl_error_string());
    } else {
        return $signature;
    }

// v5.0:
    $success = openssl_verify($msg, $signature, $key, $algorithm);
    if ($success === 1) {
        return true;
    } elseif ($success === 0) {
        return false;
    }
    // returns 1 on success, 0 on failure, -1 on error.
    throw new DomainException(
         'OpenSSL error: ' . openssl_error_string()
     );
```

This causes the logic in `Verify::verifyIdToken` to no longer try other certificates:

```
      } catch (ExpiredException $e) {
        return false;
      } catch (ExpiredExceptionV3 $e) {
        return false;
      } catch (DomainException $e) {
        // continue
      }
```

**Comment by GasparMDQ** [comment]
Exactly the same problem here. We patch it putting a constraint on our composer.json not allowing firebase/php-jwt going over version 4.*

**Comment by ken-boom** [comment]
This was driving me nuts, I was wondering why my Google Signin randomly broken -_-

**Comment by mirko77** [comment]
@GasparMDQ could you post your `composer.json`?

**Comment by GasparMDQ** [comment]
@mirko77 

[composer.json.txt](https://github.com/google/google-api-php-client/files/1415912/composer.json.txt)

**Comment by kenji-1996** [comment]
Any update on this? Should i downgrade my api composer to 2.0?

**Comment by GasparMDQ** [comment]
The PR was accepted and included in the project. By looking at the branches, I seems that will be available on version 2.2.1 (whenever they release it)

**Comment by bshaffer** [comment]
Added in [`2.2.1`](https://github.com/google/google-api-php-client/releases/tag/v2.2.1)! 

Open a new issue if you continue to experience problems. Thank you!

**Comment by kenji-1996** [comment]
@bshaffer if my current build is working with a slightly lower version of firebase working is there any reason to update to 2.2.1? or should I sit tight unless theres something in 2.2.1 i see as needed
