### ISSUE TITLE
Can not $client->fetchAccessTokenWithAuthCode($request['code']) get token with given code after redirect.

### ISSUE THREAD

**Issue by richard457** [google/google-api-php-client#1281]
Getting access_token is returning null which result into invalid json token once $client->setAccessToken($access_token); is invoked.

**Comment by chadismydad** [comment]
Are you using a service account?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
