### ISSUE TITLE
Upload File With Custom Properties in PHP Google Drive API

### ISSUE THREAD

**Issue by hlaporthein** [google/google-api-php-client#1283]
I have difficulties in setting custom properties in file upload at google drive api using php. Uploading the file is ok, but, I can't set custom properties name. I have check in their official documentation. But, I can't find it. Below are my upload codes. I also asked in **[stackoverflow](https://stackoverflow.com/questions/45564233/upload-file-with-custom-properties-in-php-google-drive-api)**. But, I didn't get the answers. Could anyone help me about that.
```

    $fileMetadata = new Google_Service_Drive_DriveFile();
    $fileMetadata->setName( 'app property test' );
    $fileMetadata->setProperties( json_encode( array(
        'key'        => 'custom_key',
        'value'      => 'This is value',
        'visibility' => 'PRIVATE',
    ) ) );

    $content = file_get_contents( $file_path );
    $file    = $service->files->create( $fileMetadata, array(
            'data'       => $content,
            'mimeType'   => $mimeType,
            'uploadType' => 'multipart',
        )
    );

```

here is some of the things that I have already tested.
```

//This one doesn't work too

$fileMetadata->setProperties(array(
    'key'        => 'custom_key',
    'value'      => 'This is value',
    'visibility' => 'PRIVATE',
));
```

I also tested with this one, too.
```

    //this is not working 
    $fileMetadata = new Google_Service_Drive_DriveFile(array(
        'name' => 'This is file name',
        'appProperties' => array(
            'my_custom_field' => 'My value'
        )
    ));
```

Could anyone advice me how I should set custom properties in google drive upload files. Thanks.

**Comment by chaoticmass** [comment]
I am also having a problem with this. Some guidance on this would be appreciated.

**Comment by chaoticmass** [comment]
Actually, I found this is working for me:

    $folder_metadata = new Google_Service_Drive_DriveFile(array(
        'name'=>$directory_name,
        'mimeType'=>'application/vnd.google-apps.folder',
        'parents'=>array($prop_folder_id),
        'teamDriveId'=>$job['team_drive_id'],
        'appProperties'=>array(
            'prop_id'=>$job['prop_id']
        )
    ));

**Comment by mattwhisenhunt** [comment]
Looks like your question was answered by helpful community members. Thanks community! Please feel free re-open if I misread the thread.

**Comment by SanderVanCamp** [comment]
Still not getting it. @chaoticmass, could you provide some more context? Could you post the actual call to $service->files->create()? Or even more? I'm really struggling! 

Thank you!

**Comment by Inchie** [comment]
@chaoticmass @SanderVanCamp The snippet works to create app properties. But the method $driveService->files->listFiles()... don't list the new properties.....

**Comment by brynhood** [comment]
just for readers who are struggling how to do this:

```
$file = new Google_Service_Drive_DriveFile(array(
            'name'=> "Hello World!",
            'mimeType' => 'application/octet-stream',
            'uploadType' => 'multipart',
            'properties' => array('expiredon' => 'test')
        ));
        $result2 = $service->files->create(
            $file,
            array(
               'data' => file_get_contents('mylocalfile.pdf'),
            )
        );
```
