### ISSUE TITLE
New version of JWT generating errors

### ISSUE THREAD

**Issue by Romain** [google/google-api-php-client#1286]
I had to rollback from version 2.2.0 to version 2.1.3 because with the version, I was repeatedly getting the following error:

```
request.CRITICAL: Uncaught PHP Exception Firebase\JWT\SignatureInvalidException: "Signature verification failed" at /www/vendor/firebase/php-jwt/src/JWT.php line 112 {"exception":"[object] (Firebase\\JWT\\SignatureInvalidException(code: 0): Signature verification failed at /www/vendor/firebase/php-jwt/src/JWT.php:112)"} []
[2017-08-10 21:46:56] request.INFO: Matched route "foo_bar". {"route_parameters":{"_controller":"App\\MyBundle\\Controller\\MyController::fooBarAction","_route":"foo_bar"},"request_uri":"https://www.foo.com"} []
```

Any idea of why I'm getting this error with v2.2.0?
What would be your hint for me to be able to securely update the bundle?

Thanks for your help,
Romain

**Comment by m-nienberg** [comment]
Me too. See issue #1279

**Comment by thejaswip** [comment]
Me too , downgrading by using
composer require firebase/php-jwt:4.0

fixed the problem for me !!! largely this is becoming a problem when things are not getting properly tested with this library for example we should have some sort of max version set in the composer file for which this library has been tested without me having to google search for solutions !

**Comment by kenji-1996** [comment]
@thejaswip thanks for the fix, fucking bizzare that official google doc here https://developers.google.com/identity/sign-in/web/backend-auth will lead to this error, I guess with so many projects they deal with these things can happen quite easily.

**Comment by bshaffer** [comment]
Added in [`2.2.1`](https://github.com/google/google-api-php-client/releases/tag/v2.2.1)! 

Open a new issue if you continue to experience problems. Thank you!
