### ISSUE TITLE
how to get usei_id 

### ISSUE THREAD

**Issue by kiranbulley** [google/google-api-php-client#1287]
**Heads up!**

We appreciate any bug reports or other contributions, but please note that this issue
tracker is only for this client library. We do not maintain the APIs that this client
library talks to. If you have an issue or questions with how to use a particular API,
you may be better off posting on Stackoverflow under the `google-api` tag.

Thank you!

**Comment by bshaffer** [comment]
Please file an issue with details for your question! This one does not have enough info
