### ISSUE TITLE
Improper content value for empty files

### ISSUE THREAD

**Issue by alexgheorghiu** [google/google-api-php-client#1288]
Retrieving the content of an empty file always is (returned as) FALSE.

The piece of code resides in function parseHttpResponse($respData, $headerSize) which in  v1 resides in Abstract.php and in v2 resides in Batch.php.

`

  private function parseHttpResponse($respData, $headerSize)
  {
    ...
      if ($headerSize) {
          **$responseBody = substr($respData, $headerSize);**
          ...
      } else {
    ...
  }
`
If the file is empty then the $respData size is the same as $headerSize thus making the $responseBody equal to FALSE.

In addition we can check the headers and see if the  content type is "application/x-empty".

Note: If my findings are true I can write a patch for this.

Note 2: Github does not allow me to attach an empty file for testing ...do they use this API too? :)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a few days ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
