### ISSUE TITLE
refresh google token must be passed in or set as part of setAccessToken automatically

### ISSUE THREAD

**Issue by mahamood** [google/google-api-php-client#1290]
I had created google access token after 1 hour , token was expired .

I want to reset access token automatically offline. please give me suggestions how to refresh token.

Thank you Advance.

**Comment by mahamood** [comment]
any help..?

**Comment by mahamood** [comment]
please give me suggestions

**Comment by xtratio** [comment]
See https://stackoverflow.com/questions/39314833/google-api-client-refresh-token-must-be-passed-in-or-set-as-part-of-setaccessto

**Comment by mattwhisenhunt** [comment]
Looks like your question was answered by helpful community members. Thanks community! Please feel free re-open if I misread the thread.

**Comment by bizmate** [comment]
I am glad i searched for this but i must say all these edge cases make it really annoying.
