### ISSUE TITLE
Delete Sheet Using Google Sheet API V4

### ISSUE THREAD

**Issue by hamzazafeer** [google/google-api-php-client#1293]
I want to delete a sheet using Google's Sheet API v4. To that end, I am using the following method to delete a sheet:

`$spreadsheetIddelete = '1sL7ZFBEFeah0OB8O6UG7L5YBGO6QS9JZV5n0Bwjbnkl';`
`$requests = new Google_Service_Sheets_Spreadsheet(array(
    "deleteSheet" => array(
        'sheetId'=> (int)'$spreadsheetIddelete',
    )
));`
`$requestBody = new Google_Service_Sheets_BatchUpdateSpreadsheetRequest();
$requestBody->setRequests($requests);
$response = $service->spreadsheets->batchUpdate($spreadsheetIddelete, $requestBody);`
`echo '<pre>', var_export($response, true), '</pre>', "\n";`

But when I execute this, I get the following error:

> Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 400, "message": "Invalid requests[0].deleteSheet: You can't remove all the sheets in a document.", "errors": [ { "message": "Invalid requests[0].deleteSheet: You can't remove all the sheets in a document.", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } }

[https://stackoverflow.com/questions/45940796/delete-sheet-using-google-sheet-api-v4](url)

**Comment by mattwhisenhunt** [comment]
It looks like you need at least one other sheet in the document before you delete your desired sheet.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We didn't see any follow up in over a week so we are closing it. Please feel free to re-open this issue with more information.
