### ISSUE TITLE
Invalid Argument details

### ISSUE THREAD

**Issue by beatscode** [google/google-api-php-client#1297]
I have been getting 400 errors "Request contains an invalid argument". Is there anyway to dig deeper on the details of the message. I'm making calls to the google my business api trying to create a location.
`{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
`

**Comment by mattwhisenhunt** [comment]
Are you using the PHP library from https://developers.google.com/my-business/samples/?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by sera527** [comment]
@mattwhisenhunt how to find out which argument is invalid?
