### ISSUE TITLE
Transfer the implementation of API from google-api-ruby-client

### ISSUE THREAD

**Issue by Avtonom** [google/google-api-php-client#1303]
Transfer to PHP implementation of API from ruby https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/mybusiness_v3/service.rb

```

"/mybusiness:v3/mybusiness.accounts.locations.getGoogleUpdated": get_google_updated_account_location
"/mybusiness:v3/mybusiness.accounts.locations.reviews.deleteReply": delete_reply
"/mybusiness:v3/mybusiness.accounts.locations.reviews.reply": reply_to_review
"/mybusiness:v3/mybusiness.accounts.locations.reviews.get": get_review
"/mybusiness:v3/mybusiness.accounts.locations.reviews.list": list_reviews
```

**Comment by mattwhisenhunt** [comment]
@Avtonom, it looks like you were making yourself a ticket and got the wrong repo.

**Comment by mattwhisenhunt** [comment]
I think I understand your request now. For now use the PHP library available at https://developers.google.com/my-business/samples/.
