### ISSUE TITLE
Offer ability to Authorize in Constructor with Service Account

### ISSUE THREAD

**Issue by voycey** [google/google-api-php-client#1307]
We use environment variables for the majority of our configuration, it seems like it should be possible to create valid authorization headers by using the Google_Client constructor, I can see some variables in there but passing in the items from the credentials json file doesn't seem to populate correctly:

```$this->client = new \Google_Client(
            [
                'client_id' => '0000000000052288323',
                'client_email' => 'somemeail@sometesting.iam.gserviceaccount.com',
                'signing_key' => "-----BEGIN PRIVATE KEY-----mykey-----END PRIVATE KEY-----\n",
                'type' => 'service_account'
            ]
        );
```

Is there a way we can accomplish this so I can use my Environment configuration to hold these values rather than having more un-version controlled files dotted about?

Thanks

**Comment by bshaffer** [comment]
Yes there is! See the method [`Google_Client::setAuthConfig`](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L845), which accepts an array matching that contained in the auth config file, e.g.:

```php
$authConfig = [
    'client_id' => getenv('GOOGLE_CLIENT_ID'),
    'client_secret' => getenv('GOOGLE_CLIENT_SECRET'),
    'redirect_uris' => ['https://www.yourwebsite.com/oauth/callback'],
];

$client = new Google_Client();
$client->setAuthConfig($authConfig);
```

**Comment by voycey** [comment]
Ah fantastic - thanks!
