### ISSUE TITLE
Strange error response when passing null rather then nothing.

### ISSUE THREAD

**Issue by LindaLawton** [google/google-api-php-client#1309]
` $service->files->ListFiles(null);`

**results in** 

> Warning: array_merge(): Argument #2 is not an array in C:\xampp\htdocs\Google-PHP-Genreated-Samples\vendor\google\apiclient-services\src\Google\Service\Drive\Resource\Files.php on line 204
> 
> Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\Google-PHP-Genreated-Samples\vendor\google\apiclient\src\Google\Service\Resource.php on line 136
> 
> Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\Google-PHP-Genreated-Samples\vendor\google\apiclient\src\Google\Service\Resource.php on line 268

The following two options work corectly

`  $parameters['pageSize'] = 1000;`
`$service->files->ListFiles($parameters);`

and

` $service->files->ListFiles();`

While i agree there is no real reason to send null as the parameter i think the error response from the library is a little strange.

**Comment by bshaffer** [comment]
The reason is when you pass `null` in, you are replacing the default parameter. The default parameter is `array()`, as you can see [here](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Drive/Resource/Files.php#L202).

It would be better if we had typehints, so `listFiles` would throw a type exception instead.

**Comment by LindaLawton** [comment]
so sending an empty array would be acceptable?

**Comment by bshaffer** [comment]
Yes, the parameters are optional. Sending an empty array is equivalent to calling the method with no parameters:

```php
$response = $service->files->ListFiles();
// is equivalent to
$parameters = [];
$response = $service->files->ListFiles($parameters);
```

**Comment by LindaLawton** [comment]
In your opinion what is the best way for users to do this.  to use a $parameter array or to use the set methods for the parameters?

`$results->getNextPageToken();`

I am in the process of building the generated sample templates for this library.    Any guidance you can to give in building solid samples which will follow your best practice guidelines would be appreciated.   [Google-APIs-PHP-Samples](https://github.com/LindaLawton/Google-APIs-PHP-Samples)
