### ISSUE TITLE
Wrong method in auth example

### ISSUE THREAD

**Issue by Ianpilip** [google/google-api-php-client#1313]
On the page https://developers.google.com/api-client-library/php/auth/web-app there is a mistake in the code example of index.php.
You have to write
$files = $drive->files->listFiles(array())->getFiles();
instead of
$files_list = $drive_service->files->listFiles(array())->getItems();

getItems(); doesn't work any more

Thank you!

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up. We will get that changed ASAP.

**Comment by NickStarlight** [comment]
The example code is still wrong.
