### ISSUE TITLE
Create Client Object with Service Account Authentication

### ISSUE THREAD

**Issue by danielrgray** [google/google-api-php-client#1316]
I am trying to connect to the Google Directory Service to pull a list of users. I am getting errors when creating the Google Client Object wehn authenticating using a service account. Here are my steps and code:

1. Created a project on the Google API Console
2. Enabled Admin SDK under Library
3. Created credentials - Service account key with DWD enabled
4. Downloaded the JSON OAuth2 Service Account JSON file that contains the Public/Private key pair
5. Created credentials - OAuth2 Service account Client ID
6. Downloaded the JSON Service account Client ID JSON file
7. Obtained API access from G Suite Admin Console providing the Client ID for the service account created above
8. Added necessary scopes: https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/admin.directory.orgunit

`putenv('GOOGLE_APPLICATION_CREDENTIALS='.$path_to_oauth2ServiceJson);

$client = new \Google_Client();
$client->setApplicationName ('Application Name');
$client->useApplicationDefaultCredentials();
$client->setScopes (['https://www.googleapis.com/auth/admin.directory.user', 'https://www.googleapis.com/auth/admin.directory.group', 'https://www.googleapis.com/auth/admin.directory.orgunit']);
$client->setAuthConfig($path_to_service_account_client_id_json);
$client->setSubject($google_service_email_address);

$service = new \Google_Service_Directory ($client);`

I get a 500 error with: Notice: Undefined index: client_secret and my service account client ID JSON does not contain a client_secret_id key.

Any assistance is greatly appreciated!

**Comment by mattwhisenhunt** [comment]
Sorry for the delay. Are you still experiencing this issue?
