### ISSUE TITLE
Oauth code to access_token

### ISSUE THREAD

**Issue by LeonNabuurs** [google/google-api-php-client#1319]
Hi,

I try to authenticate using the google-api-php-client, but I have some troubles, mainly due to my lack of knowledge. I hope someone can help me!

My application sends an authentication/access request to google and asks for access to my personal calendar. Indeed I see the request in my browser, which I approve. And I receive the code via my return_URI.
This code I need to convert to an acces_token, but that does not function for me. The relevant statements are:
$code = $_GET['code'];
$token = $client->fetchAccessTokenWithAuthCode($code);

The problem I encounter: "Call to a member function fetchAccessTokenWithAuthCode() on a non-object in xxx-xxxx-xxx.php on line 45.

Hope someone can help me!

**Comment by mattwhisenhunt** [comment]
I'm going to need more information to be able to help you:
Did you start from one of the sample projects provided by Google?
Are you using an OAuth 2.0 client credential?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
