### ISSUE TITLE
Add custom goals to list with Metrics and Dimensions Metadata API (feature request)

### ISSUE THREAD

**Issue by ssgtcookie** [google/google-api-php-client#1321]
The metadata API can be used to get a list of Metrics and Dimensions as specified [here](https://developers.google.com/analytics/devguides/reporting/metadata/v3/reference/metadata/columns/list). The following list shows the a little bit of the output when you query for metrics and dimensions:

```
ga:goalXXStarts
ga:goalStartsAll
ga:goalXXCompletions
ga:goalCompletionsAll
ga:goalXXValue
ga:goalValueAll
ga:goalValuePerSession
ga:goalXXConversionRate
ga:goalConversionRateAll
ga:goalXXAbandons
ga:goalAbandonsAll
ga:goalXXAbandonRate
ga:goalAbandonRateAll
```

The goals are marked as XX because they are UA-ID specific (correct me if I'm wrong). How cool would it be, if you can specify an UA-ID, and get a list with the XX-es filled with real numbers. I think it would be clean to add this to the `Google_Client()` class as something like "setAnalyticsId" or something like that, so you can specify you UA-ID and get a full list instead of a default list with missing goals.

As workaround I use the management function to get the goals and than I fuse them in the list with the other default metrics and dimensions. I think this looks ugly and can be improved don't you guys agree?

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
