### ISSUE TITLE
Cannot find new Conversion Linker under Tags in API

### ISSUE THREAD

**Issue by ahtinurme** [google/google-api-php-client#1323]
I would like to use also the new Adwords Conversion Linker through Tag Manager API, but I don't see any reference to it. Help?

**Comment by MitsunagaKikuchi** [comment]
I had the same problem, but this code seems to work.
Please try this.

```
            $request = new \Google_Service_TagManager_Tag();
            $request->setName('conversion_linker');
            $request->setType('gclidw');
            $request->setFiringTriggerId(['2147479553']);   // All Page View
            $request->setTagFiringOption('oncePerEvent');

```

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.
