### ISSUE TITLE
How to use Regular Expressions with Google Analytics Reporting API V4

### ISSUE THREAD

**Issue by ravigehlot** [google/google-api-php-client#1324]
I thought I would give this a try. Before I start, I would like to say that I have already posted on StackOverflow: https://stackoverflow.com/questions/46960709/how-to-use-regular-expressions-with-google-analytics-reporting-api-v4 I have also done various searches on Google Search without any success. I am unable to use REGEX. Any help is greatly appreciated.

**Comment by mattwhisenhunt** [comment]
It looks like this is being answered on SO.

**Comment by ravigehlot** [comment]
Hello Matt, yes someone is trying to help me though we still haven't arrived on a plausible solution. At this point, I am ditching the PHP client altogether.
