### ISSUE TITLE
mapTypes(): address, addressType, addressDataType issue triggers PHP error

### ISSUE THREAD

**Issue by andreisusanu** [google/google-api-php-client#1325]
Hello!

I'm getting the following PHP error while trying to get the list of addresses:

`Uncaught Error: Class name must be a valid object or a string in vendor/google/apiclient/src/Google/Model.php:113`

My code looks like this:
`$availableAddresses = $this->getComputeService()->addresses->listAddresses($this->getProjectName(), $this->getRegion());`

The source of the problem is that the following returns null for **address**:
`$propertyClass = $this->{$this->keyType($key)};`

So if $propertyClass is null, callin `elseif ($val instanceof $propertyClass)` or `new $propertyClass($val)` is generating a PHP error.

My quick fix is to change this:
`if (property_exists($this, $this->keyType($key)))`
to this: 
`if (property_exists($this, $this->keyType($key)) && !empty($this->{$this->keyType($key)}))`

But a proper fix needs to be implemented in the library.
Good luck!

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
