### ISSUE TITLE
Google_Client namespacing

### ISSUE THREAD

**Issue by Johnhhorton** [google/google-api-php-client#1327]
I'm working in the context of WordPress plugins. In WordPress, you have no way to control what other plugins are doing. This means that if another plugin is using a library (via copy/paste or composer), developers run the risk of conflicting packages.

I'm using a utility https://github.com/TypistTech/imposter that modifies namesspaces allowing me to scope all the vendor libaries for my project without creating conflicts.
 
`\Google_Client` is registered in the global namespace, and I haven't been able to figure how using composer or the utility above to change that (without editing the vendor files manually). This is producing a conflict with a 3rd party plugin that is using an old version of google/apiclient.

While this isn't an issue for single composer projects, it's a massive problem for WordPress plugin development.

**Comment by craigiswayne** [comment]
Ran into a similar issue, at the end I had to commit Google's API files  into my plugin to ensure that it's reading the right files... Added a few class exists checks, method checks and exception catches to fix this

Don't take this the wrong way... but
at the end of the day, this is not Google's problem... its yours

**Comment by Konafets** [comment]
@Johnhhorton As far as I see in the composer.json the namespace is `Google_`, not very common to do it that way, but it is not in the global `\` namespace.

**Comment by hawkidoki** [comment]
Hello!

I stumble upon the exact same problem while writing a plugin. Duplicator Pro use an old version of `Google_Client()`. Would you be kind enough to share you code modification in order to make it work?

Thanks in advance!

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free explain why you believe fixing it is essential for users of this client library.

**Comment by Konafets** [comment]
I think you should follow the PSR-Standards for namesspaces (PSR-0 and PSR-4) and add a proper vendor name + get rid of underscores in the lib name.

**Comment by mmesarina** [comment]
@Johnhhorton 
Did you find a workaround for this problem? If so, could you share?

thank you

> I'm working in the context of WordPress plugins. In WordPress, you have no way to control what other plugins are doing. This means that if another plugin is using a library (via copy/paste or composer), developers run the risk of conflicting packages.
> 
> I'm using a utility https://github.com/TypistTech/imposter that modifies namesspaces allowing me to scope all the vendor libaries for my project without creating conflicts.
> 
> `\Google_Client` is registered in the global namespace, and I haven't been able to figure how using composer or the utility above to change that (without editing the vendor files manually). This is producing a conflict with a 3rd party plugin that is using an old version of google/apiclient.
> 
> While this isn't an issue for single composer projects, it's a massive problem for WordPress plugin development.



> I'm working in the context of WordPress plugins. In WordPress, you have no way to control what other plugins are doing. This means that if another plugin is using a library (via copy/paste or composer), developers run the risk of conflicting packages.
> 
> I'm using a utility https://github.com/TypistTech/imposter that modifies namesspaces allowing me to scope all the vendor libaries for my project without creating conflicts.
> 
> `\Google_Client` is registered in the global namespace, and I haven't been able to figure how using composer or the utility above to change that (without editing the vendor files manually). This is producing a conflict with a 3rd party plugin that is using an old version of google/apiclient.
> 
> While this isn't an issue for single composer projects, it's a massive problem for WordPress plugin development.
