### ISSUE TITLE
get only public videos from youtube playlist  

### ISSUE THREAD

**Issue by usamamashkoor** [google/google-api-php-client#1330]
Hi i am trying to get only public videos from youtube playlist but i can not seem to find anything related to this on youtube api docs.

Here is my code.
```
$channelsResponse = $youtube->channels->listChannels('snippet,  contentDetails', array(
		    	                  'mine' => 'true',
		    	   	   ));
$htmlBody = '';
foreach ($channelsResponse['items'] as $channel) {
     	$uploadsListId = $channel['contentDetails']['relatedPlaylists']['uploads'];
}
$data = $youtube->playlistItems->listPlaylistItems('snippet, contentDetails, status ',array(
            'part' => 'snippet,  contentDetails , status',
            'playlistId' => $uploadsListId          
 ););  
```
i can get the public or private status after getting YouTube video data but i want to fetch only public videos from YouTube don't want to check the public or private  status after getting YouTube video.

Thanks

**Comment by mattwhisenhunt** [comment]
I can't find anything related to this in the API docs either.

This PHP client can only perform queries the API library provides. It looks to me like you are going to have to perform multiple requests.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We didn't see any follow up in over a week so we are closing it. Please feel free to re-open this issue with more information.

**Comment by gladsonrobinson** [comment]
Hi @usamamashkoor @mattwhisenhunt Have you got any updates on it.

**Comment by usamamashkoor** [comment]
@gladsonrobinson i have to get all the videos then i have to filter out the public videos by my self.

**Comment by Constantine1995** [comment]
would it be a problem for pagination, say every 10 videos? If the server receives 5 private and 5 public
