### ISSUE TITLE
Hi Team, 

### ISSUE THREAD

**Issue by parulkamra** [google/google-api-php-client#1332]
**Heads up!**

We appreciate any bug reports or other contributions, but please note that this issue
tracker is only for this client library. We do not maintain the APIs that this client
library talks to. If you have an issue or questions with how to use a particular API,
you may be better off posting on Stackoverflow under the `google-api` tag.

Thank you!

**Comment by mattwhisenhunt** [comment]
Great point. In fact, my hope is that we can leave Github issues for detailed bug reports with steps to reproduce and start asking and answering usage questions on StackOverflow, too. #[google-api-php-client](https://stackoverflow.com/questions/tagged/google-api-php-client)

**Comment by parulkamra** [comment]
ok thankyou :-)
