### ISSUE TITLE
Getting only error message in Exception

### ISSUE THREAD

**Issue by anuj9196** [google/google-api-php-client#1339]
I am using `$e->getMessage();` to get the exception error only
```
try{
     /**
      * try block
      */
        } catch (Google_Service_Exception $e) {
            $response['status'] = false;
            $response['message'] = $e->getMessage();
        } catch (Google_Exception $e) {
            $response['status'] = false;
            $response['message'] = $e->getMessage();
        }
```
But, on authentication failed. It returns json data
```
{ "error": { "errors": [ { "domain": "global", "reason": "authError", "message": "Invalid Credentials", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Invalid Credentials" } } 
```

I only want the `message:`

**Comment by net-tools** [comment]
Well, json_decode and get the message property ? 
- see if `$json = json_decode($e->getMessage())` succeeds or not (if so, we have a json string ; otherwise, plain text error message)
- if so, `$json->error->errors[0]->message` is set with the error message

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
