### ISSUE TITLE
google api after post

### ISSUE THREAD

**Issue by brainslcdevshop** [google/google-api-php-client#1340]
**Hello !**

After post with help google domain api on google plus page, top part on my post I can't see "public", how can I resolve it ?
I spoke with google support he told me what on my console all good.
My code:
`
        $plusDomain = new \Google_Service_PlusDomains($client);
        $activity = new \Google_Service_PlusDomains_Activity();
        $obj = new \Google_Service_PlusDomains_ActivityObject();

        $access = new \Google_Service_PlusDomains_Acl();
        $access_type = new \Google_Service_PlusDomains_PlusDomainsAclentryResource();
        $comment = 'new comments';

            $me = $plusDomain->people->get('me');
            $userId = $me->id;

            $obj->setContent($comment);
            $access->setDomainRestricted(true);
            $access_type->setType('public');
            $access->setItems(array($access_type));

            $activity->setObject($obj);
            $activity->setAccess($access);

            $plusDomain->activities->insert($userId, $activity);
`

Thank you!

**Comment by brainslcdevshop** [comment]
http://i.prntscr.com/afhAgxzgRz_AflG3fkLgrA.png

**Comment by mattwhisenhunt** [comment]
@brainslcdevshop could you try reproducing this in [API Explorer](https://developers.google.com/apis-explorer/#search/domains/plusDomains/v1/plusDomains.activities.insert).

**Comment by brainslcdevshop** [comment]
@mattwhisenhunt thank you for answer, will check.

**Comment by mattwhisenhunt** [comment]
This kinda sounds like a server-side API issue. If that is not the case let we can re-open this.
