### ISSUE TITLE
Google_Service_Calendar_EventReminder doesn't work

### ISSUE THREAD

**Issue by alexej123** [google/google-api-php-client#1342]
Hello there, Google_Service_Calendar_EventReminder seems to be ignored. It looks like useDefault doesn't work. I also tried setting it to "false" (string), as suggested in some blogs, but it didn't help either... Any ideas? Thanks in advance! Release 2.2.0.

`		$reminders = new Google_Service_Calendar_EventReminders();`
`		$reminder = new Google_Service_Calendar_EventReminder();`
`		$reminder->setMethod('popup');`
`		$reminder->setMinutes(60);`
`		$reminders->setUseDefault(false); `
`		$reminders->setOverrides(array($reminder));`
`		$event->setReminders($reminders);`

**Comment by mattwhisenhunt** [comment]
Are you inserting an event or updating one?

Do you get an error response? If not, try including reminders in _fields_ so they come back in the response and please include that.

More generally, please include as much as information as you can to help us reproduce your result.

**Comment by alexej123** [comment]
@mattwhisenhunt It works neither for inserting nor for updating. No error response. The events get correctly inserted / updated but with no reminders added. What do you mean by _fields_? Thanks!

**Comment by mattwhisenhunt** [comment]
Sorry this slipped through the cracks. Fields is a request field that specifies which fields to include in a partial response.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
