### ISSUE TITLE
PHP autoload.php references non-existent vendor directory in v2.2.1

### ISSUE THREAD

**Issue by jshrek** [google/google-api-php-client#1344]
In the Google API PHP Client there is /Google/autoload.php

This file within itself references /vendor/autoload.php

The /vendor/ folder does not exist, so this will always throw an error.

All the examples I can find say to require_once __DIR__.'/vendor/autoload.php'; but even if vendor folder existed, the autoload.php file simply references itself and does not do anything.

So which file in the /Google/ folder should we include instead of autoload.php?

**Comment by Retalyx** [comment]
Same problem here, any information?

**Comment by slaFFik** [comment]
You should install the lib via `composer require google/apiclient`.
This Google API client is intended to be used with composer. It will generate a correct autoload file, that you should be using to include the lib in your app.

**Comment by jshrek** [comment]
Using shared hosting so installing Composer is not an option.

I am trying to use the SERVICE ACCOUNT KEY setup in Google Developers Console so can access private liveStream and liveBroadcast informaton from YouTube API.

There must be a simpler way to do this :(

**Comment by net-tools** [comment]
Or you can also download the full release (including dependencies) : [](https://github.com/google/google-api-php-client#download-the-release), please read the readme file.

Shared hosting should not prevent you from using Composer, unless your host don't want outbound connections to Packagist...

**Comment by mattwhisenhunt** [comment]
It looks like the latest release does not have a release package. I am looking into that and in the mean time the non-composer work around is to download the source zip from 2.2.1 and google-api-php-client-2.2.0.zip from the previous release and copy the latter's vendor directory into your 2.2.1 directory tree.

**Comment by jshrek** [comment]
Shared host wont let me install Composer.

The readme file even says to use the require_once '/path/to/google-api-php-client/vendor/autoload.php'; however as I pointed out before, there is no VENDOR folder in the downloaded release.

And also, again, if you look at the autoload.php file it is also referencing /vendor/autuload.php and will ALWAYS generate an error.

And the full release also is missing the GuzzleHttp\ClientInterface class

**Comment by jshrek** [comment]
Copying VENDOR folder from 2.2.0 to 2.2.1 seems to have solved all the problems.

Thanks @mattwhisenhunt

**Comment by squarecandy** [comment]
Also experiencing this as an issue on my setup.
Please continue to support a non-composer install option going forward.

**Comment by bshaffer** [comment]
Wow, so sorry for missing this everyone. The proper zip files with all dependencies has been added to [v2.2.1](https://github.com/google/google-api-php-client/releases/tag/v2.2.1). 

Thank you all for this feedback, it's really good to know so many of you are using the non-composer install option. 

@mattwhisenhunt FYI I've been using [this script](https://gist.github.com/bshaffer/85f96c1315c486ce3bc8d4cfce033493) to create the release packages.

**Comment by sloboy** [comment]
This is the same issue as #1381
I was stumped for days...please update the readme to reflect different version for non-composer to save others time.

**Comment by steevec** [comment]
Yes, the lead from the google help page give us the wrong zip => google-api-php-client-master.zip without vendor folder
https://developers.google.com/api-client-library/php/start/installation
