### ISSUE TITLE
Insufficient scope error even when addScope used

### ISSUE THREAD

**Issue by jshrek** [google/google-api-php-client#1346]
I am using the PHP client library v2.2.1 (added vendor folder from v2.2.0).

In the Google Developer Console, I have enabled the YouTube Data API V3 and under credentials I setup a SERVICE ACCOUNT KEY and downloaded the .json key file and have it stored in non-publicly accessible location on my server.

The error I receive is insufficient scope error, however in my code below you will see that I have added the scopes required:

`[0] => Bearer realm="https://accounts.google.com/", error=insufficient_scope, scope="https://www.googleapis.com/auth/youtube.readonly"`

Here is my code:

```
//Require Google API PHP Client library
require_once __DIR__.'/google-api-php-client/vendor/autoload.php';

//Setup new Google_Client
$gooClient = new Google_Client();

//Set location of json Service Account KEY file
$gooClient->setAuthConfig('/home/myserver/google-api-php-client/myserviceaccountkeyfile.json');

//Add scopes
$gooClient->addScope(Google_Service_YouTube::YOUTUBE_FORCE_SSL);
$gooClient->addScope(Google_Service_YouTube::YOUTUBE_READONLY);
$gooClient->addScope(Google_Service_YouTube::YOUTUBE);

//Authorize and send
$httpGooClient = $gooClient->authorize();
$responseGooClient = $httpGooClient->get('https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet&broadcastStatus=active');

//View response
echo "<pre>";
print_r($responseClientBroadcast);
echo "</pre>";

```

**Comment by immyemperor** [comment]
bro its just that poople (google) sucks...im stuch with same and its been two months still this issue is not fixed...no one even helped me here

**Comment by mattwhisenhunt** [comment]
@immyemperor good point what issue did you want me to look at it. @jshrek I tried reproducing your problem and got a similar error response (Login Required).
I suspect you would have more luck with one of the Service classes:
```php
$youtube = new Google_Service_YouTube(getClient());
try {
  $broadcastsResponse = $youtube->liveBroadcasts->listLiveBroadcasts(...);
  foreach ($broadcastsResponse['items'] as $broadcastItem) {
    echo $broadcastItem . "\n";
  }
} catch(Google_Service_Exception $e) {
	echo $e->getMessage() . "\n";
}
```

**Comment by bshaffer** [comment]
Note that the Youtube Data API does not accept service account credentials ([see here](https://github.com/google/google-api-php-client/pull/1354/files)). I'm not sure if the liveBroadcasts endpoint falls in this category but you could try using Client Credentials instead.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested some course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by immyemperor** [comment]
i am getting scope error on google oauth not for youtube...i don't know why this error is being thrown i have done whatever provided in google signin documentation...this is the first time i am using php for this earlier with android it was working for me even very easy in implementation...so if you could help sorting this issue i will be very thankful to you.

**Comment by mattwhisenhunt** [comment]
@immyemperor, you can definitely use server side Java if you prefer that: https://github.com/google/google-api-Java-client. As is it, you have not provided enough detail about the PHP errors you are receiving to enable me to give you meaningful answers.
