### ISSUE TITLE
Cannot retrieve video id/URL of live video thru liveStreams or liveBroadcast

### ISSUE THREAD

**Issue by jshrek** [google/google-api-php-client#1347]
When a video is currently livestreaming, you can not get the video id  that goes on end of url https://www.youtube.com/watch?v=**video-id**

When using the Google_Service_YouTube liveBroadcast or liveStreams there is no way to get the video id of a currently playing livestream.

There should be some way to get this information, even when the livestream is UNLISTED or PRIVATE.

The following method works for PUBLIC livestreams, but not for UNLISTED or PRIVATE livestreams:
`https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=MY_CHANNEL_ID&type=video&eventType=live&key=MY_API_KEY`

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. It looks like this is actually a feature request for the [YouTube Data API](https://developers.google.com/youtube/v3/). 

If you believe that part of this issue still needs to be addressed in this client library, then feel free to re-open this issue with more information.

**Comment by jshrek** [comment]
Posted issue here:
https://issuetracker.google.com/issues/69732600
