### ISSUE TITLE
Updating Multiple Offline Calendars

### ISSUE THREAD

**Issue by tomshaw** [google/google-api-php-client#1349]
Are there any settings to be aware of when updating multiple offline calendars. Our system will only let us update a single calendar event per request. When we var dump the request no errors are thrown the api response has the correct data except the event is never created or updated in the target user calendar. It seems subsequent calls after the first just won't work.

**Comment by mattwhisenhunt** [comment]
Sending a couple of samples requests thru the [API Explorer](https://developers.google.com/apis-explorer/#search/calendar/calendar/v3/) might bring some clarity to this issue. At very least you will be able to isolate whether it is a problem with your client or the API.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
