### ISSUE TITLE
phpseclib > 2.0.7

### ISSUE THREAD

**Issue by dracoirs** [google/google-api-php-client#1350]
phpseclib update has changed from method loadKey, line 97 in 
 google-api-php-client/src/Google/AccessToken/Verify.php

If you composer update and pull in the latest phpseclib, your google-api-client library will not work

**Comment by bshaffer** [comment]
Hello @dracoirs , I am not seeing this change [in the phpseclib code](https://github.com/phpseclib/phpseclib/blob/2.0.9/phpseclib/Crypt/RSA.php#L1507). Can you provide a reproduction case?

**Comment by mattwhisenhunt** [comment]
Sounds like this may have been a problem with a library being pinned at a certain version in composer. see #[1376](https://github.com/google/google-api-php-client/pull/1376#issuecomment-395113720)
