### ISSUE TITLE
PHP Notice:  Undefined index: expires_in

### ISSUE THREAD

**Issue by slaFFik** [google/google-api-php-client#1353]
On this line:

> https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L480

```php
// If the token is set to expire in the next 30 seconds.
return ($created + ($this->token['expires_in'] - 30)) < time();
```

Here is my init code: 

```php
$client = new \Google_Client(
            array(
                'client_id'     => $this->gmail['client_id'],
                'client_secret' => $this->gmail['client_secret'],
                'redirect_uris' => array(
                    Auth::get_plugin_auth_url(),
                ),
            )
        );
$client->setAccessType( 'offline' );
$client->setApprovalPrompt( 'force' );
$client->setIncludeGrantedScopes( false );
$client->addScope( \Google_Service_Gmail::GMAIL_SEND );
$client->setRedirectUri( self::get_plugin_auth_url() );
```

If `$client->setIncludeGrantedScopes( true );` - no notice, as response is an array with `expires_in` key.

**Comment by mattwhisenhunt** [comment]
isAccessTokenExpired is testing value usually passed in by $client->setAccessToken(…). Make sure you are passing the entire JSON string, not only the token part.

Typically this string is either fetched from the server $client->fetchAccessTokenWithAuthCode(…) or retrieved from a cache on disk json_decode(file_get_contents($credentialsPath), true).

**Comment by slaFFik** [comment]
Of course, I was doing exactly that. But for some reason got a response without `expires_in`, saved it in DB to reuse later, and passed to `setAccessToken()` which uses the array keys blindly.
My main point was that when I use legitimately the API with `$client->setIncludeGrantedScopes( true );`, the `$creds` array didn't contain the `expires_in` key, which is required in other parts of your library.

**Comment by ingokasch** [comment]
Same here. I stored the original access and refresh token in the database. While using them later the response does not contain the required `expires_in` index.

Tested on v0.42.

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.

**Comment by obayesshelton** [comment]
that worked for me! I was passing the token as a string than the json which included the refresh etc
