### ISSUE TITLE
Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found when using Google_Service_Calendar

### ISSUE THREAD

**Issue by kenma9123** [google/google-api-php-client#1357]
Hi I've been trying to pull a basic list of calendars.  Unfortunately everytime I call the `listCalendarList` method. The errors throw 

```
Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found in /www/kenma9123/lib/classes/Google/vendor/google/auth/src/Cache/MemoryCacheItemPool.php on line 26 
```
Note that I was able to authenticate a user correctly using the oAuth process, so I have access token. This is my code
```
    $client = self::getGoogleClient();
    $client->setAccessToken($accessToken);
    $service = new Google_Service_Calendar($client);
    $calendarList = $service->calendarList->listCalendarList();
```
The `getGoogleClient` method is just pulling the google client. Is there any particular reason why this is happening? I've installed the `google-api-client` with composer using your method `composer require google/apiclient:^2.0` and I also did try to update it just in case with `composer update` but still the same issue.

If you have solution or recommendations, please advice. Thank you!

**Comment by bshaffer** [comment]
This is very interesting, and I'm not sure why this would happen. Can you paste your `composer.lock` on gist.github.com and link to it here?

additionally try running `composer require psr/cache`

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
