### ISSUE TITLE
Undefined index: expires_in in Google_Client->isAccessTokenExpired()

### ISSUE THREAD

**Issue by RobbMLewis** [google/google-api-php-client#1358]
When checking if the access token is expired, it appears that the token only has the access token and the index "expires_in" doesn't exist.  My code:
```
    $client = new Google_Client();
    $client->setApplicationName("Name");
    $client->setScopes(array('https://apps-apis.google.com/a/feeds/groups/'));
    $client->setAuthConfig('client_secrets.json');
    $client->setRedirectUri($redirect_uri);
    $client->setAccessType('offline');
$client->setAccessToken($access_token);
      if ($client->isAccessTokenExpired()) {
//process
}
```

the error I get is:
Notice: Undefined index: expires_in in Google_Client->isAccessTokenExpired() (line 480 of google-api-php-client/vendor/google/apiclient/src/Google/Client.php).

a printout of the $this->token is only the access token, no other indexes.  Am I missing something?

**Comment by mattwhisenhunt** [comment]
isAccessTokenExpired is testing value usually passed in by $client->setAccessToken(…). Make sure you are passing the entire JSON string, not only the token part.

Typically this string is either fetched from the server $client->fetchAccessTokenWithAuthCode(…) or retrieved from a cache on disk json_decode(file_get_contents($credentialsPath), true).

**Comment by RobbMLewis** [comment]
Thank you!  I was trying to update older code when it wasn't returned all at once.
