### ISSUE TITLE
Unable find day wise data in php API V4

### ISSUE THREAD

**Issue by ngsoftech** [google/google-api-php-client#1362]
Hello,
          I am using google analytics data api using google service Account. I am getting all data but when i try to search date wise data than i am getting on sedding data.I need all data like "Session", "New Sessions", "PageViews" etc. I am using following code 

 function getReportDateWise($analytics,$startDate,$endDate,$view_Id) {

  // Replace with your view ID, for example XXXX.
  $VIEW_ID = $view_Id;

  // Create the DateRange object.
  $dateRange = new Google_Service_AnalyticsReporting_DateRange();
  $dateRange->setStartDate($startDate);
  $dateRange->setEndDate($endDate);

  // Create the Metrics object.
  $date = new Google_Service_AnalyticsReporting_Dimension();
  $date->setName("ga:date");
  
  
 $pageviews = new Google_Service_AnalyticsReporting_Metric();
  $pageviews->setExpression("ga:pageviews");
  $pageviews->setAlias("pageviews");
  

  // Create the ReportRequest object.
  $request = new Google_Service_AnalyticsReporting_ReportRequest();
  $request->setViewId($VIEW_ID);
  $request->setDateRanges($dateRange);
  $request->setDimensions(array($date));
 ?> 
Thank you!

**Comment by mattwhisenhunt** [comment]
It looks like you are going to be limited to the format specified in the [API Reference](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet).
