### ISSUE TITLE
ServiceAccount Token Generation

### ISSUE THREAD

**Issue by vijayp4you** [google/google-api-php-client#1365]
Hi Sir,

I have multiple websites in multiple accounts and i want to track sitemap issues for all websites at one place. So i have added ServiceAccount Email ids to the domain's webmaster tools.
Now iam facing few issues such as
1. When i removed ServiceAccount Email ID for one website, it is still visible in list of sitemaps page.
2. When i r emoved website from webmaster tools, iam getting error in list of sitemaps page like below.

`Fatal error: Uncaught exception 'Google_Service_Exception' with message '{ "error": { "errors": [ { "domain": "global", "reason": "forbidden", "message": "User does not have sufficient permission for site 'https://www.standingdesk.io/'. See also: https://support.google.com/webmasters/answer/2451999." } ], "code": 403, "message": "User does not have sufficient permission for site 'https://www.standingdesk.io/'. See also: https://support.google.com/webmasters/answer/2451999." } } ' in /srv/users/serverpilot/apps/anypincode/public/api/vendor/google/apiclient/src/Google/Http/REST.php:118 Stack trace: #0 /srv/users/serverpilot/apps/anypincode/public/api/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 /srv/users/serverpilot/apps/anypinc in /srv/users/serverpilot/apps/anypincode/public/api/vendor/google/apiclient/src/Google/Http/REST.php on line 118`

Is it due to the Cache issue of google or Token Expire issue?

Plz provide me a sample code for generating Token for Service Accounts.

**Comment by vijayp4you** [comment]
Issue resolved. 
when we remove service account email id. still site is linked with that email id under permission level unverified account.

if you want to delete site from webmasters linked with service account first u need to remove the service account emailid then u can delete it. 
else error will come.

**Comment by vijayp4you** [comment]
if site is removed by delete the site or domain expired.  still it is displaying in list of sites.
how to hide the sites which are not in webmaster tools

**Comment by mattwhisenhunt** [comment]
From the list of properties in the Search Console. Click Manage property->Delete property
