### ISSUE TITLE
How can I get/list gmail filters for an authenticated user?

### ISSUE THREAD

**Issue by mdomocos** [google/google-api-php-client#1368]
An example may be great!

**Comment by net-tools** [comment]
Send a request to `$service->users_settings_filters->listUsersSettingsFilters($userid)` and you should get a `ListFiltersResponse` object, with a `filter` property being an array of `Google_Service_Gmail_Filter` objects.

If I'm wrong, the best way to find out is to `print_r` the stuff returned by the API call (I always do that for tricky things with missing samples).

https://developers.google.com/gmail/api/v1/reference/users/settings/filters/list

**Comment by LindaLawton** [comment]
```
function filtersListExample($service, $userId, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (userId == null)
			throw new Exception("userId is required.");
		// Make the request and return the results.
		return $service->filters->ListFilters($userId, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
```
[link](https://github.com/LindaLawton/Google-APIs-PHP-Samples/blob/master/Samples/Gmail%20API/v1/FiltersListSample.php)

**Comment by mattwhisenhunt** [comment]
@mdomocos I thought you were asked that an example be added to documentation but maybe you just wanted a quick answer. Looks like you got two great answers.
