### ISSUE TITLE
GA API request takes much time to render response

### ISSUE THREAD

**Issue by prashanth-sams** [google/google-api-php-client#1370]
The following API request URLs seems to take more than 3 mins to render response in our application; sometimes it may even load forever.

Here are the request URLs:

https://www.google.com/ads/user-lists/1036700521/?value=0&guid=ON&script=0&cdct=2&is_vtc=1&random=3561169623

https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-2867119-13&cid=1251822359.1514873879&jid=1235078407&_v=j66&z=1581668052

There was heavy fallback on our deployments today due to these latencies; cos, our smoke tests are written in Selenium and were breaking all the time with timeout issues waiting for the API responses.

![](https://i.imgur.com/iOSiS07.png)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We investigated and determined that this is actually a server-side issue. Please re-file it with the appropriate Google API issue tracker: https://developers.google.com/analytics/help/. If you believe that part of this issue still needs to be addressed in this client library, then feel free to re-open this issue with more information.

**Comment by prashanth-sams** [comment]
Thank you @mattwhisenhunt; I opened a ticket on the above link on Jan 18th; and haven't heard back yet. Would be great if you can escalate this issue since it affects our productivity.
https://issuetracker.google.com/issues/72137085
