### ISSUE TITLE
error while creating contact on Google Contacts API 

### ISSUE THREAD

**Issue by aa-ahmed-aa** [google/google-api-php-client#1371]
i can list all of the contacts in my account but when i try to create a new one i get this error 
Image_link : https://drive.google.com/file/d/1EffrnDMtYtnHpUyiz-SsjBo7dEnzNyKF/view?usp=sharing

CODE : -
```php
require_once __DIR__ . '/vendor/autoload.php';


define('APPLICATION_NAME', 'People API PHP Quickstart');
define('CREDENTIALS_PATH', '~/client_secret.json');
define('CLIENT_SECRET_PATH', __DIR__ . '/client_secret.json');
// If modifying these scopes, delete your previously saved credentials
// at ~/.credentials/people.googleapis.com-php-quickstart.json
define('SCOPES', 'https://www.googleapis.com/auth/contacts');

if (php_sapi_name() != 'cli') {
    throw new Exception('This application must be run on the command line.');
}

/**
 * Returns an authorized API client.
 * @return Google_Client the authorized client object
 */
function getClient() {
    $client = new Google_Client();
    $client->setApplicationName(APPLICATION_NAME);
    $client->setScopes(SCOPES);
    $client->setAuthConfig(CLIENT_SECRET_PATH);
    $client->setAccessType('offline');

    // Load previously authorized credentials from a file.
    $credentialsPath = expandHomeDirectory(CREDENTIALS_PATH);
    if (file_exists($credentialsPath)) {
        $accessToken = json_decode(file_get_contents($credentialsPath), true);
    } else {
        // Request authorization from the user.
        $authUrl = $client->createAuthUrl();
        printf("Open the following link in your browser:\n%s\n", $authUrl);
        print 'Enter verification code: ';
        $authCode = trim(fgets(STDIN));

        // Exchange authorization code for an access token.
        $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);

        // Store the credentials to disk.
        if(!file_exists(dirname($credentialsPath))) {
            mkdir(dirname($credentialsPath), 0700, true);
        }
        file_put_contents($credentialsPath, json_encode($accessToken));
        printf("Credentials saved to %s\n", $credentialsPath);
    }
    $client->setAccessToken($accessToken);

    // Refresh the token if it's expired.
    if ($client->isAccessTokenExpired()) {
        $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
        file_put_contents($credentialsPath, json_encode($client->getAccessToken()));
    }
    return $client;
}

/**
 * Expands the home directory alias '~' to the full path.
 * @param string $path the path to expand.
 * @return string the expanded path.
 */
function expandHomeDirectory($path) {
    $homeDirectory = getenv('HOME');
    if (empty($homeDirectory)) {
        $homeDirectory = getenv('HOMEDRIVE') . getenv('HOMEPATH');
    }
    return str_replace('~', realpath($homeDirectory), $path);
}

// Get the API client and construct the service object.
$client = getClient();
$service = new Google_Service_PeopleService($client);

$person = new Google_Service_PeopleService_Person();

$email = new Google_Service_PeopleService_EmailAddress();
$email->setValue('test@test.com');
$person->setEmailAddresses($email);

$name = new Google_Service_PeopleService_Name();
$name->setDisplayName('User de Test');
$person->setNames($name);

$exe = $service->people->createContact($person);

print_r($exe);
```

**Comment by net-tools** [comment]
Hi,


You are talking about Google Contacts in the thread title, but you are then using People API (two different things).

For Google Contacts, the correct scope is `http://www.google.com/m8/feeds/` ; however, there's no official PHP API available, you'll have to deal with the raw protocol and xml feeds.

**Comment by aa-ahmed-aa** [comment]
with the code above i can replace the last 12 line with the code that lists all of the contacts in my account and it works successfully 
here is the code i can put and it works successfully 
```php
$optParams = array(
    'pageSize' => 10,
    'personFields' => 'names,emailAddresses',
);
$results = $service->people_connections->listPeopleConnections('people/me', $optParams);

if (count($results->getConnections()) == 0) {
    print "No connections found.\n";
} else {
    print "People:\n";
    foreach ($results->getConnections() as $person) {
        if (count($person->getNames()) == 0) {
            print "No names found for this connection\n";
        } else {
            $names = $person->getNames();
            $name = $names[0];
            printf("%s \n", $name->getDisplayName());
        }
    }
}
```

**Comment by mattwhisenhunt** [comment]
It looks like this can be closed. @aa-ahmed-aa, thanks for posting a solution for future search results. @net-tools, as always thanks for all the help you offer.

**Comment by Lucho1976** [comment]
With examples above i've added a contact and i can see it in the list on the screen but i don't see it on my contacts.google.com . Do you know why? Here is my code:

        $client = new \Google_Client();
// I have a service Account credential
        $client->setAuthConfig('/.../xxxx.json');
       
         $client->setScopes(['https://www.googleapis.com/auth/contacts']);
     
        $people_service = new \Google_Service_PeopleService($client);

        $person = new \Google_Service_PeopleService_Person();

        $email1 = new \Google_Service_PeopleService_EmailAddress();
        $email1->setValue('xx@xx.com');
        $person->setEmailAddresses($email1);

        $name = new \Google_Service_PeopleService_Name();
        $name->setGivenName('haruki3');
        $name->setFamilyName('murakami3');
        $person->setNames($name);

        $phone1 = new \Google_Service_PeopleService_PhoneNumber();
        $phone1->setValue('5491141653254');
        $phone1->setType('mobile');
        $person->setPhoneNumbers($phone1);

        $people_service->people->createContact($person)->execute;
        

        $service = $people_service;
        // Print the names for up to 10 connections.
        $optParams = array(
            'pageSize' => 100,
            'personFields' => 'names,emailAddresses',
        );
        $results = $service->people_connections->listPeopleConnections('people/me', $optParams);

        if (count($results->getConnections()) == 0) {
            print "No connections found.\n";
        } else {
            print "People:\n";
            foreach ($results->getConnections() as $person) {
                if (count($person->getNames()) == 0) {
                    print "No names found for this connection\n";
                } else {
                    $names = $person->getNames();
                    $name = $names[0];

                    printf("%s\n", $name->getDisplayName());
                }
            }
        }

**Comment by bshaffer** [comment]
Hi @Lucho1976 
This issue is closed so please open a new issue. 

To answer your question, the account you are authorizing the API Client with is different than the one you are viewing Contacts with. Most likely you are using a service account when calling with the client, and a personal account when viewing online.

**Comment by EvgenaNet** [comment]
> Hi [@Lucho1976](https://github.com/Lucho1976) This issue is closed so please open a new issue.
> 
> To answer your question, the account you are authorizing the API Client with is different than the one you are viewing Contacts with. Most likely you are using a service account when calling with the client, and a personal account when viewing online.

I have the same problem.
So, what i have to do to solve the problem?
