### ISSUE TITLE
event is not inserted in google calender using php 

### ISSUE THREAD

**Issue by shwesrc** [google/google-api-php-client#1372]
I am trying to add event in Google Calendar using PHP. Following is my code:

 ```
$event = new Google_Event(); 
    $event->setSummary('Halloween'); 
    $event->setLocation('The Neighbourhood'); 
    $start = new Google_EventDateTime(); 
    $start->setDateTime('2018-1-19T10:00:00.000-05:00'); 
    $event->setStart($start); 
    $end = new Google_EventDateTime();
    $end->setDateTime('2018-1-19TT10:25:00.000-05:00'); 
    $event->setEnd($end); 
    $createdEvent = $cal->events->insert('primary', $event);
```

I am getting access to calendar but event is not getting added

**Comment by net-tools** [comment]
Hi,

Maybe you are missing the right scope to allow read AND write access to the calendar ? Correct scope is `https://www.googleapis.com/auth/calendar` (not `https://www.googleapis.com/auth/calendar.readonly`).

If the event is not created, you should have an exception thrown. Try enclosing the above code in a try/catch block with debug stuff in the catch part.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. @net-tools asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
