### ISSUE TITLE
How to retrive and view files 

### ISSUE THREAD

**Issue by vishwas45** [google/google-api-php-client#1373]
How to retrieve list of file and view/download it from google drive with php..

**Comment by net-tools** [comment]
Why not have a look at the API reference first ? 
First https://developers.google.com/drive/v3/reference/files/list for basic protocol knowledge
and
https://developers.google.com/api-client-library/php/start/get_started for PHP stuff

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. @net-tools asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
