### ISSUE TITLE
Firebase Cloud Messaging Service HTTP v1 Support

### ISSUE THREAD

**Issue by brianjcollins** [google/google-api-php-client#1374]
I'm trying to implement FCM using the newest server protocol.  The service isn't listed in client-service so my attempts to enable `new Google_Service_*` fails.  I understand the service files would need to be created under the other repo, but is there a way to bypass that requirement and simply make the calls direct?  I can't see how though the readme makes me believe it is possible.  Thanks!

**Comment by brianjcollins** [comment]
I wasn't able to figure it out so  I decided to spend my time on creating the FCM service files.  Works like a champ now.

**Comment by mattwhisenhunt** [comment]
Yes. https://firebase.google.com/docs/cloud-messaging/auth-server walks you through the process of using one of these API Client libraries in Python. Check out [a PHP example from another API](https://github.com/google/google-api-php-client/tree/master/examples) for PHP syntax if you want to use this library to handle authentication.

And in fact, yes, both the services library and this client library are just there for developer convenience. So if you have a method you like forming those requests that you like better that works too.

**Comment by brianjcollins** [comment]
For what it's worth... I figured I would add a gist containing the couple files I created to use the service to send notifications until FCM is added to the official services repo.

[https://gist.github.com/brianjcollins/eb12662799ecb09beeeffa70a663765d](url)

**Comment by Repox** [comment]
I had the same issue and your proposed solution gave me an idea on how to solve it by making requests directly:

https://gist.github.com/Repox/64ac4b3582f8ac42a6a1b41667db7440

I hope this helps someone.

**Comment by brianjcollins** [comment]
This is great and I would totally use this if I needed to do it again.
