### ISSUE TITLE
Client is unauthorized to retrieve access tokens using this method.

### ISSUE THREAD

**Issue by hfrid** [google/google-api-php-client#1379]
I have done the following:

1. Created a service account with Domain-wide Delegation, downloaded the corresponding .JSON
2. Setup https://mail.google.com/ permissions for the client-ID of the account created in step 1.
3. Installed v2.2.1 of google-api-php-client.

Trying to run the following code:
```
<?php
  putenv('GOOGLE_APPLICATION_CREDENTIALS=service-account.json');
  $client = new Google_Client();
  $client->useApplicationDefaultCredentials();
  $client->setScopes('https://mail.google.com');
  $client->setSubject('user@mydomain.com');

  $google_mail = new Google_Service_Gmail($client);
  $google_mail->users_messages->listUsersMessages('me');
```
Getting "Client is unauthorized to retrieve access tokens using this method." error.. this is on a Ubuntu server 14.04.5 LTS and PHP 5.5.9 please advice!

**Comment by morfinismo** [comment]
Domain wide delegation can take up to 24 hours to kick in. So if 24 hours
haven't passed, this might be a propagation issue.

------------------------------
*Francisco Morfín*
*Web Developer*
<https://mygapps.tools/>
<https://stackoverflow.com/users/5983596/morfinismo>
<https://twitter.com/morfinismo>
<https://plus.google.com/u/0/+FranciscoMorfin9>

**Comment by hfrid** [comment]
Seems like my problem was resolved by adding more scopes to the google admin api rights:

`https://mail.google.com/, https://www.googleapis.com/auth/email.migration, https://www.googleapis.com/auth/gmail.insert, https://www.googleapis.com/auth/gmail.labels`

**Comment by hbriceno** [comment]
FTR, I had a similar issue with "Client is unauthorized to retrieve access tokens using this method." and the fix was to enter the Client ID (ie a number) and not the service account name (blah@...gserviceaccount.com) in the Client Access when authorizing the scopes.

**Comment by LukevdPalen** [comment]
@hfrid thx for sharing, after hours of fiddling around, the automatic service account email to id transform of the GSuite was the issue, after delete the record and adding the rule with the Client ID instead of the service account email solved my issue.

**Comment by nsantorello** [comment]
This was my issue as well -- I added the service account email as the client name instead of its "Unique ID".  What is interesting is that when I used the email it correctly translated it to the unique ID, but only when I added the unique ID directly as the client name did it actually work.
