### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by leemunkiat** [google/google-api-php-client#1381]
Hi i would like to ask can i install without using composer? because i direct download from here and upload to my ftp i cant direct call the autoload.

Thank you

**Comment by mattwhisenhunt** [comment]
Yeah I always have to look it up too. -L stands for location as in the follow the **L**ocation field in the response header.
`curl -OL https://github.com/google/google-api-php-client/releases/download/v2.2.1/google-api-php-client-2.2.1.zip`

**Comment by LindaLawton** [comment]
The [v1-master](https://github.com/google/google-api-php-client/tree/v1-master) branch is for use without composer. and autoload.php is only part of the composer branch.  Your going to have to see what that does and load things accordingly.

**Comment by leemunkiat** [comment]
@LindaLawton i find out the problem why i can direct call the php file by download from here, below are the autoload.php code:
`<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit4bcd804d35cc650d1fb52c557725a2a1::getLoader();
`

how can i got the autoload.php correctly without generate using composer?

**Comment by LindaLawton** [comment]
session_start();
    include_once "templates/base.php";

    require_once realpath(dirname(__FILE__) . '/../src/Google/autoload.php');

Should work even without using composer the issue is where you have put your files.  When you download the library the paths have to be correct or your not going to be able to find autoload.php.

**Comment by leemunkiat** [comment]
@LindaLawton i try the code you provide, i cant find the base.php file, i download the google api php client from here https://github.com/google/google-api-php-client/releases 

I have modify the code it into
`session_start();
require_once 'google-api-php-client-2.2.1/src/Google/autoload.php');`

its still cant work. Below are my autoload.php code in the Google folder
`<?php

/**
 * THIS FILE IS FOR BACKWARDS COMPATIBLITY ONLY
 *
 * If you were not already including this file in your project, please ignore it
 */

$file = __DIR__ . '/../../vendor/autoload.php';

if (!file_exists($file)) {
  $exception = 'This library must be installed via composer or by downloading the full package.';
  $exception .= ' See the instructions at https://github.com/google/google-api-php-client#installation.';
  throw new Exception($exception);
}

$error = 'google-api-php-client\'s autoloader was moved to vendor/autoload.php in 2.0.0. This ';
$error .= 'redirect will be removed in 2.1. Please adjust your code to use the new location.';
trigger_error($error, E_USER_DEPRECATED);

require_once $file;`

Thank you

**Comment by leemunkiat** [comment]
@LindaLawton Below are my full code
`<?php 

session_start();
require_once 'google-api-php-client-2.2.1/src/Google/autoload.php');

$accessToken = initializeAnalytics();

function initializeAnalytics()
{
  $KEY_FILE_LOCATION ='client_secret_917950001739-6vodhfsbpmipoh29fl3f1pkqmo7u9dhv.apps.googleusercontent.com.json';

  $client = new Google_Client();
  $client -> setApplicationName("testing");
  $client -> setAuthConfig($KEY_FILE_LOCATION);
  $client -> setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
  $client -> refreshTokenWithAssertion();
  $client -> setAccessType("offline");
  $client -> setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/testing-embed.php');
  $token = $client->getAccessToken();
  $accessToken = $token['access_token'];

  return $accessToken;
 
}

echo $accessToken;

?>

<!DOCTYPE html>
<html>
<head></head>
<body>

<div id="embed-api-auth-container"></div>
<div id="chart-container"></div>
<div id="view-selector-container"></div>

<script type="text/javascript">
(function(w,d,s,g,js,fs){
  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
  js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
  js.src='https://apis.google.com/js/platform.js';
  fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
}(window,document,'script'));
</script>

<script type="text/javascript">

gapi.analytics.ready(function() {

  /**
   * Authorize the user immediately if the user has already granted access.
   * If no access has been created, render an authorize button inside the
   * element with the ID "embed-api-auth-container".
   */
    gapi.analytics.auth.authorize({
      'serverAuth': {
        'access_token': '<?php echo $accessToken ?>'
      }
    });


  /**
   * Create a new ViewSelector instance to be rendered inside of an
   * element with the id "view-selector-container".
   */
  var viewSelector = new gapi.analytics.ViewSelector({
    container: 'view-selector-container'
  });

  // Render the view selector to the page.
  viewSelector.execute();


  /**
   * Create a new DataChart instance with the given query parameters
   * and Google chart options. It will be rendered inside an element
   * with the id "chart-container".
   */
  var dataChart = new gapi.analytics.googleCharts.DataChart({
    query: {
      ids: "168634971",	
      metrics: 'ga:sessions',
      dimensions: 'ga:date',
      'start-date': '30daysAgo',
      'end-date': 'yesterday'
    },
    chart: {
      container: 'chart-container',
      type: 'LINE',
      options: {
        width: '100%'
      }
    }
  });


  /**
   * Render the dataChart on the page whenever a new view is selected.
   */
  viewSelector.on('change', function(ids) {
    dataChart.set({query: {ids: ids}}).execute();
  });

});
</script>

</body>
</html>`

**Comment by LindaLawton** [comment]
I think you should post a question on [stackoverflow](https://stackoverflow.com) this is not an issue with the client library but an issue with your ability to use the tutorials provided.

**Comment by leemunkiat** [comment]
ok, thanks for your help!

**Comment by mattwhisenhunt** [comment]
Looks like this issue can be closed. Thanks, @LindaLawton

**Comment by Willemgtn** [comment]
They made it kinda impossible to use there Oauth without composer and all that trash middleware!

**Comment by luiscorreal** [comment]
> I think you should post a question on [stackoverflow](https://stackoverflow.com) this is not an issue with the client library but an issue with your ability to use the tutorials provided. You should follow with tutorial [Hello analytics](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-php)
> 
> If you cant use composer you simply need to download this [branch v1-master](https://github.com/google/google-api-php-client/tree/v1-master) and make sure the src/Google directory is in your directory with your file.

**And the first 4 lines of the tutorial provided/referenced by you:**
```
<?php

// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
```
**That's simple**, there is no god information about '_how to use google-api-php-client whitout composer_' neither in stackoverflow nor in the tutorials; Maybe it's better to say that the library is dependent on composer and that's it.

**Comment by durangod** [comment]
branch v1 master is a 404 page :(     All i want is a basic dashboard for my website via browser and i have been bounced around for a solid week now from one API to another one and from one repository to another one.  Either the script is old and uses viewid which is gone with the wind because it is based on UA data, or it uses composer.   For those of us on shared servers that cant install composer we really need a solution to this issue.   Someone either needs to just admit that is impossible or provide a solution that does not use composer and uses propertyid and is for php

The google analytics data API uses propertyid but it has composer :(
https://developers.google.com/analytics/devguides/reporting/data/v1/rest

Will there be a solution to this issue from someone, anyone either on google or stackoverflow?

https://stackoverflow.com/questions/76496579/connecting-to-ga4-google-analytics-data-api-and-google-client-without-composer-u

**Comment by LindaLawton** [comment]
@durangod  you are on the wrong library this is the google api php client library .   The data api is part of the [google cloud php client libary](https://github.com/googleapis/google-cloud-php)
