### ISSUE TITLE
Post in google plus, so which Gsuite plan i need to buy.?

### ISSUE THREAD

**Issue by BilalBasha** [google/google-api-php-client#1383]
I m trying to post in google plus api, but it throws a forbidden error(403), so i m going to buy an account in gsuite, which plan is correct plan to post in google plus.???

**Comment by LindaLawton** [comment]
The Google+ API is read only there is no way to post to it.    You can post to your domains account using the Google+ domains API but these posts will not show up on the Google+ social media website.

This question really isnt related to this library but rather to Google APIs themselves.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
