### ISSUE TITLE
get() returning 404, other services don't.

### ISSUE THREAD

**Issue by newincentivesdeveloper** [google/google-api-php-client#1384]
I'm using the latest version of the library. 

I have a function that uses the get() method for Google Drive, and it constantly returns a 404. However, listFiles() does not. Here is the get()-based function I'm code.

    function getSheetMetadata($sheetID) {

		// load sheets API
		require_once('/home/ubuntu/public_html/lib/vendor/autoload.php');

		putenv('GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/sampleCreds.json');

		$client = new Google_Client();
		$client->useApplicationDefaultCredentials();
		$client->setSubject('me@example.com');
		$client->addScope('https://www.googleapis.com/auth/drive');
		$client->addScope('https://www.googleapis.com/auth/spreadsheets');

		$service = new Google_Service_Drive($client);

		$response = $service->files->get(array(
			'fileId' => $sheetID,
			'supportsTeamDrives' => true
		));

		return $response;

	}

This gives me a 404 error.

This function, using the same credentials, lists all my files. 

    function getGoogleSchemas() {

			// load sheets API
			require_once('/home/ubuntu/public_html/lib/vendor/autoload.php');

			putenv('GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/sampleCreds.json');

			$client = new Google_Client();
			$client->useApplicationDefaultCredentials();
			$client->setSubject('me@example.com');
			$client->addScope('https://www.googleapis.com/auth/drive');
			$client->addScope('https://www.googleapis.com/auth/spreadsheets');

			$service = new Google_Service_Drive($client);

			$response = $service->files->listFiles(array(
				'q' => 'mimeType="application/vnd.google-apps.spreadsheet"',
				'spaces' => 'drive',
				'corpus' => 'user',
				'includeTeamDriveItems' => true,
				'supportsTeamDrives' => true

			));

			return $response->files;

	}

Help!

**Comment by LindaLawton** [comment]
have you tried adding valid scopes like

    Google_Service_Drive::DRIVE

**Comment by newincentivesdeveloper** [comment]
Why would the scope be different between the two functions? They both are authorized for scope _https://www.googleapis.com/auth/drive_, which should give me access to everything, according to the documentation.

**Comment by LindaLawton** [comment]
Because my way is the documented way of using this library.  Which uses the variables that were created for the purpose.  Yours is a string that you yourself typed and may or may not be typed in correctly. 

That being said your first call doesnt work because you are calling it in correctly.   If you check the documentation [files.get](https://developers.google.com/drive/v3/reference/files/get) has a required parameter of fileid followed by an option string array containing the option parameters.

    $response = $service->files->get($sheetID, array('supportsTeamDrives' => true));

**Comment by newincentivesdeveloper** [comment]
Thank you! That worked. My scope appears to have been fine.

**Comment by denji** [comment]
@LindaLawton  The documentation describes only `::DRIVE` https://github.com/google/google-api-php-client#authentication-with-oauth

```php
https://www.googleapis.com/auth/{drive,spreadsheets,youtube,...}{,readonly}
....
Google_Service_{SERVICE}::{SERVICESCOPE}
```
