### ISSUE TITLE
Recommended migration of library to PSR-4

### ISSUE THREAD

**Issue by tusharth** [google/google-api-php-client#1389]
**Heads up!**

Currently, the code is following PSR-0 standards of PHP. It is recommended to follow and migrate the library code to PSR-4 standards.

Thank you!

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.

**Comment by timothymarois** [comment]
@mattwhisenhunt careful consideration? Really? Meaning you considered remaining obsolete. This API is useless in a modern era. Nonetheless, this API needs a full rewrite anyways.

**Comment by mattwhisenhunt** [comment]
@timothymarois HEY-YO you gotchme. It is a canned response.
I guess another way of putting it would have been: We are in the middle of a full rewrite anyways but we are playing are cards close to the chest until we know exact release dates. We are really excited that this new version is going to address some of the shortcomings of the current client library. Additionally, we want to make sure we are supporting current users of this client library especially with issues that are deal breakers. That is why we really encourage new issues being created and triaged and addressed. We also don't want to fall victims to the CADT model, so I am trying to get the bug count down as close to 0 as possible. That is a lot of work to do so we have employed some techniques, courteous, canned responses in this case, to get things done faster.
Gratifyingly, we have a fantastic community of developers from all over the world that are willing to jump in and test code and answer questions and submit PRs. So if my consideration seems too brief to be careful it is only in an attempt to make it also timely but never final. It's my attempt to avoid the unnecessary effort of others and also give the original feature requester info they need to make decisions as soon as possible.

**Comment by Leviathanism** [comment]
+1 @mattwisenhunt 
Have you seen the new labels with descriptions?
I feel like a maintenance label with this wonderful response of yours as the description would be great. 

It would also be wonderful if you googlers played the promise card on EVERYTHING. Lol
I just want to async n' wait on your hand already. :)
