### ISSUE TITLE
Why i cant find the class Google_Service_Drive_Permission in this repo? 

### ISSUE THREAD

**Issue by bulgariamitko** [google/google-api-php-client#1390]
Simple question. Just wondering if i want to use this class and change permission in the folder/file if i can't find this class here, how should i do it? I didn't post this is stackoverflow as i am thinking this question is this repo specific

**Comment by bulgariamitko** [comment]
I think my questions is irrelevant and i was not able to find this class using the github search, but i guess it exists and everything is ok. so i am closing my issue as i cant delete it.

**Comment by mattwhisenhunt** [comment]
Checkout https://github.com/google/google-api-php-client-services/
