### ISSUE TITLE
Google API return me 404 sudden, while it was running last few months

### ISSUE THREAD

**Issue by rescue1155** [google/google-api-php-client#1391]
Hi guys,

I have used google sheets API in my project last few months, Where i get offline token, and get refresh token on every request. 
It was working great, But no sudden it start giving me 
"error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
Or something insert new record.

Can you tell me about that reason ?

**Comment by mattwhisenhunt** [comment]
There could be any number of reasons this has happened. https://stackoverflow.com/questions/17813621/oauth2-0-token-strange-behaviour-invalid-credentials-401 has a good list of things to check.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
