### ISSUE TITLE
 Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\google\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

### ISSUE THREAD

**Issue by wubs23** [google/google-api-php-client#1392]
Hello,

I am trying to use the Google API client to make a dashboard with relevant information. However, when I follow the steps on the hello analytics tutorial, and try to connect, I get the following error:

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\google\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67

How would I go about solving this?
Thanks.

**Comment by mattwhisenhunt** [comment]
This warning has been cropping up when an older version of Guzzle is used with PHP 7.2. If upgrading Guzzle doesn't work please include a full stack trace as well as version of PHP and Guzzle.

**Comment by wubs23** [comment]
Thanks. How do you upgrade Guzzle? Because if you follow the steps specified by Guzzle itself, the installation fails because google/auth requires certain versions.

**Comment by wubs23** [comment]
what is a full stack trace? 
my php version is 7.2.2
when I update guzzle via "composer update guzzlehttp/guzzle" it says 
"Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files"

**Comment by wubs23** [comment]
So.. I am trying to update Guzzle to 6.0.3, but this doesn't work, since it says guzzlehttp/guzzle 6.3.0 requires guzzlehttp/psr7^1.4
but if I try to install psr7[1.4*] it won't let me, since it says google/auth v0.8 requires guzzlehttp/psr7 1.2.* but these conflict with your requirements or minimum-stability.

So is there any work-around?

**Comment by mattwhisenhunt** [comment]
One work around is to copy your composer.json to a new directory and run `composer install` and then to use that vendor directory to replace your old one. Another is to use a packaged release provided by us at https://github.com/google/google-api-php-client/releases

**Comment by wubs23** [comment]
Thank you. This indeed solved the problems.

**Comment by ruvictor** [comment]
This solution didn't work form me...

**Comment by inandi** [comment]
> The problem is in PHP 7.2 the parameter for count() can't be NULL. The warning gets displayed when $this->handles equals NULL. Just replace line 67 in CurlFactory.php with the following:
> 
> if (($this->handles ? count($this->handles) : 0) >= $this->maxHandles) {

it worked thanks @vinnoangel

**Comment by P-James** [comment]
> 
> 
> The problem is in PHP 7.2 the parameter for count() can't be NULL. The warning gets displayed when $this->handles equals NULL. Just replace line 67 in CurlFactory.php with the following:
> 
> if (($this->handles ? count($this->handles) : 0) >= $this->maxHandles) {

thanks a lot! @vinnoangel

**Comment by beverloo** [comment]
@jdpedrie Hi John, I see that you've made some related changes recently, can we re-open this please for tracking purposes? Asking folks to manually change this project's dependencies isn't really a solution :)

**Comment by jdpedrie** [comment]
Hi @beverloo 

Could you give me more information on what you'd like me to track? I'd be happy to reopen the issue if there's a need, but beyond potentially requiring guzzle 6.3+, I'm not sure if there's any action I can take.

The correct solution would be to upgrade to guzzle 6.3 or above. I'm not sure why anyone would be pinning to a version of guzzle 6 below that, but I think the only way this error would occur would be if for some reason you were stuck with an older version of guzzle for a reason unrelated to this library.

Perhaps we can update the minimum version for 6.x to 6.3.0. I'll need to discuss the implications of us doing that internally, but there's certainly nothing preventing you from requiring a higher version of guzzle within the 6.x series. The downloadable archives provide (for 2.4.0) guzzle 6.3.3.

**Comment by beverloo** [comment]
Guzzle 6.3 is indeed the requirement for PHP 7.4 compatibility, so updating the minimum version certainly seems like the correct solution to me as well. I'm not familiar with the impact of that on the rest of the project to assess its feasibility.

I can manually install a different version, but my project depends on `google/apiclient`, which, in its default configuration, throws warnings. That seems undesirable.

It's a side project for me, but assuming you mean Google with internal discussions, feel free to loop me in if I could provide further data.

**Comment by jdpedrie** [comment]
Thanks for the reply! 🙂

The default configuration would install the latest release in the 6.x tree. You’d need to explicitly require guzzle at a lower 6.x version somewhere else in the dependency tree to encounter the error. That’s why I’m unsure whether there’s any action needed on our end.

That said, we want to try and remove as many potential headaches as possible, given other constraints on time and backwards compatibility. So I will raise the possibility of bumping the minimum version of guzzle and see whether it’s doable in the immediate future.

**Comment by guojianing** [comment]
> The problem is in PHP 7.2 the parameter for count() can't be NULL. The warning gets displayed when $this->handles equals NULL. Just replace line 67 in CurlFactory.php with the following:
> 
> if (count( (array) $this->handles) >= $this->maxHandles) {

Thank you. solved the problems.

**Comment by bringerfast** [comment]
> Hi @beverloo
> 
> Could you give me more information on what you'd like me to track? I'd be happy to reopen the issue if there's a need, but beyond potentially requiring guzzle 6.3+, I'm not sure if there's any action I can take.
> 
> The correct solution would be to upgrade to guzzle 6.3 or above. I'm not sure why anyone would be pinning to a version of guzzle 6 below that, but I think the only way this error would occur would be if for some reason you were stuck with an older version of guzzle for a reason unrelated to this library.
> 
> Perhaps we can update the minimum version for 6.x to 6.3.0. I'll need to discuss the implications of us doing that internally, but there's certainly nothing preventing you from requiring a higher version of guzzle within the 6.x series. The downloadable archives provide (for 2.4.0) guzzle 6.3.3.

**Comment by guix77** [comment]
Same problem with:

- PHP 7.3
- google/apiclient 2.7.0
- guzzlehttp/guzzle 7.01 (automatically installed)

**Comment by guix77** [comment]
The quickstart sample codes don't set any dimensions, that's why.

Updated sample for https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-php:

```
<?php

// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';

$analytics = initializeAnalytics();
$response = getReport($analytics);
printResults($response);


/**
 * Initializes an Analytics Reporting API V4 service object.
 *
 * @return An authorized Analytics Reporting API V4 service object.
 */
function initializeAnalytics()
{

  // Use the developers console and download your service account
  // credentials in JSON format. Place them in this directory or
  // change the key file location if necessary.
  $KEY_FILE_LOCATION = __DIR__ . '/service-account-credentials.json';

  // Create and configure a new client object.
  $client = new Google_Client();
  $client->setApplicationName("Hello Analytics Reporting");
  $client->setAuthConfig($KEY_FILE_LOCATION);
  $client->setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
  $analytics = new Google_Service_AnalyticsReporting($client);

  return $analytics;
}


/**
 * Queries the Analytics Reporting API V4.
 *
 * @param service An authorized Analytics Reporting API V4 service object.
 * @return The Analytics Reporting API V4 response.
 */
function getReport($analytics) {

  // Replace with your view ID, for example XXXX.
  $VIEW_ID = "<REPLACE_WITH_VIEW_ID>";

  // Create the DateRange object.
  $dateRange = new Google_Service_AnalyticsReporting_DateRange();
  $dateRange->setStartDate("7daysAgo");
  $dateRange->setEndDate("today");

  // Create the Metrics object.
  $sessions = new Google_Service_AnalyticsReporting_Metric();
  $sessions->setExpression("ga:sessions");
  $sessions->setAlias("sessions");

  //Create the Dimensions object.
  $browser = new Google_Service_AnalyticsReporting_Dimension();
  $browser->setName("ga:browser");

  // Create the ReportRequest object.
  $request = new Google_Service_AnalyticsReporting_ReportRequest();
  $request->setViewId($VIEW_ID);
  $request->setDateRanges($dateRange);
  $request->setDimensions(array($browser));
  $request->setMetrics(array($sessions));

  $body = new Google_Service_AnalyticsReporting_GetReportsRequest();
  $body->setReportRequests( array( $request) );
  return $analytics->reports->batchGet( $body );
}


/**
 * Parses and prints the Analytics Reporting API V4 response.
 *
 * @param An Analytics Reporting API V4 response.
 */
function printResults($reports) {
  for ( $reportIndex = 0; $reportIndex < count( $reports ); $reportIndex++ ) {
    $report = $reports[ $reportIndex ];
    $header = $report->getColumnHeader();
    $dimensionHeaders = $header->getDimensions();
    $metricHeaders = $header->getMetricHeader()->getMetricHeaderEntries();
    $rows = $report->getData()->getRows();

    for ( $rowIndex = 0; $rowIndex < count($rows); $rowIndex++) {
      $row = $rows[ $rowIndex ];
      $dimensions = $row->getDimensions();
      $metrics = $row->getMetrics();
      for ($i = 0; $i < count($dimensionHeaders) && $i < count($dimensions); $i++) {
        print($dimensionHeaders[$i] . ": " . $dimensions[$i] . "\n");
      }

      for ($j = 0; $j < count($metrics); $j++) {
        $values = $metrics[$j]->getValues();
        for ($k = 0; $k < count($values); $k++) {
          $entry = $metricHeaders[$k];
          print($entry->getName() . ": " . $values[$k] . "\n");
        }
      }
    }
  }
}
```

**Comment by PraveenDev2007** [comment]
Just include the following code first and then your PHP code.
`error_reporting(0);`

This will not show any errors (no error reportings in the page/content) in PHP. Even you can limit error reporting by changing the 
number of error reporting function. The format is `error_reporting(int);`.

**Comment by Jamesbansal** [comment]
I got the same error:
PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:67 Stack trace: #0 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(67): count() #1 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(141): GuzzleHttp\Handler\CurlFactory->release() #2 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError() #3 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish() #4 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #5 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}() #6 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(72): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler{closure}() #7 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke() #8 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp{closure}() #9 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke() #10 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp{closure}() #11 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Client.php(268): GuzzleHttp\HandlerStack->__invoke() #12 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Client.php(96): GuzzleHttp\Client->transfer() #13 D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Client.php(104): GuzzleHttp\Client->sendAsync() #14 D:\xampp\htdocs\google-drive-api\vendor\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(34): GuzzleHttp\Client->send() #15 D:\xampp\htdocs\google-drive-api\vendor\google\auth\src\OAuth2.php(492): Google\Auth\HttpHandle#16 D:\xampp\htdocs\google-drive-api\vendor\google\apiclient\src\Google\Client.php(184): Google\Auth\OAuth2->fetchAuthToken() #17 D:\xampp\htdocs\google-drive-api\google-drive.php(52): Google_Client->fetchAccessTokenWithAuthCode() #18 D:\xampp\htdocs\google-drive-api\google-drive.php(70): getClient() #19 {main} thrown in D:\xampp\htdocs\google-drive-api\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67


I'm using php-8.0.9 
Can someone help me?

**Comment by HoldOffHunger** [comment]
SOLUTION:

Open the file indicated by the error and go to the line indicated:

> \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:67

(line 67 in CurlFactory.php)

Code before:

>        if (count($this->handles) >= $this->maxHandles) {

Code after:

>        if ($this->handles && count($this->handles) >= $this->maxHandles) {

Very easy.  Works now!

**Comment by HoldOffHunger** [comment]
@Jamesbansal (and anyone else who finds this): do what is described up above (or just update your code):

https://github.com/googleapis/google-api-php-client/issues/1392#issuecomment-451431434

**Comment by AhmadAdil1** [comment]
> One work around is to copy your composer.json to a new directory and run `composer install` and then to use that vendor directory to replace your old one. Another is to use a packaged release provided by us at https://github.com/google/google-api-php-client/releases

Thanks man, it is working well.

**Comment by sadats90** [comment]
> The problem is in PHP 7.2 the parameter for count() can't be NULL. The warning gets displayed when $this->handles equals NULL. Just replace line 67 in CurlFactory.php with the following:
> 
> if (($this->handles ? count($this->handles) : 0) >= $this->maxHandles) {

this helped... thanks a lot
