### ISSUE TITLE
Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found

### ISSUE THREAD

**Issue by junelmujar** [google/google-api-php-client#1394]
Hello!

I've experienced this while pushing my work onto production server:

Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found in /<-- path-redacted -->/google-api-php-client-2.2.1/vendor/google/auth/src/Cache/MemoryCacheItemPool.php on line 27

The problem does not occur locally or in one of our staging environment.

I've tried both approach as stated in the docs (https://developers.google.com/api-client-library/php/start/installation):

1) Composer
2) Downloading the a release from the repo, upload to server and reference the autoloader from that

Btw I'm running PHP Version 5.5.30 & Apache/2.4.16

Would appreciate if you can point out what am I doing wrong, system requirements, etc.

Thanks a lot.

Regards,

Junel

**Comment by billhance** [comment]
Does the file exist at vendor/psr/cache/src/CacheItemPoolInterface.php?

**Comment by junelmujar** [comment]
Yes, it does exist. Shouldn't it suppose to look at /google-api-php-client-2.2.1/vendor/psr/cache/src/CacheItemPoolInterface.php as it does have one in there? Btw the library was installed by copying the whole folder to the server and not using composer.

**Comment by billhance** [comment]
If you didn't use composer, how does your autoloader know where to look for the files to load?

**Comment by bshaffer** [comment]
You just need to include `vendor/autoload.php` at the top of your front controller (e.g. `index.php`) or which ever file is served up first:

```php
require '/path/to/vendor/autoload.php';
```
