### ISSUE TITLE
Old version of guzzlehttp/psr7

### ISSUE THREAD

**Issue by Dresing** [google/google-api-php-client#1395]
Cannot upgrade to guzzle ^6.3 in my project, I think it is a conflict with the package guzzlehttp/psr7 where this rep uses ^1.2 vs. the new version ^1.4.

It is specifically in the auth composer.json file where it is specified to ^1.2.*

https://gyazo.com/bbc31b080a6b3903bafc83d8f953ad70

**Comment by mattwhisenhunt** [comment]
You may want to copy your composer.json file into a new directory and `composer install` to get a fresh vendor directory. You could then either diff the two vendor directories for a controlled upgrade or just replace the old one altogether.
You may also want to include your composer.json file in this issue if you need help debugging it.

**Comment by Dresing** [comment]
I thoroughly look through my composer.json file and found a personal error on a package i hadn't upgraded properly, helped to look with fresh eyes. Sincerly my fault and thank you for assistance.

**Comment by scofield-ua** [comment]
I had the same error. Installation of newer version solved it:
`composer require google/apiclient:^2.2`
