### ISSUE TITLE
Update minimum php version to (at least ?) 5.5.

### ISSUE THREAD

**Issue by n00dl3** [google/google-api-php-client#1398]
Hello,
I am maintaining an old project (the kind of which you call "the monster" with a low voice) which runs on php 5.4 (I know, it's bad...) without composer.

The README says :

>## Requirements
>PHP 5.4.0 or higher

But it actually seems to require a php version higher than 5.5 as it relies on `GuzzleHttp` which calls the [`curl_reset()`](https://secure.php.net/manual/en/function.curl-reset.php) function which was added in 5.5.

This results in a Fatal error :
>Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /path_to/google-api-php-client-2.2.1/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

Note that I didn't try to run it on a php 5.5 server, but maybe the actual required version is 5.6...

Cheers.

**Comment by mattwhisenhunt** [comment]
@n00dl3 by the by, are you looking for help to get it working in 5.4 or letting us know so we can fix the docs or both?

**Comment by bshaffer** [comment]
@n00dl3 Thank you for the heads up! As a work around, try using the [`v1-master`](https://github.com/google/google-api-php-client/tree/v1-master) branch of this repo, which will definitely run on `5.4`

**Comment by n00dl3** [comment]
Thank you, @mattwhisenhunt and @bshaffer. I was just letting you know in order to fix the docs. I managed to upgrade "the monster" to php 5.6 :wink: .
