### ISSUE TITLE
Api For Custom Search

### ISSUE THREAD

**Issue by amin007** [google/google-api-php-client#1401]
Where i can find api for custom search in google.com/cse?

**Comment by mattwhisenhunt** [comment]
Assuming you either run `composer install` or download a [release](https://github.com/google/google-api-php-client/releases) the methods for the Google Custom Search API will be in vendor/google/apiclient-services/src/Google/Service/Customsearch.php. But you shouldn't have to worry about that if you are including the autoloader file: `include_once __DIR__ . '/../vendor/autoload.php';`

**Comment by amin007** [comment]
Thank you very much

**Comment by AdamMiltonBarker** [comment]
We have installed via composer and are using autoload but get this error:

PHP Fatal error:  Uncaught Error: Class 'Google_Service_Customsearch' not found in
