### ISSUE TITLE
Break in error reporting

### ISSUE THREAD

**Issue by saffabook** [google/google-api-php-client#1412]
Hi, [this line of code](https://github.com/google/google-api-php-client/blob/d669e0f3b92da94d5b4ed960d462dd3b0de920ea/src/Google/Http/REST.php#L118) seems to break the process of error reporting. 
The error is 
```
<b>Fatal error</b>:  Uncaught exception 'Google_Service_Exception' with message '{
 &quot;error&quot;: &quot;unauthorized_client&quot;,
 &quot;error_description&quot;: &quot;Unauthorized&quot;
}
' in C:\xampp\htdocs\Gofamer\api\application\vendor\google-api-php\google\apiclient\src\Google\Http\REST.php:124
Stack trace:
#0 C:\xampp\htdocs\Gofamer\api\application\vendor\google-api-php\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 C:\xampp\htdocs\Gofamer\api\application\vendor\google-api-php\google\apiclient\src\Google\Task\Runner.php(181): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\Gofamer\api\application\vendor\google-api-php\google\apiclient\src\Google\Http\REST.php(58): Google_Task_Runner-&gt;run()
#4 C:
```
When I get a positive result, all the files seem to line up bar this one. If everything is set up correctly and I am getting good results on positive returns, why would the error return not display correctly on error results?

Edit: Moved code from title to permalink

**Comment by mattwhisenhunt** [comment]
Thanks for creating this issue. I am not understanding your problem yet, this library does not offer any error display capabilities.

Please attach a working code sample, list what you expect to happen and what is actually happening.
You may also consider asking your question on [StackOverflow](https://stackoverflow.com/questions/tagged/google-api-php-client) if it is not a bug report. Some really helpful folks watch that more closely than they do this repo.

**Comment by mattwhisenhunt** [comment]
By throwing an exception the library lets an app developer (the user of the library) decide if they want to keep on going (by handling with a catch) or stop the world and end execution all together. Both can be valid decisions.

**Comment by waynef** [comment]
> Hi thank you for your reply.
> 
> If there is not error display capabilities then I guess its not a bug. Perhaps I could suggest an enhancement.
> 
> When I request analytics data, and its a positive result. I can read that data and process it on the next step. ie when I run this `$analytics->data_ga->get` and I get the results, its available for me to work on.
> 
> However if there is a error, ie someone revokes the permission, or some failure then the code just stops and I cant do work on it, ie the above error shows in my original post above. There is no easy solution if this error arises for me to deal with it. Anyways, I came up with a bit of an ugly solution but it works very well when time is short.
> 
> In this file, `google-api-php/google/apiclient/src/Google/Http/REST.php` I simply added this line on line 117
> 
> ```
> $json = json_decode($body, true);
> return $json;
> ```
> 
> and commented out the below because this just stops everything.
> 
> `//throw new Google_Service_Exception($body, $code, null, self::getResponseErrors($body)); `
> 
> With this ugly hack, it allows me to work with the error. I have my solution despite it being not so pretty. I hope this is enough for you to understand the situation. My apologies if I have not explained it properly.

Thanks @saffabook this also helped me.
