### ISSUE TITLE
conflict in installing the package

### ISSUE THREAD

**Issue by johnsky007** [google/google-api-php-client#1415]
Hi guys!
I can't install package with composer. I use Laravel 5.6 and my "guzzlehttp/psr" version is locked at version 1.4.2 while your package requires 1.2.*
please solve the issue.
tnx

**Comment by mattwhisenhunt** [comment]
Please upgrade to the latest version. It is no longer pinned to 1.2.*.

**Comment by mattwhisenhunt** [comment]
Duplicate of #1413

**Comment by mattwhisenhunt** [comment]
@johnsky007 if you are still having any problems add any detail to #1413.
