### ISSUE TITLE
Wrong annotation

### ISSUE THREAD

**Issue by TakTaki** [google/google-api-php-client#1419]
In class `Google_Service_Drive_FileList`, function `getFiles` is defined as
```
  /**
   * @return Google_Service_Drive_DriveFile
   */
  public function getFiles()
  {
    return $this->files;
  }
```
whereas the real return is an `array`.

**Comment by mattwhisenhunt** [comment]
Thanks for opening this issue. That class is autogenerated and the annotation would be overwritten if we tried to fix it with a PR. I have found the [rest reference](https://developers.google.com/drive/v3/reference/) to be the most helpful resource when understanding these APIs and methods.
