### ISSUE TITLE
Support for gift_message

### ISSUE THREAD

**Issue by feedjosiah** [google/google-api-php-client#1420]
**Support for gift_message**

Will there be support for accessing annotations under the OrderLineItem and the gift_message field in future releases?

**Comment by mattwhisenhunt** [comment]
Not sure what API you are talking about, but how it works is: an API team documents changes to methods or fields or APIs in a discovery doc and all the GA APIs (and lots of the beta) are list in our [main discovery doc](https://www.googleapis.com/discovery/v1/apis). The classes for this library autogenerated by parsing those discovery docs.

So to answer your question, I think so. Watch the release of [client-services](https://github.com/google/google-api-php-client-services) for the change you are looking for.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
