### ISSUE TITLE
One default parameter is missing in Google_Service_Drive_About in v3

### ISSUE THREAD

**Issue by NastuzziSamy** [google/google-api-php-client#1423]
Hey, 

I switched from v2 to v3 today and I noticed that the $drive->about->get() needed a `fields` parameter whereas no parameters are required as explained here: https://developers.google.com/drive/v3/reference/about/get

Is it possible to simply change that in Google_Service_Drive_Resource_About:
`$params = arrray();`
to
`$params = array('fields' => '*');`

Or update the documentation ?

Thank you

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up. I have passed your feedback along.
