### ISSUE TITLE
how can i download full code and impliment?

### ISSUE THREAD

**Issue by anilshah694** [google/google-api-php-client#1424]
hi
how to download complete code and how to implement on my server?

**Comment by mattwhisenhunt** [comment]
The release page has all this repo's code and its dependencies:
https://github.com/google/google-api-php-client/releases

Unlike most client/server network communication projects, this is just a
client project and not at all helpful in implementing one's own server.

**Comment by bshaffer** [comment]
The question (I believe) is how to run the code on a backend server, e.g. in a production environment. The instructions on how to run this are in the [README](https://github.com/google/google-api-php-client/blob/master/README.md#installation) under "Installation". Let us know if you run into any problems!

**Comment by mattwhisenhunt** [comment]
Bah, I misread the question. Sorry about that, @anilshah694; thanks for the question. It looks to be resolved, so I am going to close this issue.
