### ISSUE TITLE
Google_Model::keyType tries to autoload classes which does not necessarily exist

### ISSUE THREAD

**Issue by hjellek** [google/google-api-php-client#1425]
`class_exists` without also submitting false for autoloading causes an error to be thrown, which seems like a bad practice in an if-test.

Came upon this while using the `Google_Service_Safebrowsing_FindThreatMatchesRequest` service through https://github.com/google/google-api-php-client-services which causes an `include(MALWARE.php)` error message when a malware threat is detected.

**Comment by mattwhisenhunt** [comment]
Could you include an example of code that is causing this behavior?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
