### ISSUE TITLE
Youtube Analytics API: version error

### ISSUE THREAD

**Issue by xryst** [google/google-api-php-client#1428]
Hi,

I'am trying to get data from YouTubeAnalytics:
        
```php
        $client = new \Google_Client();
        $client->setApplicationName("ApplicationName");
        $analytics = new \Google_Service_YouTubeAnalytics($client);

        $key  = file_get_contents($key_file_location);
        $cred = new \Google_Auth_AssertionCredentials($service_account_email, [\Google_Service_YouTubeAnalytics::YT_ANALYTICS_READONLY], $key);

        $client->setAssertionCredentials($cred);
        if($client->getAuth()->isAccessTokenExpired())
        {
            $client->getAuth()->refreshTokenWithAssertion($cred);
        }

        $response = $analytics->reports->query('channel=='.$channel.'', '2018-05-01', '2018-05-11', 'subscribersGained');
```

But i get that error:

```php
Error calling GET https://www.googleapis.com/youtube/analytics/v1/reports?ids=channel{CHANEL_NAME}&start-date=2018-05-01&end-date=2018-05-11&metrics=subscribersGained: (403) Forbidden
```

For import Google API Library I'm use composer:

`composer require google/apiclient:^2.0`

\vendor\google\apiclient-services\src\Google\Service\YouTubeAnalytics.php

```
    parent::__construct($client);
    $this->rootUrl = 'https://youtubeanalytics.googleapis.com/';
    $this->servicePath = '';
    $this->version = 'v2';
```

But the error says about "v1"

What could be the problem?

**Comment by LindaLawton** [comment]
Make sure you have added the service account email address as a user on YouTube analytics

TBH I am really not sure that it supposed service account authorization

**Comment by xryst** [comment]
Good day, @LindaLawton !

I haven't service account authorization error.
Authorization occurs without problems

An error occurs on this portion of the code:

```php
$response = $analytics->reports->query('channel=='.$channel.'', '2018-05-01', '2018-05-11', 'subscribersGained');
```

When I use this function, I get the following error

`Error calling GET https://www.googleapis.com/youtube/analytics/v1/reports?ids=channel{CHANEL_NAME}&start-date=2018-05-01&end-date=2018-05-11&metrics=subscribersGained: (403) Forbidde`


Please note which URL is listed in the error: **.../youtube/analytics/v1/reports...**

Note which link should be in accordance with the file YouTubeAnalytics.php (\vendor\google\apiclient-services\src\Google\Service\)

> https://youtubeanalytics.googleapis.com/v2/reports

Here's how to create a link in a file YouTubeAnalytics.php (\vendor\google\apiclient-services\src\Google\Service\)

```php
    parent::__construct($client);
    $this->rootUrl = 'https://youtubeanalytics.googleapis.com/';
    $this->servicePath = '';
    $this->version = 'v2';
```

Why is there one link (**_v1_**) in the YouTubeAnalytics.php and an error that returns another (**_v2_**)?

**Comment by LindaLawton** [comment]
>(403) Forbidden

Is an authentication error.  The user you are authenticated with does not have permissions to do what you are trying to do.   

I just did some checking You can't use a service account when making a YouTube Analytics API request. You need to use an account that is either the owner of the YouTube channel or a content owner associated with the channel. 

You will need to go through the OAuth 2 flow once while signed in as the Google Account that owns the YouTube channel, and the saved OAuth 2 refresh token could then be used repeatedly in the future to get fresh access tokens which can be used to run reports.

**Comment by xryst** [comment]
@LindaLawton 

> Is an authentication error. The user you are authenticated with does not have permissions to do what you are trying to do. You may think you are authorizing correctly but you wont have permissions to do anything. A service account is not you its a user that needs permission to access data.
> 
> I just did some checking You can't use a service account when making a YouTube Analytics API request. You need to use an account that is either the owner of the YouTube channel or a content owner associated with the channel.
> 
> You will need to go through the OAuth 2 flow once while signed in as the Google Account that owns the YouTube channel, and the saved OAuth 2 refresh token could then be used repeatedly in the future to get fresh access tokens which can be used to run reports.

Thank you! I will check it!

**Comment by LindaLawton** [comment]
this might help 

- [Oauth2Authentication.php](https://github.com/LindaLawton/Google-APIs-PHP-Samples/blob/master/Samples/YouTube%20Analytics%20API/v1/Oauth2Authentication.php)
- [oauth2callback.php](https://github.com/LindaLawton/Google-APIs-PHP-Samples/blob/master/Samples/YouTube%20Analytics%20API/v1/oauth2callback.php)

**Comment by LindaLawton** [comment]
>Why is there one link (v1) in the YouTubeAnalytics.php and an error that returns another (v2)?

This would be an error in the API.  There is only one version of the YouTube analytics api.  you can see that here.  https://www.googleapis.com/discovery/v1/apis

**Comment by mattwhisenhunt** [comment]
This seems resolved. Thanks @LindaLawton! @xryst if you still have questions just add a comment and we will reopen this issue.
