### ISSUE TITLE
invalid_grant, Invalid JWT

### ISSUE THREAD

**Issue by jayshri123** [google/google-api-php-client#1429]
Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
Can you  please give me solution?

**Comment by LindaLawton** [comment]
please add your code its hard to assist without knowing what you are doing.

**Comment by JustinBeckwith** [comment]
Greetings!  We'd love to help, but we need more information.  If you can post your code...  we'd be happy to help!
