### ISSUE TITLE
Calendar insert return HTTP 500 but still inserts event

### ISSUE THREAD

**Issue by achabill** [google/google-api-php-client#1431]
```
$service = new Google_Service_Calendar($googleClient);
try{
    $event = $service->events->insert($calendarId, $event);
    //Does not reach here.
    printf('Event created: %s\n', $event->htmlLink);
}catch(\Exception $ex){
    printf("%s\n",$ex);
}
```

The event is created on the calendar but I cannot get the call back as it fails with HTTP 500. 
Also, no exception is thrown.

**Comment by LindaLawton** [comment]
Your code looks fine which means the 500 error is coming from someplace else in your code this is unrelated the the code you have posted here which will make it hard for us to help you.

Do a print_r on $event.   your issue may be htmlLink

**Comment by achabill** [comment]
Thanks, it was some other unrelated code.
