### ISSUE TITLE
[Drive API] Can't export a file in zip format

### ISSUE THREAD

**Issue by chalda-pnuzig** [google/google-api-php-client#1432]
Hi,
I have this code:
```php
$client = new Google_Client();
$client->setAuthConfig('file.json');
$client->setScopes(array(
	Google_Service_Drive::DRIVE,
	Google_Service_Drive::DRIVE_READONLY,
));
$service  = new Google_Service_Drive($client);
$fileid = '1GDeQU7mVbipmQlPTTccmznUeJ0AgFyNrGA4TfzTgEys'; // public spreadsheet file
$response = $service->files->export($fileid, 'application/zip', array('alt' => 'media'));
$content = $responsedownload->getBody()->getContents();
```
`$content` variable is always empty.
If I change `application/zip` mime to `application/pdf` or `text/csv` it works well.

**Comment by mxdpeep** [comment]
MIME type of a zip file is *application/octet-stream*



s pozdravem,

*Filip Oščádal*

**Comment by mattwhisenhunt** [comment]
It looks like this is an API issue. You seem to have taken all the right steps. I'm sorry to say creating an issue in this repo doesn't expedite one in Issue Tracker.

**Comment by mattwhisenhunt** [comment]
This is being tracked at https://issuetracker.google.com/issues/80362795
