### ISSUE TITLE
I created a google subcalendar within main google calendar now i wants to share that subcalendar with some user .

### ISSUE THREAD

**Issue by prafullwizorbit** [google/google-api-php-client#1433]
Hii, 
     I wants to share my google calendar with some user using this google api, but i am not finding any code to share my google calendar with some perticular user although i searched a lot.
what i found: https://developers.google.com/calendar/concepts/sharing#sharing_calendars
so anyone have idea how to share google calendar using php code .
Thanks

**Comment by mxdpeep** [comment]
use Acl: insert to create an access control rule for a user
*https://developers.google.com/google-apps/calendar/v3/reference/acl
<https://developers.google.com/google-apps/calendar/v3/reference/acl>*

$service = new Google_Service_Calendar($client);
$calendarListEntry = new Google_Service_Calendar_CalendarListEntry();
$calendarListEntry->setId($calendarId);
$createdCalendarListEntry =
$service->calendarList->insert($calendarListEntry);
echo $createdCalendarListEntry->getSummary();

I have used Google search on term "*how to share google calendar using php*
" 😎😎😎



s pozdravem,

*Filip Oščádal*

**Comment by JustinBeckwith** [comment]
Looks like this one is answered!  Please do let us know if you run into any more problems.

**Comment by prafullwizorbit** [comment]
Hello mxdpeep & JustinBeckwith 
                         Thanks for your answer but this code is not for sharing the calendar, its showing the summary only.
Thanks

**Comment by LindaLawton** [comment]
@mxdpeep adding something to the calendar list is useless it just going to add it to the list on the left hand side of the current users Google calendar web view it has nothing to do with sharing it.

@prafullwizorbit what do you mean by sharing exactly you just want to give someone else access to your calendar?

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please add a comment if you have any more questions and we can reopen this issue.
