### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Assimilationstheorie** [google/google-api-php-client#1440]
Hey People!

4 months ago someone edit the code. Is this Project dead or simple perfect? 😕

**Comment by JustinBeckwith** [comment]
Greetings! No, the project isn't dead :)  We are spending a lot of time over in https://github.com/GoogleCloudPlatform/google-cloud-php these days, but you should start to see more work in this repo in the coming weeks.

**Comment by Assimilationstheorie** [comment]
Oh okay. I rebuild the warning system, but the stupid Google Bot can't accept my request, because the "CLA" is wrong...

Good Luck, crazy Project!
