### ISSUE TITLE
Premissions returns wrong Interface

### ISSUE THREAD

**Issue by meteguerlek** [google/google-api-php-client#1446]
Hi, if i create premissions, i get Google_Service_Drive_Permission back but the batch method needs RequestInterface as argument. 

```php 

$batch = $this->service->createBatch();

$userPermission = new Google_Service_Drive_Permission([
    'type' => 'anyone',
    'role' => 'reader'
]);

$request = $this->service->permissions->create(
    $fileId, $userPermission, ['fields' => 'id']
);

$batch->add($request, 'anyone');
```
Argument 1 passed to Google_Http_Batch::add() must implement interface Psr\Http\Message\RequestInterface, instance of Google_Service_Drive_Permission given

**Comment by mattwhisenhunt** [comment]
Make sure to call `$this->service->getClient()->setUseBatch(true);` before `createBatch`.
