### ISSUE TITLE
Release Download is not complete.

### ISSUE THREAD

**Issue by michaeldprice** [google/google-api-php-client#1466]
According to the documentation, I should be able to the release version, without composer, however this does NOT appear to be the case.

"Download the Release

If you abhor using composer, you can download the package in its entirety. The Releases page lists all stable versions. Download any file with the name google-api-php-client-[RELEASE_NAME].zip for a package including this library and its dependencies.

Uncompress the zip file you download, and include the autoloader in your project:

require_once '/path/to/google-api-php-client/vendor/autoload.php';"

However this download, google-api-php-client-2.2.2.zip, does NOT contain a vendor directory.
I have read another ticket, where v1-master was recommended ...

Does this mean v2 is not supported without composer?

Are you recommending to simply use the v1-master, or use v1-master, and than overwrite with version 2.2?

**Comment by michaeldprice** [comment]
I noticed that there was only a "source code" option. My mistake.
Downloaded 2.2.1 for now.

**Comment by mattwhisenhunt** [comment]
@michaeldprice Thanks for the heads up. I just added those assets to v2.2.2.
