### ISSUE TITLE
`redirect_uri_mismatch` if `state` is set in client

### ISSUE THREAD

**Issue by Tefached95** [google/google-api-php-client#1472]
If I use my app's flow normally, the redirect works perfectly fine. However, if I try to set the state to a B64 encoded string, something like

```php
$state = SomeUtilClass::b64Encode(json_encode(array('some' => 'data')));
$client->setRedirectUri('http://local-dev-env.com/v1/gmail-callback');
$client->setState($state);
```
I get a `redirect_uri_mismatch` error. Commenting out `$client->setState($state)`gets the flow working properly again.

The redirect URI ends up looking like this:

`http://local-dev-env.com/v1/gmail-callback?state=eyJzb21lIjoiZGF0YSJ9&code=<code>&scope=https://www.googleapis.com/auth/gmail.readonly#`

**Comment by Tefached95** [comment]
Well I don't know what was going on, but I completely removed my OAuth ID on Google's console, created a new one, redownloaded my `client_secret.json` and now it seems to be working perfectly, both with and without the state.

I'll provide any info if anyone needs it, but I consider this issue closed.

**Comment by mattwhisenhunt** [comment]
Thanks for creating this issue.
