### ISSUE TITLE
Google_Service_Exception with HTML code in the response

### ISSUE THREAD

**Issue by teo1978** [google/google-api-php-client#1474]
Here's my code:
```
// I'm getting here after having authorized the app and I'm redirected to the 
// php script running this code

$client=new Google_Client();
$client->setAuthConfig('/path/to/my/youtube_credentials.json');
$client->setAccessType('offline');
$client->setIncludeGrantedScopes(true);
$client->addScope('https://www.googleapis.com/auth/youtube.readonly');
$client->addScope('https://www.googleapis.com/auth/youtube.upload');
$client->addScope('https://www.googleapis.com/auth/youtube');
$client->addScope('https://www.googleapis.com/auth/youtubepartner');
$client->addScope('https://www.googleapis.com/auth/youtubepartner-channel-audit');
$client->authenticate($_REQUEST['code']);
// SO FAR SO GOOD.

$youtube=new Google_Service_YouTube($client);
$channels = $youtube->channels->listChannels('snippet', array('mine'=>1));
```

I get a **Google_Service_Exception** at 
/vendor/google/apiclient/src/Google/Http/REST.php(118)

First of all, no matter what I'm doing wrong (if anything), I should never, ever get an error thrown from inside REST.php. I should get a higher-level exception with a sensible error message.

But hold on, that's not all.

The exception's error message shows the **contents of the response from Google** which is:

```
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 400 (Bad Request)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
</style>
<a href=//www.google.com/><span id=logo aria-label=Google></span></a>
<p><b>400.</b> <ins>That’s an error.</ins>
<p>Your client has issued a malformed or illegal request. <ins>That’s all we know.</ins>
```

Isn't that ridiculous? That's not even a valid JSON response. That's an HTML page and it's the kind of error page  that is usually displayed to end users on Google's websites.
I have already reported the issue to the Google API's bugtracker, because no matter what, there's no reason why the Google API should be returning a malformed response, even to a malformed request.

However, that the library is performing an invalid request is obviously a bug in the library. If I'm calling the library incorrectly (and I don't see where I would be), I should get an error from the library telling me what's wrong in my call.

I have modified the code in **REST.php** so that it also displays the **URL of the request** it made (it's quite pathetic that it doesn't already do that and shows the response body without showing the request URL), and the request URL is:
**https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true**

That looks pretty much correct to me, except that, if I try it in the API explorer, I see it includes an apiKey:
https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.channels.list?part=snippet%252CcontentDetails%252Cstatistics&mine=true&_h=2&
```
GET https://www.googleapis.com/youtube/v3/channels?part=snippet%2CcontentDetails%2Cstatistics&mine=true&key={YOUR_API_KEY}
```

However, I'm not sure if that's anything to do with the issue. Given that I am making the request after succesfully authenticating via oAuth, I don't think an apiKey should be required. If it is, then that would obviously be the library's responsibility to include it in the request, or to throw an exception if I am supposed to provide the key and am failing to do so - but the docs don't say anything about that.

**Comment by JustinBeckwith** [comment]
Greetings! We'd be happy to help out, answer questions, and even fix bugs. I am however, going to have to ask you to monitor your language :) We're all humans here who would love to help, but please keep things respectful. We're working on getting a code of conduct in all of our repositories, but for now let this one be your guide. Thanks!

**Comment by teo1978** [comment]
I'll be more careful with my language, but (and I'm really doing a great effort to keep my language civil right now) I think you deleted a comment of mine that actually **contained a useful workaround**.

Please restore it. Feel free to edit it to remove profanity (I think it was just one word), but I think deleting it is disproportionate. I won't waste time rewriting it, and it contained vital information for any user that is affected by the issue and needs a workaround, and I suspect it might even help you diagnose and fix the issue.

**Comment by teo1978** [comment]
> Dear Teo, it looks like you have a bug somewhere, you don't need to create
a new client.

I guess you have read my deleted comment then. (please would you restore it??)

Well, it looks to me like _you_ have a bug somewhere. If I don't create a new client, as described in the original post, it doesn't work. If I do, it works. It makes sense that I _shouldn't_ need to create a new client. That's the issue.

Even if there is something wrong in my code (which I can't see), I should get a sensible exception and/or a json response with a sensible error message. Not an HTML response that is meant for end users of the website, not the API.

**Comment by mattwhisenhunt** [comment]
I haven't been able to reproduce the HTML response. Maybe you could recreate it in a reproducible way in Postman or curl. Or maybe capture more of your request details in Charles Proxy or mitmproxy.
```php
$client->setHttpClient(new GuzzleHttp\Client(['proxy'=> 'localhost:8080','verify'=> 0]));
```

I agree about the response format, I think this client code itself has built in assumptions about the response coming back as JSON. Maybe that is why it is blowing up in REST.php where you don't expect it (just thinking out loud/ not sure)

@teo1978 your messages seem overwrought given the subject matter. If you need someone to talk about PHP or anything feel free to reach out via email.

**Comment by teo1978** [comment]
I don't understand why you now close the issue and categorize it as question.
It's not a question, it's a bug, and the fact that you are unable to reproduce it doesn't make it any less of a bug.

**Comment by teo1978** [comment]
And again, please **undelete my comment**: it contains a workaround for users affected by this issue, which also could give insight into the root cause. There's no reason for it to be deleted.

**Comment by teo1978** [comment]
![image](https://user-images.githubusercontent.com/542107/42396921-0e9436c0-8164-11e8-9625-65e85d6a6ae7.png)

If it shows there is a deleted comment, there must be a way to undelete it available to the repository admins. If there isn't, please report it as an issue to GitHub because it would be ridiculous.
 
@mxdpeep  mentioned creating a new client, which is something he must have read in my comment (unless I'm misunderstanding what he said)

> Just post it again

Yeah right.
