### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by mediatomcat** [google/google-api-php-client#1476]
Trying to install but get the following issue:

composer require google/apiclient:^2.0
==============================
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package google/apiclient No version set (parsed as 1.0.0) is satisfiable by google/apiclient[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by mattwhisenhunt** [comment]
I don't know all the ins and outs of composer. Please attach your composer.json file to make it easier to recreate this issue.

**Comment by mediatomcat** [comment]
The composer file is the same one in this git.  I am basically downloading the git and running the composer require file.   I have tried adding the "google/apiclient:^2.0" directly to the composer file, but you still get the same error.

**Comment by mattwhisenhunt** [comment]
This git is google/apiclient so you'll want to just `composer install` after a clone.

You can run `composer require google/apiclient:^2.0` from a different directory/project to treat this git as a dependency.
