### ISSUE TITLE
Prompt for select account before login?

### ISSUE THREAD

**Issue by edgargaza** [google/google-api-php-client#1478]
Hey everyone! I would like to ask if there's some way to let the user select an specific account before logging in. In some other apis (like JS) it would be an specific provider option called "prompt". If you set the value of this option to "select_account", the api will let you to select an specific account, even if you're already logged and/or with only one account "linked".

Thank you so much!

PS: Please, if someone can, add the question label. I couldn't myself!

**Comment by mxdpeep** [comment]
You add the login_hint parameter with an account value to the
authentication request.

ps: try Google next time for such a simple question


s pozdravem,

*Filip Oščádal*

**Comment by edgargaza** [comment]
Bro, I swear I did and I didn't find anything... I love you tho, thx for the answer!
