### ISSUE TITLE
Please add a service for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by dipo1** [google/google-api-php-client#1479]
See https://stackoverflow.com/questions/51228074/is-there-a-fcm-service-in-google-api-php-client-services

**Comment by mattwhisenhunt** [comment]
Looking at https://firebase.google.com/docs/cloud-messaging/server it seems that you would use the Cloud Functions API which is included as one of the services in this library. Good question, thanks. Please comment if you have anymore questions.
