### ISSUE TITLE
PolicyViolationService support

### ISSUE THREAD

**Issue by thanosalexander** [google/google-api-php-client#1482]
Goodevening!
I'd like to ask if there is support for DoubleClick Publisher , in order to access PolicyViolationService (getUrlPolicyViolationsLink)
It returns the csv link of policy violations!

**Comment by mattwhisenhunt** [comment]
Good question. It looks like you want https://github.com/googleads/googleads-php-lib.
See https://developers.google.com/doubleclick-publishers/docs/start

**Comment by thanosalexander** [comment]
I already checked the documentation and all services but i didnt find any solution about this.. 
I tried too with other tools like pupeteer to download csv manually but no luck too!
Its weird for google to miss this functionality

**Comment by mattwhisenhunt** [comment]
You might want to check out https://developers.google.com/doubleclick-publishers/community
