### ISSUE TITLE
I can't get more than 100 file using google client v2 on symfony

### ISSUE THREAD

**Issue by anonymmed** [google/google-api-php-client#1485]
I have a problem using **google Client api v2** on symfony 2.8 I want to get all videos from my drive directory, **I have more than 200 video, but when I call listFiles I only get 100**! why ? this is the code I use to get the files:

`$file_list = $drive_service->files->listFiles(array('q'=>"mimeType CONTAINS 'video/' and '$folderId' in parents"))->getItems();`

and when I execute this :

`$drive_service->files->listFiles()->count();`
I also get response 100

please help,I want to **get all the files or at least 1000.**

**Comment by mattwhisenhunt** [comment]
Check out this example from https://developers.google.com/drive/api/v2/reference/files/list, the trick is to page through the entire list of files.
```php
/**
 * Retrieve a list of File resources.
 *
 * @param Google_Service_Drive $service Drive API service instance.
 * @return Array List of Google_Service_Drive_DriveFile resources.
 */
function retrieveAllFiles($service) {
  $result = array();
  $pageToken = NULL;

  do {
    try {
      $parameters = array();
      if ($pageToken) {
        $parameters['pageToken'] = $pageToken;
      }
      $files = $service->files->listFiles($parameters);

      $result = array_merge($result, $files->getItems());
      $pageToken = $files->getNextPageToken();
    } catch (Exception $e) {
      print "An error occurred: " . $e->getMessage();
      $pageToken = NULL;
    }
  } while ($pageToken);
  return $result;
}
```
