### ISSUE TITLE
exponential backoff - not possible to provide custom retryMap.

### ISSUE THREAD

**Issue by Yahav** [google/google-api-php-client#1487]
So, i've been trying to use the exponential backoff feature and noticed you won't be able to provide a custom retryMap although it was (faultily) implemented.

So, inspecting Runner.php (Google_Task_Runner) i can see that there is a retryMap array
 ```
 /**
   * @var array $retryMap Map of errors with retry counts.
   */
  protected $retryMap = [
    '500' => self::TASK_RETRY_ALWAYS,
    '503' => self::TASK_RETRY_ALWAYS,
    'rateLimitExceeded' => self::TASK_RETRY_ALWAYS,
    'userRateLimitExceeded' => self::TASK_RETRY_ALWAYS,
    6  => self::TASK_RETRY_ALWAYS,  // CURLE_COULDNT_RESOLVE_HOST
    7  => self::TASK_RETRY_ALWAYS,  // CURLE_COULDNT_CONNECT
    28 => self::TASK_RETRY_ALWAYS,  // CURLE_OPERATION_TIMEOUTED
    35 => self::TASK_RETRY_ALWAYS,  // CURLE_SSL_CONNECT_ERROR
    52 => self::TASK_RETRY_ALWAYS   // CURLE_GOT_NOTHING
  ];
```
as well as a setter(setRetryMap).
tracked it back to REST.php (Google_Http_REST), at the execute function the 5th param is $retryMap which defaults to null, at the function it states that if the provided  $retryMap isn't null, run the setRetryMap() method of the runner, so far so good.
so tracked it back to Client.php (Google_Client) which you suppose to initiate at your code:
`$this->client = new Google_Client();`
the Google_Client class will receive a config array at the constructor 
`  public function __construct(array $config = array())`
the array will then be merged with the default config array.
the default config array contain a key names 'retry' with the following comment
```
// Task Runner retry configuration
// @see Google_Task_Runner
'retry' => array(),
```
So, natural assumption will be that when initiating the Google_Client you should provide an array with a retry key containing your desired retry maps. eg:
 `        $this->client = new Google_Client(array('retry'=>$this->retryMap));`
So far so good?
Except this won't work, Lets analyze what's happening:
we initiate the Google_Client class and provide an array with the a retry key:
 `        $this->client = new Google_Client(array('retry'=>$this->retryMap));`
this array gets merged with the Google_Client's config variable, so now our desired retryMap is stored at the retry key of the class config variable.
when a request is made the Google_Client function execute() gets executed and return the following:
`Google_Http_REST::execute($http, $request, $expectedClass, $this->config['retry']);`
notice that the 4th parameter provided is the retry map we set earlier.
so we go to the Google_Http_REST class execute function:
```
public static function execute(
      ClientInterface $client,
      RequestInterface $request,
      $expectedClass = null,
      $config = array(),
      $retryMap = null
  ) {
    $runner = new Google_Task_Runner(
        $config,
        sprintf('%s %s', $request->getMethod(), (string) $request->getUri()),
        array(get_class(), 'doExecute'),
        array($client, $request, $expectedClass)
    );

    if (null !== $retryMap) {
      $runner->setRetryMap($retryMap);
    }

    return $runner->run();
  }
```
notice that the 4th param it accepts is a config array while its the 5th that will accept a $retryMap.
now since we haven't passed a 5th ($retryMap) to the function it will be null and won't be set at the runner:
```
 if (null !== $retryMap) {
      $runner->setRetryMap($retryMap);
    }
```
now if you wonder what's the $config for at the Google_Http_REST execute function, it passed to Google_Task_Runner as the first argument and never used, although at the constructor it does search for a  'retries' key (not 'retry' as passed):
```
 if (isset($config['retries'])) {
      if ($config['retries'] < 0) {
        throw new Google_Task_Exception(
            'Task configuration `retries` must not be negative.'
        );
      }
      $this->maxAttempts += $config['retries'];
    }
```
so yeah, its not possible to set a custom retryMap alotugh it would seem someone did try to make it happen but didn't thought it through.

**Comment by Yahav** [comment]
Also, The whole exponential backoff implementation is faulty and wouldn't even work, Why? basically because Google_Task_Runner's $maxAttempts.
Someone needs to really go though the whole process and rewrite some calls.
If i'll have some time in the next few copule of days i'll write more about the issue and maybe make a pull request.

**Comment by mattwhisenhunt** [comment]
Thanks @Yahav!
