### ISSUE TITLE
Undefined property: Google_Service_Drive::$parents

### ISSUE THREAD

**Issue by coollorenzo** [google/google-api-php-client#1490]
I'm using the [code example](https://developers.google.com/drive/api/v2/reference/parents/list) from the gdrive docs:
`/**
 * Print a file's parents.
 *
 * @param Google_Service_Drive $service Drive API service instance.
 * @param String $fileId ID of the file to print parents for.
 */
function printParents($service, $fileId) {
  try {
    $parents = $service->parents->listParents($fileId);

    foreach ($parents->getItems() as $parent) {
      print 'File Id: ' . $parent->getId();
    }
  } catch (Exception $e) {
    print "An error occurred: " . $e->getMessage();
  }
}`

But I get the error Undefined property: Google_Service_Drive::$parents and I also couldn't find any code referencing parents so is the option to get and list parents removed?

**Comment by mattwhisenhunt** [comment]
Right now this client library only supports v3 of the Drive API. You will want to use files.get with ?fields=parents to list parents: https://developers.google.com/drive/api/v3/migration
