### ISSUE TITLE
How to add recovery email and contact number

### ISSUE THREAD

**Issue by anshulbhawsar** [google/google-api-php-client#1493]
We are using this google client library for creating new email address but we want to add secondary email address (Recovery email address) and also phone number with the help of this google client php library. I tried for that but i'm not finding any result. Please give me proper guidance for add this information.
Thank you.

**Comment by mattwhisenhunt** [comment]
I don't know a quick answer to this one. I would start with the documentation of the API you are using. Is that part of the GSuite?

One resource I find very useful when I don't know exactly which action I need to call but I have a general direction is [API Explorer](https://developers.google.com/apis-explorer/#p/).

**Comment by anshulbhawsar** [comment]
This is a part of G suite client php library. I have also modify the code but there is no any updates. I'm not getting any help from api explorer.

**Comment by mattwhisenhunt** [comment]
After looking at some pages I don't think this can be done programmatically (or even administratively)
