### ISSUE TITLE
Why have you made PHP5.3 obsolete?

### ISSUE THREAD

**Issue by markosjal** [google/google-api-php-client#1494]
Why has php 5.3 now been made obsolete. There are many servers sitll running it . This is a huge oversight!

Can I get the older PHP5.3 compatible version somewhere? does it still work?

**Comment by mattwhisenhunt** [comment]
:wave: Hi @markosjal,

Sounds like you are looking for version 1.1.8
https://github.com/google/google-api-php-client/tree/v1-master

**Comment by markosjal** [comment]
looking atthe link below I see 1.1.7 but no 1.1.8.
https://github.com/google/google-api-php-client/releases?after=v2.0.1

when I try to do the composer install I get

root@gvsip:/var/www/gvauth/goog $ php composer.phar install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle 5.2.0 -> satisfiable by guzzlehttp/guzzle[5.2.0].
    - guzzlehttp/guzzle 5.2.0 requires php >=5.4.0 -> your PHP version (5.3.3) does not satisfy that requirement.
  Problem 2
    - Installation request for guzzlehttp/ringphp 1.1.0 -> satisfiable by guzzlehttp/ringphp[1.1.0].
    - guzzlehttp/ringphp 1.1.0 requires php >=5.4.0 -> your PHP version (5.3.3) does not satisfy that requirement.
  Problem 3
    - Installation request for guzzlehttp/streams 3.0.0 -> satisfiable by guzzlehttp/streams[3.0.0].
    - guzzlehttp/streams 3.0.0 requires php >=5.4.0 -> your PHP version (5.3.3) does not satisfy that requirement.
  Problem 4
    - Installation request for react/promise v2.4.0 -> satisfiable by react/promise[v2.4.0].
    - react/promise v2.4.0 requires php >=5.4.0 -> your PHP version (5.3.3) does not satisfy that requirement.


I amm  worried that installing a newer PHP may break something else

**Comment by mattwhisenhunt** [comment]
I got the 1.1.8 from Packagist.org.

In your project directory I would try:
`*composer* require google/apiclient:^1.0`

**Comment by markosjal** [comment]
Thanks anyway , I give up.

 big waste of time for me

all documentation now refers to newer versions impossible for me to figure out

this is why older versions need to have the documentation maintained too

**Comment by NicoHaase** [comment]
These "many servers" should be upgraded as soon as possible. PHP 5.3 has not seen any security fixes since August 2014, that's four years before you posted your issue here. You cannot expect anybody to support this endlessly
