### ISSUE TITLE
Google Apps Directory

### ISSUE THREAD

**Issue by spbdimka** [google/google-api-php-client#1503]
Hi, is there a method for get google directory contacts? (https://contacts.google.com/directory)

**Comment by mattwhisenhunt** [comment]
There's the People API https://developers.google.com/people/ which is what I think you are looking for.

There is also the [Directory API in G Suite](https://developers.google.com/admin-sdk/directory/) but that is more for administrating  a lot of people in an enterprise or organization directory.
