### ISSUE TITLE
Support a callback when access token generated from refresh token

### ISSUE THREAD

**Issue by Scorcher** [google/google-api-php-client#300]
I am using OAuth2 to make offline request to YouTube API...
When this library refreshes an access_token using refresh_token it would be very useful to call user specified callback to make possibility storing new token somewhere in centralized storage of application.
Now I should check token changes after each exec of my script to reduce refresh.

For example:

``` php
$client = new Google_Client();
$client->setOnRefreshTokenCallback(<lambda from my code>);
```

**Comment by dmyers** [comment]
What is the purpose of having the package refresh the token? Can we currently detect the change and store it?

**Comment by Scorcher** [comment]
Yes, you can. You should check token changes after each call to Google API. If changed - store it and use new one next time. If you will use old one (ignoring changes) - the library will update token every time (it is one more request).

**Comment by bshaffer** [comment]
please see #905

**Comment by tmatsuo** [comment]
Can we close this now? #905 seems merged.

**Comment by tmatsuo** [comment]
Closing. Feel free to re open if you think differently

**Comment by bshaffer** [comment]
Yep! This is available via [`Google_Client::setTokenCallback`](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L662).
