### ISSUE TITLE
Support a token store interface within the OAuth2 implementation

### ISSUE THREAD

**Issue by Scorcher** [google/google-api-php-client#301]
Multi threaded or multi process apps can get race condition, when each process/thread will refresh token and store it to storage "simultaneously".
It would be great to have opportunity implement thread-safe TokenProvider and set it to Google_Client

Example:

``` php
interface ITokenProvider {
    public function getToken();
}

class MyTokenProvider implements ITokenProvider {
    public function getToken()
    {
        // TODO: Implement getToken() method from somewhere
    }
}

$client = new Google_Client();
$client->setTokenProvider(new MyTokenProvider());
```

**Comment by tmatsuo** [comment]
@Scorcher Is this issue still relevant? If so, are you able to create a pull request for this feature?

**Comment by tmatsuo** [comment]
@bshaffer I think the implementation around token has been changed, so can we close this now?

**Comment by bshaffer** [comment]
Closing this. `Google_Client` has a `setTokenCallback` method that can be used to handle this situation. Also, the Cache class can be customized by anything implementing the PSR-6 standard.
