### ISSUE TITLE
Uncaught Google_IO_Exception for Curl in OAuth2.php

### ISSUE THREAD

**Issue by abusalam** [google/google-api-php-client#369]
For any reason if Google API host is unreachable call to [makeRequest()](https://github.com/google/google-api-php-client/blob/master/src/Google/Auth/OAuth2.php#L106) ends with Fatal Error.

And also static property [self::$HOP_BY_HOP](https://github.com/google/google-api-php-client/blob/master/src/Google/IO/Abstract.php#L226) is not defined in class Google_IO_Abstract.

**Comment by tmatsuo** [comment]
@whatthejeff Does it make sense for you to create a Pull Request for this issue?

**Comment by michaelbausor** [comment]
This class no longer exists. cc @bshaffer
