### ISSUE TITLE
Resources with multiple collections may use one other than items

### ISSUE THREAD

**Issue by patkar** [google/google-api-php-client#375]
If I call `objects->listObjects('mybucket')` I get a `Google_Service_Storage_Objects` which `modelData['items']` is filled with the object items metadata as returned from the API. But I can't foreach through the items, because the [`collection_key` property of the collection class is `prefixes`](https://github.com/google/google-api-php-client/blob/176ded8f2614515e8e400cffd7568cf946b69686/src/Google/Service/Storage.php#L2935).

If I change the `collection_key` to `items` via reflection :neckbeard: it works.

**Comment by tmatsuo** [comment]
Now the issue should be moved to:
https://github.com/google/google-api-php-client-services

**Comment by tmatsuo** [comment]
@patkar Closing here, but feel free to open a new one on the other repo. Thanks!
