### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by ronlobo** [google/google-api-php-client#408]
Hi,

just want to ask if there are any api docs available?
If not, may I file a feature request?

E.g.: http://apigen.org/
or
http://www.phpdoc.org/

Thanks in advance.

Best,
Ron

**Comment by Skysplit** [comment]
+1 for this

it would be nice to have docs like theese (`src/Google/Service/Drive.php`):

```php
/**
 * @var Google_Service_Drive_About_Resource
 */
public $about;
/**
 * @var Google_Service_Drive_Apps_Resource
 */
public $apps;
/**
 * @var Google_Service_Drive_Changes_Resource
 */
public $changes;
/**
 * @var Google_Service_Drive_Changes_Resource
 */
public $channels;
/**
 * @var Google_Service_Drive_Children_Resource
 */
public $children;
/**
 * @var Google_Service_Drive_Comments_Resource
 */
public $comments;
/**
 * @var Google_Service_Drive_Files_Resource
 */
public $files;
/**
 * @var Google_Service_Drive_Parents_Resource
 */
public $parents;
/**
 * @var Google_Service_Drive_Permissions_Resource
 */
public $permissions;
/**
 * @var Google_Service_Drive_Properties_Resource
 */
public $properties;
/**
 * @var Google_Service_Drive_Realtime_Resource
 */
public $realtime;
/**
 * @var Google_Service_Drive_Replies_Resource
 */
public $replies;
/**
 * @var Google_Service_Drive_Revisions_Resource
 */
public $revisions;
```

This would make API much easier to use with IDE's

**Comment by ianbarber** [comment]
@Skysplit thats a separate issue - tracked in #443

**Comment by Skysplit** [comment]
Thanks ;) I missed that issue while searching, though I think they're pretty much connected, as phpdoc is the source of autocompletion for IDE.

**Comment by fireproofsocks** [comment]
+1.  Trying to figure out how to translate the methods defined in https://developers.google.com/google-apps/calendar/v3/reference/ into useable code is unnecessarily arduous.

**Comment by three3211** [comment]
+1

**Comment by theofidry** [comment]
+1

**Comment by touhonoob** [comment]
+1

**Comment by Silver89** [comment]
+1

**Comment by jeckel** [comment]
+1

**Comment by reecube** [comment]
+1

**Comment by tmatsuo** [comment]
Should we move this issue to https://github.com/google/google-api-php-client-services ?

**Comment by bshaffer** [comment]
@tmatsuo People are finding it and voting on it here, so I'm ok with leaving it.

**Comment by doodoori2** [comment]
👍 
It will be very helpful for IDE. 
![i_need_phpdocs](https://user-images.githubusercontent.com/418882/27769383-1b8c0390-5f63-11e7-92b7-9bab300e266e.PNG)

**Comment by xsimo** [comment]
+1

**Comment by mattwhisenhunt** [comment]
These are now available at developers.google.com/resources/api-libraries/documentation/<API NAME>/<API VERSION>/php/latest/

For example: https://developers.google.com/resources/api-libraries/documentation/ml/v1/php/latest/
