### ISSUE TITLE
Make composer use the distributed autoloader

### ISSUE THREAD

**Issue by whatthejeff** [google/google-api-php-client#440]
Once #437 is completed and merged, it might be nice to update `composer.json` to use the autoloader that is distributed with this project. This would prevent composer from generating an unnecessary classmap and would prevent composer users from having multiple autoloaders for the same classes.

~~~diff
--- a/composer.json
+++ b/composer.json
@@ -12,8 +12,8 @@
       "phpunit/phpunit": "3.7.*"
     },
     "autoload": {
-        "classmap": [
-            "src/"
+        "files": [
+            "src/Google/autoload.php"
         ]
     },
     "extra": {
~~~

**Comment by glensc** [comment]
i prefer composer based autoloader, because composer can write optimized version (-o). and with composer there will be only one spl_autoload method registered, instead of two (composer one and this one from project)

when using composer src/autoload.php from this project should be ignored.

so -2 for this PR

**Comment by whatthejeff** [comment]
> when using composer src/autoload.php from this project should be ignored.

@glensc I agree with you. The problem is that many files in this project manually include the non-composer autoloader. You end up with both autoloaders loaded regardless. This suggestion was only aimed at making sure you don't have two autoloaders responsible for the same classes.

**Comment by whatthejeff** [comment]
@glensc FWIW, I also prefer composer's optimized autoloaders. I think I even suggested using a classmap as the default autoloader in a different ticket.

**Comment by glensc** [comment]
well, the classloader from classes should be [removed eventually](https://github.com/google/google-api-php-client/pull/437#issuecomment-71117638). but in my own projects i've used such hack:

```php
if (!class_exists('Composer\Autoload\ClassLoader', false)) {
// setup classloader for outside composer usage
}
```

this could be put to this project's `autoload.php` to avoid two of them being setup.

**Comment by whatthejeff** [comment]
@glensc Yeah, I had also considered that solution. My concern was that it could break autoloading for projects that are using composer for some libs, but have used an alternate install method for this lib.

**Comment by AdamWill** [comment]
@whatthejeff that happens to be exactly owncloud's situation, in fact - it uses composer for the 'core' top-level 3rdparty/ directory, but the google lib is included by an 'application' and not managed by composer.

**Comment by glensc** [comment]
ah yes, [my solution](https://github.com/google/google-api-php-client/issues/440#issuecomment-71164196) only solves for Composer autoloader.

**Comment by glensc** [comment]
so, maybe in classes which load `autoload.php` use such snippet:

```php
// do this only if autoload not yet invoked
if (!class_exists('Google_Client')) {
  require_once dirname(__FILE__) . '/../autoload.php';
}
```

this will try to autoload `Google_Client` using existing methods, and if none registered, go for it's own.

i assume `Google_Client` is always necessary, but could be any other base class.
