### ISSUE TITLE
Update minimum PHP version to >= 5.3: Namespaces & PSR2

### ISSUE THREAD

**Issue by garak** [google/google-api-php-client#445]
In #1 @ianbarber suggested that php 5.2 is kind of a temporary solution.
More than one year after, and with a stable 1.1 release, it's time to reconsider that decision again? Maybe on a 2.X release.
I'd like to point out to this excellent [article](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html) from @ircmaxell 

Just to add my personal view: I'm working with php >= 5.3 since a while and I feel that going back to 5.2 is really painful. I mean, getting that huge files with a lot of classes in it is kind of a mess.

Also (maybe on a different issue?) it would be nice to see [PSR-2](http://www.php-fig.org/psr/psr-2/) coding style

**Comment by ianbarber** [comment]
I'm not against a move to 5.3 only at this point - the requirement change is just a doc change, but moving to namespaced code is the bigger (but more beneficial) part. 

The tricky thing for PSR2 is sorting out the template files - at the moment the generator puts them into one big file per service, and it is non-trivial to sort that out. It was a bit blocked when we didn't have autoloading, but since that's in, worth revisiting I'd say.

**Comment by ircmaxell** [comment]
Nothing says it needs to be PSR2. It can be a custom autoloader that detects which file to include, and include it (based on a segment of the namespace at least).

**Comment by garak** [comment]
Well, PSR-2 is just about following another standard, but of course it doesn't add anything about functionality, it's only coding style-related.
[PSR-4](http://www.php-fig.org/psr/psr-4/) is current autoloading standard proposed by FIG:

**Comment by ircmaxell** [comment]
Good point, removed comment (confused PSR2+PSR4 for a second).

**Comment by hackzilla** [comment]
(Y)

**Comment by samsamm777** [comment]
@garak its not really 'just another coding style'. I think its really important that php code open sourced to the community adheres to all the common practices etc. It will make for much happier adoption of your api's and much easier for other community members to contribute to your project. PSR is clearly defined and well structured. It makes sense to adopt it.

**Comment by garak** [comment]
@samsamm777 you don't have to persuade me: I'm a super-fan of every standard. PSRs rock!
My point was: first priority should be for namespacing and better file organization, since the current one is just a mess. If this change can come along with coding standard, that would be the best.

**Comment by samsamm777** [comment]
@garak  i see! yes of course prioritize for sure. namespacing will give a massive benefit. good to see this sdk is on the right tracks.

**Comment by garak** [comment]
I can't see how 82da936 could be related to this issue...

**Comment by ianbarber** [comment]
oh, my bad, off by one error

**Comment by TomasVotruba** [comment]
:+1:

**Comment by atrauzzi** [comment]
Looking forward to the removal of underscores in class names and the addition of namespacing.  Simplify! :)

**Comment by kesar** [comment]
:+1:

**Comment by theofidry** [comment]
+1

**Comment by JLMorales** [comment]
+1  
Eagerly looking forward to this.... the library is getting in my way without namespaces, my database library has a clas named "query" and a method named "get"  and somewhere along the line, "get" from the "query" class returns a google api obj.... I am royally stuck.... no easy way out of this one and anyway I look at this all I see is a LOT of code rewriting....

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by jshayes** [comment]
:+1: 

Would love to be able to PSR-4 autoload this.

**Comment by bshaffer** [comment]
This library is now PHP5.4  (whoopee!)

Once the master branch is stable enough to tag `v2.0.0`, We can look at upgrading to a namespaced version. Because of the sheer number of users, I wanted to do this in phases. But it is *definitely on the roadmap*, as I too cringe every time I type an underscore in the class name.

Thanks for your feedback and please continue to +1

**Comment by Sammitch** [comment]
Please, please, *please* embrace PSR-4 and abandon the classmap autoloader.

As it stands composer's `autoload_classmap.php` contains a 3541-entry array and weighs in at 432,029 bytes. This means that every time `vendor/autoload.php` is included this behemoth file may need to be yanked from disk. Once the autoloader is initialized we're now looking at a fair bit of additional memory usage as well.

Quick test script:

	<?php
	$start = microtime(true);
	printf("Cur: %10.3f kB Peak: %10.3f kB\n", memory_get_usage()/1024, memory_get_peak_usage()/1024);
	require('vendor/autoload.php');
	printf("Cur: %10.3f kB Peak: %10.3f kB\n", memory_get_usage()/1024, memory_get_peak_usage()/1024);
	printf("Microseconds: %d\n", (microtime(true) - $start)*1000000);

Current master:

	Cur:    220.820 kB Peak:    224.859 kB
	Cur:   1216.398 kB Peak:   1783.805 kB
	Microseconds: 6632
	
An unrelated project using PSR-4 autoloaders, essentially a baseline for composer:

	Cur:    220.969 kB Peak:    225.016 kB
	Cur:    345.812 kB Peak:    373.320 kB
	Microseconds: 1103

By no means an exhaustive test, but certainly worth considering.

**Comment by kkopachev** [comment]
@Sammitch when using  `--optimize` option, composer will generate classmap-based autoloader even for psr-4 libraries.

**Comment by bshaffer** [comment]
Closing, as we've moved to PHP 5.4 (see [composer.json](https://github.com/google/google-api-php-client/blob/master/composer.json#L9))
