### ISSUE TITLE
How can i get access to the Contacts API?

### ISSUE THREAD

**Issue by maikeldus** [google/google-api-php-client#446]
I need the contacts of the OAuth authenticated user, but there is not yet an Service for in this library.

How can I make a custom request with the correct OAuth headers to Google to retrieve the XML for these contacts? In older versions you could use apiHttpRequest ot get an authenticated request but I couldn't find any documentation about how this needs to be done now?

See for reference: http://stackoverflow.com/questions/22632298/google-api-php-client-contacts-service/22644607#comment44182659_22644607

**Comment by ianbarber** [comment]
The contacts API is a gdata service, and this library only handles the newer discovery based services. There is an older library that might help: https://developers.google.com/gdata/articles/php_client_lib
