### ISSUE TITLE
 Is it working ok inserting events with reminders?

### ISSUE THREAD

**Issue by maroke** [google/google-api-php-client#449]
Hi, sorry for my english.
I'm trying to insert an event with reminders but the value useDefault doesn't get the value false.
I tried with:

$set_reminders->setUseDefault(**"false"**);
and
$set_reminders->setUseDefault(**false**);

but the result always is that the event is created ok but useDefault doesn't have value:

![captura](https://cloud.githubusercontent.com/assets/10535359/5744432/0d41949c-9c21-11e4-85ef-370a1d1571ac.PNG)

This is the code i'm using:

``` php

$event = new Google_Service_Calendar_Event();
$event->setSummary($nombreEvento);
$event->setLocation($localizacion);

$start = new Google_Service_Calendar_EventDateTime();
$start->setDateTime($fechaHoraIni);
$start->setTimeZone($timeZone);
$event->setStart($start);

if($fechaHoraFin!=""){
    $end = new Google_Service_Calendar_EventDateTime();
    $end->setDateTime($fechaHoraFin);
    $end->setTimeZone($timeZone);
    $event->setEnd($end);
}


$set_reminders = new Google_Service_Calendar_EventReminders();
$set_reminders->setUseDefault("false"); 
//$set_reminders->setUseDefault(false); 
$set_reminders->setOverrides(array(
    array(
            "method" => "email", 
            "minutes" => $this->minutosRecordatorio
        ),
         array(
            "method" => "email", 
            "minutes" => 300
        )
));
$event->setReminders($set_reminders);
$new_event = null;
$new_event = $this->service->events->insert($this->calendar_id,$event,array( 'sendNotifications' => true));   

```

There is a bug??

Thanks a lot!

**Comment by whatthejeff** [comment]
Just to be sure, have you tested with `var_dump()` instead of `print_r()`? The `print_r()` function doesn't print a value for `false`. For instance:

~~~
php > $test = new stdClass;
php > $test->useDefault = false;
php > print_r($test);
stdClass Object
(
    [useDefault] => 
)
php > var_dump($test);
object(stdClass)#1 (1) {
  ["useDefault"]=>
  bool(false)
}
~~~

**Comment by maroke** [comment]
OMG! I was using print_r. Now with var_dump I can see that the value is false.....So, what I'm doing wrong with reminders??

![captura](https://cloud.githubusercontent.com/assets/10535359/5753749/6a194756-9c8e-11e4-9be6-df8c0ff1f4be.PNG)

I'm creating events without problems, only I have problems with reminders.

![captura](https://cloud.githubusercontent.com/assets/10535359/5753792/3833dc14-9c8f-11e4-9d18-6fb0afe29f05.PNG)

Maybe I'm not doing a step, but I don't know what it is :(

Thanks for your help!

**Comment by maroke** [comment]
Please, anyone could provide some code creating an event with reminders that works ok??

**Comment by ianbarber** [comment]
This tracker is not a good place for Calendar specific support, but it possibly could be a bug with the client library.  Can you see if your query works properly using the API explorer: https://developers.google.com/apis-explorer/#p/

**Comment by maroke** [comment]
Hi ianbarber, I have captured the value of $postBody in /Service/Resource.php function call, and later I have paste the json in https://developers.google.com/apis-explorer/#p/  .... and the event has been created with reminders. I'll keep looking for the problem. Thanks

**Comment by ianbarber** [comment]
Did you get any further with this? Sounds like the library was generating the right output, but something was still off?

**Comment by maroke** [comment]
I stopped trying to find the problem temporarily to do other things, because I was stuck with this task. 
In fact, I don't know what more can I do. As you can see I captured the response, I pasted the json in apis-explorer and it worked ok.... :/

**Comment by ianbarber** [comment]
Is it possible you were using a different account on the API explorer and in the client code? Perhaps the defaults were different?

**Comment by mmaiolinoc90** [comment]
tengo problemas con insert de google calendar no encuentro la manera de adaptarlo a mi sistema web

**Comment by fdnetty** [comment]
Hi, 
I have the same issue with the lastest 1.X.X release ( 1.1.7), the event is created, all works fine excepted the reminder : 

Here is my code : 

$event = new Google_Service_Calendar_Event();
$event->setSummary($event_info['event_text']);
	
$time = new DateTime();

$timeStart = new Google_Service_Calendar_EventDateTime();
$timeStart->setDateTime($time->setTimestamp($event_info['time_start'])->format(DateTime::ATOM));
$timeEnd = new Google_Service_Calendar_EventDateTime();
$timeEnd->setDateTime($time->setTimestamp($event_info['time_end'])->format(DateTime::ATOM));

$event->setStart($timeStart);	
$event->setEnd($timeEnd);	

$event->setDescription($event_info['content']);
$event->setLocation($event_info['where']);


//Add reminders
//setDefaultReminders
if($event_info['remind']){
	$set_reminders = new Google_Service_Calendar_EventReminders();
	$set_reminders->setUseDefault(FALSE);
	$set_reminders->setOverrides(array(
	    array(
	        'method' => "popup", 
	        'minutes' => $event_info['remind']/60
	    )
	));
	$event->setReminders($set_reminders);
	
}

$createdEvent = $service->events->insert($cal_id, $event);

And var_dump() : 


object(Google_Service_Calendar_Event)#313 (55) {
  ["collection_key":protected]=>
  string(10) "recurrence"
  ["internal_gapi_mappings":protected]=>
  array(0) {
  }
  ["anyoneCanAddSelf"]=>
  NULL
  ["attachmentsType":protected]=>
  string(39) "Google_Service_Calendar_EventAttachment"
  ["attachmentsDataType":protected]=>
  string(5) "array"
  ["attendeesType":protected]=>
  string(37) "Google_Service_Calendar_EventAttendee"
  ["attendeesDataType":protected]=>
  string(5) "array"
  ["attendeesOmitted"]=>
  NULL
  ["colorId"]=>
  NULL
  ["created"]=>
  NULL
  ["creatorType":protected]=>
  string(36) "Google_Service_Calendar_EventCreator"
  ["creatorDataType":protected]=>
  string(0) ""
  ["description"]=>
  string(0) ""
  ["endType":protected]=>
  string(37) "Google_Service_Calendar_EventDateTime"
  ["endDataType":protected]=>
  string(0) ""
  ["endTimeUnspecified"]=>
  NULL
  ["etag"]=>
  NULL
  ["extendedPropertiesType":protected]=>
  string(47) "Google_Service_Calendar_EventExtendedProperties"
  ["extendedPropertiesDataType":protected]=>
  string(0) ""
  ["gadgetType":protected]=>
  string(35) "Google_Service_Calendar_EventGadget"
  ["gadgetDataType":protected]=>
  string(0) ""
  ["guestsCanInviteOthers"]=>
  NULL
  ["guestsCanModify"]=>
  NULL
  ["guestsCanSeeOtherGuests"]=>
  NULL
  ["hangoutLink"]=>
  NULL
  ["htmlLink"]=>
  NULL
  ["iCalUID"]=>
  NULL
  ["id"]=>
  NULL
  ["kind"]=>
  NULL
  ["location"]=>
  string(0) ""
  ["locked"]=>
  NULL
  ["organizerType":protected]=>
  string(38) "Google_Service_Calendar_EventOrganizer"
  ["organizerDataType":protected]=>
  string(0) ""
  ["originalStartTimeType":protected]=>
  string(37) "Google_Service_Calendar_EventDateTime"
  ["originalStartTimeDataType":protected]=>
  string(0) ""
  ["privateCopy"]=>
  NULL
  ["recurrence"]=>
  NULL
  ["recurringEventId"]=>
  NULL
  ["remindersType":protected]=>
  string(38) "Google_Service_Calendar_EventReminders"
  ["remindersDataType":protected]=>
  string(0) ""
  ["sequence"]=>
  NULL
  ["sourceType":protected]=>
  string(35) "Google_Service_Calendar_EventSource"
  ["sourceDataType":protected]=>
  string(0) ""
  ["startType":protected]=>
  string(37) "Google_Service_Calendar_EventDateTime"
  ["startDataType":protected]=>
  string(0) ""
  ["status"]=>
  NULL
  ["summary"]=>
  string(4) "Test"
  ["transparency"]=>
  NULL
  ["updated"]=>
  NULL
  ["visibility"]=>
  NULL
  ["modelData":protected]=>
  array(0) {
  }
  ["processed":protected]=>
  array(0) {
  }
  ["start"]=>
  object(Google_Service_Calendar_EventDateTime)#315 (6) {
    ["internal_gapi_mappings":protected]=>
    array(0) {
    }
    ["date"]=>
    NULL
    ["dateTime"]=>
    string(25) "2016-12-02T09:45:00+01:00"
    ["timeZone"]=>
    NULL
    ["modelData":protected]=>
    array(0) {
    }
    ["processed":protected]=>
    array(0) {
    }
  }
  ["end"]=>
  object(Google_Service_Calendar_EventDateTime)#316 (6) {
    ["internal_gapi_mappings":protected]=>
    array(0) {
    }
    ["date"]=>
    NULL
    ["dateTime"]=>
    string(25) "2016-12-02T11:15:00+01:00"
    ["timeZone"]=>
    NULL
    ["modelData":protected]=>
    array(0) {
    }
    ["processed":protected]=>
    array(0) {
    }
  }
  ["reminders"]=>
  object(Google_Service_Calendar_EventReminders)#317 (8) {
    ["collection_key":protected]=>
    string(9) "overrides"
    ["internal_gapi_mappings":protected]=>
    array(0) {
    }
    ["overridesType":protected]=>
    string(37) "Google_Service_Calendar_EventReminder"
    ["overridesDataType":protected]=>
    string(5) "array"
    ["useDefault"]=>
    bool(false)
    ["modelData":protected]=>
    array(0) {
    }
    ["processed":protected]=>
    array(0) {
    }
    ["overrides"]=>
    array(1) {
      [0]=>
      array(2) {
        ["method"]=>
        string(5) "popup"
        ["minutes"]=>
        int(30)
      }
    }
  }
}


Can you help me ? Thank you all !

**Comment by moiseevigor** [comment]
Any insight on this issue? Have the same problem with reminders

```
  function createEvent($ev)
  {
    $event = new Google_Service_Calendar_Event();
    $event->setSummary($ev['title']);
    $event->setLocation($ev['where']);
    $event->setDescription($ev['desc']);

    $start = new Google_Service_Calendar_EventDateTime();
    $end = new Google_Service_Calendar_EventDateTime();

    if($ev['allday'])
    {
      $start->setDate($ev['startDate']);
      $end->setDate($ev['endDate']);
    }
    else
    {
      $start->setDateTime("{$ev['startDate']}T{$ev['startTime']}:00.000{$ev['tzOffset']}:00");
      $end->setDateTime("{$ev['endDate']}T{$ev['endTime']}:00.000{$ev['tzOffset']}:00");
    }

    $event->setStart($start);
    $event->setEnd($end);
    $event->setAttendees($ev['attendees']);

    if(isset($event['reminder']) && $event['reminder'])
    {
      $reminders = new Google_Service_Calendar_EventReminders();
      $reminders->setUseDefault(false);

      $reminder = new Google_Service_Calendar_EventReminder();
      $reminder->setMethod('email');
      $reminder->setMinutes(24 * 60);

      $reminders->setOverrides(array($reminder));
      $event->setReminders($reminders);
    }

    try {
      $createdEvent = $this->service->events->insert($ev['id_google_calendar'], $event);
    } catch(Exception $e) {
      Sys::exceptionHandler($e);
      return array(
        'status' => $e->getCode(),
        'message' => $e->getMessage(),
        'body' => $e->getTraceAsString(),
        'id_google_calendar' => null);
    }

    return array(
      'status' => '200',
      'message' => '',
      'body' => json_encode($createdEvent),
      'id_google_calendar' => $createdEvent->getId()
    );
  } // END FUNCTION createEvent
```

The I see in returned `body`

```
{
    "anyoneCanAddSelf": null,
    "attendeesOmitted": null,
    "colorId": null,
    "created": "2017-04-07T16:02:54.000Z",
    "description": "Note: ",
    "endTimeUnspecified": null,
    "etag": "\"2983161949118000\"",
    "guestsCanInviteOthers": null,
    "guestsCanModify": null,
    "guestsCanSeeOtherGuests": null,
    "hangoutLink": null,
    "htmlLink": "https:\/\/www.google.com\/calendar\/event?eid=b2NwYTJua28zdHY2djhqMWkwMzNtazVfOGcgdGtndGloYm5zNzdtcHZlN3RoZ3JpNGpmZjRAZw",
    "iCalUID": "ocpa2nko3tv6v3j5i033mk3k87@google.com",
    "id": "ocpa2nko4tv6v3j1i335mk5k8g",
    "kind": "calendar#event",
    "location": null,
    "locked": null,
    "privateCopy": null,
    "recurrence": null,
    "recurringEventId": null,
    "sequence": 0,
    "status": "confirmed",
    "summary": "test 123",
    "transparency": null,
    "updated": "2017-04-07T16:02:54.559Z",
    "visibility": null
}```

**Comment by balrog2000** [comment]
This works for me well:
`		$reminders = new Google_Service_Calendar_EventReminders();
		$reminders->setUseDefault(false);
		$reminders->setOverrides([
			[
				"method"	=> "popup",
				"minutes"	=> 5,
			],
			[
				"method"	=> "popup",
				"minutes"	=> 60,
			],
			[
				"method"	=> "popup",
				"minutes"	=> 60 * 24,
			],
		]);
		$event->setReminders($reminders);
`

**Comment by tmatsuo** [comment]
Ok, let's close this
