### ISSUE TITLE
Please provide some examples for BigQuery

### ISSUE THREAD

**Issue by FlashT** [google/google-api-php-client#453]
Could you please provide some life examples about creating tables and sending queries to BigQuery service? Seems like all available in Internet are out of date, and missing something.

**Comment by eRadical** [comment]
I can do some basic examples.
@ianbarber is it ok if I add examples in "examples/Service/Bigquery"... (thus mimicking the structure of the client library) ?

**Comment by FlashT** [comment]
Of course, Thank You!
16 sty 2015 16:11 "Gabriel PREDA" <notifications@github.com> napisał(a):

**Comment by ianbarber** [comment]
Thanks @eRadical - we don't generally include service specific examples with the library, but if you put up your own repo of examples that would be great. If you have an example that demonstrate some generic functionality which is not otherwise covered, then do feel free to contribute that though!

**Comment by eRadical** [comment]
@ianbarber  I started a repo as you said at https://github.com/eRadical/google-api-php-client-examples 

I'll be happy to merge pull request that will enrich it.
I know I've digged into the API myself for an AppEngine & BigQuery application... maybe it will be of help.
