### ISSUE TITLE
[NFR] Support Namespace, PSR1/PSR4 standard coding

### ISSUE THREAD

**Issue by joglomedia** [google/google-api-php-client#454]
Its great library to work with Google service,
I think it'd be good if this library support namespace and standard coding from PSR1 /PSR2 / PSR4
I am not sure if it is considered as new feature request,

thanks

**Comment by whatthejeff** [comment]
This is more or less covered by #445.

**Comment by samsamm777** [comment]
+1

**Comment by damienfa** [comment]
Yes, I need it too !

**Comment by spolischook** [comment]
:+1:  Please, it's needed. People that already use namespaces - can't live without it

**Comment by joglomedia** [comment]
How about creating a new branch for refactoring the codebase in standard
PSR? So, we can contribute on this new branch

**Comment by ianbarber** [comment]
Lets track namespaces/PSR naming of the service classes in #445 - both issues are largely about that.

**Comment by joglomedia** [comment]
Hai  google/google-api-php-client, 

Coba tebak - Aku akan penuhi keinginan kamu! 

Aku kirimkan voucher Rp 75.000 sehingga kamu bisa mendapatkan apa yang ada di wishlist kamu. 

Selamat berbelanja! 

 

[1] ACCEPT GIFT > 
 Links
  1 - http://t.bhm02.net/018m3py3a1gf9IrCoDBwtIW2aYF8UtrXntj7Xvps_9ARBaSEA5EKPqEuFRjxMRiBPkngSIqwcYpYQnPvJn8pX8BnWbiRW6ehn6pzvDB6oH13U5DVIdDLQp2fUGKcnuCf78ae5lNse3Ir8Dx65DFRJSw_hC1a5DCbSLi50rUGUpznbDXdxXHDPqXZWGIf8etRPFjAqHQ5RA03X1YG6F2e_m1Q://api.sociablelabs.net/shortlink/api/shortlinks/100319262752653312/follow


Zalora secara otomatis akan memasukkan kamu dalam daftar penerima Newsletter saat kamu menerima hadiah dari teman. Kamu dapat memilih untuk  [2] unsubscribe  setiap saat. 
 Links
  2 - http://t.bhm02.net/018m3py3a1gf9IrCoDBwtIW2aYF8UtrXntj7Xvps_9ARBaSEA5EKPqEuFRjxMRiBPkngSIqwcYpYQnPvJn8pX8BnWbiRW6ehn6pzvDB6oH13U5DVIdDLQp2fUGKcnuCf78ae5lNse3Ir8Dx65DFRJSw_hC1a5DCbSLi50rUGUpznbDXdxXHDPqXZWGIf8etRPFjAqHQ5RA03X1YG6F2e_m1Q://api.behavemail.net/unsub/5qkj4lpw3yxfuomt2kxnra3hxn2kwc4micw3moiexday4oceefy5drznwaccbdhnnssgw36nb2zukjjvw5fxvqsdilcrmm3sb3ym6djm5rfl4dtyj3qkeyowjuzrypqzhpm6fqqrj76mkcdj7pbo5wlz34hynj6x3m2ogng2ejshczdqak3edw2j442hzfycl3zryvdqhqjzlpgm45hwhfwzoqu4xsixv75x6otb4daxwo6x3khzqfmgt7c3rw5hg3rkp264pyrl3u3wwqftvf464txpokkpeohgmb3za34p6dk7qvgsjn7c2jzssfq5srbeiy3jo6tbrmhys6iqgcziojpmi4wsxybklpbhtfo4cglha4o4fn4jre2gahlkctcb7gbbmpin3b5xue6bvteo32u5nrtv4kpyuopmrd5wewhnw3zr5bftbyov72ehz4ifny2h7b4rw

Dengan berkunjung ke alamat email di atas, kamu menyetujui  [3] Syarat & Kebijakan Zalora  dan menerima pemberitahuan tentang penawaran dan promo Zalora. 
 Links
  3 - http://t.bhm02.net/018m3py3a1gf9IrCoDBwtIW2aYF8UtrXntj7Xvps_9ARBaSEA5EKPqEuFRjxMRiBPkngSIqwcYpYQnPvJn8pX8BnWbiRW6ehn6pzvDB6oH13U5DVIdDLQp2fUGKcnuCf78ae5lNse3Ir8Dx65DFRJSw_hC1a5DCbSLi50rUGUpznbDXdxXHDPqXZWGIf8etRPFjAqHQ5RA03X1YG6F2e_m1Q://www.zalora.co.id/privacy-policy/

Unit A-5-1, Level 5, Block A, Southgate Commerical Centre 
 No. 2, Jalan Dua, Off Jalan Chan Sow Lin 
 55200 Kuala Lumpur 
© 2015. Zalora atau perusahaan afiliasi. Hak Cipta Dilindungi Undang-Undang.
