### ISSUE TITLE
Update client.json parsing for web application keys

### ISSUE THREAD

**Issue by fireproofsocks** [google/google-api-php-client#455]
Trying to follow https://developers.google.com/drive/web/examples/php  but it seems that this library doesn't expect the same JSON structure as what's discussed in all the official google docs (?).  E.g. there is no "client_secret" key in the most current JSON structure, nor keys for "installed" or "web", which results in an exception "Invalid client secret JSON file."

Any pointers on this?  Code without docs is worse than useless because it wastes time.  Grumble...

**Comment by SDKiller** [comment]
You are using wrong key.

Create "Client ID for web application"

**Comment by fireproofsocks** [comment]
Yep, did that before I posted: http://cl.ly/image/2l083z0D451O

To review, that JSON file has the following keys it its hash:

* private_key_id
* private_key
* client_email
* client_id
* type

The source code in src/Google/Client.php looks for the following:

* installed (or web)
* client_id
* client_secret
* redirect_uris

However, going through this a THIRD time popped open a different screen: http://cl.ly/463l3J1T0J2U but there was an error that flickered in there, and the JSON that got generated had the same keys as the first 2 attempts (i.e. the incorrect ones).

So I repeat my frustrated grumblings here: the docs do not represent what's available in the dashboard. What am I missing here?

**Comment by ianbarber** [comment]
It is quite possibly different - I believe the console used to give you a separate private key file, but it sounds like the key is now included in the JSON, so I am guessing the console team made a change. If so, the client parsing code will need updating.

**Comment by ianbarber** [comment]
This is definitely a new JSON format. The current parsing is still correct for the regular types, but not for service accounts. However, they're not quite analogous in their usage, so I think we'll need a new function - something builder that takes a JSON location and some scopes and returns an assertion credential.

**Comment by fireproofsocks** [comment]
I'd be satisfied if the documentation were adequate and/or usable.  It's staggering to me that Google's service SDK's are so bloody hard to convert to working examples.  If "Documentation Driven Development" isn't a thing, perhaps it should be. (Continued grumble...)

**Comment by ianbarber** [comment]
Yeah, that's not great. Part of the problem here is that Google is large, so the team that manages the developer console doesn't necessarily interact that much with the team running a client library or a given API. Something like this new JSON is a convenience - all the old methods work - but it can cause confusion when there is inconsistent support. 

I certainly would love to see us sync everything across the board, but at the same time I would rather teams had the opportunity to try out new stuff without having to wrangle n different projects. Appreciate that's not a lot of help in your situation, so sorry about that, and thank you for doing the right thing and filing an issue - so at least we can see the situation!

**Comment by ianbarber** [comment]
Added Google_Client:loadServiceAccountJson as a helper to generate an AssertionCredential - https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L139

**Comment by freekmurze** [comment]
I'm looking for a clear example on how to use a Service account json file can be used? It's not clear how the aformentioned ` Google_Client:loadServiceAccountJson` should be used. Is there any documentation on this?

**Comment by adamellsworth** [comment]
@freekmurze it looks like it's going to be deprecated (`setAuthConfig` preffered):

https://github.com/google/google-api-php-client/blob/18dd5534280318598e8770cb7929e9a542e91c0d/UPGRADING.md#google_auth_assertioncredentials-has-been-removed
