### ISSUE TITLE
Add authorization class for compute engine service accounts

### ISSUE THREAD

**Issue by jonparrott** [google/google-api-php-client#457]
The Python oauth2client has direct support for Google Compute Engine service accounts via [this credentials class](https://github.com/google/oauth2client/blob/master/oauth2client/gce.py). The PHP client should ideally have a corresponding class.

Presently, it's somewhat non-obvious how to use the GCE service accounts. The simpliest way I figured out was [this](https://gist.github.com/jonparrott/c7c1a4ced0e07417e067).

I'm willing to write and submit a patch if no one else is currently working on this.

**Comment by ianbarber** [comment]
So similar to https://github.com/google/google-api-php-client/blob/master/src/Google/Auth/AppIdentity.php for GCE? A patch would be great! https://github.com/google/google-api-php-client/blob/master/CONTRIBUTING.md

**Comment by jonparrott** [comment]
Submitted PR #458 for the initial stab. I wasn't sure if I should create a new test class for this or if I should extend the existing one. @ianbarber PTAL?

**Comment by jonparrott** [comment]
Satisfied by PR #458.
