### ISSUE TITLE
Google Tasks - Tasklist cannot be got correctly

### ISSUE THREAD

**Issue by ansoncsh** [google/google-api-php-client#464]
I am trying to use PHP to get the tasklists and tasks.
But the returned tasklist is not the same as I have.

In this link, I can get all of my tasklists.
http://developers.google.com/apis-explorer/?hl=en_US#p/tasks/v1/tasks.tasklists.list

By using the codes below, I can get one tasklist only which the id is not the same as any id of tasklists found in the link above.
And no tasks can be returned. Seems that the tasklist is not got correctly.

```
<?php

require_once "./src/Google/Client.php";
require_once "./src/Google/Service/Tasks.php";

$client_id = 'xxxxxx.apps.googleusercontent.com';
$service_account_name = 'xxxxxx@developer.gserviceaccount.com';
$key_file_location = 'xxxxxx.p12';

$client = new Google_Client();
$client->setApplicationName("BlessAP");

$key = file_get_contents($key_file_location);
$cred = new Google_Auth_AssertionCredentials(
    $service_account_name,
    array('https://www.googleapis.com/auth/tasks.readonly'),
    $key
);

$client->setAssertionCredentials($cred);

$service_task = new Google_Service_Tasks($client);

$lists = $service_task->tasklists->listTasklists();
$tasks = $service_task->tasks->listTasks($lists[0]['id']);


echo "<pre>";
print_r($lists);
print_r($tasks);
echo "</pre>";
?>
```

Do you have any suggestions?
I can get calendars successfully similar to the above codes.
So it should not be the authentication problem.

Thank you so much!

**Comment by ianbarber** [comment]
Pretty sure it is authentication. You seem to be using a service account, which is its own user - it isn't the "you", or the same user you'd get if you signed in to the API explorer.

**Comment by ianbarber** [comment]
I'm going to close this, but feel free to reopen if there are more questions!
