### ISSUE TITLE
The service example focuses on the least used google API

### ISSUE THREAD

**Issue by callinize** [google/google-api-php-client#466]
I do not understand why Google Books would be used as the example API when google calendar or gmail would be the more useful choice.  

I have used several of these examples to different degrees and just get 404 errors.  The google documentation and this are inconsistent.

**Comment by eRadical** [comment]
I have started a repo with examples at https://github.com/eRadical/google-api-php-client-examples
It's not much yet but I hope it will grow over time.

**Comment by whatthejeff** [comment]
I think they use the books API because it's pretty simple and doesn't require much setup. To be fair, they also have examples for the Drive API which is pretty popular. You can also find some examples for the reseller API here: https://github.com/google/enterprise-deployments/tree/master/apps/php

**Comment by ianbarber** [comment]
Yeah, that's the main idea. For a little background, older versions of the lib (back when it was on subversion!) had lots of examples, which were mostly out of date - they gave a false sense of security. We (silvolu & I mainly) figured we weren't going to have time to keep all of them up to date, and we didn't have familiarity with every library, so we tried to create examples which show *library* features. From that point, it should be possible to figure out how to use a given service in PHP based on its general documentation and the API explorer. If you have seen a library feature which is missing an example do file a FR though - we want to make sure there is coverage for the types of task, if not the specific APIs.
