### ISSUE TITLE
Google Cloud Print?

### ISSUE THREAD

**Issue by DavidAnderson684** [google/google-api-php-client#467]
Hi,

Am I right in thinking that there's nothing to help with Google Cloud Print (submitting jobs) in here?

I've had working PHP code for Google Cloud Print here - http://wordpress.org/plugins/google-cloud-print-library/ - for a few years. But, recently Google has begun rejecting the ClientLogin authentication method. I'm trying to work out what API I need to enable in my Google Developer Console in order to use OAuth2 instead... there is no API listed for Google Cloud Print. So, I was wondering what I'm misunderstanding, and came here to look at your code instead. Sadly, there seems to be no current code examples for GCP that don't use ClientLogin - even on the Cloud Print site, the examples still use ClientLogin, and don't work (though, they do have a handy note that they're from 2011 and probably don't work attached! https://developers.google.com/cloud-print/docs/pythonCode#authentication).

Many thanks,
David

**Comment by whatthejeff** [comment]
I don't think Cloud Print is current supported (see #132).

**Comment by ianbarber** [comment]
Yep, this lib pretty much only supports stuff in discovery, which cloud print isn't unfortunately!

**Comment by DavidAnderson684** [comment]
Hi,

What does "stuff in discovery" mean?

David

**Comment by ianbarber** [comment]
Sorry, part of the Google Discovery Service - the json schema based service descriptions: https://developers.google.com/discovery/

**Comment by lemoslincoln** [comment]
@DavidAnderson684 , 

Do you have any progress with this?

**Comment by DavidAnderson684** [comment]
@lemoslincoin - see: https://github.com/yasirsiddiqui/php-google-cloud-print and https://github.com/yasirsiddiqui/php-google-cloud-print/issues/1

**Comment by gothick** [comment]
If it helps, you *can* use this library at least to help with Google Cloud Print, even though the Discovery methods aren't generated for you. For example, I use this library to authenticate a Service Account, then add the Google Cloud Print scope (https://www.googleapis.com/auth/cloudprint), and use the authenticated Guzzle object I'm passed back from `authorize()` to call Cloud Print methods "manually", and it works fine.

**Comment by gothick** [comment]
@net-tools I think it was very worthwhile responding to a 2-year-old post, given that I was looking for a decent Google Cloud Print API library at the weekend and didn't find yours! Thanks.
