### ISSUE TITLE
Maybe consider using Guzzle

### ISSUE THREAD

**Issue by samsamm777** [google/google-api-php-client#469]
The Google_Http_Request class is pretty crude and doesnt support handling large requests, as it has the body in a string, this can easily consume all the php allocated memory. I would suggest using the guzzle (https://github.com/guzzle/guzzle) libs as they are fully fledged.

**Comment by velosipedist** [comment]
+1

**Comment by silvolu** [comment]
@samsamm777 yeah we've been thinking about it. @ianbarber have been trying for a while to find some time to start looking a things like:
- how to convert from the [Google discovery service](https://developers.google.com/discovery/v1/using#discovery-doc) to guzzle service descriptions
- write an OAuth2 subscriber (or use an existing one, do you know any?)
- figure out if we need something for the media uploads bits to work

The good news is that it's happening tomorrow :) We'll probably push something to a new branch (given the 5.4 requirement), and then look for volunteers to help completing the work ;-)

**Comment by whatthejeff** [comment]
:+1: Would be happy to help with this!

**Comment by koconder** [comment]
Id +1 this motion :+1: - I've had headaches with some big requests, mainly with YT.

**Comment by samsamm777** [comment]
@silvolu Great! I can contribute too, my company will actively be using this sdk in the near future, so i'll be heavily involved with it.

**Comment by ianbarber** [comment]
took a quick look at this today, added a note for discuss in #473

**Comment by ianbarber** [comment]
I'll close this one for now and we can chat on the discuss thread. I suspect that the change would be substantial enough Guzzle will end up being a separate repo, but will see how we go!
