### ISSUE TITLE
Issue with Google/Cache/File.php: fread(): Length parameter must be greater than 0

### ISSUE THREAD

**Issue by ericuldall** [google/google-api-php-client#472]
We noticed one of our systems had stopped sending data to big query, not sure for how long. When debugging we got the following error:

fread(): Length parameter must be greater than 0

We were able to fix this by deleting the cache file from the /tmp dir on our system. However it is a bit concerning that this happened in the first place.

Is there any knowledge of this bug, or how it can be avoided?

**Comment by ericuldall** [comment]
Not sure why that error isn't caught and handled gracefully.

**Comment by ianbarber** [comment]
Haven't seen it, but it sounds like a corrupted cache file of some kind. Would you be able to put together a minimal sample that reproduces the issue?

**Comment by nickrobarov** [comment]
Came across the same problem. 

Deleting the cache files in the tmp dir solved the problem but this might happen again.

**Comment by ericuldall** [comment]
Sorry, not exactly sure how to reproduce the problem.
