### ISSUE TITLE
sites.Add NOT Working

### ISSUE THREAD

**Issue by tariqnaeem** [google/google-api-php-client#476]
Hi, I havee been using webmaster API service for adding, verifying and adding sitemap to a site to webmaster tools account in php. However over the past two weeks i have noticed that sites are not going through the webmaster account.
Upon debugging the code i got to know that sites have been properly verified and site map is added however the first step of adding a site to webmaster account i.e. sites.add is not working. Upon further investigation i got to know that the response code that i am receiving on sites.add is 204 which is valid.
Now i am in a dead lock situation.

**Comment by ianbarber** [comment]
Have you asked the webmaster api team? They may know of any changes. If not, best thing to do is test whether your query works as expected in the API explorer: https://developers.google.com/apis-explorer/#, and see if there is a difference in the call the client library generates, then we can look for any bugs in the library implementation.
