### ISSUE TITLE
Failed to start the resumable upload (HTTP 400: youtube.video, Bad Request)

### ISSUE THREAD

**Issue by hollycoder** [google/google-api-php-client#479]
I'm trying to upload a wmv video file, but I get this error . 
I'm using the following code:
```php
 $snippet = new Google_Service_YouTube_VideoSnippet();
            $snippet->setTitle('title');
            $snippet->setDescription('description');
            $snippet->setCategoryId("22");

            $status                = new Google_Service_YouTube_VideoStatus();
            $status->privacyStatus = "public";

            $video = new Google_Service_YouTube_Video();
            $video->setSnippet($snippet);
            $video->setStatus($status);

            $chunkSizeBytes =  1024 * 512;

            $client = ".... I'm getting the client here  ....";
            $client->setDefer(true);


            $youtube       = new Google_Service_YouTube($client);
            $insertRequest = $youtube->videos->insert("status,snippet", $video);

            $media = new Google_Http_MediaFileUpload(
                $client,
                $insertRequest,
                'video/*',
                null,
                true,
                $chunkSizeBytes
            );
            $fileSize = filesize($videoPath);
            $media->setFileSize($fileSize);


            $status = false;
            $handle = fopen($videoPath, "rb");
            while ( !$status && !feof($handle) ) {
                $chunk  = fread($handle, $chunkSizeBytes);
                $status = $media->nextChunk($chunk);
                $progress = ($media->getProgress()/$fileSize)*100;
            }

            fclose($handle);
```

It works with other files extensions, I have no idea why wmv is returning this error .. Or maybe it is another issue?

**Comment by hollycoder** [comment]
false alarm .. I set the logger, and the error was a long file title .. 
``` php
$client->setClassConfig('Google_Logger_File', 'file', '/var/path.og');
$client->setLogger(new \Google_Logger_File($client));
```
thank you anyway :)

**Comment by drsii** [comment]
Hey @hollycoder can you please stop using fraudulent cards to purchase our products. Twice in 4 months, we're on to you.

**Comment by hollycoder** [comment]
Ok but who are you? I bought from a lot ... :)

**Comment by drsii** [comment]
We're Cartalyst and we're not flattered that you love our products so much that would steal from others to use them. I wouldn't think it's worth it to ruin what little reputation you might have as a developer.

**Comment by hollycoder** [comment]
There is no stealing happening here. They ask their banks for refunds and
you end up giving the product for free (someone will pay the fee though)..
No body loses anything.
And you know nothing about my reputation ..  :)

You have a good base of products, you can end this up by giving me a
permanent access. I never pay for code!

**Comment by drsii** [comment]
Both card holders from each time your github account was associated with separate account creations said they're cards had been stolen. There is a cost buddy and an extra fee to me. Not only have you stolen from the people whose cards you stole, you have stolen $150.00 from me, and an extra $30.00 in chargeback fees.

You've also stolen from all my employees who work hard providing support and great products. Taking advantage of their effort and time is even more insulting. 

in any case, karma will catch up with you.

**Comment by kirkbushell** [comment]
Why not just report him? It's unacceptable and fraudulent behaviour.

**Comment by kayladnls** [comment]
This is not okay. Not in the slightest. Disgusting. I just can't even.

**Comment by drsii** [comment]
You forgot to delete my screenshot.

![screenshot 2015-02-14 21 58 42](https://cloud.githubusercontent.com/assets/100901/6202285/d60e3c32-b494-11e4-8f21-e91fab05be27.png)

**Comment by brunogaspar** [comment]
hahah nice try hollystealer
