### ISSUE TITLE
Downloading file/object from google cloud storage

### ISSUE THREAD

**Issue by pulkitjalan** [google/google-api-php-client#480]
I can't seem to figure out how to download an object from google cloud storage using this client. I have got as far as getting the `Google_Service_Storage_StorageObject ` object which contains the information about the object, but what next?

Thanks in advance for your help!

**Comment by ianbarber** [comment]
From a quick look it looks like it could be using alt=media as a parameter: https://cloud.google.com/storage/docs/json_api/v1/objects/get . You may run into trouble with the lib trying to parse the response as JSON though, so do give it a go If that's not it maybe try asking the cloud support team how the API is supposed to be used? https://cloud.google.com/storage/docs/resources-support#community 

Alt media download might be a useful example though, so if they give an answer please consider updating this ticket!

**Comment by pulkitjalan** [comment]
Hi @ianbarber 

Thanks for your reply, I tried this out however ran into the problem where the library is trying to parse the response as json...

Below is what I tried, and as far as I can tell it is downloading the file.

```php
$file = $storage->objects->get($bucket, $path, ['alt' => 'media']);
```

When running this I get a `Google_Service_Exception` with the message `Invalid json in service response`

Its caused in `src/Google/Http/REST.php` on line `123`.

```php
if ($code != '204') {
    $decoded = json_decode($body, true);
    if ($decoded === null || $decoded === "") {
        $error = "Invalid json in service response: $body";
        if ($client) {
            $client->getLogger()->error($error);
        }
        throw new Google_Service_Exception($error); // <=========== HERE
    }

    if ($response->getExpectedClass()) {
        $class = $response->getExpectedClass();
        $decoded = new $class($decoded);
    }
}
```

The response code for this request was `200`, so could it be as simple as adding another condition in this file?

**Comment by dheeraj143** [comment]
@ianbarber @pulkitjalan Thank you guys! This helped me: 
`$file = $storage->objects->get($bucket, $object, ['alt' => 'media']);` 
:+1:

**Comment by shyandsy** [comment]
@dheeraj2dj there is no $storage->objects now
