### ISSUE TITLE
Random HTTP 500 error during get filelist request after new PageToken

### ISSUE THREAD

**Issue by kvasko** [google/google-api-php-client#486]
Dear All,

I am using this client api to download and backup files from Google drive. My script is working but unfortunately randomly I am getting HTTP 500 error during this task - often when I got new PageToken. Here is the error code of yesterday:

[17-Feb-2015 16:59:48 Europe/Budapest] PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/drive/v2/files?pageToken=xxx&q=mimeType+%21%3D+%27application%2Fvnd.google-apps.folder%27+and+not+%27me%27+in+owners+and+trashed%3Dfalse: (500) Internal Error' in /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php:111
Stack trace:
#0 /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php(63): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/www/html/ibackup/google-api-php-client/src/Google/Task/Runner.php(172): call_user_func_array(Array, Array)
#3 /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php(47): Google_Task_Runner->run()
#4 /var/www/html/ibackup/google-api-php-client/src/Google/Client.php(564): Google_Http_REST::execute(Object(Google_Client), Obj in /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php on line 111

My idea to solve this issue with "exponential backoff" solution to retry the request. BUT now I need your help that based on the above error where and how do I have to implement this solution?

I am using this function to retrieve the filelist:

function retrieveAllFiles($service) {
  $result = array();
  $pageToken = NULL;

  do {
    try {
      $parameters = array();
      $parameters['q'] = "mimeType != 'application/vnd.google-apps.folder' and trashed=false";
      if ($pageToken) {
        $parameters['pageToken'] = $pageToken;
      }
      $files = $service->files->listFiles($parameters);

```
  $result = array_merge($result, $files->getItems());
  $pageToken = $files->getNextPageToken();
} catch (Exception $e) {
  print "An error occurred: " . $e->getMessage();
  $pageToken = NULL;
}
```

  } while ($pageToken);
  return $result;
}

Thank you for your help in advance!

BR,
Krisztián

**Comment by ianbarber** [comment]
You would implement it in your loop there. Basically, keep another counter for retrieves and when you get the exception instead of clearing your pageToken, increment the retry counter, and sleep for some multiple of that time. When you get a succesful retrieve clear the counter. You should also have a check inside the catch block that the counter is not greater than some limit (say 4) - if it is you should log that its a persistent failure, and fail the fetch.

**Comment by kvasko** [comment]
Thanks for your answer. Based on your e-mail I added the "retry" to the function but I am still getting the same error randomly. Example this was today some minutes ago:

[19-Feb-2015 03:05:59 Europe/Budapest] PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/drive/v2/files?pageToken=xxx&q=mimeType+%21%3D+%27application%2Fvnd.google-apps.folder%27+and+not+%27me%27+in+owners+and+trashed%3Dfalse: (500) Internal Error' in /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php:111
Stack trace:
#0 /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php(63): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/www/html/ibackup/google-api-php-client/src/Google/Task/Runner.php(172): call_user_func_array(Array, Array)
#3 /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php(47): Google_Task_Runner->run()
#4 /var/www/html/ibackup/google-api-php-client/src/Google/Client.php(564): Google_Http_REST::execute(Objec in /var/www/html/ibackup/google-api-php-client/src/Google/Http/REST.php on line 111

Here is the modified function by me:

function retrieveAllFiles($service) {
  $result = array();
  $pageToken = NULL;

  do {
    for ($n = 0; $n < 5; ++$n) {
    try {
      $parameters = array();
      $parameters['q'] = "mimeType != 'application/vnd.google-apps.folder' and trashed=false";
      if ($pageToken) {
        $parameters['pageToken'] = $pageToken;
      }
      $files = $service->files->listFiles($parameters);

      $result = array_merge($result, $files->getItems());
      $pageToken = $files->getNextPageToken();
    } catch (Exception $e) {
      print "An error occurred: " . $e->getMessage();
      //$pageToken = NULL;
      usleep((1 << $n) * 1000 + rand(0, 1000));
    }
    }
  } while ($pageToken);
  return $result;
}

Because of this error I am very frustrated because many times its came up in the middle of the process therefore I lost 1-2 hours work. When I got it the script stopped working and i had to start it again. 
If the backoff solution isn't solved this issue than how can I solve it? Or is it any solution to catch this error anyhow without restart the script?

I am appreciating all help!

BR,
Krisztián

**Comment by ianbarber** [comment]
Looking at your code, it seems like it should always catch the exception, but the output you pasted in indicates that you the exception was uncaught. Are you sure you're running your modified code?

**Comment by kvasko** [comment]
Yes, I checked it more than twice.

Do you have any idea how can I continue my script with the current state if I can't catch the error? 
I tried to use the PageToken value from the above mentioned error to continue the work. But when I set the $pageToken = xxx; value at the start of my script I received always the same http 500 error. (I don't know it should work or not.) After I set back the $pageToken  to NULL and my script again started working. 
Maybe if I send my codes to you would you be so kind to check what can cause this problem?

**Comment by ianbarber** [comment]
There's no reason you can't catch the exception, so I suspect there is a problem in your code yeah. Simplify your script down to the minimal possible code and see whether you can catch the exception.

**Comment by tmatsuo** [comment]
Closing this for now. Please re-open if you come up with reproducible code!
