### ISSUE TITLE
Refreshing service account access token occasionally hangs

### ISSUE THREAD

**Issue by delallea** [google/google-api-php-client#488]
I use a service account to access the Google calendar API. I'm having a problem where occasionally, calling ``refreshTokenWithAssertion()`` hangs (it freezes for like 30s then Chrome tells me connection was reset). Unfortunately, I haven't been able to figure out clear repro steps. I would appreciate some pointers, either as to what I may be doing wrong, or how to debug it out. I'm using latest release 1.1.2 with PHP 5.4.36 on a local webserver under Windows (Easy PHP dev environment). When it happens I can usually trigger it several times in a row (not sure exactly until when -- I'll try to figure it out next time it happens).

My code looks like this (I looked around and it seems it is the recommended way to do things, as far as I can tell). Note that my access token has no refresh token inside it, but my understanding is that it's normal when using a service account.

    $scopes = array('https://www.googleapis.com/auth/calendar');
    $credentials = new Google_Auth_AssertionCredentials($this->serviceAccount,
                                                        $scopes, $this->privateKey);
    $client = new Google_Client();
    $client->setAssertionCredentials($credentials);
    $accessToken = $this->getSavedAccessToken();  // load token from db
    if ($accessToken != null)
    {
        $client->setAccessToken($accessToken);
    }
    if ($client->isAccessTokenExpired())
    {
        $client->getAuth()->refreshTokenWithAssertion();  // <-- it may hang here
        $this->setSavedAccessToken($client->getAccessToken());  // save token into db
    }
    $calService = new Google_Service_Calendar($client);
    // ... (have fun with calendar)

**Comment by ianbarber** [comment]
Nothing looks wrong there. I'm guessing the request is hanging on the call to the Google auth servers to get the new token. I'm not sure what to suggest beyond checking when it happens that you server can reach Google and isn't having any other network trouble.

**Comment by ianbarber** [comment]
The one other potential thing might be if something is going odd with the caching - perhaps something odd with the filesystem. It may be worth attaching a debugger when you get a run of the slowness and see what call it actually hangs on.

**Comment by delallea** [comment]
Thanks for confirming that it should work, I'll try to dig deeper next time I run into it. So far I had it happen only a couple of times in the past week, so it's definetely not common.

**Comment by delallea** [comment]
I believe I have repro steps and they suggest the issue may not be related to this library. It seems like the problem occurs when I try to refresh an expired access token during a POST (for instance I create a new event in a form on my website, hit "Submit", and it freezes when attempting to synch to Google to add the event to my calendar). But if I try to refresh the access token while processing a GET request it seems to work fine. And I'm calling the exact same API code...

I can test it only every hour or so as I need to wait for the token to expire, so I'm not 100% sure yet this behavior is consistent. I'll be running more tests during the week and report back.

**Comment by delallea** [comment]
I'm going to close this issue as I seriously doubt the root of this problem comes from this library. I suspect something funky going on with my local dev webserver and/or Symfony. I'll let you know if I ever figure it out :) (for now I believe I found a workaround)
