### ISSUE TITLE
Abstract executeRequest return type is different than concrete classes

### ISSUE THREAD

**Issue by thejaswip** [google/google-api-php-client#489]
For the class Google_IO_Curl and  Google_IO_Stream respetively, their member method 

 public function executeRequest(Google_Http_Request $request)

should also be returning a Response of rtype Google_Http_Request , but in reality it is merely, returning  
array($response_data, $responseHeaders, $respHttpCode);

On a related note, the abstract class that is Google_IO_Abstract notably 
public function makeRequest(Google_Http_Request $request)

is returning 

$request->setResponseHttpCode($respHttpCode);
    $request->setResponseHeaders($responseHeaders);
    $request->setResponseBody($responseData);
    // Store the request in cache (the function checks to see if the request
    // can actually be cached)
    $this->setCachedRequest($request);
    return $request;

which is the expected behaviour a simple fix would be copy the code from the abstract but unsure it will break many people's implementation.

Currently I am not relying on executeRequest method instead using makeRequest .

**Comment by ianbarber** [comment]
I think the easiest fix is to change the documented return type on the abstract executeRequest. makeRequest is the right method for most cases.

**Comment by thejaswip** [comment]
Probably you are right, I would suggest , to get rid of the method all together if i could ! is kind of duplicate and without serving much of purpose i could think of .
