### ISSUE TITLE
Autoloading can't find Google_Service class after recent commits

### ISSUE THREAD

**Issue by cajax** [google/google-api-php-client#494]
Hi!
In my sumfony2 dev environment I use master branch of google-api-php-client.
After recent update via composer I have this error all the time.  I didn't test other services but i guess it is the same.
```PHP Fatal error:  Class 'Google_Service' not found in /var/www/myproject/vendor/google/apiclient/src/Google/Service/Plus.php on line 32```

**Comment by ianbarber** [comment]
A basic composer install seems to work OK here with dev master. I'm not quite familiar enough with symfony to know where to look for problems unfortunately. Could you repro with a minimal composer file (and just a simple script that instantiates Google_Client or similar?)

**Comment by cajax** [comment]
Sure.

**Comment by cajax** [comment]
OK. So, after some testing I couldn't reporduce the problem on clean Symfony installation. Looks like it happens only to my large project with many dependecies and which was initially developed with old Google Apis lib (Zend).

I believe you may close this issue. Sorry to bother you.

**Comment by ianbarber** [comment]
No problem! Certainly the autoloading has changed, but it should be possible to add the path for the API to any existing autoloader. Hope you can track down the issue!

**Comment by deepak360** [comment]
Fatal error: Class 'Google_Service' not found in C:\xampp\htdocs\database\youtube\Google\Service\YouTube.php on line 32

**Comment by cikatomo** [comment]
yes same

**Comment by avinashseth** [comment]
/signin.php - Class 'Google_Service_Plus' not found in gplus-quickstart-php-master/signin.php

**Comment by bshaffer** [comment]
@avinashseth you probably need to run `composer install` and then add `require 'vendor/autoload.php';` to `signin.php`. Have you tried following the instructions in the [README](https://github.com/google/google-api-php-client#composer)?

**Comment by sktandon0121** [comment]
I have also this error @deepak360

**Comment by nine-hundred** [comment]
I have also this error @deepak360
