### ISSUE TITLE
getSiteIdByUrl only works on one account.

### ISSUE THREAD

**Issue by hdwebpros** [google/google-api-php-client#495]
I installed https://github.com/thujohn/analytics-l4 on a site. After some tweaking we got it to work. But, it only works on one account.
![image](https://cloud.githubusercontent.com/assets/1244893/6373163/ad4b3c5e-bcce-11e4-872a-daa40b321ac3.png)
How does it know to use that one account?Does it just grab the first account? The only information I've given to the package is Client ID and Email address and website. How does it determine which account it uses, and can it be specified?

I made sure the right email address got assigned to all accounts, but it just seems to only work on one account. I get the error
>Site http://www.example.com is not present in your Analytics account.
 
Is there any way to specify the account it's in?

**Comment by ianbarber** [comment]
Maybe ask on the tracker for that package - I'm sure we have a specific opinion on how their stuff works.

**Comment by hdwebpros** [comment]
We got it figured out. Thanks
