### ISSUE TITLE
getProductStatus() returns incorrect type from ProductstatusesCustomBatchResponseEntry

### ISSUE THREAD

**Issue by dawguk** [google/google-api-php-client#496]
I'm going to namespace my comments, for purposes of sanity:

namespace Google_Service_ShoppingContent;

I'm creating a ProductstatusesCustomBatchRequest batch, and I'm adding ProductstatusesCustomBatchRequestEntry entries to it. I'm executing the batch, by calling Google_Service->productstatuses->custombatch(), which is returning a ProductstatusesCustomBatchResponse object. I can then call getEntries() on that object to return a ProductstatusesCustomBatchResponseEntry. All is fine, exactly as expected. However:

When I then call getProductStatus() on the ProductstatusesCustomBatchResponseEntry object, instead of getting the expected ProductStatus object, I get an object of type ProductStatusDestinationStatus. This is incorrect.

The only way for me to get access to the ProductStatus object is to cast the ProductstatusesCustomBatchResponseEntry to a stdClass object using the toSimpleObject() method.

Example below to duplicate:
```php
// ...
$obj_batch = new Google_Service_ShoppingContent_ProductstatusesCustomBatchRequest();
// ...
$obj_entry = new Google_Service_ShoppingContent_ProductstatusesCustomBatchRequestEntry();
$obj_entry->setProductId($obj_item->getId());
$obj_entry->setMerchantId($obj_google_merchant_id->get_value());
$obj_entry->setBatchId($int_batch_id);
$obj_entry->setMethod('get');
$arr_entries[] = $obj_entry;
// ...
$obj_batch->setEntries($arr_entries);
$obj_status_responses = $obj_google_service->productstatuses->custombatch($obj_batch);
foreach ($obj_status_responses->getEntries() as $obj_product_status_entry) {
   $obj_product_status = $obj_product_status_entry->getProductStatus();
   echo get_class($obj_product_status) . "\n";
   // Expected: Google_Service_ShoppingContent_ProductStatus
   // Returned: Google_Service_ShoppingContent_ProductStatusDestinationStatus
}
```

**Comment by ianbarber** [comment]
Do you get the wrong product type back if you use the API explorer for the same query? If so, the problem might be with the shopping API itself rather than the API. If not, just seeing what comes back might give a clue as to what the problem is: https://developers.google.com/apis-explorer/

**Comment by dawguk** [comment]
@ianbarber I did try a few tests using the API explorer, and I was getting the response that I expected, while in my code, I still was getting the wrong type returned.

However, in testing this again today using identical code, it appears to be returning the correct ProductStatus type. Odd. Maybe something has been tweaked on the API, because I haven't updated my library.

I will close this ticket for now as this issue doesn't appear to be relevant any more.
