### ISSUE TITLE
PHP 5.5 upgrade causing problem with latest google-api-php-client/src/Google/Config.php

### ISSUE THREAD

**Issue by PaulNaylor** [google/google-api-php-client#497]
(First time posting an issue here - sorry if I muck it up.)
We just received this communication today (see below), and tried switching to PHP 5.5
But we got this error...
Fatal error:  Call to undefined function sys_get_temp_dir() in <b>C:\...\google-api-php-client\src\Google\Config.php</b>

That's in the latest release of the google-api-php-client. The line is: 
'Google_Cache_File' => array(
'directory' => <b>sys_get_temp_dir()</b> . '/Google_Client'
)

but sys_get_temp_dir() is no longer available in 5.5 (see below)
Will we get a new google-api-php-client ? Is there a workaround?

-------------------
Dear App Engine Developer, 

You are receiving this important update because you are an owner or developer of an App Engine project that uses PHP. 

In response to developer feedback, we have introduced a significant upgrade of PHP in the latest release of App Engine with more features and improved performance. 

The changes include: 
...
The tempnam() and <b>sys_get_temp_dir()</b> functions are not available.
...

**Comment by thejaswip** [comment]
I guess you can close this ISSUE after the email from Google Below ,
-------

Dear App Engine Developer, 

The previous announcement contained an error.
The line “The tempnam() and sys_get_temp_dir() functions are not available” should read as “The tempnam() and sys_get_temp_dir() functions are now available”. 

Apologies for the inconvenience. 

- The PHP for App Engine Team 

---- © 2015 Google Inc. 1600 Amphitheatre Parkway, Mountain View, CA 94043 

You have received this mandatory email service announcement to update you about important changes to Google Cloud Platform or your account.

**Comment by ianbarber** [comment]
Looks like it!

**Comment by ianbarber** [comment]
FWIW though, I would probably use Google_Cache_Memcache on AppEngine. The library should do that switch automatically, but you can of course be overriding it.

**Comment by PaulNaylor** [comment]
Thanks!
