### ISSUE TITLE
PHP examples for API 2.0  and Call to undefined function listFloodlightActivityGroups()

### ISSUE THREAD

**Issue by zhihong** [google/google-api-php-client#498]
Hi, developing team, 

Recently we started to upgrade to use DCM v2.0 API  and also use some new functions for a new project, and when try to get the  FloodlightActivityGroups, got a error as below:
PHP Fatal error:  Call to undefined function listFloodlightActivityGroups()

The script we use is as below:
````php
$path = dirname(__FILE__).'/../google-api-php-client_v2.0/src';
set_include_path(get_include_path() . PATH_SEPARATOR . $path);

require_once "Google/autoload.php";
require_once "Google/Service/Dfareporting.php";

$client = new Google_Client();
$client->setApplicationName($applicationName);
	
$client->setClientId($clientId);
$client->setClientSecret($clientSecret);
$client->setRedirectUri($redirectUri);
$client->addScope("https://www.googleapis.com/auth/urlshortener");
	
$client->refreshToken($refreshToken);
	
$accessTokenJson = $client->getAccessToken();	
if(!$accessTokenJson) {
	throw new Exception("Access ERROR! AccessToken dose not exist");
}

$service = new Google_Service_Dfareporting($client); 

$profileId = getProfileId($service, $networkId);

$flActivityGroups = $service->floodlightActivityGroups; 
$flActivityGroupsList = $flActivityGroups.listFloodlightActivityGroups($profileId, array());
````
As the profileId is correct, so the authentication part has no problem. And the "ActivityGroups" part, I follow the guide in the comments in the Dfareporting.php file. But seems it dose not work.
May I know what can be the problem? 

And at the same time, I did not find php query examples (except authentication part) for API v2.0. Based on the guild here: https://developers.google.com/doubleclick-advertisers/reporting/libraries 
The samples are still on API V1.3. Could you pls provide some examples for new API V2.0?

Thanks
Zhihong

**Comment by ianbarber** [comment]
Looks like you have ".listFloodlightActivityGroups" rather than "->floodLightActivityGroups" which could be it. 

For samples - we don't generally keep service specific examples in the general client library, so the best point of call would the doubleclick team themselves. I would raise a ticket on their issue tracker for the samples repo if there is a problem: https://github.com/googleads/googleads-dfa-reporting-samples/tree/master/php
