### ISSUE TITLE
Example needed for OAuth

### ISSUE THREAD

**Issue by fireproofsocks** [google/google-api-php-client#500]
A full example of how to instantiate and use ANY service is required.  The page @ https://developers.google.com/google-apps/calendar/instantiate does not contain a full example, and I can't find one for any service anywhere.

Likewise, there does not seem to be any cohesive explanation for how the documented functions (e.g. @ http://developers.google.com/apis-explorer/?hl=en_US#p/calendar/v3/) relates to the PHP classes and functions.

**Comment by ianbarber** [comment]
There are a number of examples using the different flavours of OAuth in the examples directory. For a starter, try: https://github.com/google/google-api-php-client/blob/master/examples/user-example.php
