### ISSUE TITLE
Trying to refresh token - 302 Document moved error

### ISSUE THREAD

**Issue by SteveEdson** [google/google-api-php-client#501]
I've started getting the following error when calling `$client->refreshToken($refreshToken);`

```
[05-Mar-2015 16:10:37 UTC] PHP Fatal error:  Uncaught exception 'Google_Auth_Exception' with message 'Error refreshing the OAuth2 token, message: '<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://ipv4.google.com/sorry/IndexRedirect?continue=https://accounts.google.com/o/oauth2/token&amp;q=CGMSBDb2VRUY9f_hpwUiGQDxp4NLsjiyDjOLAX2me9d7LjLEa_gEXc8">here</A>.
</BODY></HTML>
'' in \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php:327
Stack trace:
#0 \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php(255): Google_Auth_OAuth2->refreshTokenRequest(Array)
#1 \htdocs\vendor\google\apiclient\src\Google\Client.php(352): Google_Auth_OAuth2->refreshToken('1/c5OOGvovbzYEK...')
#2 \htdocs\apps\analytics\index.php(94): Google_Client->refreshToken('1/c5OOGvovbzYEK...')
#3 {main}
  thrown in \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php on line 327
```

Obviously I should be catching the exception, however I'm not sure why it is being thrown in the first place, especially when it is from internal methods. It is currently using *1.0.3-beta*.

**Comment by lucassimmons** [comment]
Google is aware of this issue (assuming you are on app engine)

We are investigating an issue with authentication on Google App Engine
beginning at Thursday, 2015-03-05 07:32 (all times are in US/Pacific).

Affected applications are responding with a HTTP 302 on user login, or with
a 403 error connecting to Google APIs.

We will provide more information by 09:00 US/Pacific time.

On Thu, Mar 5, 2015 at 8:33 AM, Steve Edson <notifications@github.com>
wrote:

> I've started getting the following error when calling
> $client->refreshToken($refreshToken);
>
> [05-Mar-2015 16:10:37 UTC] PHP Fatal error:  Uncaught exception 'Google_Auth_Exception' with message 'Error refreshing the OAuth2 token, message: '<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
> <TITLE>302 Moved</TITLE></HEAD><BODY>
> <H1>302 Moved</H1>
> The document has moved
> <A HREF="https://ipv4.google.com/sorry/IndexRedirect?continue=https://accounts.google.com/o/oauth2/token&amp;q=CGMSBDb2VRUY9f_hpwUiGQDxp4NLsjiyDjOLAX2me9d7LjLEa_gEXc8">here</A>.
> </BODY></HTML>
> '' in \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php:327
> Stack trace:
> #0 \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php(255): Google_Auth_OAuth2->refreshTokenRequest(Array)
> #1 \htdocs\vendor\google\apiclient\src\Google\Client.php(352): Google_Auth_OAuth2->refreshToken('1/c5OOGvovbzYEK...')
> #2 \htdocs\apps\analytics\index.php(94): Google_Client->refreshToken('1/c5OOGvovbzYEK...')
> #3 {main}
>   thrown in \htdocs\vendor\google\apiclient\src\Google\Auth\OAuth2.php on line 327
>
> Obviously I should be catching the exception, however I'm not sure why it
> is being thrown in the first place, especially when it is from internal
> methods. It is currently using *1.0.3-beta*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-php-client/issues/501>.
>



-- 
Thanks -
Lucas Simmons

**Comment by SteveEdson** [comment]
I'm not on app engine, but maybe it still applies?

I've updated to the latest version of the SDK now, so I'll see how things go.

Cheers

**Comment by ianbarber** [comment]
Looks like there was a bit of an incident server side. Should all be resolved now AFAICS.

**Comment by lucassimmons** [comment]
The problem with authentication on Google App Engine and the Google APIs
was resolved as of Thursday, 2015-03-05 08:27 (all times are in
US/Pacific). We apologize to our customers for the inconvenience, and we
thank you for your patience and continued support.

We will provide a more detailed analysis of this incident once we have
completed our internal investigation.

On Thu, Mar 5, 2015 at 9:05 AM, Ian Barber <notifications@github.com> wrote:

> Looks like there was a bit of an incident server side. Should all be
> resolved now AFAICS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-php-client/issues/501#issuecomment-77404319>
> .
>



-- 
Thanks -
Lucas Simmons

**Comment by SteveEdson** [comment]
Cool, thanks guys.
