### ISSUE TITLE
Fatal error: Class 'Google_Config' Google/Client.php

### ISSUE THREAD

**Issue by JonatanM** [google/google-api-php-client#502]
Hi, I am facing another problem
Fatal error: Class 'Google_Config' not found in ROOT/vendor/google/apiclient/src/Google/Client.php on line 80

**Comment by ianbarber** [comment]
Sounds like the autoloader is not firing, how have you got it set up?

**Comment by toweringmedia** [comment]
I have the same issue, were you able to solve it?

**Comment by ianbarber** [comment]
How have you installed the library? That might give a clue

**Comment by damek132** [comment]
Got the same issue, library is installed with magento. The error is the following:

Fatal error: Class 'Google_Config' not found in /home/lasulaco/public_html/vendor/google/apiclient/src/Google/Client.php on line 80

Now the line that seems to be a problem is the following:

if (!class_exists('Google_Client')) {
require_once realpath(dirname(__FILE__) . '/../../autoload.php');
}

With the default src folder there is also an autoloader file, any ideas on this.

**Comment by toweringmedia** [comment]
I may have gotten past that last issue update shortly. This is what I did. 
Download the latest version from here https://github.com/google/google-api-php-client/releases/tag/1.1.2. 
Thanks,
http://toweringmedia.com

**Comment by makushatnik** [comment]
The same problem. I downloaded the google-api-client with help of Composer.
Google_Config class don't exists in my /vendor directory.

Version of google-api-client - 2.0

**Comment by ildarkhasanshin** [comment]
same problem
but i helped in the project folder to run a command
composer require google / apiclient: ^ 2.0
https://github.com/google/google-api-php-client#installation
