### ISSUE TITLE
Entire ShoppingContent  folder missing

### ISSUE THREAD

**Issue by sivajik34** [google/google-api-php-client#505]
I have installed your api in magento.
Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory in /var/www/myapp/lib/Varien/Autoload.php on line 94

**Comment by ianbarber** [comment]
The classes for each API are (and have always been) all in the same file: https://github.com/google/google-api-php-client/blob/master/src/Google/Service/ShoppingContent.php

Not sure how you ended up with that include!
