### ISSUE TITLE
storage.googleapis.com alternative name not handled properly in streams connections

### ISSUE THREAD

**Issue by rottingcorpse** [google/google-api-php-client#510]
stream_socket_client(): Peer certificate CN=*.storage.googleapis.com' did not match expected CN=www.googleapis.com' stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://www.googleapis.com:443 (Unknown error)

**Comment by damek132** [comment]
Perhaps this is to do with the https extension that you need to allow? Just a suggestion.

**Comment by ianbarber** [comment]
Hmm, what operation were you trying to perform? Does look like there is some mismatch, but I'm not sure if the issue is with the client library or elsewhere.

**Comment by kevindecapite** [comment]
I'm getting the same error. It used to work and I haven't changed anything (to my knowledge). Running Mavericks 10.10.2.

**Comment by ElteHupkes** [comment]
I'm not actually using this library, but found this issue through Google and figured I'd contribute my two cents.

It seems to be related to the new SSL certificate that Google issued for googleapis on March 19th. The domain used for the token endpoint (www.googleapis.com) is in this certificate's Alternative Names (the common name is *.storage.googleapis.com), which is somehow not picked up by `stream_socket_client` or the SSL library backing it. I suspect the configuration was different for the previous certificate, but I don't actually have it so I'm not sure.

Apart from disabling SSL host verification (which you shouldn't want) I currently have no idea how to circumvent this error unfortunately.

**Comment by kevindecapite** [comment]
What I don't understand, is why I'm not getting this error on my production version of this app, but only in my local environment.

**Comment by ElteHupkes** [comment]
I read somewhere someone suggested updating libssl - if the bug is caused by that, there might just be different versions on your different machines.

For me, it's happening on production though :(.

**Comment by kevindecapite** [comment]
I upgraded my openssl library to 1.0.2a via MacPorts and am still having the issue.

**Comment by ianbarber** [comment]
I'm wondering if its tied to PHP version as well. @ircmaxell - do you have much familiarity with the SSL options, know if theres any thing we could do here around SANs?

**Comment by ircmaxell** [comment]
@ianbarber PHP prior to 5.6 did not match SAN names: http://phpsecurity.readthedocs.org/en/latest/Transport-Layer-Security-%28HTTPS-SSL-and-TLS%29.html

If you can switch to CURL, it can correctly match the certificate.

**Comment by ianbarber** [comment]
That'll do it! Thanks. So - for others on the thread, you should be able to use the cURL IO variant.

**Comment by dawguk** [comment]
I understand that this is a closed issue, but I've just started seeing a number of issues (today) which points at some sort of SSL related issue in completely unrelated service calls and would like some more clarity.

I'm performing custombatch() on Products, which is returning either one of two errors:

__SSL connect error__

or

__Failed to connect to 2a00:1450:4009:800::200a: Network is unreachable__

Both look as though they are messages passed in directly from the API, as I don't appear to be able to find these strings in the library anywhere.

Should the suggestion of using the cURL IO variant still stand in this case? If not, should I be raising a new issue?

**Comment by ianbarber** [comment]
Sounds like a new issue - maybe raise that one with some code to reproduce and we can try it in other environs.
