### ISSUE TITLE
ShoppingContent - Merchant Promotions Attribute

### ISSUE THREAD

**Issue by sam-ecomdev** [google/google-api-php-client#512]
The Products Feed Specification (https://support.google.com/merchants/answer/188494?hl=en-GB) includes a field called promotion_id in the section labeled Merchant Promotions Attribute.

This field is not referenced in Google_Service_ShoppingContent_Product class in the ShoppingContent.php file.

If I add the member variable and associated getter/setter then I am able to define promotion_id in the resulting JSON definition of a product.  However when this JSON is posted to the rest endpoint I get a response that says the field promotion_id is not recognised.

Given that this field is in the Products Feed Specification I expected that I would have been able to update it via the API despite it not being part of the PHP client library.

Is promotion_id supported by Content API v2 ?
If so how do I define promotion_id against a product?
If not how do I request that support is added to the Content API v2 ?

**Comment by ianbarber** [comment]
The classes are generated from the Discovery service - in this case https://www.googleapis.com/discovery/v1/apis/content/v2/rest. I couldn't see promotion_id in there, so it may not be properly exposed through the API. I would raise that as an issue with the shopping team - they look like they have a forum https://developers.google.com/shopping-content/forum/index

**Comment by sam-ecomdev** [comment]
If anyone else is looking for a solution promotion_id is treated as a custom attribute.

Generic/custom attribute names are to be submitted without underscores. To submit a promotion id, use the following syntax:

"customAttributes": [
  {
   "name": "promotion id",
   "type": "text",
   "value": "foo"
  }
 ]

**Comment by ianbarber** [comment]
Thanks for following up Sam!
