### ISSUE TITLE
Google_Service_IdentityToolkit seems messed up

### ISSUE THREAD

**Issue by MCGamer20000** [google/google-api-php-client#514]
The [Google_Service_IdentityToolkit](https://github.com/google/google-api-php-client/blob/master/src/Google/Service/IdentityToolkit.php) code seems to be completely messed up / outdated, as I am unable to figure out how to use it, nor does it seem Google (search engine, not company) even cares how it's used. At first I thought it would be as simple as:
```php
$service = new Google_Service_IdentityToolkit($client);
echo $service->relyingparty->createAuthUri(new Google_Service_IdentityToolkit_IdentitytoolkitRelyingpartyCreateAuthUriRequest());
```
But that threw an `Error calling POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/createAuthUri: (403) Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup` exception. Am I just using it wrong? Please respond. Thanks.

**Comment by ianbarber** [comment]
You'll need to enable it on the Google developers console, and use a service account. I'd recommend taking a look at the gitkit quickstart: https://developers.google.com/identity-toolkit/quickstart/php#step_1_configure_the_google_identity_toolkit_api
