### ISSUE TITLE
Credentials check in service-account.php example always returns error

### ISSUE THREAD

**Issue by Blueprinter** [google/google-api-php-client#517]
In the service-account.php file, there is a test for the existence of the user credentials.  If the user credentials haven't been assigned to a variable, an error displays, and the code quits.  Here is the link to the file I am referencing:

https://github.com/google/google-api-php-client/blob/master/examples/service-account.php

Line 44:

    if ($client_id == 'YOUR_CLIENT_ID'

The $client_id will ALWAYS equal the $client_id.  The condition will ALWAYS evaluate to true, and display an error.  Shouldn't it be NOT EQUAL TO?

    if ($client_id != 'YOUR_CLIENT_ID'

OR change it altogether to this:

    if (!strlen($client_id)

**Comment by ianbarber** [comment]
Ah yeah, that's a bit confusing. The idea was to check if it hasn't been changed from the literal string "<YOUR_CLIENT_ID>", but you've done the fairly natural thing which is to change both instances for that string.

**Comment by Blueprinter** [comment]
Oh, okay.  I get it now.  The user isn't supposed to substitute their client Id into that spot.  Yah, I did easily misunderstand that.

**Comment by ianbarber** [comment]
Yeah, I think that's worth fixing - what I think is the right choice is to make it check for a client ID shaped thing rather than for the specific string.

**Comment by bazilio43** [comment]
> In the service-account.php file, there is a test for the existence of the user credentials. If the user credentials haven't been assigned to a variable, an error displays, and the code quits. Here is the link to the file I am referencing:
> 
> https://github.com/google/google-api-php-client/blob/master/examples/service-account.php
> 
> Line 44:
> 
> ```
> if ($client_id == 'YOUR_CLIENT_ID'
> ```
> 
> The $client_id will ALWAYS equal the $client_id. The condition will ALWAYS evaluate to true, and display an error. Shouldn't it be NOT EQUAL TO?
> 
> ```
> if ($client_id != 'YOUR_CLIENT_ID'
> ```
> 
> OR change it altogether to this:
> 
> ```
> if (!strlen($client_id)
> ```

@ianbarber
