### ISSUE TITLE
bugs Unknown field name: size

### ISSUE THREAD

**Issue by 5mehulhelp5** [google/google-api-php-client#518]
Hello i am getting error in google shopping api v2 
unknown field name size and if i try with the sizes then it's shows me invalid value "Small"
i have tried with all value like small, Medium, medium,XL,xl,S,s,M,m,L,l and also with S,M,L so please can you tell which one correct value?
also Targeted country is US and product google category is Apparel & Accessories > Clothing > Shirts & Tops

**Comment by ianbarber** [comment]
This tracker is for issues with the library itself - for help with specific APIs its best to contact the teams that manage those APIs. For shopping, try the forum: https://developers.google.com/shopping-content/forum/index

Taking a quick look at the resource though (https://developers.google.com/shopping-content/v2/reference/v2/products#resource) I notice there are different size systems, so perhaps the specific is dependent on using the size system you expect.
