### ISSUE TITLE
Warning: Permission denied on fopen

### ISSUE THREAD

**Issue by vivienfx** [google/google-api-php-client#522]
My program to access Google Drive started giving me this warning a few days ago. 

Warning: fopen(/tmp/Google_Client/d2/d2cc3021e1c7d79718c97b2906f86f5f): failed to open stream: Permission denied in /home/ddnet/public_html/paragon/google-api-php-client-master/src/Google/Cache/File.php on line 181

I assume it is from one of these functions but not sure where the problem is

/**
 * Build and returns a Drive service object authorized with the service accounts
 * that acts on behalf of the given user.
 *
 * @param userEmail The email of the user.
 * @return Google_DriveService service object.
 */
function buildService($userEmail) {
  $key = file_get_contents(SERVICE_ACCOUNT_PKCS12_FILE_PATH);
  $auth = new Google_Auth_AssertionCredentials(
      SERVICE_ACCOUNT_EMAIL,
      array(DRIVE_SCOPE),
      $key);
      
  $auth->sub = $userEmail;
  $auth->prn = $userEmail;
  
  $client = new Google_Client();

//  $client->setUseObjects(true);
  $client->setAssertionCredentials($auth);
  return new Google_Service_Drive($client);
}

function retrieveFiles($service, $parameters) {
  $result = array();
  $pageToken = NULL;

  do {
    try {
     if ($pageToken) {
        $parameters['pageToken'] = $pageToken;
      }
      $files = $service->files->listFiles($parameters);

      $result = array_merge($result, $files->getItems());
      $pageToken = $files->getNextPageToken();
    } catch (Exception $e) {
      print "An error occurred: " . $e->getMessage();
      $pageToken = NULL;
    }
  } while ($pageToken);
  return $result;
}

**Comment by ianbarber** [comment]
Sounds like the file cache can't access a file - i would just delete that file or give permissions to it. Might be worth a check first to see why the process doesn't have permission (my guess would be it was touched by a version of the client running as a different user).
