### ISSUE TITLE
Potential problem with the P12 signer

### ISSUE THREAD

**Issue by mrmark** [google/google-api-php-client#535]
Hello,

The code in question is in the `Google_Signer_P12` class and it is this line in particular:

    if (!$password && strpos($p12, "-----BEGIN RSA PRIVATE KEY-----") !== false) {

I was following the [tutorial](https://developers.google.com/api-client-library/php/auth/service-accounts) for creating a service account and instead of using the `.p12` file, I went with the `.json` file.  The private key in the `.json` file starts with "-----BEGIN PRIVATE KEY-----", but the `Google_Signer_P12` is looking for "-----BEGIN RSA PRIVATE KEY-----".

Primarily, I'm just looking for a way forward, which could include:
* I'm totally wrong and should use the `.p12` file.
* What I'm doing is correct, and for now I could safely work around this by added "RSA" into my private key so `Google_Signer_P12` picks it up.  Later versions of this PHP client will support private keys starting with "-----BEGIN PRIVATE KEY-----".

I'm in the process of migrating to this PHP client (with a tight deadline no less), so a quick assessment of this issue would be greatly appreciated.

Cheers and thanks!

**Comment by kesar** [comment]
I think you should use .p12 file. This is an example:

```php
$service_account_name = '543534543fdsfsfsfs@developer.gserviceaccount.com'; //Email Address
$key_file_location    = __DIR__ . '/gfdgdfgd-sfsdfsdfs.p12'; //key.p12

$client = new Google_Client();
$client->setApplicationName("Client_Library_Examples");
$service = new Google_Service_Prediction($client);

$key  = file_get_contents($key_file_location);
$cred = new Google_Auth_AssertionCredentials(
	$service_account_name,
	array(
		'https://www.googleapis.com/auth/devstorage.full_control',
		'https://www.googleapis.com/auth/devstorage.read_only',
		'https://www.googleapis.com/auth/devstorage.read_write',
		'https://www.googleapis.com/auth/prediction'
	),
	$key
);
$client->setAssertionCredentials($cred);
if ($client->getAuth()->isAccessTokenExpired()) {
	$client->getAuth()->refreshTokenWithAssertion($cred);
}
```

**Comment by mrmark** [comment]
Thanks for the reply, I'll go with the `.p12` file.
