### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by harshitism** [google/google-api-php-client#537]
Fatal error: Uncaught exception 'Google_IOException' with message 'HTTP Error: (0) Failed to connect to 2607:f8b0:4000:80a::200d: Network is unreachable' in /home/letmeqtv/public_html/testing/DEV/src/io/Google_CurlIO.php:128 Stack trace: #0 /home/letmeqtv/public_html/testing/DEV/src/auth/Google_OAuth2.php(101): Google_CurlIO->makeRequest(Object(Google_HttpRequest)) #1 /home/letmeqtv/public_html/testing/DEV/src/Google_Client.php(131): Google_OAuth2->authenticate(Array, '4/q94Sa597r6FIy...') #2 /home/letmeqtv/public_html/testing/DEV/glogin.php(51): Google_Client->authenticate('4/q94Sa597r6FIy...') #3 {main} thrown in /home/letmeqtv/public_html/testing/DEV/src/io/Google_CurlIO.php on line 128

**Comment by kesar** [comment]
This looks like you have a connectivity problem. Perhaps you have a firewall blocking your connection.

**Comment by harshitism** [comment]
Can you please help me out how to resolve this problem .
I have hosted my website on bigrock server and try to integrate google login.

**Comment by ianbarber** [comment]
Agree, this is a network problem with your machine, not specific to the client library. Maybe try contacting the support for your web host?
