### ISSUE TITLE
Allow revoking an access token without first calling setAccessToken

### ISSUE THREAD

**Issue by chancegarcia** [google/google-api-php-client#538]
Tried to call:

``` php
$accessToken = $storage->getGoogleAccessToken();
$client->revoke($accessToken);
```

this returned a **false** value when called. When checking security settings for the account, the permissions were **NOT** revoked (as expected given the return value)

was able to revoke the token via:

``` php
$accessToken = $storage->getGoogleAccessToken();
$client->setAccessToken($accessToken)
$client->revoke();
```

which returned true as expected. When checking security settings for the account, the permissions were revoked (as expected given the return value)

**Comment by kesar** [comment]
Your client needs a token to perform any activity. Parameter in revoke() is in the case that you want to revoke a different token, but you still need client with a valid token.

**Comment by ianbarber** [comment]
I think it would be worth making the first case here work - its not exactly a crazy use of the library, so I'll mark this one a FR.

**Comment by tmatsuo** [comment]
Hi everyone, it looks like the code in question is refactored. Is this still relevant?

**Comment by bshaffer** [comment]
Yes, this is now called via [`Google_Client::revokeToken`](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L676), which accepts either way above.
