### ISSUE TITLE
Wallet Objects Srevice Not Exist

### ISSUE THREAD

**Issue by cherSan** [google/google-api-php-client#541]
I should to ask you that your API didn't has any service of WalletObjects like in https://github.com/googlewallet/walletobjects-quickstart-php.
I create my project & used composer in there.
Of course while I load it there are no any WalletObjects.php file.
Please add this file to your base API. Thank you.

**Comment by ianbarber** [comment]
We only support the APIs available via the discovery service, which is basically the ones in the API explorer (https://developers.google.com/apis-explorer/#p/) - wallet objects seems to be a private API, so you'll need to contact the wallet team/whoever enabled your account for access for the service class.
