### ISSUE TITLE
OpenID id, extracted from id_token isn't equal to original Open ID 2.0 token

### ISSUE THREAD

**Issue by samuelsh** [google/google-api-php-client#542]
According to https://developers.google.com/identity/protocols/OpenID2Migration
>The openid_id field holds the OpenID 2.0 identifier. OpenID 2.0 identifiers are strings that begin with >https://www.google.com/accounts/o8/id?id=.
...
>To migrate your sign-in infrastructure from OpenID 2.0 to OpenID Connect, add code to your >application that does the following for each response that you receive from a token request:
1. Extract the sub field from the token-request response. This is the OpenID Connect identifier.
2. In your user database, link the openid_id to the new sub ID.

But when I'm extracting openid id from id_token and compare it to original OpenID 2.0 id, stored in my DB, they're not the same.
It's actually an issue, because in "sign-in" process, we're using opendID to identify users.
If it changes now, we have to recreate all users with new open ID , or just drop it and use 'sub' 

open_id id extraction code:
`function getOpenIDFromToken($client, $token) {`
`		$id_token = json_decode ( $token );`
`		$ticket = $client->verifyIdToken ( $id_token->{'id_token'} );`
`		if ($ticket) {`
`			$data = $ticket->getAttributes ();`
`			return $data ['payload'] ['openid_id']; // user ID`
`		}`
`		return false;`
`	}`

Thanks

**Comment by ianbarber** [comment]
Only thing I can think is that you're using a slightly different openid realm on the openid parameter - that openID 2 ids are realm specific. You might be better off asking this one on the google-openid tag on StackOverflow - I don't think the issue is client library specific.

**Comment by samuelsh** [comment]
Yep,
Looks like a WAD.
"Please make sure you use EXACTLY the same openid.realm value during the migration flows as you used during the initial OpenID2 flows: any mismatch in those values (even a missing trailing slash char) will lead to completely different openid identifier values."

http://stackoverflow.com/a/23051643/524743

Thanks Ian
