### ISSUE TITLE
Memory exhausted while submitting product with content API

### ISSUE THREAD

**Issue by ram-readwhere** [google/google-api-php-client#543]
I am receiving error for memory limit exhausted when submitting product with Shopping Content.
It is giving fatal error saying 
"Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 523800 bytes) in /var/www/de-viewer/webroot/readwhere-admin/webroot/protected/components/Google/Model.php on line 166".

I have tried upto 2 GB of memory limit.

**Comment by ianbarber** [comment]
While this is happening in the library, I doubt the library is using 2GB of model. Check whether you have a loop or something that is making the call many times, or using up a lot of memory in another way.
