### ISSUE TITLE
Are you using semver?

### ISSUE THREAD

**Issue by onema** [google/google-api-php-client#544]
I see that you have now two new tags: `1.1.1` and `1.1.2` Are you using semantic versioning?

I'm asking because I'm currently locked on version `1.0.4-beta`, and would like to know if I can set the version to `~1.1` in my composer.json file to get the latest non-breaking features and bug fixes. 

Thank you.

**Comment by ianbarber** [comment]
There are definitely potentially breaking changes between 1.0.* and 1.1.* (I think we moved to autoloading then, so it depends how you're using the library).

**Comment by onema** [comment]
Thank you for your answer and for letting me know about potential breaking changes between `1.0.*` and `1.1.*`. 

But what I would like to know is if you have adopted semver at all on any of your current versions `v1.1.*`?

Thank you

**Comment by gmorel** [comment]
:+1:
