### ISSUE TITLE
Make file upload example batch fread chunks before sending

### ISSUE THREAD

**Issue by woofyman99** [google/google-api-php-client#546]
PHP will only return a max of 8192 bytes per read.  That will make the resumable file upload example incredibly slow.  Instead, buffer up reads from the handle until you get enough data to chunk to YouTube.

**Comment by ianbarber** [comment]
Interesting, thanks! Please do send a pull request if you have an improved version of the chunking.

**Comment by woofyman99** [comment]
Pull request sent.  The sample code actually work fine since it’s using a local file.  If you were reading from a URL, it would be very slow.

This code monkey’s your sample code and is very, very, very slow.

https://developers.google.com/youtube/v3/code_samples/php#resumable_uploads <https://developers.google.com/youtube/v3/code_samples/php#resumable_uploads>

**Comment by tmatsuo** [comment]
@woofyman99 Hi, thanks for the report. where is the pull request?

**Comment by woofyman99** [comment]
The pull request was already merged.
