### ISSUE TITLE
Planning another release/tag?

### ISSUE THREAD

**Issue by tomwalder** [google/google-api-php-client#547]
Hi there,

The latest release is `1.1.2` from Nov last year. Any plans for a new release, so I can stop using `dev-master` for some of the more recent fixes and upgrades (~250 commits)?

Also, the docs here indicate `1.0. beta` is the suggested tag - which is from Sep and is missing over 500 more recent commits.

https://developers.google.com/api-client-library/php/start/installation

Cheers,

Tom

**Comment by ianbarber** [comment]
No specific plans, but sounds worth releasing another tag. Agreed that doc page is out of date - I think we'll just point people towards packagist to see the available versions.

**Comment by elyobo** [comment]
Just as a heads up, v201409 is out of date, with a sunset date of 14 July at the moment (I just got bitten having not upgraded to 201409...)

https://developers.google.com/adwords/api/docs/sunset-dates

**Comment by kcrawley** [comment]
:+1: there are certain features in `dev-master` that we could use. With >250 commits untagged, it seems to me that a new tag would be on the horizon.

**Comment by ianbarber** [comment]
Just tested, and tagged 1.1.3
