### ISSUE TITLE
Can I have more than email?

### ISSUE THREAD

**Issue by Sinaboi** [google/google-api-php-client#550]
I checked the idtoken.php file, it said
$client->setScopes('email');

can I have more than just email?

Thanks,
Sinaboi

**Comment by ianbarber** [comment]
Any profile scope should allow retrieving an id token, so profile or email should work. Note that ID tokens are not used for authorization - e.g. they're not used to allow you to query Google APIs.

**Comment by msrumon** [comment]
> I checked the idtoken.php file, it said
> $client->setScopes('email');
> 
> can I have more than just email?
> 
> Thanks,
> Sinaboi

@Sinaboi Yes, you can set `profile` scope as well. But that scope doesn't work for me for some reasons.
