### ISSUE TITLE
Getting your ducks together - Doc vs Git vs Code

### ISSUE THREAD

**Issue by TeckniX** [google/google-api-php-client#551]
For being a company that strives on simplicity, documentation, open source, etc. I find it absolutely pathetic that you can't even get your documentation/code samples together. 

Developers rely on your code/information to implement your service, yet it's baffling to me that your tutorials are from 2009-2012 and have completely wrong information (queue https://developers.google.com/analytics/solutions/articles/hello-analytics-api)

Your 'hello world' to analytics fails on so many levels, I don't understand how that slides. By all means bash the n00b in me for not understanding right away how to use your api; having terrible documentation for a product that you create/support is simply worse than no documentation at all.

**Comment by TeckniX** [comment]
Just another proof:
'https://developers.google.com/analytics/devguides/reporting/core/v3/coreDevguide'  - Last updated April 7, 2015.

Yet the call to the PHP analytics service is: `$analytics = new apiAnalyticsService($client);` :-1:

**Comment by kesar** [comment]
```
I find it absolutely pathetic that you can't even get your documentation/code samples together.
```

Good thing about being openSource is that people like you can contribute to get this better :)

**Comment by TeckniX** [comment]
@kesar :+1:  :100: 

I'll try to keep my code clean and create a PR for an Analytics PR :P

**Comment by kesar** [comment]
That will be great! thanks! :+1:
