### ISSUE TITLE
[bigquery] issues with select queries

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [google/google-api-php-client#553]
Recently I have been having issues with selects in bigquery being run in the following manner:

```
$query = new Google_Service_Bigquery_QueryRequest();
        $query->setQuery($stmt);
        $response = $this->service->jobs->query(STATS_PROJECT, $query);
        $result = array();
        foreach ($response->getRows() as $row => $data){
            foreach($data['modelData']['f'] as $k => $v){
                $result[$row][$response['modelData']['schema']['fields'][$k]['name']] = $v['v'];
            }
        }
        return $result;
```

I expect the response to look something like:

`{"cacheHit":false,"jobComplete":true,"kind":"bigquery#queryResponse","pageToken":null,"totalBytesProcessed":"387824112","totalRows":"7"}`

However I am getting:
`{"cacheHit":null,"jobComplete":false,"kind":"bigquery#queryResponse","pageToken":null,"totalBytesProcessed":null,"totalRows":null}`

quite frequently.

What might be causing this issue? It seems as though it always runs for about 10-11s then returns this response.

**Comment by ianbarber** [comment]
Not sure - sounds like it might be an issue with bigquery itself rather than the client library though. Have you contacted the bigquery team?

**Comment by Ewan-GrandSlam** [comment]
It seemed to be an issue with bigquery itself.
