### ISSUE TITLE
Webmaster tools - Login Required

### ISSUE THREAD

**Issue by clarkk** [google/google-api-php-client#556]
When retrieving data from webmaster tools

The API key is generated here (Public API access)
https://console.developers.google.com/project

```
require_once 'Google/autoload.php';

try{
    $client = new Google_Client();
    $client->setApplicationName("My project");
    $apiKey = "xxx";
    $client->setDeveloperKey($apiKey);

    $service = new Google_Service_Webmasters($client);
    $service->sites->listSites();
}
catch(Google_Service_Exception $e){
    echo $e->getMessage();
}
```

error
```
(401) Login Required
```

**Comment by franchos25** [comment]
tanks.

**Comment by ianbarber** [comment]
Sounds like you need more than just the simple API access key. Take a look at a sign in example to see how to get an access token to authenticate your request: https://github.com/google/google-api-php-client/blob/master/examples/user-example.php

**Comment by imotski** [comment]
Hi Ianbarber,
could you please post an actual google-api-user-example. Your link doesn't function.
thx
