### ISSUE TITLE
Gmail api thread: list  parameter maxResults not working

### ISSUE THREAD

**Issue by navneet10sep** [google/google-api-php-client#560]
Hi 

Whenever i list all threads without maxResults parameter it works fine. But when i use maxResults to any positive number it keeps loading. API do not return anything. 

https://developers.google.com/gmail/api/v1/reference/users/threads/list

**Comment by ianbarber** [comment]
Does the same thing happen via the API explorer on the page you linked? Wondering whether the issue is the API or the library.

**Comment by navneet10sep** [comment]
According to me issue is in the google-api-php-client because it works in the API explorer page. 
https://developers.google.com/gmail/api/v1/reference/users/threads/list. 

Here is the code i tried from the example 


function listThreads($service, $userId) {
  $threads = array();
  $pageToken = NULL;
  do {
    try {
      $opt_param = array( 'maxResults'  => 1   );
      if ($pageToken) {
        $opt_param['pageToken'] = $pageToken;
      }
      $threadsResponse = $service->users_threads->listUsersThreads($userId, $opt_param);
      if ($threadsResponse->getThreads()) {
        $threads = array_merge($threads, $threadsResponse->getThreads());
        $pageToken = $threadsResponse->getNextPageToken();
      }
    } catch (Exception $e) {
      print 'An error occurred: ' . $e->getMessage();
      $pageToken = NULL;
    }
  } while ($pageToken);

  foreach ($threads as $thread) {
    print 'Thread with ID: ' . $thread->getId() . '<br/>';
  }

  return $threads;
}

**Comment by navneet10sep** [comment]
Hi, I am waiting on this bug to be resolved. 

I tried to fix it. There is no problem with the request. Here is the output below of  class  Google_Http_Request object when requesting data with listUsersThreads method . 
Query Parameter is also there in request. 

 Google_Http_Request Object
(
    [batchHeaders:Google_Http_Request:private] => Array
        (
            [Content-Type] => application/http
            [Content-Transfer-Encoding] => binary
            [MIME-Version] => 1.0
        )

    [queryParams:protected] => Array
        (
            [maxResults] => 10
        )

    [requestMethod:protected] => GET
    [requestHeaders:protected] => Array
        (
            [authorization] => Bearer ya29.***********************
            [accept-encoding] => gzip
        )

    [baseComponent:protected] => https://www.googleapis.com
    [path:protected] => /gmail/v1/users/me/threads
    [postBody:protected] => 
    [userAgent:protected] =>  google-api-php-client/1.1.5 (gzip)
    [canGzip:protected] => 1
    [responseHttpCode:protected] => 
    [responseHeaders:protected] => 
    [responseBody:protected] => 
    [expectedClass:protected] => Google_Service_Gmail_ListThreadsResponse
    [expectedRaw:protected] => 
    [accessKey] => 
)

I captured the network traffic on Wireshark. Google keeps sending packets to my server for next 10 minutes , it seems like Google didn't read the max Result parameter  and sent all the threads in once that's why page keeps loading. I will appreciate if you can help me on this,

**Comment by rahnas** [comment]
is it not fixed yet?

**Comment by ak8zs** [comment]
Having same problem.. 

Works well on [https://developers.google.com/gmail/api/v1/reference/users/threads/list?apix=true](url)

while using API  **maxresult** parameter not reflecting any changes in result.
kindly let us know status for this..

**Comment by bustamantelujano** [comment]
> It is working..
> 
> i was doing the same mistake as in posted code.. remove the loop which checks for nextPageToken.
> 
> for fixing see [Stackover Flow](https://stackoverflow.com/questions/33577273/users-threads-list-in-gmail-api-not-working-with-maxresults)

This works for me, thanks :D
