### ISSUE TITLE
PubSub API not working.

### ISSUE THREAD

**Issue by s-chizhik** [google/google-api-php-client#567]
Hi. I tried to use PubSub API with this client:

```php
<?php
require_once 'vendor/autoload.php';

// all authorizations things here

$client = new Google_Client();

$pub_sub = new Google_Service_Pubsub($client);

$topics = $pub_sub -> projects_topics -> listProjectsTopics('projects/my-project');

echo "Topics:" . PHP_EOL;
foreach ($topics as $topic) {
	echo "\t" . $topic['name'] . PHP_EOL;
}
```
When I tried to run it, I've got error
```
PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/v1beta2/projects/my-project/topics: (404) Not Found' in /some_directory/vendor/google/apiclient/src/Google/Http/REST.php:110
```
By documentation I need to send requests to `pubsub.googleapis.com`, but here `www.googleapis.com`. I fixed this problem, but it's not solution:

```php
// Google_Service_Pubsub::_construct
    parent::__construct($client);
    $this->servicePath = 'v1beta2/';
    $this->version = 'v1beta2';
    $this->serviceName = 'pubsub';

    $this -> rootUrl = 'https://pubsub.googleapis.com';   // <= so ugly
    ...
```
Also, my composer.lock:
```json
 "name": "google/apiclient",
 "version": "1.1.4",
 "source": {
     "type": "git",
     "url": "https://github.com/google/google-api-php-client.git",
     "reference": "2adb5ba90612858d4add0342eee6b8b9aaca398d"
},
```

**Comment by jonathantrevorh** [comment]
If you don't want to modify the source code to add the custom rootUrl, create an ini file with these contents:
```
base_path = 'https://pubsub.googleapis.com'
```

Then inject the configuration, by creating the client like so, instead:
```
$client = new Google_Client(new Google_Config($path_to_your_ini));
```

Once pubsub exits beta, it might be migrated to `www.google.com`, which would save us from this wokaround.

**Comment by bshaffer** [comment]
We have merged in a fix for this, and `master` is now using `pubsub:v1`

Please update the library and confirm this fixes your problem. Thank you!

**Comment by s-chizhik** [comment]
I've tested my code with `dev-master` revision. Seems it works fine! Would you be kind to tag this changes?

**Comment by bshaffer** [comment]
I do not have the ability to tag this repo, unfortunately. @tbetbetbe are you the one to do this?

**Comment by s-chizhik** [comment]
Also, when somebody will make a tag, look please to [this](https://github.com/google/google-api-php-client/issues/647) small fix.

**Comment by 4414** [comment]
---------- Proslijeđena poruka ----------
Šalje: "Brent Shaffer" <notifications@github.com>
Datum: 17. 8. 2015. 23:36
Predmet: Re: [google-api-php-client] PubSub API not working. (#567)
Prima: "google/google-api-php-client" <
google-api-php-client@noreply.github.com>

We have merged in a fix for this, and master is now using pubsub:v1

Please update the library and confirm this fixes your problem. Thank you!

**Comment by kumardippu** [comment]
Below are the code I'm trying but nothing print..... 

$pub_service = new Google_Service_Pubsub($client);
$topicsList = $pub_service->projects_topics->listProjectsTopics('https://pubsub.googleapis.com/v1beta2/projects/qustn-1051');
//$topicsList = $pub_service->projects_topics->listProjectsTopics('projects/qustn-1051');
print_r($topicsList);exit;

**Comment by s-chizhik** [comment]
@kumardippu try to use `projects/qustn-1051` instead of full URI.

**Comment by hashtag-framework** [comment]
will this change also be made in the v1-master branch?   i'm using v1-master for a PHP App Engine app.... should i be using master instead?   the github page and other google docs say to use v1-master.

**Comment by bshaffer** [comment]
@hashtag-framework Yes, try with `v2.0.0-RC2`, but keep in mind there are some differences between the libraries that might require you to refactor your code.

**Comment by s-chizhik** [comment]
Suppose I can close this issue due to date.
