### ISSUE TITLE
Error when calling library on localhost

### ISSUE THREAD

**Issue by tomasienrbc** [google/google-api-php-client#568]
When calling any function that requires me to go out to Google on localhost (MAMP) I'm getting this error (Laravel, latest version of library) 

exception 'Google_IO_Exception' with message 'SSL read: error:00000000:lib(0):func(0):reason(0), errno 60' in /Applications/MAMP/htdocs/notes/vendor/google/apiclient/src/Google/IO/Curl.php:81

On my live version (which goes over SSL) it works fine. Do you require SSL for the library to work? It worked fine in the past.

**Comment by ianbarber** [comment]
SSL is required.
