### ISSUE TITLE
Intermittent issue posting to Big Query from App Engine 

### ISSUE THREAD

**Issue by ericuldall** [google/google-api-php-client#570]
We're getting this error occasionally when streaming rows into big query from GAE PHP:

Failed to post to BQ: HTTP Error: Unable to connect: 'fopen(**REDACTED_URL**): failed to open stream: Unsupported SSL context options are set. The following options are present, but have been ignored: cafile
Fetch error'

Steps to reproduce:
Sending 40 parallel requests of 40 records each containing 25 columns

**Comment by dt-rush** [comment]
[Someone else with this issue seems to have found a googler who knows of the issue, has reproduced it, is working on it, and who provides a work-around](https://gae-php-tips.appspot.com/2013/12/23/getting-started-with-the-cloud-datastore-on-php-app-engine/).

At the very least, the error message looks the same. Can you test if the suggested work-around works for you?

**Comment by adetogni** [comment]
Hi dt-rush. I have the same issue with SSL and I checked that link. However the solution proposed does not apply as at line 107 there is not that code and I couldn't find anywhere else in Stream.php.
It's very annoying as it happens randomly...

**Comment by sjlangley** [comment]
This is an intermittent fetch error connecting to the backend - if possible add some retry logic to the write.

**Comment by adetogni** [comment]
@sjlangley yep, that's an option but it's pretty time consuming as my app does a LOT of calls to Storage, in many files. I'm pretty sure I'll add some bugs when modifying such a big amount of code :)

**Comment by bgold0** [comment]
This is happening to me too. Anyone who has found any other information please let me know

**Comment by nebadom** [comment]
I have a open ticket on this subject:

https://github.com/google/google-api-php-client/issues/608

With no response so far.

**Comment by bshaffer** [comment]
this was fixed in #631
