### ISSUE TITLE
cURL says "Problem (2) in the Chunked-Encoded data"

### ISSUE THREAD

**Issue by Kirkis** [google/google-api-php-client#571]
While fetching some Google Analytics data with this API, requests may fail.
I am using a service account for authentication with the following options:
scope: https://www.googleapis.com/auth/analytics.readonly
assertionType: http://oauth.net/grant_type/jwt/1.0/bearer
(and relevant credentials from the Google Console)

This sometimes works, sometimes not. When it fails, I get the following cURL error:
Problem (2) in the Chunked-Encoded data
Which is thrown in Google_IO_Curl (v1.1.4) around line 115.

One fix is to add the following line to Google_IO_Curl::executeRequest():
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);

**Comment by Kirkis** [comment]
Hi,
This fix was not included in the latest release. Any ideas as to why?
Thanks,

**Comment by Kirkis** [comment]
Line number changed in recent releases.
The fix is now to add the following:
```
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);
```
Before or after this line:
```
curl_setopt($curl, CURLOPT_URL, $request->getUrl());
```
which is still inside Google_IO_Curl::executeRequest()

**Comment by Kirkis** [comment]
Hi
Has this issue been closed because of the v2 release? I'd venture not everybody will upgrade right away, so maybe this fix could make it to the next v1 relase?
Thanks,

**Comment by jpeak5** [comment]
I'm not using this project, but in googling, I came across the fix posted here. I found a potentially better solution in yet another project that I'm not involved with ;) here https://github.com/jackalope/jackalope-jackrabbit/issues/89

Basically, upgrading ubuntu 14.04 curl from version 7.35 to 7.36 

- hth ...
