### ISSUE TITLE
Connect to cloud print service using service account credentials 

### ISSUE THREAD

**Issue by acidmk** [google/google-api-php-client#572]
While using 'service-account.php' example code i managed to get token with p12 key and changed url in cred info. 

$cred = new Google_Auth_AssertionCredentials(
    $service_account_name,
    array('https://www.googleapis.com/auth/cloudprint'),
    $key
);

Still it seems not to be working correctly. Can't get any printers or print with this token. Request to this link https://www.google.com/cloudprint/search returns 
            [id] => __google__docs
            [name] => Save to Google Docs
            [displayName] => РЎРѕС…СЂР°РЅРёС‚СЊ РІ Google Р”РѕРєСѓРјРµРЅС‚Р°С…
            [ownerName] => Cloud Print
            [connectionStatus] => ONLINE

It would be nice if cloud print service was added to this library.

**Comment by ianbarber** [comment]
Unfortunately, cloud print isn't in discovery, and all the Service classes are generated from discovery documents (https://developers.google.com/discovery/).
