### ISSUE TITLE
refreshToken Issue

### ISSUE THREAD

**Issue by rossdotparker** [google/google-api-php-client#573]
Hello,

I have two installs of Gibbon (https://gibbonedu.org) which uses your library to connect to a Google Account and get calendar information. On one install it works perfectly. The other, which is on the same server, but using a separate Google Dev Console project (set up with the same APIs, etc) does not work quite right. Users can log in fine, and for the first hour all is well. Then, however, when the access token has expired, and it tries to do a token refresh, it does not work. The code below is called via AJAX, and it just never returns, either returning a 500 error, or simply not returning.

``` php
if ($client->isAccessTokenExpired()) { //Need to refresh the token
        //Get API details
        $googleClientName=getSettingByScope($connection2, "System", "googleClientName" ) ; 
        $googleClientID=getSettingByScope($connection2, "System", "googleClientID" ) ; 
        $googleClientSecret=getSettingByScope($connection2, "System", "googleClientSecret" ) ; 
        $googleRedirectUri=getSettingByScope($connection2, "System", "googleRedirectUri" ) ; 
        $googleDeveloperKey=getSettingByScope($connection2, "System", "googleDeveloperKey" ) ;

        //Re-establish $client
        $client->setApplicationName($googleClientName); // Set your application name
        $client->setScopes(array('https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/plus.me', 'https://www.googleapis.com/auth/calendar')); // set scope during user login
        $client->setClientId($googleClientID); // paste the client id which you get from google API Console
        $client->setClientSecret($googleClientSecret); // set the client secret
        $client->setRedirectUri($googleRedirectUri); // paste the redirect URI where you given in APi Console. You will get the Access Token here during login success
        $client->setDeveloperKey($googleDeveloperKey); // Developer key
        $client->setAccessType('offline');  
        $client->refreshToken($_SESSION[$guid]["googleAPIRefreshToken"]);
        $_SESSION[$guid]['googleAPIAccessToken']=$client->getAccessToken();
    }
```

By commenting out various parts of the code, it seems that the issue is with the $client->refreshToken command.

I have updated to your latest release, but it makes no different.

Any idea what might be causing this?

Thanks!

Ross

**Comment by ianbarber** [comment]
Are you sure $_SESSION['guid'] is working properly? Maybe you're getting collisions between the two instances, and its messing up the refresh token storage on one?

**Comment by rossdotparker** [comment]
Ian,

Thanks for getting back to me. The collision idea is interesting, but no,
the GUIDs are different, and there are no collisions elsewhere on the
system. Also, the issue is only on one instance, but if there was a
collision, I would expect it on both. I also figured that fact that they
are under different domains/vhosts, would give further protection against
this.

Also, it works fine for the first hour, and the access token is also stored
in the session variable, using $guid.

Any other ideas?

Ross

On Wed, Jun 3, 2015 at 11:36 AM, Ian Barber <notifications@github.com>
wrote:

> Are you sure $_SESSION['guid'] is working properly? Maybe you're getting
> collisions between the two instances, and its messing up the refresh token
> storage on one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-php-client/issues/573#issuecomment-108178804>
> .
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by ianbarber** [comment]
hmm, few things off the top of my head:

* Is there a refresh token actually in there? You don't always get a refresh token (basically, you do if you request offline AND the user saw the consent screen - so if you reconsent someone the resulting token JSON wont necessary contain a refresh token). This could happen if you sign in on one, then sign in on the other, but they're the same google developers console project?

* Are you using the right redirect URL in the second instance? That has to match up with what is expected on the developer console for that client ID, or the exchange will fail (maybe its the same redirect URL across both?)

* Are the times right? Sometimes having a bit of drift will fail token verification. That said, I'd expect that to hit both as they're on the same box. 

*

**Comment by tmatsuo** [comment]
Adding a possible cause
* Cache conflict between two installation?

**Comment by rossdotparker** [comment]
tmatsuo thanks for adding a new idea here. I can't remember the exact details (I forgot to come back and update the post), but at some point this one was resolved. Wish I could say how! Going to close this now. Cheers. Ross.
