### ISSUE TITLE
Api Google service licensing : Unauthorized operation for the given domain

### ISSUE THREAD

**Issue by lomvel** [google/google-api-php-client#575]
I want to manage user licenses with the PHP API Enterprise License Manager but i have always the same error :

Error calling GET https://www.googleapis.com/apps/licensing/v1/product/Google-Vault/sku/Google-Vault/user/< email > : (403) Unauthorized operation for the given domain

Whatever the method used : get or listForProduct.
```
      $client  = new Google_Client ();
      $client -> setApplicationName (GoogleAppName);
      $service = new Google_Service_Licensing ($client);
      if (isset ($_SESSION ['service_token'])) {
        $client -> setAccessToken ($_SESSION ['service_token']) ;
      }
      $key  =  file_get_contents (GoogleKeyLocation);
      $cred  = new Google_Auth_AssertionCredentials
              (  GoogleServiceAccount
                 , array ('https://www.googleapis.com/auth/apps.licensing')
                 , $key
                 , 'notasecret'
                 , 'http://oauth.net/grant_type/jwt/1.0/bearer'
                 , GoogleAdmin
              );
      $client -> setAssertionCredentials ($cred) ;
      if($client -> getAuth () -> isAccessTokenExpired ()) {
        $client -> getAuth () -> refreshTokenWithAssertion ($cred) ;
      }
      $_SESSION ['service_token']     =  $client -> getAccessToken () ;
      $service -> licenseAssignments -> get ('Google-Vault', 'Google-Vault', <email>)
```
Any Idea ?

**Comment by ianbarber** [comment]
Sounds like your service account doesn't have authorization. Have you delegated authority to it on your domain?

**Comment by rudythesnowman** [comment]
Shut the fuck up!

**Comment by lomvel** [comment]
Yes, I think I have. I've added this scope : https://www.googleapis.com/auth/apps.licensing for the service account's client id.
I use the same client id for Drive and Directory Api without any problem.

**Comment by ianbarber** [comment]
Sounds like you've set it up correctly to me - only other thing I can think to check is that you've enabled the API properly in the developer console (https://console.developers.google.com) for that project?

You might get a better response on the SO tag: http://stackoverflow.com/questions/tagged/google-admin-sdk - there should be people on there who are more familiar with this specific API. 

@rudythesnowman :heart: you too!

**Comment by lomvel** [comment]
It was a token conflict with the other api. Thanks
