### ISSUE TITLE
YouTube  - Upload Fails when including recordingDetails - Invalid value for Double

### ISSUE THREAD

**Issue by stecca21** [google/google-api-php-client#576]
I'm trying to add recordingDetails to an upload call. It seems to work fine on small test files, but with larger files I'm getting the following error:

Failed to start the resumable upload (HTTP 400: global, Invalid value for Double: )
With the help of some debugging code I was able to find out this error happens when executing this line of code: $status = $media->nextChunk($chunk);

If i comment out $video->setRecordingDetails($recordingDetails); the same file uploads fine.

I'm new to the API, and I can't seem to find anything related to this error online. Any guidance or suggestions would be greatly appreciated!

My code is below:

        $videoPath="some_path"

        // Create a snippet with title, description, tags and category ID
        // Create an asset resource and set its snippet metadata and type.
        // This example sets the video's title, description, keyword tags, and
        // video category.
        $snippet = new Google_Service_YouTube_VideoSnippet();
        $snippet->setTitle($video_title);
        $snippet->setDescription($video_description);
        $snippet->setTags(array($video_keywords));

        $snippet->setCategoryId($video_category);

        // Set the video's status to "public". Valid statuses are "public",
        // "private" and "unlisted".
        $status = new Google_Service_YouTube_VideoStatus();
        $status->privacyStatus = $video_status;
        $status->setLicense($video_publish_license);
        $status->setPublicStatsViewable($video_public_stats_viewable);

        //
        $recordingDetails=new Google_Service_YouTube_VideoRecordingDetails();

        $locationdetails=new Google_Service_YouTube_GeoPoint();
        $locationdetails->setLatitude($resource['geo_lat']);
        $locationdetails->setLongitude($resource['geo_long']);

        $recordingDetails->setLocation($locationdetails);

        // Associate the snippet and status objects with a new video resource.
        $video = new Google_Service_YouTube_Video();
        $video->setSnippet($snippet);
        $video->setStatus($status);
        $video->setRecordingDetails($recordingDetails);

        // Specify the size of each chunk of data, in bytes. Set a higher value for
        // reliable connection as fewer chunks lead to faster uploads. Set a lower
        // value for better recovery on less reliable connections.
        $youtube_chunk_size=10;

        $chunkSizeBytes = intval($youtube_chunk_size) * 1024 * 1024;

        // Setting the defer flag to true tells the client to return a request which can be called
        // with ->execute(); instead of making the API call immediately.
        $client->setDefer(true);

        // Create a request for the API's videos.insert method to create and upload the video.
        $insertRequest = $youtube->videos->insert("status,snippet,recordingDetails", $video);

        // Create a MediaFileUpload object for resumable uploads.
        $media = new Google_Http_MediaFileUpload(
            $client,
            $insertRequest,
            'video/*',
            null,
            true,
            $chunkSizeBytes
        );
        $media->setFileSize(filesize($videoPath));

        // Read the media file and upload it chunk by chunk.
        $status = false;
        $handle = fopen($videoPath, "rb");
        while (!$status && !feof($handle)) {
          $chunk = fread($handle, $chunkSizeBytes);
          $status = $media->nextChunk($chunk);
        }

        fclose($handle);

        // If you want to make other calls after the file upload, set setDefer back to false
        $client->setDefer(true);

        $youtube_new_url = "https://www.youtube.com/watch?v=" . $status['id'];

        return array(true,$youtube_new_url);
      }

**Comment by ianbarber** [comment]
Do you get any more detail on the error? YouTube has a pretty good list of error details that can point in the right direction: https://developers.google.com/youtube/v3/docs/errors

**Comment by stecca21** [comment]
That's all the error I get :(

I have looked over the Google API errors before posting here (not that I
couldn't have missed it) but came up empty.

Is there any way to make the errors more verbose? Would a var dump of any
of those variables shed some light?

Allison Stec
Senior Developer & Asset Management Specialist
Colorhythm
http://www.colorhythm.com

Main Office: +1 415-399-9921
Fax: +1 415-399-9928

astec@colorhythm.com

**Comment by ianbarber** [comment]
Maybe try enabling the logging and see if that gives you anything: https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L254 there is a FileLogger that might help. I'm guessing something is failing to parse properly on the recording details, but it'd be easier to inspect in a log. Maybe try hard coding some known good values as well.

**Comment by stecca21** [comment]
I had a tough time getting FileLogger to work, but was able to dump the response from getResumeUri so i could get more info.

You were right on with it being related to bad values being set. Thanks for the direction.

**Comment by mikeytown2** [comment]
What was the fix, what values where bad?
