### ISSUE TITLE
Internal server error response from API when copying file

### ISSUE THREAD

**Issue by ghost** [google/google-api-php-client#577]
I'm getting this error message when copying a file of a shared file, using the latest version of php library. This issue seem to just appear since earlier today.

Google_Exception: Error calling POST https://www.googleapis.com/drive/v2/files/<file id>/copy: (500) { "error": { "code": 500, "message": null } }

Edit: This issue seem to just appear since 3am, 4th Jun 2015 (from Google dev console) and only happening to large files (~1GB). Those files are now showing "Google Drive can't scan this file for viruses." when trying to download it. 

Screenshot API console: http://i.imgur.com/4xckdFa.png

**Comment by ianbarber** [comment]
Sounds like an issue with Drive rather than the client library itself. Though, the extra / in the URL there looks odd. Can you try it via the API explorer and see if it still has the issue there (in which case its definitely an API side issue): https://developers.google.com/apis-explorer/#p/

**Comment by tmatsuo** [comment]
@ghost Sounds like it was the server side issue. Closing for now. Please reopen if it's still an issue.
