### ISSUE TITLE
IO Exception when uploading big files with Drive resumable upload

### ISSUE THREAD

**Issue by RogerG14** [google/google-api-php-client#579]
The following error happens after several GB's of uploading the file we're trying to backup in Drive. Happens at different stages. Already did the Steam.php fix mentioned and the MediaFileUpload.php fix (this one made the error prompt even faster).

[09-Jun-2015 11:02:41] PHP Fatal error:  Uncaught exception 'Google_IO_Exception' with message 'HTTP Error: Unable to connect: 'fopen(https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&upload_id=AEnB2Urc2_53dFy5ypIcncNv6OZWSIeEz3x3ZdaaOupBfBLyB4K4gRw7TAeoCs-Zov2Yjlj8Ws6pUqobagjeC4y_bUJ06Xf-kA): failed to open stream: operation failed'' in /root/scriptEnCrontab/libs/src/Google/IO/Stream.php:141

Stack trace:
#0 /root/scriptEnCrontab/libs/src/Google/IO/Abstract.php(136): Google_IO_Stream->executeRequest(Object(Google_Http_Request))
#1 /root/scriptEnCrontab/libs/src/Google/Http/MediaFileUpload.php(164): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /root/scriptEnCrontab/respaldoDrive.php(169): Google_Http_MediaFileUpload->nextChunk('?M??d????????...')
#3 /root/scriptEnCrontab/respaldoDrive.php(85): insertFile(Object(Google_Client), Object(Google_Service_Drive), '/root/ITbk/www_...', 'bck21-html_4.tg...', '0B2Xiur2QhdC6fl...')
#4 {main}

  thrown in /root/scriptEnCrontab/libs/src/Google/IO/Stream.php on line 141

**Comment by ianbarber** [comment]
If its unable to connect, could you try catching and retrying? There isn't any automatic retry in the library unfortunately.

**Comment by RogerG14** [comment]
Oh, i thought that that's why the status flag was for, let me try it. I'll come back with what happened.

**Comment by bshaffer** [comment]
This is no longer valid as `v1-master` is no longer maintained.
