### ISSUE TITLE
Unable to create a new calendar

### ISSUE THREAD

**Issue by tareq-halaby** [google/google-api-php-client#580]
I am trying to create new calendar, but when I call ``$Service->calendars->insert($Calendar)``
I get the following error

```
Call to undefined method Google_Service_Calendar_Calendar::toSimpleObject() 
```

Full Code
```
$Service	= new Google_Service_Calendar($this->Client);
$Calendar = new Google_Service_Calendar_Calendar();
$Calendar->setSummary('My Events');
$Calendar->setTimeZone('America/Los_Angeles');
$createdCalendar = $Service->calendars->insert($Calendar);
```

**Comment by ianbarber** [comment]
Which version of the client library are you using? That is a fairly fundamental method its missing.

**Comment by tareq-halaby** [comment]
Looks like I was overloading Google_Model with my own model which have the same name.

After figuring this out, everything is working fine.
