### ISSUE TITLE
Annoying Method could not be found error/warning IDE

### ISSUE THREAD

**Issue by martybalandis** [google/google-api-php-client#583]
My IDE (Php Storm) reports it cannot find a method although it still works. It applies for this example from: https://developers.google.com/google-apps/calendar/v3/reference/calendarList/list or ANY that involves loops like that. I could hide OR ignore the error, but I find it inconvenient cause it would not warn where there is an actual error and it does not suggest me any options I can use. It is more an annoying thing than a bug (or is it?) and I would prefer if it is somehow fixed in the classes.

this happens for those parts:
    $calendarList->getItems()
    $calendarListEntry->getSummary()
and
    $calendarList->getNextPageToken()

    $calendarList = $service->calendarList->listCalendarList();

    while(true) {
      foreach ($calendarList->getItems() as $calendarListEntry) {
        echo $calendarListEntry->getSummary();
      }
      $pageToken = $calendarList->getNextPageToken();
      if ($pageToken) {
        $optParams = array('pageToken' => $pageToken);
        $calendarList = $service->calendarList->listCalendarList($optParams);
      } else {
        break;
      }
    }

**Comment by ianbarber** [comment]
Is the issue with the classes or the editor? Have you reached out to the phpstorm folks?

**Comment by martybalandis** [comment]
It is really hard to tell. It is more likely that ide doesn't detect it well and might require annotation in classes or something like that but it is not really a big issue. Perhaps newer versions will address the issue and make the inspector better. Nothing needs to be done on your end right now I think, thanks for response.
