### ISSUE TITLE
CREATING CALENDAR WITH ATTACHMENT OF DRIVE FILES

### ISSUE THREAD

**Issue by SaradambalMunusamy** [google/google-api-php-client#587]
I want to update the calendar attachment of drive files using service of calendar and drive. 
The following error happens after i called below function with 5 params as below:
1.calendar service
2.Drive service
3.Calendar Id
4.Event Id which i created calendar with attachment
5.File id which i need to update the attachment file.
**Patch Function**
function addAttachment($calendarService, $driveService, $calendarId, $eventId, $fileId) {
  $file = $driveService->files->get($fileId);
  $event = $calendarService->events->get($calendarId, $eventId);
  $attachments = $event->attachments;
  $attachments[] = array(
    'fileUrl' => $file->alternateLink,
    'mimeType' => $file->mimeType,
    'title' => $file->title
  );
  $changes = new Google_Service_Calendar_Event(array(
    'attachments' => $attachments
  ));
/*****Upto this function running fine, and get the attached file also***/
  $calendarService->events->patch($calendarId, $eventId, $changes, array(
    'supportsAttachments' => TRUE
  ));
}

**An uncaught Exception was encountered**
ype: Google_Exception
**Message: (patch) unknown parameter: 'supportsAttachments'
Filename: ......application\third_party\Google\Service\Resource.php
Line Number**: 132
Backtrace:
**File: .......\application\third_party\Google\Service\Calendar.php
Line: 1645**
Function: call   

Referred:
https://developers.google.com/google-apps/calendar/create-events#attachments

Using above link , manually i can create the attachment file after enabling the authorize button. But i cant through this google client library.

Please solve this issue as soon as possible.

**Comment by ianbarber** [comment]
The service generator got stuck - it should be updated now.
