### ISSUE TITLE
LIB ERR -> while uploading any file in G Drive

### ISSUE THREAD

**Issue by SaradambalMunusamy** [google/google-api-php-client#590]
While running below function showing error in latest copy. But working In version 1.1.14.

function UploadPdf($title,$description,$mimeType,$parentId,$uploadfilename){
  $file = new Google_Service_Drive_DriveFile();
    $file->setTitle($title);
    $file->setDescription($description);
    $file->setMimeType($mimeType);
    if ($parentId != null) {
        $parent = new Google_Service_Drive_ParentReference();
        $parent->setId($parentId);
        $file->setParents(array($parent));
    }
    try
    {
        $data =file_get_contents($uploadfilename);
        $createdFile = $service->files->insert($file, array(
            'data' => $data,
            'mimeType' => $type,
            'uploadType' => 'media'
                    ));  
    }
    catch (Exception $e)
    {
        echo $e->getMessage();
    }}

**Error calling POST https://www.googleapis.com//upload/drive/v2/files?uploadType=multipart: (400) Uploads must be sent to the upload URL. Re-send this request to https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart**

**Note**: If i mention upload type as 'resumable', its creating the file w/o any errors in drive. But still upon opening that uploaded file from the drive, document content is null and if it's a pdf, it's not even opening.

This was working perfectly until the Release V1.1.4. So, its a regression from the fix of #587 release

**Comment by fonsclaessen** [comment]
In MediaFileUpload.php  

When you examine the Post url you see there is a double /  
//upload

I changed this function :
  private function transformToUploadUrl()
  {
    $base = $this->request->getBaseComponent();
    //$this->request->setBaseComponent($base . '/upload');
	$this->request->setBaseComponent($base . 'upload');  //fix
  }

This solved the double / in de upload URL

It works for me.

**Comment by tmatsuo** [comment]
Seems like there's a workaround?
