### ISSUE TITLE
Could not json decode the token

### ISSUE THREAD

**Issue by camohub** [google/google-api-php-client#591]
Hi,
can you explain me the flow of this API please? 
I want to achieve simple user login. I go acording this: https://developers.google.com/identity/sign-in/web/backend-auth 
So I have Javascript response and I want to send the token to PHP via Ajax. Javascript works fine, but PHP throws me an exception: Could not json decode the token.
I asked on Stackoverflow http://stackoverflow.com/questions/31087070/google-javascript-php-login-api but I did not get answer.  

**EDIT:**
Now I send JSON.stringify(jsResponse) which I mean looks like(has json format) **$client->setAccessToken()** requires. But it throws Invalid token format exception.

jsResponse is result of: JSON.stringify( googleUser.getAuthResponse() )

What is wrong?

**EDIT2:**
If I understant well, I should use **$client->verifyIdToken($id_token)** without $client->setAccessToken()
But it kills an Apache. In Apache log is:
[Thu Jul 02 19:54:34.578125 2015] [mpm_winnt:notice] [pid 656:tid 392] AH00455: Apache/2.4.4 (Win32) PHP/5.4.12 configured -- resuming normal operations
[Thu Jul 02 19:54:34.578125 2015] [mpm_winnt:notice] [pid 656:tid 392] AH00456: Server built: Mar  1 2013 20:59:19
[Thu Jul 02 19:54:34.578125 2015] [core:notice] [pid 656:tid 392] AH00094: Command line: 'C:\Apache24\bin\httpd.exe -d C:/Apache24 -f C:\Apache24\conf\httpd.conf -d C:\Apache24\.'
[Thu Jul 02 19:54:34.578125 2015] [mpm_winnt:notice] [pid 656:tid 392] AH00418: Parent: Created child process 696

**Comment by camohub** [comment]
Hi,
now I send JSON.stringify(jsResponse) which I mean looks like(has json format) $client->setAccessToken() requires. But it throws Invalid token format exception. 

jsResponse is result of: JSON.stringify( googleUser.getAuthResponse() )

What is wrong?

**Comment by borgogelli** [comment]
Ok , but If I I should use only $client->verifyIdToken($id_token), how can I use other object like Google_Service_Oauth2 ?

When I use:
$google_oauth2 = new \Google_Service_Oauth2($client);
I get:
Error calling GET https://www.googleapis.com/oauth2/v2/userinfo: (401) Invalid Credentials

**Comment by tmatsuo** [comment]
@borgogelli The original stackoverflow question seems to have some answers. Closing for now, but feel free to re open if it's still an issue.
