### ISSUE TITLE
Remove Computeaccounts in Service

### ISSUE THREAD

**Issue by khoatranthanh** [google/google-api-php-client#592]
2 file are same name. Please remove one of there

**Comment by localheinz** [comment]
If you clone the repository on a case-insensitive OS, you end up with a dirty working tree, is there a reason for it?

 <img width="952" alt="screen shot 2015-07-07 at 10 16 36" src="https://cloud.githubusercontent.com/assets/605483/8548188/4baf2f2a-2491-11e5-8cd2-083b4da02021.png">

<img width="976" alt="screen shot 2015-07-07 at 10 18 49" src="https://cloud.githubusercontent.com/assets/605483/8548235/9ab8b122-2491-11e5-90de-fe0b7b27a34b.png">

**Comment by kesar** [comment]
nope, I think its an error in the script that generate classes from documentation

**Comment by localheinz** [comment]
@kesar 

Ha! Interesting! Can we fix that?

**Comment by kesar** [comment]
> Ha! Interesting! Can we fix that?

That script is not public :disappointed:

**Comment by localheinz** [comment]
@kesar 

Interesting nonetheless that Google generates code from documentation, rather than the other way around.

**Comment by kesar** [comment]
Yep, it's a smart way to keep updated all the SDKs for different languages :)
