### ISSUE TITLE
PHP StreamWrapper for Google Cloud Storage

### ISSUE THREAD

**Issue by austinh** [google/google-api-php-client#595]
Currently the PHP API lacks a proper StreamWrapper to allow for gc:// to read/write files on non AppEngine instances.

From my Google Compute Engine I would like to be able to write files via Storage.

Amazon has a similar StreamWrapper and it's unfortunate that google doesn't provide one.
https://github.com/aws/aws-sdk-php/blob/master/src/S3/StreamWrapper.php

The AppEngine has one, but is there a way this could be ported over to the regular PHP API? It currently uses the AppEngine SDK. I tried to get it working and "fake" an AppEngine context, but this proved to be too much work. I then tried to write my own, but this proved to be a heavy task that I eventually abandoned. It was easier and cheaper (time wise) to just not use Google Storage.

https://code.google.com/p/googleappengine/source/browse/#svn%2Ftrunk%2Fpython%2Fphp%2Fsdk%2Fgoogle%2Fappengine%2Fext%2Fcloud_storage_streams%253Fstate%253Dclosed

This should be for userland streamwrapping on any server that is not an AppEngine. This is currently the main reason I am unable to use Google Storage for my apps. This is pretty standard for storage CDNs, to be able to write from a non-app related server from the same cloud project.

**Comment by thejaswip** [comment]
+1

**Comment by austinh** [comment]
Any Update?

**Comment by austinh** [comment]
Any update?

**Comment by marslangoog** [comment]
The App Engine SDK is now open-sourced: https://github.com/GoogleCloudPlatform/appengine-php-sdk but the GCS wrapper won't work outside the App Engine environment yet.

**Comment by austinh** [comment]
Thanks. Are there plans in the work for the regular php api to work outside the App Engine environment? And if so anyway I can help?

**Comment by marslangoog** [comment]
The plan is to get it work in Managed VMs (https://cloud.google.com/appengine/docs/managed-vms/) first, and eventually in any environment. That said, the wrapper could theoretically work in its current form with some modifications to the auth layer.

**Comment by mappedinn** [comment]
Any news on for the users of the google compute engine? @austinh @thejaswip @marslangoog

**Comment by bshaffer** [comment]
This was added to `google-cloud-php`! Check out the documentation [here](https://github.com/GoogleCloudPlatform/google-cloud-php#stream-wrapper):

```php
require 'vendor/autoload.php';

use Google\Cloud\Storage\StorageClient;

$storage = new StorageClient([
    'projectId' => 'my_project'
]);
$storage->registerStreamWrapper();

$contents = file_get_contents('gs://my_bucket/file_backup.txt');
```
