### ISSUE TITLE
Field to sort or organize uploaded files in Drive Web Client

### ISSUE THREAD

**Issue by RogerG14** [google/google-api-php-client#606]
I want to set a custom filter so I can view my files that were uploaded with the API in the client, but I can't seem to find a filter option besides the 4 basic ones in the Web Client.

**Comment by RogerG14** [comment]
Could i alter the modified date (as the files will only be opened, they can't be edited) so i could filter them with a custom date I inserted? Even if the date is before the creation of the document?

**Comment by tmatsuo** [comment]
Sorry, but if it's a question, consider using stackoverflow
