### ISSUE TITLE
Fresh clones of repo has modified file....

### ISSUE THREAD

**Issue by longlivelance** [google/google-api-php-client#607]
I believe this is something to do with case-sensitive vs insensitive OSes. Our HD is on an OS X mac formatted as HFS+ which is case-insensitive. It appears two files are checked into the repo, with different case.

src/Google/Service/ComputeAccounts.php
src/Google/Service/Computeaccounts.php

Currently when we clone the repo, one of these files is overwriting to other, and it leaves us with what git thinks is a modified version of src/Google/Service/ComputeAccounts.php. This disallows any automated processes to continue, i.e. checking out a different tag.

The fix should be removing the duplicated file from the repository.

**Comment by kesar** [comment]
There is a PR related to this: https://github.com/google/google-api-php-client/pull/601 soon will be removed

**Comment by tmatsuo** [comment]
Seems like we can close this
