### ISSUE TITLE
Google_Service_Plus_Moment issue

### ISSUE THREAD

**Issue by djkuddel** [google/google-api-php-client#610]
Hello,

if i try to post with Google_Service_Plus_Moment

$plusservicemoment = new Google_Service_Plus_Moment();
$plusservicemoment->setType("http://schemas.google.com/AddActivity");
$plus = new Google_Service_Plus($client);
$item_scope = new Google_Service_Plus_ItemScope();
$item_scope->setType("http://schemas.google.com/AddActivity");
$item_scope->setUrl($myurl);
$plusservicemoment->setTarget($item_scope);
$momentResult = $plus->moments->insert('me', 'vault', $plusservicemoment, array("debug"=>true));

than I got this error on the last line above

Catchable fatal error: Object of class Google_Service_Plus_Moment could not be converted to string

Can anyone help?

Many thanks
DJ

**Comment by ianbarber** [comment]
I think the moments API is deprecated: https://developers.google.com/+/web/api/rest/latest/moments - guessing its returning some warning.
