### ISSUE TITLE
ContactsService?

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [google/google-api-php-client#611]
Why is there no ContactsService available? Or how should contacts be created, fetched, ... through the API?

**Comment by bshaffer** [comment]
The Contacts API is unfortunately not a part of this library. To access it, see the [contacts API documentation](https://developers.google.com/google-apps/contacts/v3/). The examples do not currently support PHP. Sorry for the inconvenience.

**Comment by net-tools** [comment]
Hi Ruben,

Are still looking for a Contacts service ? If so, I'm currently working on a PHP library handling all dirty stuff with the raw http Contacts API. The library is looking like all other Google PHP libraries, such as Calendar or Gmail. 

For example, to create a contact, you will do : 
```php
    // creating a contact
    $c = new Contact();
    $c->familyName = 'Smith';
    $c->givenName = 'John';
    $c->title = $c->givenName . ' ' . $c->familyName;
    $c->emails = array((object)array(
                                'address' => 'john.smith@test.com',
                                'primary' => true,
                                'rel' => Contact::TYPE_HOME
                            ));
    
    // send the request to create the contact and get an updated Contact object with etag, links and other api-related stuff
    $newc = $service->contacts->create($c);
```

If you are interested, I will give you all required information (as the Readme file on the repository is a bit messy actually, I will have to split it in several files...)
