### ISSUE TITLE
Unable to set curl options for Google_IO_Curl with Google_Client

### ISSUE THREAD

**Issue by corycburke** [google/google-api-php-client#612]
I am trying to set the default timeout for curl using the code
```php
    $client->setClassConfig('Google_IO_Curl', 'options',
        array(
		CURLOPT_CONNECTTIMEOUT => 10,
		CURLOPT_TIMEOUT => 10
		)
    );
```
This works fine when setting and even retrieving the values. When I execute code that would use this option the timeout is set at 100 seconds.

Am I implementing this incorrectly? Is it not possible to alter these options this way?

As a side note, even though I have Google_Task_Runner 'retries' set to 5, this timeout always throws an Exception. I was under the impression that the Task Runner would retry curl code 28 up to the maximum number in Google_Task_Runner retries option.

**Comment by corycburke** [comment]
This seems to be an issue of a misconfiguration on our part. We were creating a new client to do a sub request and not setting the timeout again on that client.

Closing this as it is a non-issue. Apologies for the confusion.

**Comment by AnthumChris** [comment]
As of today (v2.2.0), the following code correctly sets the timeout for 3 seconds and I tested to verify:

```
$google_client = new Google_Client();
$google_client->getHttpClient()->setDefaultOption('timeout', 3);
```

You could also set the `connect_timeout`, which would occur before `timeout`:
```
$google_client->getHttpClient()->setDefaultOption('timeout', 2);
```

**Comment by x000zh** [comment]
setDefaultOption was removed in  [Guzzle 6](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md.)
I have to extend Google_Client modify the `Google_Client::createDefaultHttpClient()` method.

**Comment by savoy-wang** [comment]
> `setDefaultOption` was removed in [Guzzle 6](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md).
> I have to extend `Google_Client` modify the `Google_Client::createDefaultHttpClient()` method.

How to solve in v2.4.0?

**Comment by savoy-wang** [comment]
> As of today (v2.2.0), the following code correctly sets the timeout for 3 seconds and I tested to verify:
> 
> ```
> $google_client = new Google_Client();
> $google_client->getHttpClient()->setDefaultOption('timeout', 3);
> ```
> 
> You could also set the `connect_timeout`, which would occur before `timeout`:
> 
> ```
> $google_client->getHttpClient()->setDefaultOption('connect_timeout', 2);
> ```

How to solve in v2.4.0?
