### ISSUE TITLE
Google Sheets API

### ISSUE THREAD

**Issue by keyur-padalia** [google/google-api-php-client#613]
Sorry If I am posting this in wrong place.

I am working on Google Sheets API to update cells in my Google Spreadsheet and I am using this wonderful google-api-php-client to get access token. I was looking into the service directory and can't find Google Sheets API, so I thought to make suggestion to add Google Sheets API functionality to this great api class. Thank you.

**Comment by ianbarber** [comment]
Unfortunately sheets is a gdata API - you can use this lib to get the access token, but it only supports the newer Discovery service based APIs.
