### ISSUE TITLE
date.timezone use

### ISSUE THREAD

**Issue by vincetg2** [google/google-api-php-client#614]
In #284, the changing of the global `date.timezone` value via `date_default_timezone_set()` was removed.
This was mostly a good thing because this client never changed it back to its original value, meaning that external code that used this client would find that this global value had changed unexpectedly.

However, it looks like `Google_Http_CacheParser::isExpired()` uses `strtotime()` and `Google_IO_Abstract->makeRequest()` uses `date()`.
Both `strtotime()` and `date()` can be affected by the value of `date.timezone`, so it seems that those uses of these functions may have relied on it being **UTC**.

Would it be worth changing `date.timezone` temporarily and then restoring the original `date.timezone` before and after the use of `strtotime()` and `date()`?

**Comment by vincetg2** [comment]
Actually, for `date()`, it looks like `gmdate()` can be used as a drop-in replacement to get **UTC**-zoned output.

**Comment by tmatsuo** [comment]
Closing. Please re-open if it's still an issue.
