### ISSUE TITLE
Dead links on developers.google.com

### ISSUE THREAD

**Issue by flashultra** [google/google-api-php-client#615]
On https://developers.google.com/api-client-library/php/guide/aaa_overview links: 
 1)  OAuth 2.0 For Webservers
 2) OAuth 2.0 Service Accounts
returns 404 error

**Comment by brynnbp** [comment]
Anyone know how to access these resources? Still dead.

**Comment by brynnbp** [comment]
I think those might be linking to the sections in the sidebar now, for example:

https://developers.google.com/api-client-library/php/auth/web-app

**Comment by bshaffer** [comment]
Thanks for pointing these out! These have been fixed.
