### ISSUE TITLE
Cannot use dryRun mode on inventory custombatch

### ISSUE THREAD

**Issue by danselley** [google/google-api-php-client#616]
It doesn't look like dryRun is supported when updating inventory as per https://developers.google.com/shopping-content/v2/reference/v2/inventory/custombatch

Can anyone confirm?

**Comment by tmatsuo** [comment]
https://github.com/google/google-api-php-client-services/blob/b00efad5e592afc4d385854bf9096fa7eed0178e/src/Google/Service/ShoppingContent/Resource/Inventory.php#L40

Maybe you can pass the `$optParams`?
