### ISSUE TITLE
Please update PubSub API from Beta1 to V1

### ISSUE THREAD

**Issue by tomalbers** [google/google-api-php-client#618]
Hi,

Pubsub seems to be out of beta. Can you update the code?

https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Pubsub.php
$this->version = 'v1beta1';

Google API Reference V1:
https://cloud.google.com/pubsub/reference/rest/index#pubsub.googleapis.com_1

Please note that this api uses urls below https://pubsub.googleapis.com in v1, instead of https://www.googleapis.com/pubsub/v1beta1

**Comment by KevBurnsJr** [comment]
+1

v1beta1 is deprecated. This library is out of date.

**Comment by pffy** [comment]
+

**Comment by tomwalder** [comment]
+1

**Comment by bshaffer** [comment]
I will try giving this a crack and submitting a PR (hopefully this week)

**Comment by s-chizhik** [comment]
+1
Also, I guess it might be related => https://github.com/google/google-api-php-client/issues/567
