### ISSUE TITLE
Add setIamPolicy to pubsub-api

### ISSUE THREAD

**Issue by tomalbers** [google/google-api-php-client#619]
https://developers.google.com/gmail/api/guides/push describes a way to deliver push notifications from GMail. In that guide, there is a section to grant publishing rights to GMail towards the topic, by using the setIamPolicy call:
https://developers.google.com/gmail/api/guides/push#grant_publish_rights_on_your_topic

Can you provide an API to that? I know Google has not documented it either:
https://cloud.google.com/pubsub/reference/rest/index#pubsub.googleapis.com_1

But I hope you can.

**Comment by mvanbaak** [comment]
+1

**Comment by bshaffer** [comment]
This has been added for [Subscriptions](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Pubsub/Resource/ProjectsSubscriptions.php#L215) and [Topics](https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Pubsub/Resource/ProjectsTopics.php#L142), but please see the official [Google Cloud PHP Pubsub](https://github.com/GoogleCloudPlatform/google-cloud-php-pubsub) client for calling the PubSub API!
