### ISSUE TITLE
Blogger : Get profiles & blog data

### ISSUE THREAD

**Issue by nratifainah** [google/google-api-php-client#621]
Hello, 
I would like to integrate my application with Blogger. 
After authenticate user with $authUrl = $client->createAuthUrl(), is it possible to get user's profile data  with Access token?
 I have tried with 'me' as user_id in parameter, but it return error   "message": "We're sorry, but the value for field resource_id was not valid."

Thanks..

**Comment by ghprod** [comment]
Try with scope google plus :)

**Comment by ghprod** [comment]
```php
$oauth2 = new Google_Service_Oauth2($client);

dump($oauth2->userinfo->get());
```
