### ISSUE TITLE
autoload condition fails when the API is used in CodeIgniter

### ISSUE THREAD

**Issue by TheNavigat** [google/google-api-php-client#622]
``` php
if (!class_exists('Google_Client')) {
  require_once dirname(__FILE__) . '/autoload.php';
}
```

Those lines written in Client.php file fail when the API is used in CodeIgniter. I didn't trace it, but I believe it's because Google_Client class is in the same file and therefore the condition is always true. Maybe I'm wrong.

The solution anyway is to replace Google_Client with Google_Config. Doing that will make it work seamlessly.

**Comment by monkeymars** [comment]
@TheNavigat so is it just load Client.php in codeigniter?

**Comment by TheNavigat** [comment]
Although I'm a bit confused by the comment, but I guess that bit answers your  question.

"The solution anyway is to replace Google_Client with Google_Config. Doing that will make it work seamlessly."

**Comment by bshaffer** [comment]
What do you mean exactly by "code igniter fails"? How does it fail?

This line of code, while silly, shouldn't cause any errors. As you said, it will always return true and so include the autoloader. I would expect it to be innocuous.

**Comment by TheNavigat** [comment]
It's a bit difficult for me to remember what happened, so most of the following is just recalling, I apologize if something's wrong.

What I'm saying is that the ```Google_Client``` class is coded in the same exact file where this condition is, so ```class_exists``` will *always* return true, regardless of whether ```autoload.php``` is actually loaded or not. That causes an error because the rest of the files are never loaded.

The solution I suggested is based on the fact that ```Google_Config``` is a class in a completely independent file, so ```class_exists``` will only return true if the whole stack is actually loaded, which is supposed to only happen when ```autoload.php``` is, in fact, loaded.

**Comment by tmatsuo** [comment]
Please re-open if it's still an issue
