### ISSUE TITLE
	403 Forbidden - This service is not available from your country

### ISSUE THREAD

**Issue by Dad79** [google/google-api-php-client#627]
[error] [exception.Google_Service_Exception] exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/androidpublisher/v2/applications/com.ultimateguitar.tabprofree/purchases/subscriptions/com.ultimateguitar.tabprofree.1yeararn/tokens/xxx-token-xxx: (403) This service is not available from your country' in %app_path%/Google/src/Google/Http/REST.php:111
Stack trace:
#0 %app_path%/Google/src/Google/Http/REST.php(63): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 %app_path%/Google/src/Google/Task/Runner.php(172): call_user_func_array(Array, Array)
#3 %app_path%/Google/src/Google/Http/REST.php(47): Google_Task_Runner->run()
#4 %app_path%/Google/src/Google/Client.php(564): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#5 %app_path%/Google/src/Google/Service/Resource.php(227): Google_Client->execute(Object(Google_Http_Request))
#6 %app_path%/Google/src/Google/Service/AndroidPublisher.php(2238): Google_Service_Resource->call('get', Array, 'Google_Service_...')

The server is in the Amsterdam.
IP-address of our server is: 178.18.22.103

**Comment by tmatsuo** [comment]
If the service is really not available for your country, there's nothing we can do in the client library.
Please re-open if you think it's an issue within the library.
