### ISSUE TITLE
strpos() == false VS strpos() === false

### ISSUE THREAD

**Issue by JHGitty** [google/google-api-php-client#629]
Is this a mistake or right?
https://github.com/google/google-api-php-client/blob/master/examples/user-example.php#L101

`strpos() == false` and `strpos() === false` are two different things!

Remember: `0 == false` is TRUE.

**Comment by bshaffer** [comment]
This file has been moved to [`examples/url-shortener.php`](https://github.com/google/google-api-php-client/blob/master/examples/url-shortener.php) and the conditional removed.
