### ISSUE TITLE
Could we get an example of offline access

### ISSUE THREAD

**Issue by jakewhiteley** [google/google-api-php-client#632]
Could we get an example of https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en#offline within a normal user flow?

The example should indicate how the token can be saved and reused.

**Comment by bshaffer** [comment]
Yes! Check out [`examples/service-account.php`](https://github.com/google/google-api-php-client/blob/master/examples/service-account.php)

**Comment by bshaffer** [comment]
For saving/reusing, check out the [`Caching`](https://github.com/google/google-api-php-client#caching) section of the README.
