### ISSUE TITLE
Is json key supported?

### ISSUE THREAD

**Issue by ymakux** [google/google-api-php-client#635]
Hello
Can I use .json key instead of .p12?

**Comment by tomwalder** [comment]
Try something like this?

```php
$obj_client = new \Google_Client();
$obj_client->setAssertionCredentials($obj_client->loadServiceAccountJson(
      '/path/to/file.json',
      [\Google_Service_Datastore::DATASTORE, \Google_Service_Datastore::USERINFO_EMAIL]
));
```

Obviously, you'll need to define the right scopes for your use case.

**Comment by bshaffer** [comment]
Yes! In the latest version this is now the default. See [Authenticating with OAuth](https://github.com/google/google-api-php-client#authentication-with-oauth) in the README:

```php
$client = new Google_Client();
$client->setAuthConfig('/path/to/client_credentials.json');
```
