### ISSUE TITLE
List search not paging when using both publishedBefore and publishedAfter params

### ISSUE THREAD

**Issue by elliotthill** [google/google-api-php-client#636]
Steps to replicate:
1. Go here: https://developers.google.com/youtube/v3/docs/search/list
2. Set the following:

part: id,snippet
publishedAfter: 2015-05-01T00:00:00+01:00
publishedBefore: 2015-05-01T01:00:00+01:00
query: Path of exile
type: video
1. Execute, take note of the first videoid which is FoRmdifCh20. It indicates the total results are also 17147
2. Copy the nextPageToken into the corresponding box above, to fetch the next page.
3. Execute, see the same list of videos, the first videoid is again FoRmdifCh20

**Comment by tmatsuo** [comment]
Seems like it's not an issue within the library
