### ISSUE TITLE
What is the usage logic of this API client?

### ISSUE THREAD

**Issue by StevenFlecha** [google/google-api-php-client#638]
Hi,

I'm trying to figure out this package but due lack of docs its hard to find a logic flow...
It does not seem to run in parallel with the actual API functions 

eg from https://developers.google.com/youtube/v3/docs/
Youtube data api > videos -> list 
but in the api this is Youtube -> videos -> ListVideos
Why??

Also the classes initiated when doing $youtube->videos->ListVideos is actually Google_Service_YouTube_Channel_Resources and not just Google_Service_YouTube_Channel. Why?

And then how can I for example use functions like:
Google_Service_YouTube_Channel->getContentDetails
Google_Service_YouTube_Channel->getContentOwnerDetails
Google_Service_YouTube_Channel->getSnippet

Thanks!

**Comment by tmatsuo** [comment]
Sorry, but for questions, consider using stackoverflow
