### ISSUE TITLE
CURLOPT SSLVERSION

### ISSUE THREAD

**Issue by gjellis** [google/google-api-php-client#639]
Our environment
PHP 5.3.3
libcurl 7.19.7-46
google-api-php-client 1.1.5

Our problem
We had eight web heads all configured identical running the Google Client code.  After several weeks and escalated traffic, we suddenly started getting 'No Data Available' errors when we tried to execute a Google library.

After many hours of research, we realized we didn't have our code written properly.  Our order was off, calling OAuth Authorize before we created our Google Service Classes.  So, we fixed order and pushed to production.  Still getting 'No Data Available'.  After further research, we realized Curl was  causing httpd to die within src/Google/IO/Curl.php inside curl_exec().   

We finally had a break thru this morning on this issue.  We had tried many different debugging techniques, but everything we tried pointed back to the Apache child dying every time our application executed a curl_exec(), and all output stopped.
 
After a solid week of debugging and investigating, we have finally come up with a solution to this issue.
 
One character change in the Google API PHP Client code, inside the src/Google/IO/Curl.php,
 
we changed
    curl_setopt($curl, CURLOPT_SSLVERSION, 1);
to
    curl_setopt($curl, CURLOPT_SSLVERSION, 3);
 
And all was well.
 
There seemed to be a issue with this version of curl and https sites dealing with certificates.  We are not sure why one server never stopped working, and in the beginning, all the servers were working.  Something, might have been with the security certificates, that started causing the issue.
 
 
The StackOverFlow article that eventually lead us to the solution.
 
http://stackoverflow.com/questions/26009611/php-curl-returns-35-ssl-connect-error/32079279#32079279

**Comment by eRadical** [comment]
This fix is rather worrisome...

What is actually means is that you are moving from CURL_SSLVERSION_TLSv1 (that is TLS v1.x) to CURL_SSLVERSION_SSLv3 which was deprecated recently (SSLv3 is disabled by default since version 7.39.0 or curl library).

At a given time in future (when PHP will catch up with the curl library) the code will probably error out.

**Have you tried commenting out the line?**... Thus leaving the curl library to decide what `ssl` version to use as this is the default behavior in curl (quote: CURL_SSLVERSION_DEFAULT » The default action. This will attempt to figure out the remote SSL protocol version.)

**Comment by gjellis** [comment]
I did comment out this line and thing still worked.  So this must be the better fix.

Thank you

**Comment by eRadical** [comment]
I'm sure in the long term will pay off.

Are you going to make a pull request out of it?
[ I can do that if you don't want/have time! ]

**Comment by gjellis** [comment]
Thank you for the help.  If you don't mind, I will let you take the lead here and put in a pull request.

Thanks

**Comment by ramsy-abg** [comment]
This is security risk. It's necessary to correct and announce immediately.
Please hurry.

**Comment by 4414** [comment]
Thanks for help

**Comment by bshaffer** [comment]
fixed in a07f4584d92c47d9af52b35d4bb1a43c5e0ca51b
