### ISSUE TITLE
DimensionFilterGroups doesn't work

### ISSUE THREAD

**Issue by minobedin** [google/google-api-php-client#641]
Hi all,
I don't understand how to set filters when I use the query function in Webmaster service.
I'm trying to create a Google_Service_Webmasters_ApiDimensionFilterGroup and Google_Service_Webmasters_ApiDimensionFilter obiects and pass it to the function, but this doesn't work for me. All code I tested works, but the result was the same than when I didn't use the filters. I don't receive any errors, only the returned data was wrong.
I also tried to pass the filters with an array (commented line), but doesn't work.

Can anyone help me? 

This is my code

$request = new Google_Service_Webmasters_SearchAnalyticsQueryRequest;
$request->setStartDate('2015-06-03');
$request->setEndDate('2015-06-09');
$request->setDimensions(array('query'));
$request->setRowLimit("5");
$filtri = new Google_Service_Webmasters_ApiDimensionFilterGroup;
$filtro = new Google_Service_Webmasters_ApiDimensionFilter;
$filtro->setDimension("device");
$filtro->setOperator("equals");
$filtro->setExpression("tablet");
$filtri->setFilters($filtro);
//$filtri = array('filters' => array( "dimension" => "device", "operator"=> "equals", "expression" => "tablet"));
$request->setDimensionFilterGroups($filtri);

$request->setSearchType("web");

$qsearch = $searchanalytics->query("http://www.******", $request); 
$rows = $qsearch->getRows();

**Comment by minobedin** [comment]
I found the solution. The filter must be passed as array of object. I change this line:

$filtri->setFilters(array( $filtro ));

and

$request->setDimensionFilterGroups(array($filtri));


and now the code works

**Comment by phpgeekfr** [comment]
Thank you!
I had the exact same problem, filters were not taken into account.
I already tried to give an array of filters to "setFilters" but not to "setDimensionFilterGroups".

**Comment by PromInc** [comment]
Well done @minobedin - I was just struggling with this today as well, but your fix was just the trick!

**Comment by riconeitzel** [comment]
I'm very sorry but even the "array" code fix doesn't work at our end. Perhaps I just missed a crucial part, but here's my code and it looks like the one above!

```php
        $query = new Google_Service_Webmasters_SearchAnalyticsQueryRequest();
        $query->setAggregationType('byPage');
        $query->setSearchType('web');
        $query->setRowLimit('5000');
        $query->setDimensions(array('page', 'query', 'country', 'device'));
        $query->setStartDate($startDate);
        $query->setEndDate($endDate);

        $filter = new Google_Service_Webmasters_ApiDimensionFilter();
        $filter->setDimension('device');
        $filter->setOperator('equals');
        $filter->setExpression('Mobile');

        $filtergroup = new Google_Service_Webmasters_ApiDimensionFilterGroup();
        $filtergroup->setGroupType('and');
        $filtergroup->setFilters(array($filter));
        $query->setDimensionFilterGroups(array($filtergroup));

        $response = $service->searchanalytics->query('https://www.••••••••••••.de/', $query);
```

Thanks for your second pair of eyes.

Rico

**Comment by PromInc** [comment]
In my experience, I could never get filter groups to work.  Though I couldn't figure out how to get it to work in the (https://developers.google.com/apis-explorer/#p/webmasters/v3/webmasters.searchanalytics.query)[api explorer] either.  (If you have tips on how to set the group I'd appreciate any tips!)

That said, my guess without testing your code is that the block group is the issue:
```
$filtergroup = new Google_Service_Webmasters_ApiDimensionFilterGroup();
$filtergroup->setGroupType('and');
$filtergroup->setFilters(array($filter));
$query->setDimensionFilterGroups(array($filtergroup));
```

**Comment by riconeitzel** [comment]
are you accessing the API with a machine (server-to-server) user or your real G-user account?!

**Comment by PromInc** [comment]
I do a server to server connection.

Here are the steps I'm using to create the account, as well as my full repository for accessing the API.
https://github.com/PromInc/organic-search-analytics

For reference, the script that builds my API call is organic-search-analytics/inc/code/dataCapture.php

You'll notice thought that I am not using DimensionFilterGroups - I haven't been able to get them to work in the API explorer and thus was not able to verify that they work in my API script.

That said, when I was testing with the groups I believe I would get an empty response - not an error.  What is the response you are getting?  Is there an error code associated?

**Comment by cjmling** [comment]
@minobedin  Thanks That worked for me :+1:

**Comment by tmatsuo** [comment]
Closing, please reopen if it's still an issue

**Comment by nisarkhalid** [comment]
here is my sample code working with single filter and multiple filters using PHP

`/*'dimFilter'    => array(
    'dimensionName' => 'ga:browser',
    'operator'      => 'EXACT',
    'expression'   => 'Safari'
),*/

'dimFilter'    => array(

    'filters' => array(
        array(
            'dimensionName' => 'ga:browser',
            'operator'      => 'EXACT',
            'expression'   => 'Chrome'
        ),
        array(
            'dimensionName' => 'ga:medium',
            'operator'      => 'EXACT',
            'expression'   => 'organic'
        ),
        array(
            'dimensionName' => 'ga:country',
            'operator'      => 'EXACT',
            'expression'   => 'Pakistan'
        ),
        array(
            'dimensionName' => 'ga:operatingSystem',
            'operator'      => 'EXACT',
            'expression'   => 'Windows'
        )
    )
),`


here is PHP code 
`if (isset($param['dimFilter']) && isset($param['dimFilter']['dimensionName']) && isset($param['dimFilter']['operator']) && isset($param['dimFilter']['expression'])) {

        $filter = new Google_Service_AnalyticsReporting_DimensionFilter();

        $filter->setDimensionName($param['dimFilter']['dimensionName']);
        $filter->setOperator($param['dimFilter']['operator']);
        $filter->setExpressions($param['dimFilter']['expression']);

        if (isset($param['dimFilter']['exclude'] ))
            $filter->setNot($param['dimFilter']['exclude']);

        $filter_clause = new Google_Service_AnalyticsReporting_DimensionFilterClause();
        $filter_clause->setFilters($filter);

        $filtersGroup = $filter_clause;



    }else if(isset($param['dimFilter']['filters'])){

        $filtersGroup = array();
        foreach( $param['dimFilter']['filters'] as $filter ) {

            $dimensionFilter = new Google_Service_AnalyticsReporting_DimensionFilter();
            $dimensionFilter->setDimensionName( $filter['dimensionName'] );
            $dimensionFilter->setOperator( $filter['operator'] );
            $dimensionFilter->setExpressions( $filter['expression'] );

            /*if (isset($param['dimFilter']['exclude'] ))
                $filter->setNot($param['dimFilter']['exclude']);*/

            $filter_clause = new Google_Service_AnalyticsReporting_DimensionFilterClause();
            $filter_clause->setFilters($dimensionFilter);

            $filtersGroup[] = $filter_clause;
        }
    }`


setting up request
$request->setDimensionFilterClauses($filtersGroup);

**Comment by kennblvnp** [comment]
Is this your own class, "Google_Service_Webmasters_ApiDimensionFilterGroup"?
