### ISSUE TITLE
Autoloader.php not compatable with PHP version 5.2.1 or greater.

### ISSUE THREAD

**Issue by enzommx** [google/google-api-php-client#642]
As stated in the requirements PHP version 5.2.1 or greater. The autoloader (in Google/autoloader.php) will not work.

Here is the fixed autoloader function.

```
function autoloader ($className) {
  $classPath = explode('_', $className);
  if ($classPath[0] != 'Google') {
    return;
  }
  // Drop 'Google', and maximum class file path depth in this project is 3.
  $classPath = array_slice($classPath, 1, 2);

  $filePath = dirname(__FILE__) . '/' . implode('/', $classPath) . '.php';
  if (file_exists($filePath)) {
    require_once($filePath);
  }
}
```

spl_autoload_register('autoloader');

**Comment by DavidAnderson684** [comment]
I wanted to ask about this also, as I am using the SDK as part of a WordPress plugin - WordPress supports PHP 5.2.4 onwards. (I know: nobody sane should be using PHP 5.2 now... but sadly, it's still out there, and if you have a 500,000 install base on a WP plugin, there are plenty of people who'll complain if it breaks...)

David

**Comment by enzommx** [comment]
Yup, I see what you are saying.  How I discovered this problem (and the fix) was via this PHP article on the spl_autoload_register function: http://php.net/manual/en/function.spl-autoload-register.php 

Scroll down to the Example 1, and you'll see where it talks about this.

**Comment by bshaffer** [comment]
This file has been removed in favor of composer autoloading, so this issue is no longer relevant.
