### ISSUE TITLE
Generated URL has an extra forward slash?

### ISSUE THREAD

**Issue by gauntface** [google/google-api-php-client#645]
I'm trying to use the Cloud Storage API in the PHP library and I'm getting the following error:

Type: Google_Service_Exception

Message: Error calling POST https://www.googleapis.com//upload/storage/v1/b/gauntface-site-uploads/o?name=download.png&uploadType=multipart: (400) Uploads must be sent to the upload URL. Re-send this request to https://www.googleapis.com/upload/storage/v1/b/gauntface-site-uploads/o?name=download.png&uploadType=multipart

I've looked through the code and there are two places I can think of that could be tweaked to fix this issue.

https://github.com/google/google-api-php-client/blob/master/src/Google/Http/MediaFileUpload.php#L241

or

https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Storage.php#L62

I don't know the library well enough to say which would be the best, or whether there is something else that should be happening to make everything consistent.

Happy to make a PR if anyone can direct me on the right solution.

**Comment by apothan** [comment]
Getting the same issue when I have updated this lib. How did you solve it?

**Comment by ktello** [comment]
Same here, hopefully this gets solved soon

**Comment by apothan** [comment]
This is no longer a bug in v2. This can potentially be closed. I am not sure if v1 will still be maintained.
