### ISSUE TITLE
[question] `Google_Auth_Exception` in `Google_Auth_OAuth2`

### ISSUE THREAD

**Issue by s-chizhik** [google/google-api-php-client#649]
Hi! I'd like to ask about `Google_Auth_OAuth2` class. There are a couple of methods, like `authenticate` and `refreshTokenRequest`, where all http errors interprets as `Google_Auth_Exception`. Is it normal practic? I guess it will be more conveniently to separate different kinds of exceptions. For example `Google_Auth_Exception` will be thrown for errors, like `Code was already redeemed.`, `Malformed code.`, `Invalid code.`, but not for internal errors, such as `internal_failure` with 500 code. My general idea is to add ability to handle different error cases in applications, so maybe improve logging(just needed cases), user communications(separate user problem and client), etc.

**Comment by bshaffer** [comment]
These classes have been refactored in favor of [google/auth](https://github.com/google/google-auth-library-php). Please use `v2` and see if your issue is resolved.
