### ISSUE TITLE
Class 'stdClass' not found

### ISSUE THREAD

**Issue by atrauzzi** [google/google-api-php-client#650]
I just recently started encountering the error `Class 'stdClass' not found` which is originating from [line 132 of the Model class](https://github.com/google/google-api-php-client/blob/master/src/Google/Model.php#L132).

This error happens when trying to run on Google App Engine and as a result, I'm really unable to infer any more details about the problem.  The only obvious thing is that PHP is likely expecting this class name to be fully qualified.

Although why this is happening when the whole library is not namespaced escapes me.

Here's the visual representation of the error I get from my app:

![image](https://cloud.githubusercontent.com/assets/115199/9559905/729a325a-4dc3-11e5-8330-dbd25f3efc1f.png)

There's no further stack trace as it's a fatal PHP error and there is nothing really to report except that an attempt to resolve an unqualified class was made in the Google library.

**Comment by samuelwilliams** [comment]
What version of PHP are you running?

**Comment by atrauzzi** [comment]
5.5 on GAE and 5.6 locally.

**Comment by atrauzzi** [comment]
I manually deployed some diagnostic code to GAE which contained the following:

`var_dump(__NAMESPACE__);`

...just prior to the line in question.  The value is coming back as `""`, so PHP does not think it's in any particular namespace at the moment.

**Comment by sjlangley** [comment]
Maybe add this line just before to help you debug:

syslog(LOG_DEBIUG, 'Defined classes: ' . print_r(get_declared_classes(), true));

**Comment by atrauzzi** [comment]
@sjlangley - I don't know why, but when I go between curl lite and regular curl, the issue goes away...  I'll be updating our google issue tracker ticket.

**Comment by atrauzzi** [comment]
@sjlangley @samuelwilliams - Any progress on this issue?  Running into it again trying to launch my app.

**Comment by cdman** [comment]
There seems to be some kind of memory corruption issue, possibly related to loading curl.so on GAE. See https://code.google.com/p/googleappengine/issues/detail?id=12451

**Comment by ijt** [comment]
@atrauzzi can you point to some code that reproduces this issue?

**Comment by bshaffer** [comment]
We believe this issue has now been fixed. Please open a new issue if this is not the case.

**Comment by cdman** [comment]
I don't think this is fixed - see https://issuetracker.google.com/issues/35899850 where the code.google.com issue was migrated - and which is still marked as an unsolved bug.

Then again, the issue is most probably not related to google-api-php-client but rather to some memory corruption in the Google Appengine Standard PHP runtime.

**Comment by ijt** [comment]
Hi Attila, I deployed your test case to
https://b35899850-php-structures.appspot.com
<https://www.google.com/url?q=https://b35899850-php-structures.appspot.com/&sa=D&usg=AFQjCNESDgJTNALFvHcDgmY1mo4CN4F5FQ>
and
it seems to be working. If you find that this is still a problem, please
send a reproducing test case and I will look into it.
