### ISSUE TITLE
URGETNT: 'Google_IO_Exception' with message 'HTTP Error

### ISSUE THREAD

**Issue by codeartist254** [google/google-api-php-client#655]
Hello guys, I hope you can help me. I'm having a hard time in debugging google QPX Express error. I am creating a travel agent website. One of the feature of the site is flights search engine. Now  I can't figure the real issue here:

Uncaught exception 'Google_IO_Exception' with message 'HTTP Error: Unable to connect: 'fopen(compress.zlib://https://www.googleapis.com/qpxExpress/v1/trips/search?key=X): failed to open stream: operation failed'' in F:\xampp\htdocs\web\flight\apis\Google\IO\Stream.php:141 Stack trace: #0 F:\xampp\htdocs\web\flight\apis\Google\IO\Abstract.php(136): Google_IO_Stream->executeRequest(Object(Google_Http_Request)) #1 F:\xampp\htdocs\web\flight\apis\Google\Http\REST.php(60): Google_IO_Abstract->makeRequest(Object(Google_Http_Request)) #2 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request)) #3 F:\xampp\htdocs\web\flight\apis\Google\Task\Runner.php(174): call_user_func_array(Array, Array) #4 F:\xampp\htdocs\web\flight\apis\Google\Http\REST.php(46): Google_Task_Runner->run() #5 F:\xampp\htdocs\web\flight\apis\Google\Client.php(593): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request)) #6 F:\xampp\htdocs\web\fl in F:\xampp\htdocs\web\flight\apis\Google\IO\Stream.php on line 141

where X is the App Key.

**Comment by Kirkis** [comment]
Hi
Did you try the fix suggested in issue #571?

**Comment by bshaffer** [comment]
This is no longer relevant, as the `IO` classes were removed in `v2`.
