### ISSUE TITLE
orderBy parameter is not available in client libraries PHP

### ISSUE THREAD

**Issue by hiddenpearls** [google/google-api-php-client#656]
Hello,

I am playing with Google Drive SDK and noticed that PHP Client libraries doesn't have implementation of orderBy parameter like in API explorer https://developers.google.com/drive/v2/reference/files/list#try-it

I am getting below error

Uncaught exception 'Google_Exception' with message '(list) unknown parameter: 'orderBy''

**Comment by tpnprins** [comment]
Same here! Would be great if this is implemented.

**Comment by hiddenpearls** [comment]
Yeah!

On Thu, Sep 10, 2015 at 2:25 AM, tpnprins <notifications@github.com> wrote:

> Same here! Would be great if this is implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-php-client/issues/656#issuecomment-139050318>
> .
>



-- 
Muhammad Adnan
twitter: @hiddenpearls <http://www.twitter.com/hiddenpearls>
I blog too do u know ?  adnan.pk <http://www.adnan.pk/>
Failure takes you higher than success ..!

http://www.youtube.com/watch?v=HbEpeiYdzh8

**Comment by bshaffer** [comment]
added in https://github.com/google/google-api-php-client/pull/666

**Comment by bshaffer** [comment]
The PR of the Beast

**Comment by hiddenpearls** [comment]
awesome!

On Thu, Sep 10, 2015 at 9:38 PM, Brent Shaffer <notifications@github.com>
wrote:

> The PR of the Beast
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-php-client/issues/656#issuecomment-139305029>
> .
>



-- 
Muhammad Adnan
twitter: @hiddenpearls <http://www.twitter.com/hiddenpearls>
I blog too do u know ?  adnan.pk <http://www.adnan.pk/>
Failure takes you higher than success ..!

http://www.youtube.com/watch?v=HbEpeiYdzh8

**Comment by tpnprins** [comment]
Thanks!

**Comment by hugohuynh** [comment]
This one cost me a lot of time to debug. Please support orderBy. Thanks

**Comment by bshaffer** [comment]
The fix for this has been merged and tagged in 1.1.5

**Comment by jonyking** [comment]
The problem is also available in the latest version.
