### ISSUE TITLE
Page won't display after oAuth callback...

### ISSUE THREAD

**Issue by jeremyhodges** [google/google-api-php-client#657]
Trying to go through the quickstart guide to get the Google Analytics API working via PHP (https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/web-php). While the page loads and jumps over to Google for authorization, the callback page won't load when it comes back from Google: `oauth2callback.php?code=4/xvilrDCNpY6MpFd6cqe2OoWNINiodiZCC0iyX8ZtNtM#`

I just get the following from Chrome and no PHP errors or anything:

> No data received
> ERR_EMPTY_RESPONSE

**Comment by tmatsuo** [comment]
I don't think it's library's bug
