### ISSUE TITLE
Google_Http_MediaFileUpload::resumeUri needs to be public/gettable to resume from a different process

### ISSUE THREAD

**Issue by DavidAnderson684** [google/google-api-php-client#658]
Explained in https://github.com/google/google-api-php-client/issues/143#issuecomment-40210269 - still a live issue for me.

I would create a patch with a getResumeUri() method, but there's already a method with that name that does something else. Ideas?

David

**Comment by DavidAnderson684** [comment]
My code also has to set Google_Http_MediaFileUpload::progress in order to resume, so that has to be settable too.

**Comment by bshaffer** [comment]
Fixed in #675
