### ISSUE TITLE
Curl issue on API

### ISSUE THREAD

**Issue by paultebbatt** [google/google-api-php-client#660]
This is more of a heads up than an issue, hope that is ok.

All of a sudden my analytics stop working and was getting blank screen trying to access the api. 

This issue was solved by changing the ssl type in the Curl.php from 1 to 3. on line 77.

curl_setopt($curl, CURLOPT_SSLVERSION, 3);

Just incase anyone gets this issue.

**Comment by eRadical** [comment]
This was already discussed in Case #639 and addressed in Pull Request #644 .

**Comment by bshaffer** [comment]
This is no longer relevant, as the `Curl.php` class has been removed in favor of `guzzlehttp/guzzle`
