### ISSUE TITLE
Handling multiple google signed-in users using oAuth

### ISSUE THREAD

**Issue by nebadom** [google/google-api-php-client#661]
I have this app that uses data from gmail accounts. I have been able to create a php site that retrieves the oAuth tokens (online and offline) and later the necessary user information from the mailbox, all using the Google php api. Now to my problem:

When a secondary user logs into gmail in a browser that was previously used by an authorized user, the credentials seems to "stay". So the 2nd (or 3rd or nth user) can see data non-related to them, which becomes a security hole. But most important: every loged in user into gmail is seeing only the data of the 1st logged in user.

The question: Is there a way I can use Google PHP API or Google JavaScript API to retrieve ONLY the session data of the account requesting it? 

For example:

https://mail.google.com/mail/u/0/# - user 1
https://mail.google.com/mail/u/1/# - user 2
https://mail.google.com/mail/u/2/# - user 3

This is the current php piece of code I've been using to retrieve the user data:

```
 use google\appengine\api\users\User;
 use google\appengine\api\users\UserService;

 session_start(); 

 $user = UserService::getCurrentUser();
 $userEmail = htmlspecialchars($user->getEmail());
```

What I want is that if a user has several gmail accounts, I can tell wich of these accounts is accessing MY app. But most importantly, that ALL of these accounts can access my app and not just one.

Any ideas or suggestions are welcome.

**Comment by nebadom** [comment]
I have made a change in the app.yaml so every logged in user in gmail gets served a different uri from my app. That works. Now I face a new issue: how can I make the PHPSESSID and SACSID cookies to use an specific path instead of the whole domain?

I've read the whole documentation about the UserService but it seems all I can do is redirect to this:

UserService::createLoginURL($_SERVER['REQUEST_URI']);

And that takes care of the authentication. How can I restringe the scope so the cookies gets the appropriate path?

**Comment by nebadom** [comment]
Today I started to expirience a lot of issues regarding the session authentication: $_session is empty and it does not stay on, constantly requiring authentication unless I use the app.yaml login:require.

NOTE: I've been using PHP API v1.1.5. I've seen that there are more updates recently.

Does anyone nows if there has been a recent change regarding session_start() or anything that can give a hint of what have change recently? #

**Comment by nebadom** [comment]
I had this issue "kind of" solved assigning a SACSID cookie to individual path in my server, so each concurrent user would get served a different "folder", each with an unique SACSID cookie.

Then, on monday this week everything started to fail. The `session_start()` would not recognize but the base site SACSID, allowing one and only one user at-a-time to access my app.

Does anyone, really, anyone knows how to allow multiple signed-in users? Any tips?

**Comment by antonioperic** [comment]
@nebadom you can use 
https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=your_token

**Comment by ashishkmishra95** [comment]
did you resolve your issues, I'm trying to save login info and when i select one account it mail with that account not for default
