### ISSUE TITLE
verifyIdToken method takes very long to execute

### ISSUE THREAD

**Issue by ekr3peeK** [google/google-api-php-client#663]
I am working on a dynamic website, which relies heavily on ajax calls. I've noticed that when I load in my front page, and try to access the main search box on this page, it takes 5-7 seconds until the ajax request completes which populates the main search box. I've managed to figure out that delay is being caused by the Google API PHP Library, which starts as soon as the HTML of my page is loaded, to try to authenticate the visiting user. I've benchmarked the script in parts, and figured out, that the problem is in the "verifyIdToken" method of the library, which to complete, takes around 5 seconds. Is this normal behaviour for this method to take this long to complete? 

I've noticed that in the documentation and tutorials, you say: "The library will automatically download and cache the certificate required for verification, and refresh it if it has expired."

Is this the standard behaviour, or I have to set this somewhere? If it is the standard behaviour, how could I check if the caching actually happens or not?

**Comment by bshaffer** [comment]
@ekr3peeK the method [`verifyIdToken`](https://github.com/google/google-api-php-client/blob/master/src/Google/Auth/OAuth2.php#L481) does not appear to have any caching. Although you could add your own caching by saving [the certificates](https://www.googleapis.com/oauth2/v1/certs) to a local file and then pointing to them in the client config:

```php
$client->setClassConfig('Google_Auth_OAuth2', 'federated_signon_certs_url', '/path/to/certs.json');
```

A better method would be to use the new [`google/auth`](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L302) library, and call the `verifyIdToken` method there without any arguments like this:

```php
$oauth = new Google\Auth\OAuth2(['id_token' => $idToken]);
$payload = $oauth->verifyIdToken();
```

**Comment by ekr3peeK** [comment]
I've tried the manual caching, which solved the problem with the long execution time of the verifyIdToken method, but now, my curl request to get the userinfo(https://www.googleapis.com/userinfo/v2/me) takes around 4 seconds.

Strangely, when I first started debugging my functions, my first tought was that the long execution time of the script comes from this curl request, and now, it really does come from here.

But I can't understand why:|

So, before cached certs, verifyIdToken took around 5 seconds, but the curl request didn't take up more than a second, now, with cached certs, verifyIdToken takes around 0.01 second to execute, while the curl requests execution time was raised to 5 seconds.

I will try your other suggested method also.

**Comment by ekr3peeK** [comment]
The problem was on my side, everything works fine now. If anyone is facing simmilar problems, while curl-ing www.googleapis.com, check that curl can correctly resolve the DNS or not.

**Comment by bshaffer** [comment]
@ekr3peeK what did you do to fix the problem? Also please close the issue if there is no work left to be done

**Comment by ekr3peeK** [comment]
The problem was, not with the php-api but with php's curl function, because it took 5 seconds for it to resolve the DNS when I was trying to access www.googleapis.com. I added "curl_setopt($curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);" to my code, and this solved the problem.

Here's a stackoverflow, related to the problem, thank you for taking the time and trying to help me out here:)

http://stackoverflow.com/questions/32481611/curl-from-php-takes-more-time-than-curl-via-putty?noredirect=1#comment52826922_32481611
