### ISSUE TITLE
Matching filename and classname

### ISSUE THREAD

**Issue by thatisuday** [google/google-api-php-client#667]
I am using website in which I have implemented autoloading of files with filename same classname they represent. In this case, google class name starts with 'Google_' making class name like 'Google_xxx'  but filename is just 'xxx'. That is creating huge problems in existing setup as we can not implement nested autoloading. Twitter, facebook, instagram done it well, I don't know why Google plus didn't think this through.

**Comment by bshaffer** [comment]
@thatisuday this is following the PHP code standard [PSR-0](http://www.php-fig.org/psr/psr-0/) (see the section "Underscores in Namespaces and Class Names")

Use [`composer`](getcomposer.org) or just include the library's autoloader to your front controller or autoload script:

```php
require '/path/to/google-api-php-client/autoload.php';
```
