### ISSUE TITLE
Fatal error: Class 'Google_Cache_File' not found 

### ISSUE THREAD

**Issue by timint** [google/google-api-php-client#676]
**Fatal error: Class 'Google_Cache_File' not found in ~/google-api-php-client-master/src/Google/Client.php on line 641**

Happens right after initiating the autoloader:
```require_once 'path/to/google-api-php-client-master/src/Google/autoload.php';```

Using the example code for HelloAnalytics found on https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php

Using the master as of todays date 2015-09-16.

**Comment by bshaffer** [comment]
I downloaded the file, cloned the repo, and the `Google_Cache_File` class was picked up by the autoloader just fine.

Is it possible you've accidentally renamed that file or the class inside it?

**Comment by timint** [comment]
No Sir. Uploaded as is. The file File.php is in it's Cache folder untouched. I will do some more debugging tomorrow what's going on inside the autoloader. I wil also checkout a new build. Stay tuned.

**Comment by timint** [comment]
Invalid issue ticket. The FTP software skipped transfering folders named cache/.

**Comment by bshaffer** [comment]
How smart of it to do that :P

**Comment by timint** [comment]
This is one of those times when something very smart out of one aspect is not the brightest idea out of another. :~ A big apreciation for the fast replies. I am back on track and it's all rolling fine.
