### ISSUE TITLE
$file->getDownloadUrl() returns null always

### ISSUE THREAD

**Issue by hiddenpearls** [google/google-api-php-client#678]
I am not able to download the files from $file object. Title and other attributes works fine but $file->getDownloadUrl() doesn't return anything.

**Comment by bshaffer** [comment]
Can you post some of your code here so we can help you debug the issue? We have more than one API that uses `getDownloadUrl`

**Comment by hiddenpearls** [comment]
Here is my function that lists all the files and then I am trying to get downloadURL but it is empty in returned Object as well.


function listAllFiles($driveService){

	$parameters = array(
		'maxResults' => '10'
		);

	//$_GET['action']

  	$results = $driveService->files->listFiles($parameters);

  	echo '<table>';

  	foreach($results->getItems() as $file){

  		formatPre(json_encode($file->getDownloadUrl())); 
  		
  		echo '<tr><td><img src="'. $file->iconLink .'"/> ' . $file->title . '</td><td><a href="' . $file->alternateLink . '" target="_blank">View</a> <a href="?action=download">Download</a> <a href="?action=trash">Trash</a> </td><td><a href="?action=delete">Delete</a></td></tr>';
		
  	}

  	echo '</table>';
}

**Comment by tmatsuo** [comment]
Is this related?
http://stackoverflow.com/questions/34717916/android-google-drive-api-getdownloadurl-return-null

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by hiddenpearls** [comment]
Hey @mattwhisenhunt 
I worked on this thing couple of years ago. I am not sure if this issue is still valid or not. You can test it in the current codebase and continue ;)

Cheers!

**Comment by loicgirard** [comment]
In the appscript.json of my Google App Script project, I have this scope but it still resturns null ...

```json
  "oauthScopes": [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/drive.readonly",
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file",
    "https://www.googleapis.com/auth/script.external_request"]
```
