### ISSUE TITLE
Filter results with DimensionFilterGroups doesn't work

### ISSUE THREAD

**Issue by riconeitzel** [google/google-api-php-client#682]
I'm trying to filter the result set of a query with a filter ground containing a filter.

The code below returns the same result set as the same query without the filter group and filter

``` php
        $query = new Google_Service_Webmasters_SearchAnalyticsQueryRequest();
        $query->setAggregationType('byPage');
        $query->setSearchType('web');
        $query->setRowLimit('5000');
        $query->setDimensions(array('page', 'query', 'country', 'device'));
        $query->setStartDate($startDate);
        $query->setEndDate($endDate);

        $filter = new Google_Service_Webmasters_ApiDimensionFilter();
        $filter->setDimension('device');
        $filter->setOperator('equals');
        $filter->setExpression('Mobile');

        $filtergroup = new Google_Service_Webmasters_ApiDimensionFilterGroup();
        $filtergroup->setGroupType('and');
        $filtergroup->setFilters(array($filter));

        $query->setDimensionFilterGroups(array($filtergroup));

        $response = $service->searchanalytics->query('https://www.••••••••••••.de/', $query);
```

The postBody created for this query is identical to the one that you can create with the API Explorer (TRY IT!™) but the result is different.

One reason (never tested it) might be the fact, that I'm using a server-to-server-account created in the API console. Another reason could be that the API distinguishes real world and try-it™ requests …

I have no idea and all tricks with array indizes or no arrays at all or specifying the postbody manually didn't work.

Right now I think there is a server-side problem and not a problem in the PHP Library.

Rico

**Comment by alinr** [comment]
I face the same problem. @riconeitzel: did you find a workaround for this?
