### ISSUE TITLE
Use Guzzle Parser instead of our own

### ISSUE THREAD

**Issue by bshaffer** [google/google-api-php-client#686]
We could possibly implement the URITemplate logic using [guzzle3/parser](https://github.com/Guzzle3/parser/blob/master/UriTemplate/UriTemplate.php). We currently use our own `Google_URITemplate` class, and it works great, but consolidating them would mean less code in the universe, which is a good thing.

**Comment by mtdowling** [comment]
Guzzle 3 code is basically unmaintained at this point (I'm the author). If you want to use this code, it might be better to fork it or vendor it. Alternatively, the PSR-7 stuff newer versions of Guzzle uses has the parser as well:

- https://github.com/guzzle/psr7/blob/master/src/functions.php#L440
- https://github.com/guzzle/psr7/blob/master/src/functions.php#L468
