### ISSUE TITLE
Issue with curl requests

### ISSUE THREAD

**Issue by jfosnight** [google/google-api-php-client#689]
I was experiencing the same issue as #663 (verifyIdToken takes long time to load) and as suggested was able to resolve the issue by changing the Curl.php file of the Google Api.  (https://github.com/google/google-api-php-client/blob/master/src/Google/IO/Curl.php)

I placed the code change on line 80, but anywhere within that section should work.  The line (as suggested in the other bug report) was `curl_setopt($curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);`  Adding this single line immediately fixed my problem with the API hanging while trying to use it.  (The hanging only manifested itself after 5 minutes of inactivity on the server, as I imagine that was when the DNS timed out.)

I would like to suggest incorporating this change into the API codebase, as the almost 5 second lag time caused by the DNS issue is quite annoying, and having to manually modify the API client is messy.

**Comment by gonzzza007** [comment]
Yes, it would be nice to be able to set such setting for the API. Currently we have to alter the source code.

**Comment by bshaffer** [comment]
Closing, as the IO classes have been removed in favor of `guzzlehttp/guzzle` in `v2`.
