### ISSUE TITLE
OAUTH2_ISSUER can either be 'accounts.google.com' or 'https://accounts.google.com'

### ISSUE THREAD

**Issue by cartland** [google/google-api-php-client#698]
According to https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken, the `iss` can have one of two values:

"Verify that the value of `iss` in the ID token is equal to `accounts.google.com` or `https://accounts.google.com`."

The `OAUTH2_ISSUER` used in `Google_Auth_OAuth2` is currently a single constant: `'accounts.google.com'`.
https://github.com/google/google-api-php-client/blob/b90b9d530148533ecbe234c7c57c1a9010987132/src/Google/Auth/OAuth2.php#L34

According to the above definition, the client library should accept either issuer.

**Comment by bshaffer** [comment]
see #697
