### ISSUE TITLE
Add support for beta Compute Engine API

### ISSUE THREAD

**Issue by DicsyDel** [google/google-api-php-client#703]
Discovery link: https://www.googleapis.com/discovery/v1/apis/compute/beta/rest

Thanks,
Igor

**Comment by bshaffer** [comment]
see #704 and #705 - these are now updated for [Compute API v1](https://www.googleapis.com/discovery/v1/apis/compute/v1/rest)

Note that `master` has changed significantly since #695, so you may want to update your library from `v1-master` instead.

**Comment by DicsyDel** [comment]
@bshaffer But there is no support for beta features (beta version), only for v1. How we can get support for beta version? (I've provided a link to the API: https://www.googleapis.com/discovery/v1/apis/compute/beta/rest). We need lables functionality.

Regards,
Igor

**Comment by bshaffer** [comment]
You can authenticate using the google/auth library directly and call the APIs directly with HTTP. This library can only support one version of the APIs at a time, so we support the most recent stable version.
