### ISSUE TITLE
Unable to load Google_Auth_AssertionCredentials in Laravel

### ISSUE THREAD

**Issue by bstump** [google/google-api-php-client#706]
I'm using this library in Laravel. Today I did a composer update and now I get error below and all of my Google Auth stuff is broken. I reverted to using "v1-master" for now and it works:

'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Google_Auth_AssertionCredentials' not found' in /path/to/app/Models/ModelName.php:129
Stack trace:
#0 {main}

**Comment by bshaffer** [comment]
As of this morning, `master` represents `v2` of this library, and `Google_Auth_AssertionCredentials` has been removed (see [UPGRADING.md](https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#google_auth_assertioncredentials-has-been-removed) for more info).

Are you following a blog/tutorial somewhere that we can update for the new version?

**Comment by bstump** [comment]
No, I just did a "composer update" and everything stopped working in my web application. Didn't see the upgrading.md file. Thanks!
