### ISSUE TITLE
Youtube: request a feed of another user's playlists

### ISSUE THREAD

**Issue by collectorofbones** [google/google-api-php-client#711]
API v2 supported requesting other (NON-AUTHENTICATED) user's playlist:

https://developers.google.com/youtube/2.0/developers_guide_protocol_playlists?hl=en
->
https://gdata.youtube.com/feeds/api/users/userId/playlists?v=2

but v3 allows get list only for authenticated user, atleast I haven't figured out other way. Alhtough .readonly scope is good, there is still need to access only public list of playlists (e.g user logs into system without need to grant access to private lists)

so, is there some way how to get user's public list of playlists or is this feature coming in near future? or for example youtube-public scope?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
