### ISSUE TITLE
$client->refreshTokenWithAssertion() is giving error

### ISSUE THREAD

**Issue by rahul9878** [google/google-api-php-client#717]
$client->refreshTokenWithAssertion() is giving error.
it gives following error

PHP Fatal error:  Uncaught exception 'LogicException' with message 'config parameter "signing_key" must be set to refresh a token with assertion' in /Users/CFADMIN/Work/googleanalytics/google-api-php-client/src/Google/Client.php:201
Stack trace:
#0 /Users/CFADMIN/Work/googleanalytics/google-api-php-client/src/Google/Client.php(190): Google_Client->fetchAccessTokenWithAssertion()
#1 /Users/CFADMIN/Work/googleanalytics/HelloAnalytics.php(27): Google_Client->refreshTokenWithAssertion()
#2 /Users/CFADMIN/Work/googleanalytics/HelloAnalytics.php(101): getService()
#3 {main}

can you please tell me why is giving error. and how to resolve this.

**Comment by bshaffer** [comment]
The library is complaining that you need to provide a signing_key config
parameter, have you tried this?

More instructions:
https://developers.google.com/api-client-library/php/auth/service-accounts

**Comment by rahul9878** [comment]
HI @bshaffer ,
All the documentation on google and other place uses some functions that are deprecated/removed like Google_Auth_AssertionCredentials() and if i use new functions in place of these deprecated functions then i get error(above). Is there not a latest documentation for this library? The documentation given by  you in the above comment also use that deprecated/removed functions. I am unable to use these new functions in correct way.

**Comment by bshaffer** [comment]
The other version has not been deprecated, `v2` is not considered stable so the documentation has not been changed.  I suggest checking out the `v1.1.6` tag of this library.

If you'd like to get this to work, try setting your signing key using:

 ```php
$client->setConfig('signing_key', $signingKey);
```

truthfully, this should be set automatically when `$client->setAuthConfig` is called. I'll look into making this change.

Thanks for bringing this to my attention!

**Comment by csengineer13** [comment]
Hmm.. I'm using a fresh pull of the latest, and I am experiencing the exact same issue.
