### ISSUE TITLE
Things to consider before 2.0

### ISSUE THREAD

**Issue by Nyholm** [google/google-api-php-client#719]
It has been a while since I looked at this repo. I see that you have done a lot of work and that is great!

I just read the [Upgrade.md](https://github.com/google/google-api-php-client/blob/master/UPGRADING.md) and there are some issues that I want you to reconsider. 

First of all, you start passing around the access token as an array instead of json. That is better, sure. But I believe it would be event better to create an `AccessToken` object. It will be easier to extend in the future and it gets easier to test. Say that we want a function like `AccessToken::createdAt` and return a `DateTime`. 

So.. not using an object will limit you in the future. 

--------

About Guzzle5; Apart from Guzzle5 is not the latest version of Guzzle, you should look into the [PHP-HTTP](https://github.com/php-http/httplug). With HTTPlug you can be independent of any transport library. They will soon release a stable version of the library. 

I hope you will address these issues and make adjustments before releasing 2.0.

**Comment by bshaffer** [comment]
@Nyholm I understand the desire for an AccessToken object, but arrays are simpler, which is why that decision was made. As for Guzzle, it would be great to have this library be compatible with Guzzle6. Unfortunately, because Guzzle6 breaks BC in almost every way with 5, and we are dependent on libraries which use 5, this is not a trivial change. We will track this in #720

**Comment by bshaffer** [comment]
Thanks for your feedback!

**Comment by Nyholm** [comment]
AccessToken: Fair enough. 

Guzzle. Please take a moment and reconsider. I understand from your answer that you have not looked into PHP-HTTP. 

First of, the solution suggested in #720 is wrong. Don't do that. It is insane that every package should make adapters for Guzzle5, Guzzle6, Buzz, Sockets etc etc. 

I'm telling you to make this library **independent** from all of these HTTP adapters. Yes, it might be a BC break but that's okey since it is a new major version. 

I am happy to help implementing PHP-HTTP if you want to.

**Comment by bshaffer** [comment]
Why do you think #720 requires adapters for other projects? It only would make this repo compatible with Guzzle 5 *or* Guzzle 6, and the user can decide which.

**Comment by Nyholm** [comment]
Sorry for the terminology missmatch. 
#720 suggest to do what AWS has done. They have created adapters (`GuzzleHandler`) for Guzzle5 and Guzzle6. It is a good pattern to do so. The problem is when you take this to a larger scale. AWS has two adapters, we have two adapters, package Foo has some adapters, package Bar has some more adapters.. Eventually there are a lot of different adapters, right?

PHP-HTTP is a set of packages that gathers all of these adapters. They are actually the next version of [Ivory Http Adaper](https://github.com/egeloen/ivory-http-adapter). 

Implementing PHP-HTTP, then we don't have to implement our own `Guzzle5Handler` or `Guzzle6Handler`. Every user of Google API client may choose for which transport library he/she want to use. 

The benefit of PHP-HTTP is that we do not have to bother with the transport anymore. We will not see issues like #720 when they ask us to implement a future Guzzle8 etc. We can also support users that can't install Guzzle5 because Guzzle6 is already installed.

**Comment by bshaffer** [comment]
I agree that Guzzle has created quite the pickle for all us dependent libraries. I'm not stoked about having to implement these adaptors. But the repo you linked has a single interface with a single method in it. Perhaps you could point me to some better documentation on how it works? 

For us to make this library dependent on yet another library (which I've never heard of until now) will require some (serious) vetting. Also, keep in mind our [auth library](https://github.com/google/google-auth-library-php) will need to follow suit.

**Comment by Nyholm** [comment]
Thank you for considering this. 

PHP-HTTP is under development and pieces are soon falling together for a stable release. I said the library is the next version of [Ivory Http Adaper](https://github.com/egeloen/ivory-http-adapter). It is pretty much Ivory but with [PSR-7](http://www.php-fig.org/psr/psr-7/) (which we want to support). Here is the [PSR-7 repo](https://github.com/php-fig/http-message).

You can find the documentation for PHP-HTTP here: http://php-http.readthedocs.org/en/latest/
(They just did a major update on the docs today)

**Comment by bshaffer** [comment]
FWIW we don't need to be compatible with every http library out there. We just need this library to work really well with at least one http client. The problem I'm most concerned with is libraries depending on Guzzle6 will get an unresolvable conflict when they include us.

Fortunately, if we implement #720, we should become `PSR7`-compatible in the process.

Thanks for your feedback and info. I'll continue to monitor the progress of PHP-HTTP.

**Comment by Nyholm** [comment]
Just let me know if you want any help implementing PHP-HTTP. I'm happy to contribute.

**Comment by Nyholm** [comment]
FYI, here is a implementation with PHP-HTTP for the LinkedIn library. The google library is far more complex but it just to give an example.  
https://github.com/Happyr/LinkedIn-API-client/blob/psr7/src/LinkedIn.php#L165

``` composer.json
require": {
        "php": ">=5.4",
        "php-http/httplug": "@dev",
        "php-http/client-implementation": "@dev",
        "php-http/discovery": "@dev"
    },
    "require-dev": {
        "php-http/guzzle6-adapter": "@dev",
    },

```

**Comment by dwsupplee** [comment]
> Users of your package will have to select a concrete adapter in their project to make your package installable. Best point them to the virtual package howto page.

The requirement of an additional dependency on the consumer of the package definitely gives me some pause.
