### ISSUE TITLE
Move unstable v2 out of master

### ISSUE THREAD

**Issue by brianhogg** [google/google-api-php-client#723]
Can the unstable v2 be moved to a separate branch (ie. v2-master) instead if it is not stable?  All the documentation (ie. https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php, https://developers.google.com/api-client-library/php/start/get_started) is broken without knowing to checkout the v1-master branch.

**Comment by bshaffer** [comment]
Thank you for bringing these to our attention! We will update the documentation to point to the stable `v1-master` version of this library.

**Comment by bshaffer** [comment]
in the meantime, if you run the following instead, you'll be set:

```
git checkout -b v1-master https://github.com/google/google-api-php-client.git 
```

**Comment by brianhogg** [comment]
No problem!  Yes I was able to switch branches no problem, just feels like it would be best to have the unstable version not be on the default/master branch.  But if you're able to update all the documentation everywhere that works too :)

**Comment by bshaffer** [comment]
the docs have been updated to point to `v1-master`. Hopefully this will help avoid confusion in the future!

Once `v2` is stable, we will switch the documentation back.
