### ISSUE TITLE
Class 'GuzzleHttp\Collection' not found in Client.php line 93

### ISSUE THREAD

**Issue by heradonbenin** [google/google-api-php-client#724]
hi , i just get the lastest version an get this error. how to solve. thanks

**Comment by heradonbenin** [comment]
i can't see the folder GuzzleHttp on the cloned repository

**Comment by bshaffer** [comment]
The latest version must have dependencies installed via composer. See [Upgrading](https://github.com/google/google-api-php-client/blob/master/UPGRADING.md#installation-now-uses-composer) for more information.

Alternatively, check out the previous version of this library, which does not have this requirement:

```
git clone -b v1-master https://github.com/google/google-api-php-client.git 
```
