### ISSUE TITLE
REST.php inconsistent naming of included URITemplate.php

### ISSUE THREAD

**Issue by martinlevington** [google/google-api-php-client#725]
In the /Http/REST.php file the include_once statement is as follows:-

require_once 'Google/Utils/URITemplate.php';

the file name is named    UriTemplate.php which on linux systems  causes an issue as the file is not found.

**Comment by bshaffer** [comment]
I believe someone must have added that requirement to your code, as the line you've mention does not appear in any of the current versions of this library.

**Comment by bshaffer** [comment]
see [here](https://github.com/google/google-api-php-client/blob/master/src/Google/Http/REST.php) and [here](https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Http/REST.php)

**Comment by martinlevington** [comment]
odd as the library was installed using composer.

as described here
https://developers.google.com/api-client-library/php/start/installation

**Comment by bshaffer** [comment]
Ahh yes, you must have been pointing to [v1.0.6-beta](https://github.com/google/google-api-php-client/tree/1.0.6-beta/src/Google/Utils) or another earlier version.

This is also strange since `URITemplate.php` is properly named in those versions. Whatever the case, I'm glad you could get the issue resolved.

**Comment by aylesworthDev** [comment]
I have run into this issue after downloading the 1.1.7 release, the file was named UriTemplate.php, but file_exists() was looking for URITemplate.php  (I var_dumped out the $classPath in the google_api_php_client_autoload() function). Renaming the file has fixed it.

**Comment by bshaffer** [comment]
The file is named correctly in your release [here](https://github.com/google/google-api-php-client/tree/1.1.7/src/Google/Utils).  I imagine this has to do with OSX's case-insensitive filesystem, the fact it was renamed to `UriTemplate.php` in `master`, and the way you're deploying from there to a linux machine.
