### ISSUE TITLE
Spreadsheet Service coming soon?

### ISSUE THREAD

**Issue by wstoettinger** [google/google-api-php-client#734]
Before I start to build something here, I just wanted to know if a Google Sheets Service is in the makings? 

I didn't find any library which could do the following: 
 1. Authentication using service accounts
 2. Not only read but also update Spreadsheets
 3. Work on Google App Engine

While @asimlqt built a great little library which can handle nr. 1, it can't update Sheets nor does it work on the App Engine 
https://github.com/asimlqt/php-google-spreadsheet-client

Zend Framework (which is referenced by the Google Data API in it's outdated Version 1.x) seems to be the other option but I can't seem to get service account authentication running nor does it work on App Engine either I think.

Shouldn't be too hard to put something together here. 

:question:

**Comment by bshaffer** [comment]
the [Script API](https://developers.google.com/apps-script/guides/rest/quickstart/php) is the recommended way to interact with Google Spreadsheets. Also the Drive API can be used to pull down and upload the files themselves.

**Comment by wstoettinger** [comment]
Thanks for the quick response! Am I assuming correctly, that this requires to set up an Apps Script project first? Maybe I'm getting it wrong, but this looks a bit too complicated to setup for such very basic needs. 

I'd basically just like to add rows to an existing spreadsheet or update them (with data from a registration form in this case, so much similar to what google forms does). This shouldn't be more complicated than selecting the spreadsheet/worksheet via name or id and sending an array for insert or update (of course the authentication has to happen before). 

Before Google shut down the username/password authentication, I used this neat library (it requires ZEND 1) which shows quite nicely how easily it could be done: http://www.farinspace.com/saving-form-data-to-google-spreadsheets/. Unfortunately it neither works with service accounts, nor on the GAE.

**Comment by bshaffer** [comment]
What you want should be easy to achieve with AppScript. But also you could
download the csv, add the rows, and upload the new csv with the Drive API.
