### ISSUE TITLE
Request body empty when using batch - V2 beta API

### ISSUE THREAD

**Issue by am63** [google/google-api-php-client#736]
Hi,

When batching Gmail API requests, such as "modify" requests for messages (setting/unsetting labels on messages), I noticed that with v2 beta API, the API returns a 500 server error.

By using some print_r statements in the v2 API source code, I have found that when using batch (Google_Http_Batch) containing POST requests with a body, the request effectively sent does not have any body. However, when NOT using batch calls, everything works fine. Further debugging shows that the request being batched is well constructed, and contains a body.

Having a look at the Google\Http\Batch.php source code (lines 77-81) :       
$body .= sprintf(
          '%s %s HTTP/%s',
          $request->getMethod(),
          $request->getResource(),
          $request->getProtocolVersion()
);

we can see that there's nothing to include the $request body (could be obtained by $request->getBody()).

It tried to figure out how it could be done (by refering to the request being sent by v1 API), with :
      $body .= sprintf(
          '%s %s HTTP/%s %s',
          $request->getMethod(),
          $request->getResource(),
          $request->getProtocolVersion(),
          $request->getBody() ? "\n\n" . $request->getBody():''
);

but I always encounter a 500 server error.

Please, anyone can have a look at this issue ? Thanks

**Comment by bshaffer** [comment]
Who needs that POST body anyway? Okay well I guess it is kind of important. 

Good catch. Can you update your code to #737 and see if this fixes it?

**Comment by am63** [comment]
Code updated with new Batch.php, everything works as expected ! Thanks.
