### ISSUE TITLE
service-account example; Fetching access token

### ISSUE THREAD

**Issue by csengineer13** [google/google-api-php-client#744]
I've been playing around with the RC, looking at examples, and digging through method calls. It looks like you can't retrieve an access token when using a service-account; is this true?

It looks like in the non-service-account examples, the two methods we use to get the access token are:

`fetchAccessTokenWithAuthCode` and
`refreshTokenWithAssertion`

The first requiring an authCode passed in from OAuth, and the second requiring a signing key be set before it can be used.

It may be worth noting that I can query data just fine, but `$client->getAccessToken();` returns no value.

**Comment by csengineer13** [comment]
It looks like this was taken care of here:

https://github.com/google/google-api-php-client/issues/717

Setting a composer dependency on v ^2@DEV seems to do the trick, while @RC is still broken for this.

**Comment by bshaffer** [comment]
@csengineer13 apparently our tag is broken on packagist because we're including a `v` in the version for the `google/auth` library. Once it's updated, 2@RC will work.

**Comment by bshaffer** [comment]
Okay, everything is updated. Please test with the @RC tag 

https://packagist.org/packages/google/apiclient#v2.0.0-RC2

**Comment by csengineer13** [comment]
@bshaffer Thanks for the quick turnaround :+1:
