### ISSUE TITLE
Google_Service_Analytics::management_accounts::listManagementAccounts() result is not right

### ISSUE THREAD

**Issue by ascalabro** [google/google-api-php-client#747]
When calling 

```
 $accounts = $analytics->management_accounts->listManagementAccounts();
```

as found in [documentation](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/accounts/list), `$accounts` contains all accounts which contain the app's `client_email` as an entry in their User Management section of Google Analytics Admin. In it's current state, `$accounts` is not limited to just the accounts that belong to the authenticated user, but rather all accounts which this app has been given access to. 
Before the recent upgrade, this function returned back **all accounts which belong to the authenticated user**

**Comment by LindaLawton** [comment]
As stated in the documentation [Accounts: list] (https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/accounts/list). Lists all accounts to which the user has access.  This is the current authenticated user.  Each request you send against the google api is against the authenticated user.   It has nothing to do with the authenticated applications access.  

Even the old legacy v2  [Account Feed](https://developers.google.com/analytics/devguides/config/mgmt/v2/mgmtFeedReference#accountFeed) The account feed is the entry point to all management information for the authenticated user.

This is something ingrained in OAuth and not related to the PHP client library.  If anything it would be related to the Google Analytics API. 

The results returned by the API are correct.

**Comment by ascalabro** [comment]
Your reply makes sense. When I downgrade to v1, it works as expected for me without changing any code, surprisingly. When calling the service from the OAuth2 playground it also works as expected.
That's why I suspect it must be internal code at fault. I will look more into why this is happening within the scope of this project and return.

**Comment by LindaLawton** [comment]
Tip:  [Account Summaries: list](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/accountSummaries/list)   will get back all the Accounts -> web properties -> and views that a user has access to in one call :)

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
