### ISSUE TITLE
composer download fail..

### ISSUE THREAD

**Issue by vacho** [google/google-api-php-client#750]
I run 

$ composer require google/apiclient:^2.0.0@RC 

This error appear:
  [Composer\Repository\RepositorySecurityException]                                                                                           
  The contents of http://packagist.org/p/provider-2014%2428f0c2279506e7aca4ad1bdeee6e6a9f41aeb8de001554de8ad5e8ddb48f8037.json do not match   
  its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

**Comment by bshaffer** [comment]
Hmm, it's probably because we updated the tag of `^2.0.0@RC` to point to a new SHA (notice the URL you provided does not exist). Try running:

```sh
$ composer clear-cache
```
