### ISSUE TITLE
Parse error in dependencies

### ISSUE THREAD

**Issue by tigerhawkvok** [google/google-api-php-client#757]
For `2.0.0rc2`:

`Parse error: syntax error, unexpected '[', expecting ')' in /path/to/lib/google-php-client/vendor/react/promise/src/functions.php on line 68`

Whoops .....

**Comment by tigerhawkvok** [comment]
Ahh, PHP 5.4 whereas my client's server is 5.3. Closing.

**Comment by bshaffer** [comment]
Check out the v1-master branch for Php 5.3 compatibility
