### ISSUE TITLE
Blog status

### ISSUE THREAD

**Issue by juloxrox** [google/google-api-php-client#758]
Hi everyone,

I'm talking about Blogger Service.
Does the function getStatus and setStatus work for you? It doesn't return / modify anything when using it.

<code>
$status = $service->blogs->get($blogId)->getStatus();
echo $status;
</code>

Can you help me to fix that?
By the way, what are the differents status values ? LIVE, DELETED and ?

Thanks !

**Comment by mattwhisenhunt** [comment]
I think those methods are still in the client library even though they have been removed from the latest version of the API itself: https://developers.google.com/blogger/docs/3.0/reference/

Were you able to find a different solution?

**Comment by mattwhisenhunt** [comment]
This issue will be addressed by a fix to [google-api-php-client-services#44](https://github.com/google/google-api-php-client-services/issues/44)
