### ISSUE TITLE
Incorrect url for channel stopping in Directory API

### ISSUE THREAD

**Issue by Faradei** [google/google-api-php-client#760]
I'm trying to use channels->stop() to unsubscribe from notifications about changes in domain:
$channel = new Google_Service_Directory_Channel();
$channel->id = $channel_id';
$channel->resourceId = $resource_id;
try
{
    $response = $service->channels->stop($channel);
}
catch (Exception $e)
{
    // error handling  
}
It returns: Error calling POST https://www.googleapis.com/admin/directory/v1//admin/directory_v1/channels/stop: (404) Not Found
Seems that the same problem in other client libraries: 
https://github.com/google/google-api-ruby-client/issues/251

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
