### ISSUE TITLE
Sandbox mode for Reseller Service

### ISSUE THREAD

**Issue by fedebalderas** [google/google-api-php-client#764]
Is there a way to use sandbox mode with PHP SDK without modify the Google_Service_Reseller class?? I'm working with Reseller Service.

If i'm right, servicePath would be "apps/reseller/v1sandbox/" instead of "apps/reseller/v1/"

Thanks in advance!

**Comment by mattwhisenhunt** [comment]
Don't modify, inherit!
```php
class Reseller_Sandbox_Service extends Google_Service_Reseller {
	public function __construct(Google_Client $client)
	{
		parent::__construct($client);
		$this->servicePath = 'apps/reseller/v1sandbox/';
	}
}
```
