### ISSUE TITLE
Problems uploading a video

### ISSUE THREAD

**Issue by dakiquang** [google/google-api-php-client#766]
Hi there, 

I'm using google/google-api-php-client version 1.1.6. And I got this problem when trying to upload new video to youtube with message (view my attached):

```
'Failed to start the resumable upload (HTTP 500: global, Backend Error)'
Stack trace:
#0 Google_Http_MediaFileUpload->getResumeUri()
```

This seems to be a problem with PHP Client Library of Google API from Google server. How can I fix that problem?

![2015-12-04_10h56_01](https://cloud.githubusercontent.com/assets/1046250/11581597/2da235d0-9a76-11e5-8e24-ceba1e2bc46a.png)

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
