### ISSUE TITLE
Contact Google regarding review process for public YouTube upload

### ISSUE THREAD

**Issue by verbruggenalex** [google/google-api-php-client#770]
Is there a Google developer that can refer me to a representative that can discuss a Drupal implementation for public YouTube uploads? The reason I'm asking here is because I cannot find an appropriate contact to ask my question.

I developed the following module: https://www.drupal.org/project/media_youtube_upload. So people can allow the public to upload videos to a sitewide YouTube account. But now it seems also private videos are flagged for inappropriate content and will result in a shutdown of your channel (https://productforums.google.com/forum/#!topic/youtube/ccvN9wAN1z0;context-place=forum/youtube).

I wish to speak to a representative that can discuss or inform me about the possibilities of a review process that allows for such an implementation to be successful.

**I wouldn't be asking this question here if I didn't already put two months work into this module. So please don't shoot me for not posting an API related issue.**

**Comment by bshaffer** [comment]
I won't shoot you, but this is not the proper place to be asking this question. I would ask this question on the youtube help forums or [file a bug](https://code.google.com/p/gdata-issues/issues/entry?template=YouTube%20(Defect%20Report)).
