### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by iwxfer** [google/google-api-php-client#772]
Next exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate' in D:\wamp\www\...\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:51

**Comment by bshaffer** [comment]
this is an environmental problem. See some ways to solve it [here](https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate)
