### ISSUE TITLE
getting cloud storage data

### ISSUE THREAD

**Issue by iftikhardirv** [google/google-api-php-client#774]
Hi,
I'm using bellow code to get cloud storage data but its give me error that login required but I'm already logged in

<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
// Load the Google API PHP Client Library.
require_once 'src/Google/autoload.php';

// grab the first argument

$projectId = "xxxxxx";

// Authenticate your API Client
$client = new Google_Client();
$client->setAuthConfigFile('client_secrets.json');
$client->addScope(Google_Service_Storage::DEVSTORAGE_FULL_CONTROL);

$storage = new Google_Service_Storage($client);

/**
 * Google Cloud Storage API request to retrieve the list of buckets in your project.
 */

$buckets = $storage->buckets->listBuckets($projectId);

foreach ($buckets['items'] as $bucket) {
  echo $bucket->getName();
}

**Comment by bshaffer** [comment]
It's possible your project ID is not the same as in `client_secrets.json`. Check the "project_id" property in the json file to make sure they're the same. 

It's also possible the user who downloaded the `client_secrets.json` file does not have access to cloud storage, and the credentials need to be downloaded by someone with full access to the project.
