### ISSUE TITLE
REQUEST FOR G DRIVE API V3 SUPPORT

### ISSUE THREAD

**Issue by SaradambalMunusamy** [google/google-api-php-client#775]
As per this https://developers.google.com/apis-explorer/#p/  link, one new version updated in **Drive Api** service as **v3**, so need to update drive file also from **v2** to **v3** which is located in https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Drive.php Line no.86.

I checked latest version of 1.1.6 Release, in this package the drive file not having current version **v3** 

Please fix ASAP

**Comment by SaradambalMunusamy** [comment]
Any updates regarding version issue,  we need API V 3 support drive in google-api-php-client immediately.

Please any one update.

**Comment by bshaffer** [comment]
Try including [this file](https://gist.github.com/bshaffer/9bb2cdccd315880ab52f) and you should be good to go.
