### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by sraul2015** [google/google-api-php-client#777]
Hi,

I was reading documentation to integrate Gmail API, came across user authentication link that is not working, this information is vital, kindly fix this. thanks.

Broken link URL:
https://developers.google.com/api-client-library/php/guide/aaa_oauth2_web

**Comment by bshaffer** [comment]
where is the broken link happening? Can you provide a link to the page where you found it?

**Comment by bshaffer** [comment]
This is probably the content you are looking for: https://developers.google.com/api-client-library/php/auth/web-app
