### ISSUE TITLE
Argument 1 passed to Google\Auth\OAuth2::fetchAuthToken() must be callable

### ISSUE THREAD

**Issue by verbruggenalex** [google/google-api-php-client#778]
I'm getting the following error when trying to connect to my YouTube account.

> Recoverable fatal error: Argument 1 passed to Google\Auth\OAuth2::fetchAuthToken() must be callable, object given, called in /var/aegir/platforms/mediayoutubeupload-7.41/sites/all/libraries/google-api-php-client/src/Google/Client.php on line 175 and defined in Google\Auth\OAuth2->fetchAuthToken() (line 442 of /var/aegir/platforms/mediayoutubeupload-7.41/sites/all/libraries/google-api-php-client/vendor/google/auth/src/OAuth2.php).

Apparently it chokes on this: $this->client->authenticate($code)

Could this have something to do with this commit: https://github.com/google/google-api-php-client/commit/778b1dcd462ee87ce9a15de98ec78914ceb113f3?

**Comment by verbruggenalex** [comment]
The authentication was working in RC1 and not anymore in RC2 if that helps narrow it down.

**Comment by dmatora** [comment]
i got this fixed by changing google/auth from latest to 0.4

**Comment by Philippus** [comment]
Thank you @dmatora ! This had us stumped for hours.

**Comment by bshaffer** [comment]
Aha, yes this is because `v2.0.0-RC2` checks out to `~v0.4`, which will update (unfortunately) to `v0.5` automatically, which is not backwards compatible.

I will try to update the tag to fix this

**Comment by bshaffer** [comment]
fixed in bc2f60271ef1042aaef8c8d3ca238613478fe4e9 and [`v2.0.0-RC3`](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC3) has now been created. Please update your dependencies and this will be fixed.
