### ISSUE TITLE
Missing  Google Knowledge Graph Search API Client

### ISSUE THREAD

**Issue by jakemcgraw** [google/google-api-php-client#780]
The documentation

```
https://developers.google.com/knowledge-graph/libraries
```

links to

```
https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Kgsearch.php
```

but that is an invalid link.

Additionally, I was unable to find `Kgsearch.php` in repository.

**Comment by mattwhisenhunt** [comment]
Thanks for the heads up. Looks like the correct link is https://github.com/google/google-api-php-client-services/blob/master/src/Google/Service/Kgsearch.php
