### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by Philippus** [google/google-api-php-client#783]
When trying to use this package in combination with a service account for Google Analytics we are running into google service exception.

 "error": "invalid_grant",
 "error_description": "Not a valid email."

Does anyone have an idea what might be causing this?

stacktrace:
PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message '{\n "error": "invalid_grant",\n "error_description": "Not a valid email."\n}\n' in /usr/www/dynamic/vendor/google/apiclient/src/Google/Http/REST.php:120\nStack trace:\n#0 /usr/www/dynamic/vendor/google/apiclient/src/Google/Http/REST.php(80): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Message\\Response), Object(GuzzleHttp\\Message\\Request))\n#1 [internal function]: Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Message\\Request))\n#2 /usr/www/dynamic/vendor/google/apiclient/src/Google/Task/Runner.php(181): call_user_func_array(Array, Array)\n#3 /usr/www/dynamic/vendor/google/apiclient/src/Google/Http/REST.php(56): Google_Task_Runner->run()\n#4 /usr/www/dynamic/vendor/google/apiclient/src/Google/Client.php(779): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Message\\Request), Array)\n#5 /usr/www/dynamic/vendor/google/apiclient/src/Google/Service/Resource.php(226): Google_Client->execute(Object(GuzzleHttp\\ in /usr/www/dynamic/vendor/google/apiclient/src/Google/Http/REST.php on line 120

**Comment by bshaffer** [comment]
Hmm... Can you paste the code for the call you're making? I believe that error happens when a `sub` is being requested that the service account does not have access to.

**Comment by Philippus** [comment]
Thanks @bshaffer for the help. We made a silly mistake, we were using the wrong e-mail address as the subject (...@company instead of ...@gmail.com)
