### ISSUE TITLE
Issue: Trying to access a Google Spreadsheet and I get this error: "message": "File not found

### ISSUE THREAD

**Issue by vikasmalhotra08** [google/google-api-php-client#787]
Hello

I have implemented a code using this library to access a Google Spreadsheet and update it based on data coming in from some where. 

When I run my code in one GAE account, it works fine and updates the sheet with data.

When I replicate the same process in another GAE account, I get the error of file not found.

I have tried to delegate the roles, create new service accounts and get new client secrets.

I have already changing the project and it still does not work.

**Comment by mattwhisenhunt** [comment]
@vikasmalhotra08, are you still searching to a solution to this issue?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
