### ISSUE TITLE
Google Contacts API

### ISSUE THREAD

**Issue by intekhabrizvi** [google/google-api-php-client#791]
Hi, is there any documentation or help available for capture Google contacts data?? There is no example to call or capture data from google contacts.

**Comment by Marius2805** [comment]
It seems that there is no ready original PHP Contacts library from Google out there.
But there are already a few open source third party libraries.
Maybe you can use/customize them.

For the "low level" HTTP communication please consult: https://developers.google.com/google-apps/contacts/v3/

**Comment by bshaffer** [comment]
I cannot find this API in the [APIs Explorer](https://developers.google.com/apis-explorer/#p/), but I have found reference to [the scope](https://github.com/bshaffer/google-api-php-client/blob/update-services/src/Google/Service/People.php#L38) and the [api endpoint](https://github.com/google/google-api-php-client/blob/master/src/Google/Service/Script.php#L40) mentioned in the documentation above.

As explained in #855 and #820, if you have the URL of the API, you can use the `authorize` method for authentication, and use the resulting HTTP Client to call the API:

```php
$client = new Google_Client();

// set your auth
if ($youAreUsingServiceAccount) {
    $client->useApplicationDefaultCredentials();
} elseif($youAreUsingThreeLeggedOAuth) {
    $client->setAccessToken($accessToken);
}

// get the authorized HTTP Client object
$http = $client->authorize();

// make the call!
$userEmail = 'your@email.com';
$url = "https://www.google.com/m8/feeds/contacts/$userEmail/full"
  . '?updated-min=2007-03-16T00:00:00';

$result = $http->get($url);
```
