### ISSUE TITLE
Update DCM API Service to newest version before sunset on Feb 29

### ISSUE THREAD

**Issue by tfranke** [google/google-api-php-client#803]
The DCM/DFA Reporting and Trafficking API Service (DFAreporting.php) is currently set to work with version v2.1 which will be sunset on Februaray 29 (https://developers.google.com/doubleclick-advertisers/reporting/deprecation).

Will there be a new release that works with the newewst version (v2.3) in time?

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
