### ISSUE TITLE
getResultSizeEstimate is giving odd results

### ISSUE THREAD

**Issue by justberare** [google/google-api-php-client#804]
<?
I am trying to get the number of emails (read & unread shown separately) for a given search. I've read that the labels.get() function does the trick but I don't know how to use it. Here's the code I have to detect if I have less or more than 100 result for a given sender.

```
  require_once '../../vendor/autoload.php';
  session_start();
  $client = new Google_Client();
  $client->setAuthConfigFile('../../client_secrets.json');
  $client->addScope(Google_Service_Drive::DRIVE_METADATA_READONLY);
  $client->addScope(Google_Service_Gmail::GMAIL_READONLY);
  $client->setAccessType("offline");
  $client->setApprovalPrompt('force');
  $client->setAccessToken($_SESSION['token']);
  $service = new Google_Service_Gmail($client);

  $sender = array();
  $sender[] = 'sender1@email.com';
  $sender[] = 'sender2@email.com';
  $sender[] = 'sender3@email.com';

  function countfrom($service, $userId, $expeditor) {
        try
        {
          unset($optParamsamz);
          $optParamsamz = [];
          $optParamsamz['maxResults'] = 100; // Return Only 5 Messages
          $optParamsamz['q'] = "From: '".$expeditor."'  "; 
          $messagesamz = $service->users_messages->listUsersMessages('me',$optParamsamz);
          $listamz = $messagesamz->getMessages();
          echo sizeof($listamz);

      }
     catch (Exception $e)
        {
          print 'An error occurred: ' . $e->getMessage();
        }

      }
```

foreach ($sender as $key => $value)
            {
             echo $value .': ';
             countfrom($service,$_SESSION['emaile'],$value)  ;
             echo '<br/>';
            }
------------------- EDIT ----------------------

I have tried a new solution that seems closer to what I'm looking for. The issue now comes from Google who returns some odd number for the resultestimatsize:

<?
  require_once '../../vendor/autoload.php';
  session_start();
  $client = new Google_Client();
  $client->setAuthConfigFile('../../client_secrets.json');
  $client->addScope(Google_Service_Drive::DRIVE_METADATA_READONLY);
  $client->addScope(Google_Service_Gmail::GMAIL_READONLY);
  $client->setAccessType("offline");
  $client->setApprovalPrompt('force');
  $client->setAccessToken($_SESSION['token']);
  $service = new Google_Service_Gmail($client);

  $sender_array[] = 'sender1@sender.com';
  $sender_array[] = 'sender2@sender.com';
  $sender_array[] = 'sender3@sender.com';
  $sender_array[] = 'sender4@sender.com';

  foreach ($sender_array as $key => $expeditor)
  {

```
$optParamsamz1['q'] = "From: '".$expeditor."' is:read  "; 
$optParamsamz2['q'] = "From: '".$expeditor."'   "; 

echo $expeditor.": ".$service->users_messages->listUsersMessages('me',$optParamsamz1)->getResultSizeEstimate() . "
                   ".$service->users_messages->listUsersMessages('me',$optParamsamz2)->getResultSizeEstimate(); 
echo "<br>";
```

  }
?>

Somehow the results are wrong. When I compare them to reality they are totally different

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
