### ISSUE TITLE
Google_Http_MediaFileUpload::nextChunk fails for resumable upload if filesize is greater than chunksize

### ISSUE THREAD

**Issue by josedsilva** [google/google-api-php-client#805]
While uploading a large file (10 - 100MB) from GCS to Google Drive in a Google APP Engine application, the call "$status = $media->nextChunk($chunk);" fails and throws the following error:
HTTP Error: Unable to connect: 'fopen(): Unknown status code.'

Chunk size is set to 1MB. If the filesize is less than chunk size, it gets uploaded without any issues but if greater than chunk size, the above mentioned error is throw.

I am using PHP client library ver 1.0.6-beta. I tried upgrading the client library to 1.1.6. It doesn't help.

For more information on the issue please refer 
https://code.google.com/p/googleappengine/issues/detail?id=12584

**Comment by bshaffer** [comment]
Do you have a stack trace for the error?

**Comment by josedsilva** [comment]
You can see the stack trace here:
http://jensen-education-system.appspot.com/test/test-upload-resumable

**Comment by mattwhisenhunt** [comment]
@josedsilva Are you still looking for a solution to this issue?

**Comment by josedsilva** [comment]
Hi Matt,

If the issue is resolved in the later/newer versions of the Google API PHP
client library (ver 1.1.6+) then please close this issue. I haven't tested
ver 2.0+ of the php client library.

**Comment by tinusg** [comment]
I'm still running into this issue.
