### ISSUE TITLE
fopen(/tmp/google-api-php-client/e6/e636...): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by nicolasbadia** [google/google-api-php-client#806]
Hi,
I've updated my google api php client from RC2 to RC4 and I'm now getting a lot of warning (actually thousands of warning emails in my mailbox...) saying: `fopen(/tmp/google-api-php-client/e6/e63617e9de932b7845fe794b2537c09a): failed to open stream: Permission denied`.

The issue might come from the fact that I'm using the library from fpm with a `www-data` user and from cli in `root` (cron job). But I assume this is a common use case and the library should be able to handle it (by using different cache directories depending of the user for example).

Here is the stacktrace in case you need it:

    /home/gestixi/vendor/google/apiclient/src/Google/Cache/File.php 192
    /home/gestixi/vendor/google/apiclient/src/Google/Cache/File.php 177
    /home/gestixi/vendor/google/apiclient/src/Google/Cache/File.php 99
    /home/gestixi/vendor/google/apiclient/vendor/google/auth/src/CacheTrait.php 65
    /home/gestixi/vendor/google/apiclient/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php 138
    /home/gestixi/vendor/google/apiclient/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php 113
    /home/gestixi/vendor/google/apiclient/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php 114
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php 42
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/Middleware.php 30
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php 68
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/Middleware.php 57
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/HandlerStack.php 67
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/Client.php 268
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/Client.php 98
    /home/gestixi/vendor/google/apiclient/vendor/guzzlehttp/guzzle/src/Client.php 104
    /home/gestixi/vendor/google/apiclient/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php 33
    /home/gestixi/vendor/google/apiclient/src/Google/Http/REST.php 73
    /home/gestixi/vendor/google/apiclient/src/Google/Task/Runner.php 181
    /home/gestixi/vendor/google/apiclient/src/Google/Http/REST.php 57
    /home/gestixi/vendor/google/apiclient/src/Google/Client.php 758
    /home/gestixi/vendor/google/apiclient/src/Google/Service/Resource.php 232
    /home/gestixi/vendor/google/apiclient/src/Google/Service/Calendar.php 1636

Hope you guys can fixe this issue. Let me know if you need more details.

**Comment by bshaffer** [comment]
Looking at [the difference between the tags](https://github.com/google/google-api-php-client/compare/v2.0.0-RC2...v2.0.0-RC4) there were some [refactorings](https://github.com/google/google-api-php-client/compare/v2.0.0-RC2...v2.0.0-RC4#diff-e912e39fbc1c619500bee6c1bab1600eL76) for `Google\Cache\File`. However, none of these seem like they would cause the issue above. Can you switch to RC3 and verify this fixes the issue?

**Comment by nicolasbadia** [comment]
It indeed seem that switching to RC3 fixes the issue.

**Comment by bshaffer** [comment]
fixed in #839
