### ISSUE TITLE
Reduce/Eliminate manual steps in OAuth flow

### ISSUE THREAD

**Issue by vsubramani** [google/google-api-php-client#809]
When using the php libraries for obtaining OAuth credentials to use with APIs hosted on GCP, these manual steps are involved:
1. Copy Auth url to browser
2. Accept on the consent screen
3. Copy the auth code into the go application

See example https://developers.google.com/google-apps/calendar/quickstart/php

Google API client libraries for other languages host an http listener thereby avoiding the need for  manual steps 1 and 3. Please consider doing similar for the php client libraries.

**Comment by bshaffer** [comment]
This may be more complicated than for python, due to the lack of multithreading in PHP.

**Comment by bshaffer** [comment]
Closing as we do not really need this.
