### ISSUE TITLE
Server-side worflow : URI postmessage

### ISSUE THREAD

**Issue by gourlaa** [google/google-api-php-client#811]
Hey,

When we use this worflow : https://developers.google.com/identity/sign-in/web/server-side-flow

We must register postmessage as URI like this : $client->setRedirectUri("postmessage");

However this protection : 
```php
if (!$this->isAbsoluteUri($uri)) {
      throw new \InvalidArgumentException(
          'Redirect URI must be absolute');
}
```
Throw an exception because postmessage is not an absolute URI.

And if we set another uri like : http://www.website.com , the script tell us there is a mismatch URI because we set postmessage during the javascript workflow as the docs said.

Any solution ?

Thanks

**Comment by bshaffer** [comment]
`postmessage` does not follow the OAuth2 spec for a valid absolute URI. If anything, it should be something like `urn:postmessage`. 

I suppose the solution would be to add an explicit check for `postmessage` in [this function](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L1134). I would love to have whoever made the decision to support `postmessage` defend this reasoning, however!

**Comment by gourlaa** [comment]
Thanks for your answer.

I suspect there is also a problem for iOS & Android with this redirect_uri : urn:ietf:wg:oauth:2.0:oob, or urn:ietf:wg:oauth:2.0:oob:auto ?

Docs : https://developers.google.com/identity/protocols/OAuth2InstalledApp

Have a great day.

**Comment by bshaffer** [comment]
fixed in https://github.com/google/google-auth-library-php/pull/92

No, `urn:...` will validate just fine, since it follows a standard URI format.
