### ISSUE TITLE
Video Upload not working

### ISSUE THREAD

**Issue by ximrx** [google/google-api-php-client#815]
Simple video upload  using latest release 1.1.6 and sample code from Youtube API V3 is not working and giving 500 internal server error.

Fatal error: Class 'Google_Service' not found in google-api-php-client/src/Google/Service/YouTube.php on line 32'

Code:
https://developers.google.com/youtube/v3/code_samples/php#upload_a_video

Details:
http://stackoverflow.com/questions/34954443/how-to-upload-video-to-youtube-using-google-api-php-client-library-and-youtube-a

**Comment by bshaffer** [comment]
You need to include the `src/Google/autoload.php` file in your application.
