### ISSUE TITLE
Working example? Looking for updated tutorial.

### ISSUE THREAD

**Issue by smurfxx** [google/google-api-php-client#818]
Where can I find a working example of Google working authentication with the latest release of this library and without using Composer?
I found a lot of tutorials but all of them refers to old libraries.

My main goal is create a php web application that insert, edit and delete google calendar events, in a shared web space, without composer.

Thank you!

**Comment by mTorres** [comment]
Weather you use composer or not is completely up to you. Composer is just a tool to get the library downloaded, you can do that by downloading a ZIP file from github and then manually creating an autoloader (or requiring each used file).

As for an example, I've just [pushed a gist](https://gist.github.com/mTorres/b4808841bf718abcb940) with a working sample to reproduce [an issue](https://github.com/google/google-api-php-client/issues/819), maybe you'll find it useful?

**Comment by smurfxx** [comment]
Thank you very much for the example, I downloaded a wong version of Google API PHP Library, now I downloaded the one that doesn't need composer and infact everything is ok!

Now I can go on and develop my web application, thank you very much!

**Comment by bshaffer** [comment]
wow, right on @mTorres! thanks for the help.
