### ISSUE TITLE
Google Plus service returnig stale data

### ISSUE THREAD

**Issue by mTorres** [google/google-api-php-client#819]
I've just found what seems a weird issue with latest version (2.0@dev, not sure with previous but with this is happening with *master*). Retrieving user information  with ```$plus->people->get("me");``` gives information of the last logged user, not the current one. It seems a cache issue somewhere but I'm unable to find it.

## Steps to reproduce

I've created [this gist](https://gist.github.com/mTorres/b4808841bf718abcb940) to share the code I'm using to reproduce this issue (notice that no session is used, so no information is stored across requests)

Once setup just:

1. Access the script directly and start the OpenID Connect flow by clicking the ```here``` link, which will redirect you to Google Server, there enter your credentials.
2. Check at the callback page (should be the same) and see your name and mail.
2. On another tab, [logout from your Google account](https://accounts.google.com/logout)
3. Retry the flow in step 1 to connect to Google and check the information about the user, notice that it shows the information of the last already logged out user and not the currently logged in.

Maybe it's my environment that can be using some sort of cache layer?

## Environment info
Tried with:
  - Windows7+PHP5.5 (Op cache enabled)
  - OSX PHP5.5 opcache disabled

**Comment by ajcerqueti** [comment]
Confirm this is also happening with Gmail API as well. For me, it's caching the last successful user to send an email, and subsequent calls are trying delegate to that user, as the client is retaining that user. Can't find which cache it could be though, I've cleared apc cache etc.

Can't revert to RC3 because other core dependencies require a newer version of Guzzle. Stuck. Seems to be something in google/auth 0.5, from what I can trace, but I'm fairly lost that far down the rabbit hole!

**Comment by ajcerqueti** [comment]
As a workaround, delete the contents of ```/tmp/google-api-php-client``` before you create a client. There was a file (```/tmp/google-api-php-client/d4/d41d8cd98f00b204e9800998ecf8427e```) with the old access code, which is where it's being cached by the client.

I can understand why it's doing this, but it should probably check when a new access token is set, or there should be some functionality to clear the cache. Happy to implement and make a pull request if someone can suggest what the preferred solution is.

**Comment by bshaffer** [comment]
this will be resolved in #842 - I am removing the default file cache implementation

**Comment by bshaffer** [comment]
This is now fixed in [RC5](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC5). Please update to this version and reopen this issue if the problem continues.

Thank you!

**Comment by mTorres** [comment]
Yes RC5 is working, thanks!
