### ISSUE TITLE
Where is google news and video search?!

### ISSUE THREAD

**Issue by dotku** [google/google-api-php-client#820]
I didn't find the service for Google News and Google Video search?!

**Comment by bshaffer** [comment]
Hmm, I do not know if those APIs are supported. See the [APIs explorer](https://developers.google.com/apis-explorer/#p/) for the current list

**Comment by bshaffer** [comment]
Both of these APIs are deprecated ([Video Search API](https://developers.google.com/video-search/), [News API](https://developers.google.com/news-search/))

However, as explained in #855, if you have the URL of the API, you can use this library to handle authentication, and use the HTTP Client to call the API directly using the `authorize` method:

```php
$client = new Google_Client();

// set your auth
if ($youAreUsingServiceAccount) {
    $client->useApplicationDefaultCredentials();
} elseif($youAreUsingThreeLeggedOAuth) {
    $client->setAccessToken($accessToken);
}

// get the authorized HTTP Client object
$http = $client->authorize();

// make the call!
$url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
  . '?location=-33.8670522,151.1957362'
  . '&radius=500'
  . '&types=food'
  . '&name=harbour'

$result = $http->get($url);
```
