### ISSUE TITLE
When will it out from 1.0.*@beta releases?

### ISSUE THREAD

**Issue by itsazzad** [google/google-api-php-client#824]
In the readme its suggesting to use the 1.0.*@beta:
```
NOTE: If you arrived here from developers.google.com, you should be using the v1-branch of this repo
```

Is the v2 supporting better?
Can we choose the v2 instead of v1?

**Comment by bshaffer** [comment]
Feel free to use v2. It is the recommended version. however, the documentation on developers.google.com has not been updated (at the time of this comment), and so the docs will need tweaking to get it to work.
