### ISSUE TITLE
quotaExceeded error after adding 1000 URLs in Google Search Console

### ISSUE THREAD

**Issue by mseshachalam** [google/google-api-php-client#826]
I have asked this on SO.
http://stackoverflow.com/questions/35155515/quotaexceeded-403-error-on-google-search-console-apis

I am using service account to authenticate API calls and I am doing batch request to add sites to search console. 

Using php Google API client lib, how can I set quotaUser optional query field. I am not sure why this is happening.

**Comment by bshaffer** [comment]
Do you have an API Key set?

```php
$client->setDeveloperKey($myApiKey);
```

**Comment by mseshachalam** [comment]
Nope, Why do we need to set developerkey if we are using service account's json credentials ? 
Someone replied on google product forums regarding this. I was using sites add API to add an page URL not a domain name. I was adding something like, http://example.com/blog/2016-02-18-hello but the api is intended to use to add the domain name like http://example.com/ . 

Am I wrong ?

**Comment by bshaffer** [comment]
Yeah that sounds right. I'm glad you figured it out?
