### ISSUE TITLE
Exception occurs when I try to get access token from code

### ISSUE THREAD

**Issue by deniszubkov** [google/google-api-php-client#829]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\cloudsheet\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\xampp\htdocs\cloudsheet\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\cloudsheet\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\cloudsheet\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\Easy in C:\xampp\htdocs\cloudsheet\google-api-php-client\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

Please help me.

**Comment by bshaffer** [comment]
Hmm, my guess is that you are behind a firewall, or some other strangeness is happening with your network connection.  Have you tried pinging the APIs or curling the API endpoints directly from the command line?

**Comment by deniszubkov** [comment]
Thank you for your reply.
There was problem with my network.
And it was solved clearly.
:)
