### ISSUE TITLE
setAuthConfig fails with service account JSON from Developer's Console

### ISSUE THREAD

**Issue by ericnorris** [google/google-api-php-client#832]
Hello there,

As noted in #455, calling `setAuthConfig` fails when it is provided the newer format JSON keys.

@ianbarber made a commit (82da936b6e29daf54ba0843d6d88e0b0ed5b4802) that added a new function `loadServiceAccountJson` to handle the newer format, but it uses the deprecated (per [this document](https://github.com/google/google-api-php-client/blob/a4cd92fbb56f8e80503765cd582a319ec9c6855b/UPGRADING.md#google_auth_assertioncredentials-has-been-removed)) for v2 `Google_Auth_AssertionCredentials`. Additionally, that helper function does not appear at all in v2 and so will break on upgrade for anyone using it.

I would suggest backporting the v2 `setAuthConfig` JSON-loading into the current v1-master branch.

**Comment by bshaffer** [comment]
if you are using JSON keys in `v1`, use `Google_Client:: loadServiceAccountJson`

If you are using JSON keys in `v2`, use `Google_Client::setAuthConfig`

Backporting is not necessary, as `v1` is deprecated.

**Comment by ericnorris** [comment]
Hey @bshaffer, thanks for the response! I am aware of the functions, but the point I was trying to make was that if you want to write `v1` code that can be upgradeable to `v2`, using `Google_Client::loadServiceAccountJson` would mean you would have issues later on.

Both `v1` and `v2` have the `Google_Client::setAuthConfig` function, so if the `v1` version was updated to work with the new-style JSON config you'd have no troubles dropping in `v2` when you were able to upgrade. If you used a separate function (`Google_Client::loadServiceAccountJson`) you would need to remember to change this usage when you were able to upgrade.

I realize `v1` is deprecated but it does seem that it is still being updated (`v1.1.7` was released 7 days ago and `v1.1.6` was just a few short months ago). Backporting would be really helpful to those who are unable to upgrade a major version yet, but would like to in the future.

**Comment by bshaffer** [comment]
I'm not a fan of development on deprecated products. However, I'm definitely open to PRs which backport this behavior. In the meantime, I've added this to `UPGRADING.md` (#841), so hopefully this will help.
