### ISSUE TITLE
Allowing multiple users to access the app

### ISSUE THREAD

**Issue by nebadom** [google/google-api-php-client#833]
Does anyone knows how to work with the PHP API to allow multiple google users to access different folders/paths without interfering with the authentication?

Any response, ANY will be most appreciated.

**Comment by bshaffer** [comment]
This question is quite confusing to me. You can handle multiple users by maintaining multiple sessions (like any other app), and if you wanted to restrict different folders/paths in your application, you'd have to implement your own ACL or use a framework ACL for that.

Can you provide a little bit more on what you're trying to accomplish?

**Comment by nebadom** [comment]
Put it this way:

I have this app that I want multiple users from the SAME browser to access it. I'm talking:  I want users from gmail to access my app. Currently, only the 1st user of Google/Gmail (the main user) is allowed to access my app. If I want another user, I have to trigger `UserService::createLoginURL($_SERVER['REQUEST_URI']);` if I want another user to access it. Most frustrating is that I can't have multiple users from the same browser accessing my app simultaneusly.

Is there a way I can overcome this? I used to play with the SACSID cookies so I could define one per user per path. But now, all of the sudden this week, that stopped from working... is like if the session manager is not reading any SACSID cookie that is not "root".

**Comment by nebadom** [comment]
Basically, what I want is to mimick the google `?authuser=1` behavior. Any thoughts?

**Comment by nebadom** [comment]
Ok, I was able to do this by:

- Asking authorization to each user attempting to access the folders
- Storing the user information into $_SESSION (into an array)
- Comparing such array data to the user attepmting to access the path: if it was not authorized to that path, then prompts for authorization.

So far so good. I'm back in business.

**Comment by bshaffer** [comment]
Glad to hear it!
