### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by gurwika** [google/google-api-php-client#836]
i have installed the script but i have got file missing, 
in google-api-php-client/src/Google/autoload.php

there is: $file = __DIR__ . '/../../vendor/autoload.php';

but vendor/autoload.php file is missing..

Can you help me?

**Comment by bshaffer** [comment]
try running `composer install` in the root directory.  First, you'll need to [install composer](getcomposer.org)

The alternative is to download a zip file from the [Releases](https://github.com/google/google-api-php-client/releases) section.
