### ISSUE TITLE
[GTM] "Backend errors" when working with folders

### ISSUE THREAD

**Issue by ArtemGordinsky** [google/google-api-php-client#837]
Hi,
I've been trying out the Google Tag Manager API, and noticed some issues when working with folders:
The requests to list the contents of a folder (tagmanager.accounts.containers.folders.entities.list), or move items inside of a folder (tagmanager.accounts.containers.move_folders.update) invariably return a "Backend Error" (500). I was also able to reproduce these issues in the API Explorer:
![backend_error](https://cloud.githubusercontent.com/assets/1506254/12881992/e3d2f4a2-ce56-11e5-8d7f-818ca71df93d.png)

Am I missing something here? Any help would be appreciated.

P.S. I have also asked this question [on Google Forums](https://productforums.google.com/forum/#!msg/tag-manager/zsi1B9d4nqI/e12Wt_4sAgAJ).

**Comment by bshaffer** [comment]
I have seen these same errors in our testing environment. They are very intermittent, and the best thing to do is to retry the request. I will look into building retries into the library.

**Comment by ArtemGordinsky** [comment]
Hi,
I'm pretty sure the errors in our case weren't intermittent at all – 100% of them failed for three days straight.
Fortunately, it seems to have been finally [fixed](https://productforums.google.com/d/msg/tag-manager/zsi1B9d4nqI/GedaAAUxAwAJ) yesterday, so I'll go ahead and close this issue.
