### ISSUE TITLE
invalid grant

### ISSUE THREAD

**Issue by ervaibhavsinghal** [google/google-api-php-client#838]
Fatal error: Uncaught Google_Auth_Exception: Error refreshing the OAuth2 token, message: '{ "error" : "invalid_grant" }' in /opt/lampp/htdocs/views/google-api-php-client/src/Google/Auth/OAuth2.php:364 Stack trace: #0 /opt/lampp/htdocs/views/google-api-php-client/src/Google/Auth/OAuth2.php(313): Google_Auth_OAuth2->refreshTokenRequest(Array) #1 /opt/lampp/htdocs/views/HelloAnalytics.php(29): Google_Auth_OAuth2->refreshTokenWithAssertion(Object(Google_Auth_AssertionCredentials)) #2 /opt/lampp/htdocs/views/HelloAnalytics.php(104): getService() #3 {main} thrown in /opt/lampp/htdocs/views/google-api-php-client/src/Google/Auth/OAuth2.php on line 364

**Comment by bshaffer** [comment]
I have seen this issue before. You are trying to exchange an Authorization Code for an Access Token and you have not set your `redirect_uri` in the google client:

```php
$client = new Google_Client();
$client->setClientId($yourClientId);
$client->setClientSecret($yourClientSecret);

// you must set your redirect URI to exchange an access token:
$redirectUri = 'http://www.example.com/oauth2callback';
$client->setRedirectUri($redirectUri);

// now this should work
$client->fetchAccessTokenWithAuthCode($code);
```

**Comment by bshaffer** [comment]
In future bug reports it is bad form to post only a stack trace with no code samples or further explanation of context.
