### ISSUE TITLE
Class OAuth2 not found

### ISSUE THREAD

**Issue by Rainking80** [google/google-api-php-client#845]
I see this error because the OAuth2 class seems moved to Service/Oauth2... Is that right? The Client.php still tries to find it in Google/Auth/OAuth2 which crashes my webservice.

PHP Fatal error:  Class 'Google\Auth\OAuth2' not found in //google-api-php-client/src/Google/Client.php on line 902

Example from Client.php line 902
` 
/**
   * @return Google\Auth\OAuth2 implementation
  */
protected function createOAuth2Service()
  {
    $auth = new OAuth2(
        [
          'clientId'          => $this->getClientId(),
          'clientSecret'      => $this->getClientSecret(),
          'authorizationUri'   => self::OAUTH2_AUTH_URL,
          'tokenCredentialUri' => self::OAUTH2_TOKEN_URI,
          'redirectUri'       => $this->getRedirectUri(),
          'issuer'            => $this->config['client_id'],
          'signingKey'        => $this->config['signing_key'],
          'signingAlgorithm'  => $this->config['signing_algorithm'],
        ]
    );

    return $auth;
  }`

The folder Google/Auth does not exist in my library.

Kind Regards!

**Comment by bshaffer** [comment]
No, the error is referring to [this class](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php). The problem is you need to [run composer](http://getcomposer.org) to install the dependencies for the library. Alternatively, you can [download the zip](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC5) by clicking the `google-api-php-client-2.0.0-RC5.zip`, and all the dependencies will be pre-installed.

**Comment by androide1022** [comment]
I just download the m.zip and put the folder  on my project on htdocs in loclalhost using xampp, i have the same error 



<?php
session_start();

//Include Google client library 
require_once 'google-api-php-client-2.0.0-RC5/vendor/autoload.php';
//include_once 'vendor/Google_Oauth2Service.php';




/*
 * Configuration and setup Google API
 */
$clientId = 'InsertGoogleClientID';
$clientSecret = 'InsertGoogleClientSecret';
$redirectURL = 'http://localhost/school/index2.php';

//Call Google API
$gClient = new Google_Client();
$gClient->setApplicationName('Login to CodexWorld.com');
$gClient->setClientId($clientId);
$gClient->setClientSecret($clientSecret);
$gClient->setRedirectUri($redirectURL);

$google_oauthV2 =  new Google_Oauth2Service;
?>
that was my Code
what im doing wrong ?

**Comment by bshaffer** [comment]
Hmm, can you open a new issue describing your problem please? This issue's been closed. Also include the exact error message you're receiving. Thank you!

**Comment by hamiderremli** [comment]
I have the same pb. I've tried with composer and download alternatively the zip without any impact... always the error: ... Fatal error: Uncaught Error: Class 'Google_Oauth2Service' not found in ...

**Comment by mf01** [comment]
Any news in this case?
