### ISSUE TITLE
Issue with Google_Client no longer using caching with subsequent API calls

### ISSUE THREAD

**Issue by am63** [google/google-api-php-client#849]
Hi,

Since this commit, most API calls are broken in my application.

Here are some details about the issue and when it occurs :

- single API call (such as a new event in Calendar) : OK, no issue
- 2 or more API calls, with a recent login (less than one hour) ; for example, read an event in Calendar, and send back the event with some updates : OK, no issue
- **2 or more API calls, with a login done more than one hour ago : KO**, exception is thrown. If I delete the token (which I store in a database), the user logs again, and all is OK.

The error returned by the API has the following data :
`'Client error: POST https://www.googleapis.com/oauth2/v3/token resulted in a 400 Bad Request response: { "error": "invalid_request", "error_description": "Required parameter is missing: grant_type" } '`

and here is the stack trace :

```
#0 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Client.php(104): GuzzleHttp\Promise\Promise->wait()
#10 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(33): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/google/auth/src/OAuth2.php(449): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
#12 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/google/auth/src/Credentials/UserRefreshCredentials.php(83): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle6HttpHandler))
#13 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php(135): Google\Auth\Credentials\UserRefreshCredentials->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle6HttpHandler))
#14 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/google/auth/src/Middleware/AuthTokenMiddleware.php(113): Google\Auth\Middleware\AuthTokenMiddleware->fetchToken()
#15 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): Google\Auth\Middleware\AuthTokenMiddleware->Google\Auth\Middleware\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#16 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#17 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#18 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#19 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#20 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Client.php(268): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#21 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#22 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#23 /home/assistano/www/lib/google-api-php-client-2.0.0-RC5/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('get', 'https://www.goo...', Array)
#24 /home/assistano/www/common/com_google.php(1201): GuzzleHttp\Client->__call('get', Array)
```

**It seems that the token is never refreshed.**
**
If I revert back my code to use RC4, everything is fine**. RC5 and the Google_Client no longer using caching may have some undesired side-effects.

I can reproduce the issue with any Google API I'm using : Calendar, Gmail, Drive (and also Contacts and CloudPrint, which don't have a PHP api, so that I had to communicate with xml or json raw data).

Can anyone help ? Thanks

**Comment by bshaffer** [comment]
Hi @am63. Thank you for reporting this.
The issues we experienced with the caching in place (users receiving data from other users' access tokens) was too big an issue to not remove caching for the time being until we could solve the problem.
You can almost certainly solve this by implementing caching manually on your end like this:

```php
$cacheDir = '/your/cache/dir';
$cache = new Google_Cache_File($cacheDir);
$client = new Google_Client();
$client->setCache();
if ($accessToken = $cache->get('access_token')) {
    $client->setAccessToken($accessToken);
}
// go on and do your thing
```

With this approach, you'll have to be sure to **store** your access token in cache when you first receive it:

```php
// *** In your authorization callback ***
$client = new Google_Client();
// retrieving access token from authorization code
$accessToken = $client->fetchAccessTokenWithAuthCode($_GET['code']);
// now store it in the cache!
$cacheDir = '/your/cache/dir';
$cache = new Google_Cache_File($cacheDir);
$cache->set('access_token', $accessToken);
```

If nothing else, you could subclass `$client` to behave like it used to:

```php
class CachedGoogleClient extends Google_Client
{
    protected function getAuthHandler()
    { 
        return Google_AuthHandler_AuthHandlerFactory::build($this->getCache());
    }
}
```

Now if you set the cache (you still have to do that manually), the access tokens will be cached as before

**Comment by am63** [comment]
Thanks for replying so quickly, since I was not sure how this issue could be solved on my side (I'm not experienced in the Google auth process). 

Since I'm not concerned by the cache issue with multiple users (for the time being, my application is single-user), I'm using the Client (RC4) file ; as soon as the caching issue is solved I will update it.

Thanks again, have a nice day!

**Comment by am63** [comment]
Hi,

After some tests with RC5 and the Client class no longer caching tokens, here are some details about circumstances when the issue mentionned in my first post occurs (or NOT occur) : 
- issue occurs when using tokens that have been first obtained with _setAccessType('offline')_ ; offline tokens include a refresh token that is used to fetch a new short-lived token.
- issue occurs when the PHP library automatically refreshes the expired token (first request is OK, token is refreshed ; second request throws an exception)
- issue does NOT occur when we are manually refreshing the expired token in our application :
 
`if ( $client->isAccessTokenExpired() )
{
    $token = $client->fetchAccessTokenWithRefreshToken($our_token['refresh_token']);
    

}
`

**Comment by bshaffer** [comment]
Hmm, this is interesting.  This  *really* shouldn't be necessary.

In the `authorize` function, this [same logic](https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L351) is already implemented, making the above code redundant. Have you tried letting the library handle this logic instead?

**Comment by am63** [comment]
Oh yes ! That's the first thing I tried ! 

I saw the logic in Client.php, and I still can't figure out why it's not working as expected. I tried to insert debug print_r at critical lines in Client.php to see what was going on, but I had to admit this was beyond my knowledge (and required debug time !).

All I can say is that RC4 and caching is fine, RC5 with caching deactivated has this issue.

To be more precise : the issue does not occur as long as the newly fetched token is active (one hour). After that delay, the token stored in _access_token_ is expired and must be refreshed by the library. This is the case where the issue occurs : access token is expired and we have to work with refreshed tokens.

The first request is handled correctly, the expired token is refreshed, but if it's followed in the source code by a second request, the second one fails (the token is not refreshed, and the "old" expired one is used). 

This use case is typical of reading data, modifying stuff, and writing back to Google any changes.

I had a long 2 hours debug session last week-end but I failed to conclude anything about why this does not work as expected...

**Comment by am63** [comment]
Here is the print_r output of line 351 (sensitive data replaced by dummy values) ; the code I use is reading data, and then writing by updated data, so there's two refreshed tokens used. But the second one fails to be fetched (it fails at line 83 in /vendor/google/auth/src/Credentials/UserRefreshCredentials.php, that 's what some debug here told me) :

`$this->auth->fetchAuthToken($httpHandler);` 

debug data :
```
Google\Auth\Credentials\UserRefreshCredentials Object
(
    [auth:protected] => Google\Auth\OAuth2 Object
        (
            [authorizationUri:Google\Auth\OAuth2:private] => 
            [tokenCredentialUri:Google\Auth\OAuth2:private] => GuzzleHttp\Psr7\Uri Object
                (
                    [scheme:GuzzleHttp\Psr7\Uri:private] => https
                    [userInfo:GuzzleHttp\Psr7\Uri:private] => 
                    [host:GuzzleHttp\Psr7\Uri:private] => www.googleapis.com
                    [port:GuzzleHttp\Psr7\Uri:private] => 
                    [path:GuzzleHttp\Psr7\Uri:private] => /oauth2/v3/token
                    [query:GuzzleHttp\Psr7\Uri:private] => 
                    [fragment:GuzzleHttp\Psr7\Uri:private] => 
                )

            [redirectUri:Google\Auth\OAuth2:private] => 
            [clientId:Google\Auth\OAuth2:private] => xxxxxxxxxxxxx.apps.googleusercontent.com
            [clientSecret:Google\Auth\OAuth2:private] => -xxxxxxxxxcx7d-RUYuOVw4b
            [username:Google\Auth\OAuth2:private] => 
            [password:Google\Auth\OAuth2:private] => 
            [scope:Google\Auth\OAuth2:private] => Array
                (
                    [0] => http://www.google.com/m8/feeds/
                )

            [state:Google\Auth\OAuth2:private] => 
            [code:Google\Auth\OAuth2:private] => 
            [issuer:Google\Auth\OAuth2:private] => 
            [audience:Google\Auth\OAuth2:private] => 
            [principal:Google\Auth\OAuth2:private] => 
            [sub:Google\Auth\OAuth2:private] => 
            [expiry:Google\Auth\OAuth2:private] => 60
            [signingKey:Google\Auth\OAuth2:private] => 
            [signingAlgorithm:Google\Auth\OAuth2:private] => 
            [refreshToken:Google\Auth\OAuth2:private] => 1/xxxxxxxVy19ge0VAKaIb0SWfAczPT0owkCfQm0PTFHBactUREZofsF9C7PrpE-j
            [accessToken:Google\Auth\OAuth2:private] => 
            [idToken:Google\Auth\OAuth2:private] => 
            [expiresIn:Google\Auth\OAuth2:private] => 
            [expiresAt:Google\Auth\OAuth2:private] => 
            [issuedAt:Google\Auth\OAuth2:private] => 
            [grantType:Google\Auth\OAuth2:private] => 
            [extensionParams:Google\Auth\OAuth2:private] => Array
                (
                )

        )

)


userRefreshCredentials::fetchAuthTokenGoogle\Auth\Credentials\UserRefreshCredentials Object
(
    [auth:protected] => Google\Auth\OAuth2 Object
        (
            [authorizationUri:Google\Auth\OAuth2:private] => 
            [tokenCredentialUri:Google\Auth\OAuth2:private] => GuzzleHttp\Psr7\Uri Object
                (
                    [scheme:GuzzleHttp\Psr7\Uri:private] => https
                    [userInfo:GuzzleHttp\Psr7\Uri:private] => 
                    [host:GuzzleHttp\Psr7\Uri:private] => www.googleapis.com
                    [port:GuzzleHttp\Psr7\Uri:private] => 
                    [path:GuzzleHttp\Psr7\Uri:private] => /oauth2/v3/token
                    [query:GuzzleHttp\Psr7\Uri:private] => 
                    [fragment:GuzzleHttp\Psr7\Uri:private] => 
                )

            [redirectUri:Google\Auth\OAuth2:private] => 
            [clientId:Google\Auth\OAuth2:private] =>xxxxxxx.apps.googleusercontent.com
            [clientSecret:Google\Auth\OAuth2:private] => -xxxxxxxPhAcx7d-RUYuOVw4b
            [username:Google\Auth\OAuth2:private] => 
            [password:Google\Auth\OAuth2:private] => 
            [scope:Google\Auth\OAuth2:private] => Array
                (
                    [0] => http://www.google.com/m8/feeds/
                )

            [state:Google\Auth\OAuth2:private] => 
            [code:Google\Auth\OAuth2:private] => 
            [issuer:Google\Auth\OAuth2:private] => 
            [audience:Google\Auth\OAuth2:private] => 
            [principal:Google\Auth\OAuth2:private] => 
            [sub:Google\Auth\OAuth2:private] => 
            [expiry:Google\Auth\OAuth2:private] => 60
            [signingKey:Google\Auth\OAuth2:private] => 
            [signingAlgorithm:Google\Auth\OAuth2:private] => 
            [refreshToken:Google\Auth\OAuth2:private] => 1/xxxxxxxqVy19ge0VAKaIb0SWfAczPT0owkCfQm0PTFHBactUREZofsF9C7PrpE-j
            [accessToken:Google\Auth\OAuth2:private] => 
            [idToken:Google\Auth\OAuth2:private] => 
            [expiresIn:Google\Auth\OAuth2:private] => 
            [expiresAt:Google\Auth\OAuth2:private] => 
            [issuedAt:Google\Auth\OAuth2:private] => 
            [grantType:Google\Auth\OAuth2:private] => 
            [extensionParams:Google\Auth\OAuth2:private] => Array
                (
                )

        )

```
as you can see requests look alike... But the second one fails !

**Comment by tristanbailey** [comment]
Thank you so much for posting this any your code work @am63. I set up a new server and composer bumped googleapi from version 1.1.6 to 1.1.7 and it broke any second pages to try and get an access_token from the refresh_token. So I would agree with you the access_token is valid for the first setup with user interaction, but the second time we call it "offline" in a cron job the refresh_token will not create a access_token and we get invalid_grant error from the api. 
So at least the 2 days of trying to debug what I had broken in the code can be a new task to update the code for this updated package.

**Comment by am63** [comment]
I hope the guys here will be able to patch this caching/token issue soon !

**Comment by bshaffer** [comment]
@am63 check out #867 - this should fix your issue.

**Comment by am63** [comment]
Nice work, it works perfectly ! I can now rely on the library to refresh the tokens as needed ; I deleted in my code the isAccessTokenExpired() stuff mentionned above.

Thanks !

**Comment by tristanbailey** [comment]
@bshaffer I saw you PR, is this fix for the v2.* branch or should it also work for the 1.1.* one?
We have not move to v2 as its still marked RC.

**Comment by bshaffer** [comment]
@tristanbailey this issue is not relevant to the `v1-master` branch.  Whatever issue you are experiencing has to do with something else.

**Comment by tristanbailey** [comment]
@bshaffer Thanks for sharing, and fixing the mentioned issue. I have the same symptoms. Api works fine getting the first token and then does not want to get a second access token when offline.  I will look for steps and repost as a new issue here or on SO.
