### ISSUE TITLE
$client->refreshToken missing return [FIXED]

### ISSUE THREAD

**Issue by xdanik** [google/google-api-php-client#850]
In *\vendor\google\apiclient\src\Google\Auth\OAuth2.php

New token is succesfuly pulled from Google, but not returned to user. (NULL)

FIX:
Add "return json_encode($this->token);" on to line 365
Add "return" before "$this->refreshTokenRequest(..." on line 272

**Comment by am63** [comment]
Hi,

Are you refering to current release (v2 RC5) ? I don't think so, as I can't find the line/file mentionned in you post.

Could you be more precise about the library version you are using ? I used to have some issues with refreshing tokens and your post could be useful

**Comment by xdanik** [comment]
Damm it...
Composer has downloaded old release...
I have "google/apiclient": "^1.1"

Any idea about way to force him to install newest branch?

**Comment by am63** [comment]
Sorry, I don't use composer, so I can't help you (I downloaded the full release here [https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC5])

**Comment by xdanik** [comment]
For me it is now working fine out of the box...
I just have to change my code because accessToken is now Array (insted of JSON string)

**Comment by mTorres** [comment]
BTW to install a composer version just run ```composer require "google/apiclient:2.0-RC5@dev"```. Your problem is that the v2 branch is still in developement and composer does not install developement branches if you don't specifically say it (hence the ```@dev``` at the end of the version).

**Comment by xdanik** [comment]
Yeap.. I already figured it out.
For me is version 2.0-RC5 working OK out of the box without any modifications.
