### ISSUE TITLE
Add support for subnetworks in Google_Service_Compute

### ISSUE THREAD

**Issue by DicsyDel** [google/google-api-php-client#852]
Hi,

Recently GCE added support for subnetworks and right now it's impossible to launch an inctance via this library.

Can you please add support for: https://cloud.google.com/compute/docs/reference/latest/subnetworks

Thanks,
Igor

**Comment by recipe** [comment]
+1

**Comment by bshaffer** [comment]
This will be added in #835

**Comment by bshaffer** [comment]
this has now been merged into the `master` branch
