### ISSUE TITLE
Google Calendar Resources

### ISSUE THREAD

**Issue by lfroidmo** [google/google-api-php-client#853]
On December 15, the old GDATA Calendar Resource API was replaced by a new Calendar Resource API, part of the Admin SDK’s Directory API  (http://googleappsdeveloper.blogspot.be/2015/12/introducing-new-calendar-resource-api.html)

As far as I see, this open some possibilities for solving https://github.com/google/google-api-php-client/issues/206, and allow to manga ressources from php-client.

Is there any plan to implement this? 

Kind regards,

**Comment by bshaffer** [comment]
This will be added in #835

**Comment by bshaffer** [comment]
this has now been merged into the `master` branch

**Comment by lfroidmo** [comment]
Thanks, it works like a charm ! 

```
$client = new \Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(['https://www.googleapis.com/auth/admin.directory.resource.calendar','https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly']);
$client->setSubject('user@domain.com');
$directoryService = new \Google_Service_Directory($client);

$resources = $directoryService->resources_calendars->listResourcesCalendars('my_customer')->getItems();
```

**Comment by vipin-infobeans** [comment]
@lfroidmo , I got below error 

Fatal error: Call to undefined method Google_Client::setSubject() , There is no method into Google_Client.php
