### ISSUE TITLE
Google places API support

### ISSUE THREAD

**Issue by Mevrael** [google/google-api-php-client#855]
Couldn't find a service class for google places API. Is it possible right now to fetch place lat, long, name, country, address details by place_id or place name?

Also I have a question not related to this repo. Why Google allows searching for places by name without APP KEY and requires APP KEY when searching by place_id?

**Comment by bshaffer** [comment]
@Mevrael The `Places API` is not currently exposed in the [Discovery Service](https://developers.google.com/discovery/), which is what this library uses to generate the service classes.

For this reason, I suggest making the calls with basic HTTP, which you can do using the `authorize` method:

```php
$client = new Google_Client();
// set your API Key
$client->setDeveloperKey($myKey);

// get the authorized HTTP Client object
$http = $client->authorize();

// make the call!
$url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
  . '?location=-33.8670522,151.1957362'
  . '&radius=500'
  . '&types=food'
  . '&name=harbour'

$http->get($url);
```
