### ISSUE TITLE
Not working with developer key!

### ISSUE THREAD

**Issue by itsazzad** [google/google-api-php-client#856]
The batch example: https://github.com/google/google-api-php-client/blob/master/examples/batch.php#L43 not working if the developer key is set but if commenting out then its working!
How is it like so?
If try to print the result then the error message in the array like so:
```
There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.
```
But I should not have exceeded the quota.

**Comment by bshaffer** [comment]
This message is not about the quota, it's about the IP address you are making the request from.

Try whitelisting your requesting IP by editing your API Key where it says *Accept requests from these server IP addresses *:

![screen shot 2016-02-16 at 11 42 12 am](https://cloud.githubusercontent.com/assets/103941/13088754/66dd904a-d4a2-11e5-9c49-0ac7e9acc02a.png)

The reason you can comment out the key is the `Book API` is public. However, you have a limited quota when accessing it this way, and will eventually receive a quota error without a key.

**Comment by itsazzad** [comment]
I see. I was using browser key instead of server key.

**Comment by bshaffer** [comment]
Yes, Google "what is my IP" and use that one.

**Comment by bshaffer** [comment]
... Assuming your application is running on your local machine.
