### ISSUE TITLE
[BUG] Google Drive V3, API client 2.0

### ISSUE THREAD

**Issue by temuri416** [google/google-api-php-client#860]
Hi,

Batch upload fails using Google Drive V3 with master branch of API (v2.0).

I've modified https://github.com/google/google-api-php-client/blob/master/examples/batch.php with service account credentials.

The code:

```php
<?php
include_once __DIR__ . '/../vendor/autoload.php';
include_once "templates/base.php";

echo pageHeader("Batching Queries");

// USE TRUE OR FALSE TO TOGGLE BETWEEN BATCHED AND SEQUENTIAL UPLOADS.
$useBatch = true;

$client = new Google_Client();
$client->setScopes([
    'https://www.googleapis.com/auth/drive',
]);
if ($credentials_file = checkServiceAccountCredentialsFile()) {
  // set the location manually
  $client->setAuthConfig($credentials_file);
} elseif (getenv('GOOGLE_APPLICATION_CREDENTIALS')) {
  // use the application default credentials
  $client->useApplicationDefaultCredentials();
} else {
  exit;
}
$client->setSubject('some@email.com');
$service = new Google_Service_Drive($client);
$client->setUseBatch($useBatch);

if ($useBatch) {
    $batch = $service->createBatch();
}

$folder = new Google_Service_Drive_DriveFile([
  'name' => 'Invoices',
  'mimeType' => 'application/vnd.google-apps.folder'
]);

$req = $service->files->create($folder, [
  'fields' => 'id'
]);

if ($useBatch) {
    $result = $batch->add($req, 'newfolder');
    $folder = $batch->execute()['response-newfolder'];
    $newFolderId = $folder->id;
} else {
    $newFolderId = $req->id;
}

$uploadIDs = null;

if ($useBatch) {
    $batch = $service->createBatch();
}

for ($i=1;$i<=3;$i++) {
    $file = new Google_Service_Drive_DriveFile([
        'name' => $i . '.jpg',
        'mimeType' => 'image/jpeg',
        'parents' => [$newFolderId],
    ]);

    $req = $service->files->create($file, [
        'data' => file_get_contents('img/'.$i.'.jpg'),
        'mimeType' => 'image/jpeg',
        'uploadType' => 'media',
        'fields' => 'id',
    ]);

    if ($useBatch) {
        $batch->add($req, $i);
    } else {
        $uploadIDs[] = $req->id;
    }
}

if ($useBatch) {
    $results = $batch->execute();
} else {
    print_r($uploadIDs);
}
```

*CASE 1.*
The code above will fail with "**Not Found**" after running last ```$results = $batch->execute();```. Folder *Invoices* will be created successfully.

![image](https://cloud.githubusercontent.com/assets/3987203/13200906/de405822-d829-11e5-8d71-201494b17efe.png)

*CASE 2*
Change variable to: ```$useBatch = false;```.
The same code will successfully create folder *Invoices* and will place three JPGs in it.

I expect that exactly the same code should work batched or sequentially.

Thanks!

**Comment by bshaffer** [comment]
For starters, your line for adding the parent ID is not correct. In [the docs](https://developers.google.com/drive/v2/web/folder), the parent should be linked like this:

```json
{
  "title" : "cat.jpg",
  "mimeType" : "image/jpeg",
  "parents": [{
    "kind": "drive#fileLink",
    "id": "0Bz0bd074"
  }]
}
```
So in your code, it should be changed to look like this:

```php
$file = new Google_Service_Drive_DriveFile([
    'name' => $i . '.jpg',
    'mimeType' => 'image/jpeg',
    'parents' => [
        [ 'id' => $newFolderId, 'kind' => 'drive#fileLink' ]
    ],
]);
```

Try this and let me know if it works.

**Comment by temuri416** [comment]
@bshaffer 

Thanks for your response.

I tried as you suggested and result is exactly the same.

I'd like to point out the following:

1. You were looking at V2 reference, while my question was about [V3](https://developers.google.com/drive/v3/web/folder). So, my code is using the right syntax.

2. Event if I omit 'parents' property, all uploaded files should be placed in account's root folder. Which isn't happening either (with batched uploads).

3. If I disable batched uploads everything works as expected. V3 documentation does not require changes to the way ```->files->create()``` is called to be compatible with batched uploads.

4. It does not look like permissions issue, as I'm trying to upload files in the newly created folder (again, it is all fine with sequential upload).

It definitely looks like a bug.

Any other suggestions/ideas?

Cheers!

**Comment by bshaffer** [comment]
@temuri416 so I believe the short answer here is [it isn't supported](https://developers.google.com/api-client-library/python/guide/batch).

**Comment by temuri416** [comment]
Are you referring to this?

```
Note: You cannot use a media upload object in a batch request.
```

Are all uploads considered "media uploads"?

**Comment by bshaffer** [comment]
As stated in #768, this can be implemented using Guzzle and Promises. It's different than the API's batch implementation, because this actually makes separate HTTP requests, but does so in parallel.

Here is an example using [Guzzle 5 Batch Requests](http://docs.guzzlephp.org/en/5.3/clients.html#batching-requests):

```php
// Guzzle 5
use GuzzleHttp\Pool;

$client = new Google_Client();
$service = new Google_Service_Drive($client);
$file1 = new Google_Service_Drive_DriveFile([
        'name' => '1.jpg',
        'mimeType' => 'image/jpeg',
        'parents' => [$newFolderId],
]);
$file2 = new Google_Service_Drive_DriveFile([
        'name' => '2.jpg',
        'mimeType' => 'image/jpeg',
        'parents' => [$newFolderId],
]);

$req1 = $service->files->create($file1, [
        'data' => file_get_contents('img/1.jpg'),
        'mimeType' => 'image/jpeg',
        'uploadType' => 'media',
        'fields' => 'id',
]);
$req2 = $service->files->create($file2, [
        'data' => file_get_contents('img/2.jpg'),
        'mimeType' => 'image/jpeg',
        'uploadType' => 'media',
        'fields' => 'id',
]);

$requests = [$req1, $req2];

// Results is a GuzzleHttp\BatchResults object.
$results = Pool::batch($client->getHttpClient(), $requests);

// Can be accessed by index.
echo $results[0]->getStatusCode();

// Can be accessed by request.
echo $results->getResult($requests[0])->getStatusCode();
```
