### ISSUE TITLE
Google_Service_Analytics -> data_ga->get -> getRows() returns null, with no errors or warnings

### ISSUE THREAD

**Issue by konrados** [google/google-api-php-client#875]
Hello.

I use v.1x branch

This is my last piece of code:

```
$data = $analytics->data_ga->get($analyticsViewId, $startDate, $endDate, $metrics, array(
    'dimensions'    => 'ga:pagePath',
    'filters'       => 'ga:pagePath==http://...correct url',
    'sort'          => '-ga:pageviews',
));
$items = $data->getRows();  
```

And $items now contains null, although there is data in GA (that is when I open https://analytics.google.com/analytics/web ). And... no errors or warnings are displayed.

How can I know what's happening? I obviously made an error somewhere, but I have no idea where.

Additionally, when I intentionally make typos in "OAuth2 service account ClientId" or "OAuth2 service account email address" (this is while creating Google_Client instance) there are no errors/warnings as well. But there is when I make a typo in "$analyticsViewId" so exceptions generally do work.

I've searched the issues for "null" and "no error", but I can't see anything related, so maybe this is by design, and there is an explanation, but for me it is still a bug.

**Comment by lptn** [comment]
Hey @konrados 
Possibly you use invalid filters. Try to use a valid relative URL for ga:pagePath (with leading slash)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
