### ISSUE TITLE
Unable to parse the p12 file

### ISSUE THREAD

**Issue by themags-company** [google/google-api-php-client#877]
Hi,
I wanted to use your API (https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php) for a project I am working on in order to connect to the Analytics.
I went step by step:
- Create project
- Enable Analytics API
- Went to Credentials
- Generated an API key - server
- Went to Services (https://console.developers.google.com/permissions/serviceaccounts?project=_)
- Selected my Project
- Created an account and setting up name (checked the option for DwD)
- Saved key P12 in my project & copied the email generated (name themags):
  - themags@astute-harmony-123608.iam.gserviceaccount.com

Then I downloaded the API (https://github.com/google/google-api-php-client/tree/v1-master) and included it in the project. After that I followed the "HelloAnalytics.php" example:
`/ Creates and returns the Analytics service object.

  // Load the Google API PHP Client Library.
  require_once 'google-api-php-client/src/Google/autoload.php';

  // Use the developers console and replace the values with your
  // service account email, and relative location of your key file.
  $service_account_email = '<Replace with your service account email address.>';
  $key_file_location = '<Replace with /path/to/generated/client_secrets.p12>';

  // Create and configure a new client object.
  $client = new Google_Client();
  $client->setApplicationName("HelloAnalytics");
  $analytics = new Google_Service_Analytics($client);

  // Read the generated client_secrets.p12 key.
  $key = file_get_contents($key_file_location);
  $cred = new Google_Auth_AssertionCredentials(
      $service_account_email,
      array(Google_Service_Analytics::ANALYTICS_READONLY),
      $key
  );
  $client->setAssertionCredentials($cred);`

Unfortunately I get error from 'Google_Auth_AssertionCredentials'. The error states:

> Unable to parse the p12 file. Is this a .p12 file? Is the password correct? OpenSSL error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

I checked:
- p12 key file is accessible and has full rights - read, write everything, i've set it to 777 even
- providing p12 key as string, instead of going through file_get_contents, no change
- I entered (https://console.developers.google.com/permissions/serviceaccounts?project=astute-harmony-123608) and for THEMAGS created a new key, this time downloaded the JSON file
  - I tried including this file
  - Using it as string
  - Tried using this approach I found somewhere in this section
`$client->setAssertionCredentials($client->loadServiceAccountJson(
      Config()->CONFIG_PATH . 'API-Project-4989ab8a90b6.json',
      [Google_Service_Datastore::DATASTORE, Google_Service_Datastore::USERINFO_EMAIL]
))`

No change at all. I tried changing the p12 file into .pem:
`openssl pkcs12 -in "API Project-39255d2f4c4a.p12" -out "api_key.pem"`
I get the following errors:

> 9364:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:.\crypto\asn1\tasn_dec.c:1196:
> 9364:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:.\crypto\asn1\tasn_dec.c:370:Type=PKCS12

I've tried setting up a key on the default email: 440123294185-compute​@developer.gservicea​ccount.com and went through all of these steps again, but still the same.

I've tried also to read the certificate manually without going through the API, so I just set:
`openssl_pkcs12_read($key, $dummy, 'notasecret')`
Where $key carried the value of the certificate - both approaches file_get_contents && string tested. I received same error as listed before.

Both:
440123294185-compute​@developer.gservicea​ccount.com
and 
themags@astute-harmony-123608.iam.gserviceaccount.com
are set in the Analytics account and have access, but I don't think the problem is there.

There is something wrong with the certificate File I am downloading, but I can't understand what...

I've read and tested quite a lot of scenarios, but nothing seems to work.

Please advice! Am I missing something or doing something wrong?

Will be waiting for your reply.

Kind regards,
Svetoslav Dragoev

**Comment by themags-company** [comment]
O.k. solved that my self, at least the p12 wrong encoding.
Exporting the key from: https://console.developers.google.com/permissions/serviceaccounts?project=_ on Windows does not work, you should use Linux some other distribution.
Exporting the key from such, did the work for me... that's kind of strange behavior, I think at least there should be a warning message, stating you SHOULD use another operating system, instead developers waste days in debugging that...

Thanks in advance for the "FAST" response also.

Not happy from really happy from your support.

Kind regards

**Comment by bshaffer** [comment]
Sorry to hear you have been having issues. As you may know, the `p12` is deprecated in favor of JSON credentials. Good luck.

**Comment by amit-extreme** [comment]
// Create and configure a new client object.
        $client = new \Google_Client();
        $client->setApplicationName("{application name}");
        $analytics = new \Google_Service_Analytics($client);
        $cred = new \Google_Auth_AssertionCredentials(
            $service_account_email,
            array(\Google_Service_Analytics::ANALYTICS_READONLY),
              "{your private_key}"
        );     
        $client->setAssertionCredentials($cred);
        if($client->getAuth()->isAccessTokenExpired()) {
            $client->getAuth()->refreshTokenWithAssertion($cred);
        }
        $optParams = [
            'dimensions' => 'ga:date',
            'sort'=>'-ga:date'
        ] ;       
        
        $results = $analytics->data_ga->get(
           'ga:{View ID}',
           $date_from,
           $date_to,
           'ga:sessions,ga:users,ga:pageviews,ga:bounceRate,ga:hits,ga:avgSessionDuration',
           $optParams
           );
            
            $rows = $results->getRows();
            $rows_re_align = [] ;
            foreach($rows as $key=>$row) {
                foreach($row as $k=>$d) {
                    $rows_re_align[$k][$key] = $d ;
                }
            }           
            $optParams = array(
                        'dimensions' => 'rt:medium'
                );
            try {
              $results1 = $analytics->data_realtime->get(
                  'ga:{View ID}',
                  'rt:activeUsers',
                  $optParams);
              // Success. 
            } catch (apiServiceException $e) {
              // Handle API service exceptions.
              $error = $e->getMessage();
            }
            $active_users = $results1->totalsForAllResults ;
            return [
                'data'=> $rows_re_align ,
                'summary'=>$results->getTotalsForAllResults(),
                'active_users'=>$active_users['rt:activeUsers']
                ] ;


Unfortunately I get error from Google_Auth_Exception
Unable to parse the p12 file. Is this a .p12 file? Is the password correct? OpenSSL error: error:0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data

please give solution

**Comment by jdpedrie** [comment]
As @bshaffer mentioned above, p12 credentials files are deprecated. Are you able to replace them with a json credentials file?
