### ISSUE TITLE
Offline Access Token?

### ISSUE THREAD

**Issue by GustavoA23** [google/google-api-php-client#879]
Is there a method to cache an offline access token or extend the duration of the token? Im running a script thats running comparisons on upwards of 15'000 rows, and after about an hour my script times out (i believe the access token runs out?). This token is being used with the spreadsheets API, with a service account.

**Comment by bshaffer** [comment]
See [this comment](https://github.com/google/google-api-php-client/issues/801#issuecomment-171417538) about the ways you can handle this. Access tokens expire in an hour (3600 seconds), so yes I imagine that's what is happening.
