### ISSUE TITLE
Not able to get urlCrawlErrorsSamples using API

### ISSUE THREAD

**Issue by chiragvels** [google/google-api-php-client#884]
Hello All,

Search Console API is not returning urlCrawlErrorsSamples for any domain using search console API.

I am using like this .
$webmastersService = new Google_Service_Webmasters($client);
$webmastersService->urlCrawlErrorsSamples;
$urlcrawlerrorssamples->listUrlcrawlerrorssamples($url, $category, $platform);

Is there anything is going on from API end.

Please let me know your view here.

Thanks

**Comment by himmerman** [comment]
Do you have access to user data on your credentials?

I think the call should be something like  this
`$webmastersService = new Google_Service_Webmasters($this->client);`
`$webmastersService->urlcrawlerrorscounts->query($url, $category, $latestCountsOnly, $platform);`

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by chiragvels** [comment]
Hello Matt,

Never received the clarifying questions.

Can you please let me know what the questions about?

Thanks,

**Comment by mattwhisenhunt** [comment]
Can you reproduce this issue in [API Explorer](https://developers.google.com/apis-explorer/#p/webmasters/v3/) or [Try This API](https://developers.google.com/webmaster-tools/search-console-api-original/v3/urlcrawlerrorssamples/list?apix=true)?

**Comment by mattwhisenhunt** [comment]
@chiragvels is this something you are still trying to track down?

**Comment by chiragvels** [comment]
@mattwhisenhunt No, I am not able to reproduce same issue.
I am closing down this thread.
