### ISSUE TITLE
No full package download for RC6 ?

### ISSUE THREAD

**Issue by am63** [google/google-api-php-client#885]
Hi,

I have noticed that there's no full package (dependencies) download for RC6 release ? 

I tried to figure out which vendor/* packages have been updated since RC5 (for example, google/auth has been updated to 0.7), but a full dependencies packages would be appreciated.

I can't use composer because some hosters I'm using (hopefully, not all) don't provide me with ssh access, so running composer command lines is not possible (I know I could user PHP and exec() but error feedback would be a mess).

Thanks

**Comment by bshaffer** [comment]
@am63 The download is [here](https://github.com/google/google-api-php-client/releases/tag/v2.0.0-RC6). I think it was accidentally in draft mode.
