### ISSUE TITLE
Calendar API getStart()->dateTime

### ISSUE THREAD

**Issue by nickyoung87** [google/google-api-php-client#886]
Hello,

When getting the event start time using `getStart()->dateTime` the value returned is not always what is expected. The date is returned like this:

`2016-03-07T12:00:00-07:00`

This looks fine at first but the problem is when there is a timezone set at the event level. The example above is taken from an event that actually has the event timezone set as UTC-5. 

Is it possible the dateTime can return the actual time set of the event and not the adjusted time the calendar outputs? 

I was not sure if this is an issue with the PHP API or if it is something that would have to be changed on Google's end, any insight is appreciated.

Thanks!

**Comment by bshaffer** [comment]
Hello! 

The `dateTime` property will always be an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp, according to [the docs](https://developers.google.com/google-apps/calendar/v3/reference/events#resource-representations). You can use PHP's `DateTime` object from there:

```php
$d = new DateTime($event->dateTime);

var_dump($event->dateTime);
// string(25) "2016-03-07T12:00:00-07:00"
var_dump($d->format('Y-m-d'));
// string(10) "2016-03-07"
var_dump($d->format('U'));
// int(1457377200)
```

**Comment by nickyoung87** [comment]
Hey thanks for the response. We did end up figuring out the issue was deep within our code and were able to get it working how we need.
