### ISSUE TITLE
Drive: missing methods since switch to v3

### ISSUE THREAD

**Issue by Fneufneu** [google/google-api-php-client#888]
Since Feb 5, you switch Drive to v3 api but you miss lot's of new method that make the api usable,
like: parents.*, children.*, properties.*

Have you already worked on it or it'll be done in the futur ?
any ETA ?

**Comment by bshaffer** [comment]
bump!
![bump](https://cloud.githubusercontent.com/assets/103941/13789239/50cda182-eaa0-11e5-96e3-d6f75ef840f7.gif)

This issue will be closed if there is no response.

**Comment by Fneufneu** [comment]
Okey, i mean now in v3, files.get return only few settings and the object is almost empty: no filesize, md5, etc ... 
it miss properties and i can't a proper way to get it

**Comment by bshaffer** [comment]
Using the [API Explorer](https://developers.google.com/apis-explorer/#p/drive/v3/drive.files.get), you need to specify the fields you'd like to receive back:

```
GET https://www.googleapis.com/drive/v3/files/{YOUR_FILE_ID}?fields=md5Checksum%2Csize%2Cname&key={YOUR_API_KEY}
 
{
 "name": "FILE_NAME",
 "md5Checksum": "acbdefdb4ccacbdef4fccc4aacbdef",
 "size": "3"
}
```

Without actually testing it, this call should look something like this:

```php
$drive = new Google_Service_Drive($client);
$result = $drive->files->get($fileId, [
    'fields' => 'name,md5Checksum,size'
]);
```
