### ISSUE TITLE
Service definition for Webmasters (v3)

### ISSUE THREAD

**Issue by gaiterjones** [google/google-api-php-client#890]
I would like to access the "Links to your site" and "Google index" data. Am I correct in thinking that at the moment the data available from webmaster tools (search console) using Service definition for Webmasters (v3) is restricted to search analytics and crawl info.

**Comment by bshaffer** [comment]
The APIs exposed in this library mirror those available in the [apis explorer](https://developers.google.com/apis-explorer/#p/), so if the APIs you are looking for exist there, this library supports them. A cursory search shows no WebMasters API, however some of the other APIs may perform these services.
