### ISSUE TITLE
Documentation Request: Using APIs not in the discovery service

### ISSUE THREAD

**Issue by cedricziel** [google/google-api-php-client#897]
It would be great if there was a bit of documentation on how to use API endpoints that are now exposed in the discovery mechanism like various maps services.

I just discovered https://github.com/google/google-api-php-client/issues/855 and I wonder if there is more I need to care about than just authorizing the client with the key and executing the call.

**Comment by bshaffer** [comment]
This has been added to the README! See [Making HTTP Requests Directly](https://github.com/google/google-api-php-client#making-http-requests-directly)

**Comment by cedricziel** [comment]
Great, thx!
