### ISSUE TITLE
reopened: user to impersonate get authentication errors

### ISSUE THREAD

**Issue by jqr108** [google/google-api-php-client#898]
Same issue listed here, still happening:
https://github.com/google/google-api-php-client/issues/891

**Comment by bshaffer** [comment]
Have you tried reauthorizing the user you are impersonating?

**Comment by jqr108** [comment]
@bshaffer How do you go about reauthorizing an impersonated user?

**Comment by bshaffer** [comment]
@jqr108 I wrote about a few ways you can do this [here](https://github.com/google/google-api-php-client/issues/801#issuecomment-171417538)

**Comment by jqr108** [comment]
@bshaffer Thanks bshaffer, that did it!

Couple notes for anyone else with this issue that follows Option #2 above:

`$client->fetchAccessTokenFromAuthCode($code);`
should be
`$client->fetchAccessTokenWithAuthCode($code);`

and if you're using v1 you'll want to use 
`$client->authenticate($code);`
