### ISSUE TITLE
Connect to multiple memcache servers

### ISSUE THREAD

**Issue by jmcquillan** [google/google-api-php-client#899]
Google_Cache_Memcache seems to only allow for connecting to a single memcache host.  I need the ability to try multiple memcache hosts.

**Comment by bshaffer** [comment]
Yes, you're right. We should change this to accept a `Memcache` class as the first argument, or an array of configuration parameters (host, port, etc).

**Comment by bshaffer** [comment]
Closing, as all Cache classes have been removed in favor of PSR-6
