### ISSUE TITLE
Ability to commit multiple entities at once with Google_Service_Datastore_Commit_Request

### ISSUE THREAD

**Issue by adamcodes** [google/google-api-php-client#902]
Chances are that I'm doing this wrong. However, I wanted to double-check. Forgive me, I am new to this api and github in general.

Rather than looping over Google_Service_Datastore_CommitRequest for every row I want to commit, I saw that Commit supports multiple entities in the same request (https://cloud.google.com/datastore/docs/apis/v1beta2/datasets/commit).

However, I couldn't figure out how to set up my request. I tried setting my entities to an array:

```
$entity[] = new \Google_Service_Datastore_Entity([
                'key' => $keyset,
                'properties' => $properties
            ]);
```

And then sending it via CommitRequest:

```
$request = new \Google_Service_Datastore_CommitRequest([
            'mode' => 'NON_TRANSACTIONAL',
            'mutation' => [
                $insertParam => [$entity]
            ]
        ]);
```

However, the $postBody in Resources.php seemed to have an extra array element after the upsert. I was able to resolve my issue adding the following conditional after $postBody is set (line 115):

```
if ( isset($postBody['mutation']['upsert'][0]) ) {
        $postBody['mutation']['upsert'] = $postBody['mutation']['upsert'][0];
      }
```

This works for me but it feels kludgy. Please let me know if there is a better way. Thank you.

**Comment by tomwalder** [comment]
Have you considered using (my) wrapper library. Makes *most* Datastore operations trivial from PHP.

It supports "putting" multiple entities of the same Kind at once.

https://github.com/tomwalder/php-gds

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
