### ISSUE TITLE
Why not Logging API?

### ISSUE THREAD

**Issue by tmatsuo** [google/google-api-php-client#903]
I looked at [google-api-php-client-services](https://github.com/google/google-api-php-client-services) and noticed that the [Logging API](https://cloud.google.com/logging/docs/api/tasks/) is not there. Is it possible to add Logging API?

**Comment by bshaffer** [comment]
I was previously generating services for "stable only" apis (i.e. excluding `alpha` and `beta` releases).

I'll run the generator again for the remaining APIs

**Comment by bshaffer** [comment]
fixed in https://github.com/google/google-api-php-client-services/commit/7e193165bf66445ae0a6dd2e760311b1f595317b (see `Logging`)

**Comment by tmatsuo** [comment]
Sweet! Thanks!
