### ISSUE TITLE
YouTubeReporting.php not available in composer install

### ISSUE THREAD

**Issue by dafyddPrys** [google/google-api-php-client#904]
When installing v1-master with composer, the YouTubeReporting.php file does not exist in the src/Google/Service file.

I'm using the following command in my composer.json file (in the require):

     "google/apiclient" : "1.0.*@beta"

as instructed in the [installation guide.](https://developers.google.com/api-client-library/php/start/installation#requirements)

**Comment by bshaffer** [comment]
You'll want to use `1.1.*` to use the [YouTubeReporting](https://github.com/google/google-api-php-client/blob/v1-master/src/Google/Service/YouTubeReporting.php) service:

```
"google/apiclient" : "1.1.*"
```
