### ISSUE TITLE
Upload video to a specific channel

### ISSUE THREAD

**Issue by redayoub** [google/google-api-php-client#907]
Is there a way to let users upload a video from my website to my youtube channel (not their's) ?

**Comment by redayoub** [comment]
Up

**Comment by redayoub** [comment]
Any help please.

**Comment by redayoub** [comment]
up

**Comment by bshaffer** [comment]
Check out [this repo](https://github.com/youtube/api-samples/blob/master/php/) for a bunch of sample code. The [resumable upload](https://github.com/youtube/api-samples/blob/master/php/resumable_upload.php) sample specifically should have what you're looking for. Note these samples use an earlier version of the client library (`v1-master`), but should still work.
