### ISSUE TITLE
Resumable upload with Google Drive

### ISSUE THREAD

**Issue by Aspie96** [google/google-api-php-client#909]
Hi!

What is the correct code to perform the upload of a large file with the Drive APIs?

I've tried this script:
```
$chunkSize = 1024*1024; 
$request = $driveService->files->create(new Google_Service_Drive_DriveFile(array( 
    "name" => $filename, 
    "mimeType" => "audio/mp3")), array( 
    "mimeType" => "audio/mp3", 
    "uploadType" => "resumable")); 
$media = new Google_Http_MediaFileUpload($client, $request, "audio/mp3", null, true, $chunkSize); 
$media->setFileSize(filesize($fileToUpload)); 
$status = false; 
$handle = fopen($fileToUpload, "rb"); 
while(!$status && !feof($handle)) { 
    $chunk = fread($handle, $chunkSize); 
    $status = $media->nextChunk($chunk); 
} 
$client->setDefer(false);
```

But it is not working.

I get this error:
> Uncaught exception 'Google_IO_Exception' with message 'SSL read: error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac, errno 0'

Thank you very much in advance.

**Comment by bshaffer** [comment]
This looks to be an environmental issue with your SSL setup. [This SO article](http://stackoverflow.com/questions/4496941/curl-php-request-executes-50-of-the-time) may help. Additionally you can try using the `v2` version of this library, which supports Guzzle under the hood and so has better HTTP/SSL support.
