### ISSUE TITLE
as I can create a module in zend2 for api google drive?

### ISSUE THREAD

**Issue by losorio35** [google/google-api-php-client#910]
hi guys, I created a module to integrate google api v3 https://github.com/google/google-api-php-client/tree/v1-master with ZF2, which have not been successful, I uploaded has github module, to see if anyone can help me achieve the integration of the api. 

github https://github.com/losorio35/module-api-google-zf2/tree/master/Apigoogle

**Comment by bshaffer** [comment]
It looks like you've included the code to this library directly into your module. You should use `composer` to pull the library in, as what you are doing is definitely not recommended:

```
composer require google/apiclient:^1.1
```

Follow the [zf2 setup instructions](https://github.com/zendframework/zf2) for more information. Most likely, at some point you'll be adding `require "vendor/autoload.php";` to your front controller (`web/index.php`)

So, just to be clear, there should be no "module to integrate google api v3" necessary. Just use composer. 

Also, you've included your credentials in your repo ([here](https://github.com/losorio35/module-api-google-zf2/blob/master/Apigoogle/client_id.json) and [here](https://github.com/losorio35/module-api-google-zf2/blob/master/Apigoogle/oauth-credentials.json)). You will want to delete these credentials from the Cloud Console and make new ones, as they are now insecure.
