### ISSUE TITLE
Class 'Google_Service_Directory' not found

### ISSUE THREAD

**Issue by JBerkvens** [google/google-api-php-client#911]
Hello,
I'm trying to get my server application to add a new forwarding address, and I've read that I need to use the Google_Service_Directory class to do so, but when I create a new class I get a "not found" error.
Can someone help me with this?

**Comment by bshaffer** [comment]
Hi @JBerkvens, can you include the code you're using?

**Comment by JBerkvens** [comment]
<code>include_once "google-api-php-client/vendor/autoload.php";</code>
<code>$private_key_file = '/location/to/secret.json';</code>
<code>$scopes = array('https://www.googleapis.com/auth/admin.directory.group', 'https://www.googleapis.com/auth/admin.directory.group.member', 'https://www.googleapis.com/auth/admin.directory.user');</code>

<code>$client = new Google_Client();</code>
<code>putenv('GOOGLE_APPLICATION_CREDENTIALS='.$private_key_file);</code>
<code>$client->useApplicationDefaultCredentials();</code>
<code>$client->setScopes($scopes);</code>
<code>$service = new Google_Service_Directory($client); //Here I get the error.</code>
<code>$results = $service->members->listMembers('mailing@list.com', array())->getMembers();</code>
<code>print_r($results);</code>

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
