### ISSUE TITLE
Implementation "manage worksheet data"

### ISSUE THREAD

**Issue by stopsopa** [google/google-api-php-client#913]
Please implement "manage worksheet data"  (https://developers.google.com/google-apps/spreadsheets/data) in this library. There is no need to additionally include https://github.com/asimlqt/php-google-spreadsheet-client library to deal with such natural needed feature. 

Please, you really make my life easier this way (i guess not only my), especially that this additional/external library doesn't work for me, i,ve got Fatal error: Uncaught exception 'Google\Spreadsheet\UnauthorizedException' with message 'Access token is invalid' (i have Drive API enabled), instead that there is no problem with tokens when i'm using google-api-php-client
library to other available operations

**Comment by mattwhisenhunt** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
