### ISSUE TITLE
Posting Content to google plus

### ISSUE THREAD

**Issue by edreamzdotnet** [google/google-api-php-client#914]
I want post content(image video ) to google plus from third party website. I am using google plus Api. Able to fetch user profile information and access token also.  But facing problem to post content. link or code demo will helpfull.

**Comment by bshaffer** [comment]
There are samples for using Google+ [here](https://developers.google.com/+/web/samples/php) for the `v1-master` branch. We'll try to get them updated soon, but it's a good place to start.
