### ISSUE TITLE
How to consume a IAB 

### ISSUE THREAD

**Issue by NathanVss** [google/google-api-php-client#915]
Hello ! 
I'm currently using this lib to check one the server-side the validity of a IAB via its purchaseToken.
According to this doc section ( http://developer.android.com/google/play/billing/api.html#consume ) we can consume a purchase. But I can't find how to do that with this lib ? 

Thank you !

**Comment by bshaffer** [comment]
I do not think this API is included as one of this library's [API Services](https://github.com/google/google-api-php-client-services). However, if the Google Play Billing API supports HTTP, you can use this library by [Making HTTP Requests Directly](https://github.com/google/google-api-php-client#making-http-requests-directly).
