### ISSUE TITLE
Getting error - expecting T_CONSTANT_ENCAPSED_STRING ClientTest.php on line 21

### ISSUE THREAD

**Issue by cmohanraj10** [google/google-api-php-client#917]
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in C:\Inetpub\vhosts\BostonAdaptive.secureserver.net\jeefocus\testing\loginWithGmailPHP2\tests\Google\ClientTest.php on line 21

**Comment by bshaffer** [comment]
You are running a version of PHP not supported by this library. [PHP 5.4 and higher](https://github.com/google/google-api-php-client#requirements) are required for this library.
