### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Google_Auth_Exception' with message 'Could not json decode the access token' 

### ISSUE THREAD

**Issue by jcsvwinston** [google/google-api-php-client#922]
The request seems to be incompleted. If I change on file OAuth2.php file... (lines 346...)
$body = $request->getResponseBody();
    if (200 == $code) {
      echo "\n$body";
      print_r($request);

I receive the next response.

[transfer-encoding] => chunked
            [{
  "access_token" ] => "ya29..wQKKQCh8UWP
        )

    [responseBody:protected] => cbF2tpv70QmwTZ2DjnejAQny0y-vkvqL_G_6z45-hxuxl50J9dq_IgPsckHSYojWZq-05PjPrXNzwFv6kp4u2B64vjnA3tX-wmqJLbx6zXCkUcA07bylTCvVbVQ87TE8NDfxP",
  "token_type" : "Bearer",
  "expires_in" : 3600
}
    [expectedClass:protected] =>
    [expectedRaw:protected] =>
    [accessKey] =>

**Comment by bshaffer** [comment]
Sorry, I am not exactly sure what you are trying to do or what the issue is here.
