### ISSUE TITLE
GuzzleHttp Version PHP 5.4 Not supported

### ISSUE THREAD

**Issue by mjniuz** [google/google-api-php-client#926]
Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /var/www/vhosts/web/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

**Comment by bshaffer** [comment]
Use guzzle5 instead:

```bash
composer require guzzle\guzzlehttp:~5.2
```

Guzzle 6 is [not compatible with php 5.4](https://github.com/google/google-api-php-client/blob/master/.travis.yml#L27)
