### ISSUE TITLE
Where has YouTube.php gone?

### ISSUE THREAD

**Issue by cyphix333** [google/google-api-php-client#928]
I'm following the example guide here: https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/insert#examples

However when downloading this library the YouTube.php file wasn't included. Where has it gone? If it has been deleted then the documentation really should be updated.

**Comment by bshaffer** [comment]
Hi @cyphix333! Sorry you're having trouble. Can you explain what commands you used to download the library that didn't work?

You can [install via composer](https://developers.google.com/api-client-library/php/start/installation#cloning-from-github) (as recommended by the documentation above) or download from the [releases](https://github.com/google/google-api-php-client/releases) page. Either method should include the `YouTube.php` file.

**Comment by cyphix333** [comment]
I just downloaded it via GitHub via the download zip option. When I navigate to that directory on GitHub you will see the YouTube file isn't there.

I will try those other options - thanks!

**Comment by cyphix333** [comment]
Ok, I just downloaded it via the releases page and there is still no YouTube.php file in the Services directory. :(

The project I am working on atm doesn't use Composer, but I will use that option somehow if nothing else works.

**Comment by bshaffer** [comment]
@cyphix333 if you click on `google-api-php-client-2.0.0-RC7.zip` on the release page, you will download a package with all the dependencies. The `YouTube.php` class is at `vendor/google/apiclient-services/Google/Service/YouTube.php`:

<img width="1230" alt="screen shot 2016-04-18 at 10 20 02 am" src="https://cloud.githubusercontent.com/assets/103941/14613032/3d5bcdb2-054f-11e6-909f-53a4ecb3379a.png">

**Comment by cyphix333** [comment]
Ahhhh, my bad, I was looking in the `src` directory.

Do I need _all_ the files/folders from that directory?

Thanks for your help!

**Comment by bshaffer** [comment]
No, just the ones for the service you're using, i.e. 'YouTube.php' and everything in the `YouTube/` directory.

**Comment by cyphix333** [comment]
Great, thanks!
