### ISSUE TITLE
OAUTH2 problem

### ISSUE THREAD

**Issue by sergeinua** [google/google-api-php-client#929]
I'm trying to get data from GoogleAdWords via OAUTH2
I've set in auth.ini:

developerToken = "xxxxxx"
userAgent = "xxxxxxxxxx"
client_id = "xxxxxxxxxxxx-dhd9orivgglf2863p3o99afcaurnp9s4.apps.googleusercontent.com"
client_secret = "xxxxxxxxxxxxxxx"
refresh_token = "xxxxxxxxxxxx"

During the process of the authentification I'm getting the error:

Log in to your AdWords account and open the following URL: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=xxxxxxxx-dhd9orivgglf2863p3o99afcaurnp9s4.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadwords&access_type=offline After approving the token enter the authorization code here: Your OAuth2 Credentials are incorrect. Please see the GetRefreshToken.php example. { "error" : "invalid_request", "error_description" : "Missing required parameter: code" }

What am I doing wrong? Thnx

**Comment by mattwhisenhunt** [comment]
You may want to start with some example code from a different API just to get the OAuth2 part working: https://developers.google.com/gmail/api/quickstart/php

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We offered some guidance a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
