### ISSUE TITLE
Delivery Speed is cleared by the Google Side or the api client after update/patch the account shipping rates

### ISSUE THREAD

**Issue by tmp2000** [google/google-api-php-client#930]
I am testing the google content api which update the shipping price only.
The workflow is:
        $googleConfig = new Google_Config();
        $googleConfig->setClassConfig('Google_Cache_File', array('directory' =>"/tmppath"));

```
    $client = new Google_Client($googleConfig);
    $client_email = $configs->client_email;
    $private_key = $configs->private_key;

    $scopes = array("https://www.googleapis.com/auth/content");
    $credentials = new Google_Auth_AssertionCredentials(
        $client_email,
        $scopes,
        $private_key
    );
    $client->setAssertionCredentials($credentials);
    $this->merchant_id = $configs->merchantId;
    $this->service = new Google_Service_ShoppingContent($client);
$accountShipping = $this->service->accountshipping->get($this->merchant_id ,$this->merchant_id);
$rateTables=$accountShipping->getRateTables();
```

//The left flow is loop the ratetables and change the price value only. ..............
    foreach($rateTables as $rateTable){
        $rules=$rateTable->getContent();
        foreach($rules as $rule){
                       $price=$rule->getRate();
                        $price->setValue(22);
                }
$this->service->accountshipping->update($this->merchant_id,$this->merchant_id,$accountShipping);  

The problem is the delivery date is cleared which is already set by the admin GUI.
Is it the API bug?

**Comment by mattwhisenhunt** [comment]
Did you get this working yet?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
