### ISSUE TITLE
No such file : Service/Youtube.php

### ISSUE THREAD

**Issue by guizput** [google/google-api-php-client#931]
Hi,

I'm a little bit confused, because in every Youtue API samples, you require 'Google/Service/Youtube.php'.
However, when I browse this directory, I cannot see such a file... 
Can anyone help me understand this?

Thank you in advance.

**Comment by guizput** [comment]
Ok I found it in the Master V1 branch.

**Comment by khurramar** [comment]
@guizput can you link it here please?

**Comment by khurramar** [comment]
@guizput should you combine the files from v1 branch into the master branch?
