### ISSUE TITLE
Pass custom request options.

### ISSUE THREAD

**Issue by radzserg** [google/google-api-php-client#933]
Currently there's no way to pass custom guzzle request options. For example I want to get request stats or progress info. 

http://docs.guzzlephp.org/en/latest/request-options.html#on-stats

Currently there's no way to do that.

**Comment by radzserg** [comment]
Actually was able to do that. But it doesn't looks good. Have to override functions. 
```php
 $service = new Google_Service_Drive($client);
$client = $service->getClient();
$client->setDefer(true);
$request = $service->files->get($googleDriveId, ['alt' => 'media']);
$http = $client->authorize();

 try {
            $httpHandler = Google\Auth\HttpHandler\HttpHandlerFactory::build($client);
            $response = $httpHandler($request, [
                'progress' => function($downloadTotalSize, $downloadedSize, $uploadTotalSize, $uploadedSize) {
                    // do all work here
                }
            ]);
        } catch (GuzzleHttp\Exception\RequestException $e) {
            // if Guzzle throws an exception, catch it and handle the response
            if (!$e->hasResponse()) {
                throw $e;
            }

            $response = $e->getResponse();
        }

        return Google_Http_REST::decodeHttpResponse($response, $request, 'Google_Service_Drive_DriveFile');


```

**Comment by bshaffer** [comment]
Have you tried passing this in to the `$config` array in the Guzzle Client's constructor (`GuzzleHttp\Client::__construct($config)`)? These options are merged with the request options in [`prepareDefaults`](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L204). This means you Try this instead:

```php
$http = new GuzzleHttp\Client(/* pass options here */);
$client->setHttpClient($http);
// make your request...
```

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
