### ISSUE TITLE
When will the V1 version support setting the live streaming format options seperately?

### ISSUE THREAD

**Issue by cyphix333** [google/google-api-php-client#939]
https://developers.google.com/youtube/v3/live/docs/liveStreams#properties

For `cdn.format` is states:

> This property has been deprecated as of April 18, 2016. Instead, please use the cdn.frameRate and cdn.resolution properties to specify the frame rate and resolution separately.

Though I couldn't see a way to set these separately.

**Comment by bshaffer** [comment]
You are right, for the `v1` version of this library these options are not available. You can see in the current version they are supported as part of the [CdnSettings](https://github.com/google/google-api-php-client-services/blob/master/YouTube/CdnSettings.php) object.

**Comment by bshaffer** [comment]
This is definitely a hack, but try the following commands:

```sh
cd /path/to/google-api-php-client
rm src/Google/Service/YouTube.php 
composer require google/apiclient-services
```

Now when you include the autoloader, it will include all the services from [google-api-php-client-services](https://github.com/google/google-api-php-client-services).

When composer installs, the only files you really need are those in the [YouTube Directory](https://github.com/google/google-api-php-client-services/tree/master/YouTube) and [YouTube.php](https://github.com/google/google-api-php-client-services/tree/master/YouTube.php), so alternatively you can just copy those over to your project and include them.

**Comment by bshaffer** [comment]
Once #952 is merged, you will be able to get the latest services using composer:

```
composer require google/apiclient-services
```

Then, as long as you include composer's autoloader, you'll use the updated services instead of the services included directly in `google/apiclient:v1`

**Comment by keskedememek** [comment]
REMOVE ME

2016-05-18 3:51 GMT+03:00 Brent Shaffer <notifications@github.com>:

**Comment by bshaffer** [comment]
This is now fixed, and the latest service classes can be used in `v1-master`. See the [README](https://github.com/google/google-api-php-client-services#usage-in-v1)
