### ISSUE TITLE
Rethink the caching layer

### ISSUE THREAD

**Issue by bshaffer** [google/google-api-php-client#941]
We have had a few ways of tackling the caching problem in this library and [google/google-auth-library-php](https://github.com/google/google-auth-library-php) (#905, #925), and both of these feel like a hack.

To begin addressing this problem at its core, we should consider implementing [PSR-6](http://www.php-fig.org/psr/psr-6/) interfaces in both libraries. With this, we could do one or more of the following:

- Use `isHit` to determine if a new access token has been created
- Refactor all `Google/Cache` classes OR remove them in favor of a standard PHP caching library
   - PROS: We've already written the code, refactoring shouldn't be too difficult
   - CONS: one more PHP caching library in the universe to be maintained
- Just remove *all* cache classes and default cache logic, and only provide a getter/setter for users to add this.
   - PROS: There is not really a single lightweight caching library that i have found (maybe [`doctrine/cache`](https://github.com/symfony/cache))? So it seems best to leave this up to the users.
   - CONS: Some things (such as fetching certs) should *always* be cached, so not including a default implementation is cruel

We may also be concerned that [not everyone in the community is stoked about PSR-6](http://andrewcarteruk.github.io/programming/2015/12/07/psr-6-has-serious-problems.html#disqus_thread), although regardless of your feelings on PSR-6, it's gotta be better than using [our oversimplified interface](https://github.com/google/google-auth-library-php/blob/master/src/CacheInterface.php)...

**Comment by Behunin** [comment]
PSR-6! 😁 That guys bias against PSR-6 is ill founded, and is proven as such in the comments.

**Comment by bshaffer** [comment]
I am leaning towards the following implementation:

- Implement PSR6
- Remove `CacheInterface` from `google/auth`
- Remove all files in [`src/Google/Cache`](https://github.com/google/google-api-php-client/tree/master/src/Google/Cache) except for the file cache
- Use File Cache as the default for storing certs
- That's it!

Pros:
 - Easy
 - Simplified
 - A default cache is provided
 - We aren't depending on any 3rd party caching library
Cons:
 - There is still no per-session caching of tokens 
 - It's still not straightforward when a token has been received. We will need to document this.

**Comment by bshaffer** [comment]
Added in #108
