### ISSUE TITLE
refreshTokenWithAssertion  Failing reauthentication

### ISSUE THREAD

**Issue by jmckay56** [google/google-api-php-client#942]
I am running a script to patch 2000 business using Google My Business
At record 900 i get 
"code": 401,
    "message": "Request had invalid authentication credentials.",

Before each curl call I am checking the token

if ($client->isAccessTokenExpired()) {
            $oauth2Token = $client->refreshTokenWithAssertion()['access_token'];
 }

Are there any timeout issues here?  Is this the correct implementation for  "google/apiclient": "2.0.0-RC7"

**Comment by jmckay56** [comment]
I am running a script to patch 2000 business using Google My Business
At record 900 i get 
"code": 401,
"message": "Request had invalid authentication credentials.",

Before each curl call I am checking the token
I am getting a UNAUTHENTICATED error between 900 and 1000 records when doing a test update

if ($client->isAccessTokenExpired()) {
$oauth2Token = $client->refreshTokenWithAssertion()['access_token'];
}

Are there any timeout issues here? Is this the correct implementation for "google/apiclient": "2.0.0-RC7"

**Comment by bshaffer** [comment]
What you are doing looks correct. It does seem like `refreshTokenWithAssertion` is not successfully fetching the token.

I would debug what is being returned first, and see if that sheds any light on the issue.  If a JSON error is the response from the HTTP server, then that error will be returned from `refreshTokenWithAssertion`:

```php
if ($client->isAccessTokenExpired()) {
    $result = $client->refreshTokenWithAssertion();
    if (!isset($result['access_token'])) {
        throw new \Exception('unexpected response: ' . json_encode($result));
    }
    $oauth2Token = $result['access_token'];
}
```

 If that doesn't work, you should be able to use a web proxy like [Charles](https://www.charlesproxy.com/) to debug the `HTTP` request going across the wire:

```php
$client = new Google_Client;
$http = new GuzzleHttp\Client([
    'proxy' => 'localhost:8888', // this is where charles is running
    'verify' => false,
]);
$client->setHttpClient($http);
```

**Comment by bshaffer** [comment]
This issue has been closed due a lack of response. Please reopen with more information if the problem is still occurring.
