### ISSUE TITLE
Where is the file saved to?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [google/google-api-php-client#945]
After making a service account and using the simple-file-upload.php code to upload a file, I cant find it anywhere in my drive, and going to the link posted even with the super administrator account logged in, I still have to request permission, from whom I do not know!

**Comment by bshaffer** [comment]
Service accounts have their own user id for Drive, so you can access those files via the service account, but (AFAIK) you can't log in and see them in the UI anywhere.
