### ISSUE TITLE
commentThreads method in Google_Service_YouTube dont exist

### ISSUE THREAD

**Issue by mgodinez98** [google/google-api-php-client#946]
i try to run that example https://github.com/youtube/api-samples/blob/master/php/comment_handling.php but in line 76 crash

**Comment by bshaffer** [comment]
What is the error you are receiving? Please provide all relevant code and output so we can help identify the issue.

**Comment by sumitdnit** [comment]
error message is: "Undefined property: Google_Service_YouTube::$commentThreads" .
I found "public $commentThreads & public $comments" is not in "Youtube.php" file in below path "vendor\google\apiclient\src\Google\Service"

**Comment by khurramar** [comment]
I can't even discover **Google/Service/YouTube.php** at all in api. That leads all example php files with error at 2nd require_once  

> require_once(Google/Service/YouTube.php): failed to open stream

Nothing found about it...

**Comment by bshaffer** [comment]
@mgodinez98 @khurramar
This sample is out-of-date. I've submitted [a PR to fix it](https://github.com/youtube/api-samples/pull/78). In the meantime, commentThreads and comments [are definitely a part of YouTube.php](https://github.com/google/google-api-php-client-services/blob/master/YouTube.php#L58).

Try using the [composer](http://getcomposer.org) autoloader:

```php
# if installing via composer
require_once '/path/to/my-project/vendor/autoload.php';
# If installing via downloaded release
require_once '/path/to/google-api-php-client/vendor/autoload.php';
```

Everything else should be the same. Let me know if you have any other questions.
