### ISSUE TITLE
Error deleting objects from GCS

### ISSUE THREAD

**Issue by paulcanning** [google/google-api-php-client#953]
I am receiving errors when deleting objects in a bucket. The object is removed, but the error shows regardless.

In https://github.com/google/google-api-php-client/issues/78 it was due to gzip being enabled for older versions of PHP. However, I am using PHP 5.6 and I believe gzip is the issue.

The error I get is:

> HTTP Error: Unable to connect: 'fopen(compress.zlib://https://www.googleapis.com/storage/v1/b/MY_BUCKET/o/MY_FILE.JPG?key=d687c7417ba524c0fe64905a23250af5e5e0c332): failed to open stream: operation failed'

**Comment by paulcanning** [comment]
In fact, I just added the following to the Google_Client() config and the error has gone.

> $client->setClassConfig('Google_Http_Request', 'disable_gzip', true);

Could it be my WAMP install is lacking GZIP? I cannot seem to find any mention of it in the Apache or PHP settings.

**Comment by bshaffer** [comment]
I am closing this as it's an issue with your environment and not this library. I imagine it is an issue with certain versions of PHP on windows.
