### ISSUE TITLE
Possibly provide in memory implementation

### ISSUE THREAD

**Issue by bshaffer** [google/google-api-php-client#954]
If `useApplicationDefaultCredentials` is set, a new token will be requested on each call by default. This is because we don't supply a default cache, or a default token callback. We should do one of the following:

 - Include [this in-memory PSR6 implementation](https://github.com/php-fig/cache-util/pull/2/files) for very basic caching, or just create our own.
 - Include [stashphp](http://stashphp.com)
 - provide a default token callback to call `Google_Client::setAccessToken` property when a token is fetched.

**Comment by Behunin** [comment]
Stash the json

**Comment by bshaffer** [comment]
This is being added to the underlying auth library in https://github.com/google/google-auth-library-php/pull/126

**Comment by bshaffer** [comment]
Added in #1019
