### ISSUE TITLE
Start and end times must either both be date or both be dateTime

### ISSUE THREAD

**Issue by giwrgos88** [google/google-api-php-client#955]
Hello, I'm getting the following error message everytime when I'm trying to make a POSt to google service "Start and end times must either both be date or both be dateTime". The dates have the following format from the database "2016-05-20 17:04:17" and in order to make it RFC3339 I used the following method 
`date("c", strtotime($eventModel->event_ends_datetime));`

Still getting the error code so I used the DateTime class of php with createFromFormat but still the same error. Does anyone knows how I can fix it?

**Comment by Behunin** [comment]
What API are your targeting? Calendars?

**Comment by giwrgos88** [comment]
yes the calendars

**Comment by Behunin** [comment]
The best way I have found to submit dateTime to google is to instantiate the DateTime class in php and then format it to the DATE_ATOM format, [which PHP recommends for ISO-8601 compatibility](http://php.net/manual/en/class.datetime.php).
`$format = 'Y-m-d\TH:i:sP';	//DATE_ATOM`
`$endDate = new DateTime($eventModel->event_ends_datetime);`
`$endsDate = $endDate->format($format);`

**Comment by giwrgos88** [comment]
@Behunin is working with your way, thanks a lot
