### ISSUE TITLE
Google Calendar Api is setting wrong time on an event (Calendar)

### ISSUE THREAD

**Issue by giwrgos88** [google/google-api-php-client#957]
Hello, I want to set a specific date and time on the Google Calendar Event. So I used the Google_Service_Calendar_EventDateTime to set my starting and end time. Then I formated the time to have the accepted format that Google is asking. So instead of setting the time to 11:25 it sets it to 2:25pm for start and for end instead of 11:55 it sets it to 2:55p. If I do a var_dump to the Google_Service_Calendar_EventDateTime is shows me the correct time. Here is my code

```php
            $eventService = new Google_Service_Calendar_Event();
            $format = 'Y-m-d\TH:i:sP';
            $starDate = new \DateTime($event->calendar_starts_datetime);
            $event->calendar_starts_datetime = $starDate->format($format);
            $endDate = new \DateTime($event->calendar_ends_datetime);
            $event->calendar_ends_datetime = $endDate->format($format);
            $start->setDateTime($event->calendar_starts_datetime);
            $end->setDateTime($event->calendar_ends_datetime);
            $start->setTimeZone('Europe/Athens');
            $end->setTimeZone('Europe/Athens');
            $eventService->setStart($start);
            $eventService->setEnd($end);
```
Does anyone knows how i can fix this issue? So if I put star time 10:00 and end time 20:00 to set it 10am and 8pm to calendar?

**Comment by Behunin** [comment]
Sorry, I should have mentioned this before, with PHP DateTime, the Timezone is set to the servers default timezone if you don't set the Timezone when you instantiate DateTime. 
This should work for you:
`$starDate = new \DateTime($event->calendar_starts_datetime, new DateTimeZone("Europe/Athens"));`
`$endDate = new \DateTime($event->calendar_ends_datetime, new DateTimeZone("Europe/Athens"));`
Then remove both:
`$start->setTimeZone('Europe/Athens');`
`$end->setTimeZone('Europe/Athens');`
FYI Timezone has to be set this way( i.e.)
`$date->setTimeZone(new DateTimeZone("Europe/Amsterdam");`

**Comment by giwrgos88** [comment]
It is working thanks a lot for your help
