### ISSUE TITLE
Classroom new methods ?

### ISSUE THREAD

**Issue by sergicurtu** [google/google-api-php-client#958]
Api classroom has been updated a few days ago with new features to Create assignments, modify student work, retrieve course content.

But I cant access new resources CourseWork & StudentSubmission  because I dont find the new methods : courses.courseWork.create , .get, .list , ...

**Comment by bshaffer** [comment]
@sergicurtu thanks for the heads up! These models have been created [here](https://github.com/google/google-api-php-client-services). 

If you want the latest version, set your `minimum-stability` to `dev` and request any version of this library:

```json
{
    "require": {
        "google/apiclient": "*"
    },
    "minimum-stability":"dev"
}
```
