### ISSUE TITLE
How to get Cloud Storage usage?

### ISSUE THREAD

**Issue by paulcanning** [google/google-api-php-client#963]
Is it possible to somehow get the data usage of GCS?

I am looking at the Cloud Monitoring class, but it seems to be based on the older API (v2) and even if that version can do it, I'm unsure how to get it working.

I want to be able to see how much space is being used in total, maybe with the billing cost?

**Comment by bshaffer** [comment]
See [The Storage FAQ](https://cloud.google.com/storage/docs/faq#policy) for an answer to this question:

> **How can I get a summary of daily space usage?**
> You can use the gsutil du command to display the total space used by all objects for a specified bucket. For example, to get the total space used by all objects in the bucket "bucketname", use the command:
>
>     gsutil du -sh gs://bucketname
>
> See the du command help for more options you can use, including how to return the size of all objects underneath a prefix. 
> 
> You can also set up bucket logging where the total size of a bucket is automatically reported once a day. For more information, see [Access Logs & Storage Data](https://cloud.google.com/storage/docs/access-logs). If the number of objects in your bucket is large (e.g., hundreds of thousands or millions), this is a much more efficient way to track space usage. The gsutil du command calculates space usage by making bucket listing requests, which can take a long time for large buckets.

**Comment by paulcanning** [comment]
So, no way other then using command line?

**Comment by paulcanning** [comment]
Do you know of any way what-so-ever to do this via PHP?

**Comment by bshaffer** [comment]
Please note that this issue tracker is only for this client library. We do not maintain the APIs that this client library talks to. If you have an issue or questions with how to use a particular API, you are better off posting on Stackoverflow under the `google-api` tag.

That being said, you could try using the JSON API to pull down the [access logs](https://cloud.google.com/storage/docs/access-logs) and derive your usage from there.
