### ISSUE TITLE
Error when verifying token

### ISSUE THREAD

**Issue by startDaemons** [google/google-api-php-client#964]
I'm getting a fatal error when verifying the token after updating to 2.0.0-RC8.

PHP Fatal error:  Uncaught Error: Call to undefined method Stash\\Pool::save() in .../vendor/google/apiclient/src/Google/AccessToken/Verify.php:186

I haven't tested it with the master branch but skimming the code it looks like it would have the same result.

**Comment by bshaffer** [comment]
This is an interesting error. You can see [here](https://github.com/tedious/Stash/blob/master/src/Stash/Pool.php#L162) that `Stash\Pool::save` does exist. Is it possible you're using a different, older version of Stash?

**Comment by startDaemons** [comment]
Yep I had an old version Stash in my composer.json
