### ISSUE TITLE
Update to google-auth 0.9 to support newer Guzzle version

### ISSUE THREAD

**Issue by bencromwell** [google/google-api-php-client#969]
I already have Guzzle so can't use this until it's updated to use google-auth v0.9

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Installation request for google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0].
    - Conclusion: remove guzzlehttp/psr7 1.3.0
    - Conclusion: don't install guzzlehttp/psr7 1.3.0
    - google/auth v0.8 requires guzzlehttp/psr7 1.2.* -> satisfiable by guzzlehttp/psr7[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - Can only install one of: guzzlehttp/psr7[1.2.0, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.1, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.2, 1.3.0].
    - Can only install one of: guzzlehttp/psr7[1.2.3, 1.3.0].
    - Installation request for guzzlehttp/psr7 (locked at 1.3.0) -> satisfiable by guzzlehttp/psr7[1.3.0].
```

**Comment by bshaffer** [comment]
@bencromwell I have opened a PR to fix this, but please tell me why it's so important to use `guzzlehttp/psr7:1.3.0`?

**Comment by bshaffer** [comment]
@bencromwell try adding `"google/apiclient": "^2.0"` directly to `composer.json` and running `composer update` and you'll have a better time.

Composer won't update your existing deps unless you run `composer update`, so it behaves differently when you simply use `composer require`, and in this case, throws an error.

**Comment by bencromwell** [comment]
I see what you mean - at first I thought you meant the package in general now I see you meant that specific version. 

Composer update does indeed work: 
  - Removing guzzlehttp/psr7 (1.3.0)
  - Installing guzzlehttp/psr7 (1.2.3)
    Downloading: 100%         

Can only assume judging by semver that any implementation using these deps (older version) is missing backwards compatible fixes.

Thanks for opening the PR :+1:
