### ISSUE TITLE
Cannot install library using composer

### ISSUE THREAD

**Issue by manojmilani123** [google/google-api-php-client#971]
Hi

I am trying to install this package/library using composer but it gives me below error:

**Problem 1
    - The requested package google/apiclient No version set (parsed as 1.0.0) is satisfiable by google/apiclient[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0].
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8] but these conflict with your requirements or minimum-stability.**

Any fix?

Thanks,
Manoj M

**Comment by bshaffer** [comment]
@manojmilani123 have you tried adding this dependency directly to your composer file and running composer update? i.e.:

```
{
  "require": {
    //...
    "google/apiclient": "^2.0",
  }
}
```

And now run `composer update`. This should install the library successfully.

**Comment by bshaffer** [comment]
see [this duplicate issue](https://github.com/google/google-api-php-client/issues/969#issuecomment-224758153)

**Comment by arafathussein** [comment]
any solution for this issue?

**Comment by bshaffer** [comment]
Try adding `"google/apiclient": "^2.0"` directly to `composer.json` and running `composer update` and you'll have a better time.

Composer won't update your existing deps unless you run `composer update`, so it behaves differently when you simply use `composer require`, and in this case, throws an error.

**Comment by anmolio** [comment]
@bshaffer  : Still facing the same issue ! What to do ?

**Comment by mediatomcat** [comment]
Did you ever find a solution?

**Comment by ipsjolly** [comment]
- Install [Composer](https://getcomposer.org/download/) (PHP Package manager like NPM).
- Create a new folder "GoogleAPI".
- Create a new file composer.json with the following content.

```
{
  "require": {
    "google/apiclient": "^2.0"
  }
}
```
- Open CMD from this folder (GoogleAPI)
- Run following command in CMD
`composer update`

Then it will start loading files....
