### ISSUE TITLE
Can not change the path of stored file on google

### ISSUE THREAD

**Issue by harshal-ytel** [google/google-api-php-client#974]
I uploaded the file on storage using APi but I want different path . But unable to change that.

**Comment by bshaffer** [comment]
You should be able to make a [patch](https://cloud.google.com/storage/docs/json_api/v1/objects/patch) request and change the name in the [request body](https://cloud.google.com/storage/docs/json_api/v1/objects). 

If not, you can definitely [copy it](https://cloud.google.com/storage/docs/json_api/v1/objects/copy).
