### ISSUE TITLE
Laravel 4.2 compatibility 

### ISSUE THREAD

**Issue by techiemon** [google/google-api-php-client#977]
Do you see any issue with updating to phpseclib v 2.0+  https://github.com/phpseclib/phpseclib/tree/2.0

Laravel 4.2 cannot install google-api-php-client because phpseclib v 2.0 is required.

**Comment by bshaffer** [comment]
phpseclib in this library is v2.0. In laravel 4.2 they require [`0.3.*`](https://github.com/laravel/framework/blob/4.2/composer.json#L22)

**Comment by bshaffer** [comment]
Try installing [laravel 5.2](https://github.com/laravel/framework/blob/5.2/composer.json) or use `v1-master` of this library to get around the issue. We could also consider moving `phpseclib` to an optional dependency, if this continues to be a problem

**Comment by techiemon** [comment]
Thanks!  I believe the v1-master branch worked, it certainly installs fine.  It's a existing project so laravel 5.2 is to much of a leap.
