### ISSUE TITLE
when i use Service Mode

### ISSUE THREAD

**Issue by toohamster** [google/google-api-php-client#980]
Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Error c
alling POST https://www.googleapis.com/upload/youtube/v3/videos?part=status%2Csn
ippet&uploadType=multipart: (401) Unauthorized' in C:\work\space\source\ws\vendo

**Comment by bshaffer** [comment]
Looks like you are not providing any authentication (hence the `401 Unauthorized` status code)

**Comment by bshaffer** [comment]
Make sure the environment variable `GOOGLE_APPLICATION_CREDENTIALS` is set, and is a valid path to the service account credentials on your machine.

```php
putenv('GOOGLE_APPLICATION_CREDENTIALS=/path/to/my-project-credentials.json');
```
