### ISSUE TITLE
Certificates caches ttl is too long and does not invalidate 

### ISSUE THREAD

**Issue by staelche** [google/google-api-php-client#982]
It seems like that the default ttl of the PSR 6 compliant cache library you use is set to 5 days which is too long, I think.

If you create the cache you should set a proper ttl.

    // Verify.php
    if (is_null($cache) && class_exists('Stash\Pool')) {
      $cache = new Pool(new FileSystem);
    }

Furthermore, the cache entries don't get invalidated. I didn't look too close into it but this could be an issue of the library, as well.

Library Version: v2.0.1

**Comment by bshaffer** [comment]
Why is 5 days too long? Also cache invalidation should not handled by this library, but by the PSR-6 compatible caching libraries.
