### ISSUE TITLE
Invalid token format

### ISSUE THREAD

**Issue by ace411** [google/google-api-php-client#984]
I keep getting the following error message whenever I run my PHP script.

Fatal error: Uncaught InvalidArgumentException: Invalid token format in C:\xampp\htdocs\fair\vendor\google\apiclient\src\Google\Client.php:423 Stack trace: #0 C:\xampp\htdocs\fair\index.php(42): Google_Client->setAccessToken(Array) #1 C:\xampp\htdocs\fair\index.php(52): getClient() #2 {main} thrown in C:\xampp\htdocs\fair\vendor\google\apiclient\src\Google\Client.php on line 423

Below is the code:

define('APPLICATION_NAME', 'Sample Sheets');
define('CLIENT_SECRET_PATH', $dir.'client_secret.json');
define('CREDENTIALS_PATH', $dir.'credentials.json');
define('SCOPES', implode(' ', array(
        Google_Service_Sheets::SPREADSHEETS_READONLY
    )                        
));
function getClient() {
    $client = new Google_Client();
    $client->setApplicationName(APPLICATION_NAME);
    $client->setScopes(SCOPES);
    $client->setAuthConfigFile(CLIENT_SECRET_PATH);
    $client->setAccessType('offline');

    // Load previously authorized credentials from a file.
    if (file_exists(CREDENTIALS_PATH)) {
        $accessToken = file_get_contents(CREDENTIALS_PATH);
    } else {
    // Request authorization from the user.
    $authUrl = $client->createAuthUrl();
    printf("Open the following link in your browser:\n%s\n", $authUrl);
    print 'Enter verification code: ';
    $authCode = trim(fgets(STDIN));

    // Exchange authorization code for an access token.
    $accessToken = $client->authenticate($authCode);

    // Store the credentials to disk.
    if(!file_exists(dirname($credentialsPath))) {
      mkdir(dirname($credentialsPath), 0700, true);
    }
    file_put_contents($credentialsPath, $accessToken);
    printf("Credentials saved to %s\n", $credentialsPath);
    }
    $client->setAccessToken($accessToken);

    // Refresh the token if it's expired.
    if ($client->isAccessTokenExpired()) {
    $client->refreshToken($client->getRefreshToken());
    file_put_contents($credentialsPath, $client->getAccessToken());
    }
    return $client;
}

$client = getClient();
$service = new Google_Service_Calendar($client);
$spreadsheetId = "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms";
$range = "Class Data!A2:E";
echo CREDENTIALS_PATH;
$response = $service->spreadsheets_values->get($spreadsheetId, $range);
$values = $response->getValues();
var_dump($values);

**Comment by bshaffer** [comment]
This is because the `$accessToken` variable being supplied to `Google_Client::setAccessToken` is not in the proper format. The error is thrown when the array key `access_token` does not exist. 

This is because your call to `Google_Client::authenticate` is returning an *error response*. The error is JSON when it comes back from the API, so it's returned as an array.  Try `var_dump($accessToken);` to see what the error is.

**Comment by seliver** [comment]
this is happening because the documentation is outdated. check here: https://stackoverflow.com/questions/39792859/google-oauth-2-0-with-service-account-with-php-invalid-token-format-error

**Comment by saifrehman15** [comment]
I have the same issue but above solution not working for me . 


Fatal error: Uncaught InvalidArgumentException: invalid json token in E:\xampp\htdocs\php-oauth2-example\vendor\google\apiclient\src\Google\Client.php:430 Stack trace: #0 E:\xampp\htdocs\php-oauth2-example\index.php(71): Google_Client->setAccessToken(NULL) #1 E:\xampp\htdocs\php-oauth2-example\index.php(95): getClient() #2 {main} thrown in E:\xampp\htdocs\php-oauth2-example\vendor\google\apiclient\src\Google\Client.php on line 430

**Comment by DmitriyChiroky** [comment]
just use $client->setAuthConfig( $accessToken );
instea $client->setAccessToken($accessToken);
