### ISSUE TITLE
proxy no working

### ISSUE THREAD

**Issue by orvice** [google/google-api-php-client#987]
Hi, I following this to set proxy:

```
// FOR DEBUGGING ONLY
$httpClient = new GuzzleHttp\Client([
    'proxy' => 'localhost:8888', // by default, Charles runs on localhost port 8888
    'verify' => false, // otherwise HTTPS requests will fail.
]);

$client = new Google_Client();
$client->setHttpClient($httpClient);
```

but it doesn't work,and if I try to set ` export https_proxy=127.0.0.1:10245 ` , the proxy is working.

**Comment by bshaffer** [comment]
@orvice What proxy application are you using? It looks like your proxy is listening on a different port. Try changing my example code to:

```php
$httpClient = new GuzzleHttp\Client([
    'proxy' => '127.0.0.1:10245', // since this is what yours is running on
    'verify' => false, // otherwise HTTPS requests will fail.
]);
```

**Comment by orvice** [comment]
@bshaffer 
Hi,  
```
$httpClient = new GuzzleHttp\Client([
    'proxy' => '127.0.0.1:10245', // since this is what yours is running on
    'verify' => false, // otherwise HTTPS requests will fail.
]);
```
its still not working, and this proxy is working in my chrome.

**Comment by bshaffer** [comment]
What proxy software are you using? And what are you using the proxy for?

**Comment by orvice** [comment]
hi, I am using privoxy to cover a socket proxy to http  proxy,and this http proxy is working in chrome.

because google is blocked in china.

**Comment by bshaffer** [comment]
Using privoxy, I was able to do the following and get this to work:

```php
$httpClient = new GuzzleHttp\Client([
    'proxy' => '127.0.0.1:8118', // this is the default privoxy port
    'verify' => false, // otherwise HTTPS requests will fail (THIS IS FOR DEBUGGING ONLY)
]);
```
