### ISSUE TITLE
google analytic offline access issue

### ISSUE THREAD

**Issue by ashik906** [google/google-api-php-client#992]
Hello

**I given full path for credentialsfile**

$credentialsFile = '/var/www/html/example.com/analiytics/client_secrets.json';
$client->setAuthConfig($credentialsFile);

This error genrate

Deprecated: google-api-php-client's autoloader was moved to vendor/autoload.php in 2.0.0. This redirect will be removed in 2.1. Please adjust your code to use the new location. in /var/www/html/example.com/analiytics/google-api-php-client-2.0.0/src/Google/autoload.php on line 19

and also every time link redirect to google authentication url after show data

Deprecated: google-api-php-client's autoloader was moved to vendor/autoload.php in 2.0.0. This redirect will be removed in 2.1. Please adjust your code to use the new location. in /var/www/html/example.com/analiytics/google-api-php-client-2.0.0/src/Google/autoload.php on line 19

First view (profile) found: All Web Site Data

Total sessions: 50

Total Pageviews: 124

Total User: 27

Thankyou

**Comment by bshaffer** [comment]
The error states the use of the file `src/Google/autoload.php` is deprecated, and instead you need to use `vendor/autoload.php`. If you follow what the error states, and update all includes to the new file location, the error will be resolved. i.e:

```php
// what you have now:
require_once '/path/to/google-api-php-client/src/Google/autoload.php';
// what you should update it to:
require_once '/path/to/google-api-php-client/vendor/autoload.php';
```

**Comment by kamleshwebtech** [comment]
I am using zend framework 3 version, included autoload.php file in controller file

require_once(ROOT_PATH.'/vendor/google-api-php-client-2.4.0/vendor/autoload.php');

now when i call "$client = new Google_Client();" it returns me an error 

'Google_Client' not found while i am using latest SDK downloaded without composer from https://github.com/googleapis/google-api-php-client/releases

Kindly share your suggest to get this issue fixed. Thanks in advance.
