### ISSUE TITLE
Empty uploaded file, Google Drive PHP API

### ISSUE THREAD

**Issue by shubaivan** [google/google-api-php-client#997]
I upload file some formats and in google drive have file with empty body. Why not understand

I install google api client 

            "name": "google/apiclient",
            "version": "1.1.7",

and try upload file in google dics
I get access token help with HWIO bundle, add scope 

    scope:               
    "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive"

and get accesToken like this 

    {"access_token":"TOKEN", "refresh_token":"TOKEN", "token_type":"Bearer",
     "expires_in":3600, "id_token":"TOKEN", "created":1320790426}

beign I try upload exist file (doc, pdf, img)

        $client = $this->get('artel.google.api.client');

        /** @var CodeUserReference[] $accessToken */
        $accessToken = $this->get('doctrine.orm.entity_manager')->getRepository('ArtelProfileBundle:CodeUserReference')
            ->getReferenceAccessClient($user);
        if ($accessToken) {
            $client->setAccessToken($accessToken[0]->getAccessTokenClient());
        } else {
            $view = $this->view(['No accessToken was found for this user id'], 400);
            return $this->handleView($view);
        }
        $service = new \Google_Service_Drive($client->getGoogleClient());
        $file = new \Google_Service_Drive_DriveFile();
        $file->setName($request->request->get('title')
            ? $request->request->get('title')
            : $request->files->get('file')->getClientOriginalName()
        );
        $file->setDescription($request->request->get('description'));
        $file->setMimeType($request->request->get('mimeType')
            ? $request->request->get('mimeType')
            : $request->files->get('file')->getClientMimeType()
        );

        // Set the parent folder.Google_Service_Drive_ParentReferen, this class not find in google/apiclient, version": "1.1.7", I don\'t know why..(
        if ($request->request->get('parentId') != null) {
            $parent = new Google_Service_Drive_ParentReferen();
            $parent->setId($request->request->get('parentId'));
            $file->setParents(array($parent));
        }

        try {
            $data = $request->files->get('file');

            $createdFile = $service->files->create($file, array(
                'data' => $data,
                'mimeType' => $request->request->get('mimeType')
                    ? $request->request->get('mimeType')
                    : $request->files->get('file')->getClientMimeType(),
                'uploadType' => 'media'
            ));

            // Uncomment the following line to print the File ID
            // print 'File ID: %s' % $createdFile->getId();
            return View::create()
                ->setStatusCode(200)
                ->setData([$createdFile]);

        } catch (\Exception $e) {
            $view = $this->view((array) $e->getMessage(), 400);
            return $this->handleView($view);
        }

have response 

    
      {
    "internal_gapi_mappings": [],
    "model_data": [],
    "processed": [],
    "collection_key": "spaces",
    "capabilities_type": "Google_Service_Drive_DriveFileCapabilities",
    "capabilities_data_type": "",
    "content_hints_type": "Google_Service_Drive_DriveFileContentHints",
    "content_hints_data_type": "",
    "id": "0B2_i_Tc5Vr8UWV9Jc2psQkhqS3M",
    "image_media_metadata_type": "Google_Service_Drive_DriveFileImageMediaMetadata",
    "image_media_metadata_data_type": "",
    "kind": "drive#file",
    "last_modifying_user_type": "Google_Service_Drive_User",
    "last_modifying_user_data_type": "",
    "mime_type": "application/msword",
    "name": "Resume — Symfony Backend Developer, PHP, Shuba Ivan.doc",
    "owners_type": "Google_Service_Drive_User",
    "owners_data_type": "array",
    "permissions_type": "Google_Service_Drive_Permission",
    "permissions_data_type": "array",
    "sharing_user_type": "Google_Service_Drive_User",
    "sharing_user_data_type": "",
    "video_media_metadata_type": "Google_Service_Drive_DriveFileVideoMediaMetadata",
    "video_media_metadata_data_type": ""
  }

all I have in file this: 

    /tmp/phpaPpHBp

I use this [doc v3][1] because in "name": "google/apiclient", "version": "1.1.7" no find function "insert", 

So, mime_type correct but inside emty, only like this - /tmp/phpaPpHBp
I try some uploadType - media, multipart, resumable but stil empty
When try pdf mime_type =  application/pdf but still emty
What I\'am doing wrong and why I have emty file in google drive? 

  [1]: https://developers.google.com/drive/v3/reference/files/create#try-it

**Comment by gmotov** [comment]
This code
```
        $parent = new Google_Service_Drive_ParentReferen();
        $parent->setId($request->request->get('parentId'));
        $file->setParents(array($parent));
```
you can replace with
```
        $file->setParents(array($request->request->get('parentId')));
```

and this:

```        
        $data = $request->files->get('file');
```

replace with
```
        $data = file_get_contents($request->files->get('file'));
```
it might be helpful

**Comment by shubaivan** [comment]
@gmotov very thnks

**Comment by shubaivan** [comment]
work fine 
        // Set the parent folder.
        if ($request->request->get('parentId') !== null) {
            $parent = new \Google_Service_Drive_ParentReference();
            $parent->setId($request->request->get('parentId'));
            $file->setParents(array($parent));
        }

        $insertArray = [
            'mimeType' => isset($fileUpload) ? $fileUpload->getClientMimeType() :  $request->request->get('mimeType')
        ];

        if (isset($fileUpload)) {
            $insertArray ['uploadType'] = 'media';
            $insertArray ['data'] = $data = file_get_contents($fileUpload);;
        }

        try {
            $createdFile = $service->files->insert($file, $insertArray);

            return View::create()
                ->setStatusCode(200)
                ->setData([$createdFile]);

        } catch (\Exception $e) {
            $view = $this->view((array) self::ERROR_OCCURRED . $e->getMessage(), 400);
            return $this->handleView($view);
        }
